const esc = (value) => escapeHtml(value ?? "");
let agentState = { config: null, conversationId: null, messages: [] };

function renderAgent() {
  if (location.hash !== "#agente") return;
  const config = agentState.config || {};
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Atendimento inteligente</p><h2>Agente Focussdev</h2><p>O agente consulta o catálogo e mantém contexto. Ações externas só serão executadas quando houver ferramenta e autorização.</p></div><span class="finance-status ${config.enabled ? "positive" : "neutral"}">${config.enabled ? "Ativo" : "Desativado"}</span></section><section class="agent-grid"><article class="data-card agent-config-card"><div class="section-heading"><div><p class="card-kicker">Configuração</p><h3>Operação segura</h3></div></div><dl class="agent-facts"><div><dt>Modelo</dt><dd>${esc(config.model || "—")}</dd></div><div><dt>Versão do prompt</dt><dd>${esc(config.prompt_version || "—")}</dd></div><div><dt>API de IA</dt><dd>${config.ai_configured ? "Configurada no servidor" : "Aguardando chave no servidor"}</dd></div></dl><form data-agent-config><label>Nome do agente<input name="name" value="${esc(config.name || "Agente Focussdev")}" required></label><label>Modelo<input name="model" value="${esc(config.model || "gpt-5")}" required></label><label>Nível de autonomia<select name="autonomy_level"><option value="0">0 — somente responder</option><option value="1">1 — preparar</option><option value="2">2 — ações simples</option><option value="3">3 — fluxos autorizados</option><option value="4">4 — automações configuradas</option></select></label><label class="agent-check"><input name="enabled" type="checkbox" ${config.enabled ? "checked" : ""}> Ativar agente</label><button class="button button-primary compact-action" type="submit">Salvar configuração</button><output data-agent-config-status role="status"></output></form></article><article class="data-card agent-chat-card"><div class="section-heading"><div><p class="card-kicker">Teste controlado</p><h3>Converse com o agente</h3></div><button class="compact-action" data-agent-clear type="button">Nova conversa</button></div><div class="agent-messages" data-agent-messages>${agentState.messages.map((item) => `<div class="agent-message ${item.role === "assistant" ? "is-agent" : "is-user"}">${esc(item.text)}</div>`).join("") || `<p class="agent-empty">Teste uma pergunta comercial ou um comando administrativo autorizado.</p>`}</div><form class="agent-compose" data-agent-compose><textarea name="message" rows="3" placeholder="Ex.: Quero um site para minha clínica. O que você recomenda?" required></textarea><button class="button button-primary compact-action" type="submit">Enviar</button><output data-agent-status role="status"></output></form></article></section>`;
  dashboardGrid.querySelector(".page-intro")?.insertAdjacentHTML("afterend", ui.stats([
    { label: "Status", value: config.enabled ? "Ativo" : "Desativado", tone: config.enabled ? "green" : "orange" },
    { label: "Modelo", value: esc(config.model || "Não definido") },
    { label: "Autonomia", value: `Nível ${Number(config.autonomy_level ?? 1)}` },
    { label: "Mensagens na sessão", value: ui.number(agentState.messages.length) }
  ]));
  const select = dashboardGrid.querySelector("[name=autonomy_level]"); if (select) select.value = String(config.autonomy_level ?? 1);
  dashboardGrid.querySelector("[data-agent-clear]")?.addEventListener("click", () => { agentState.conversationId = null; agentState.messages = []; renderAgent(); });
  dashboardGrid.querySelector("[data-agent-config]")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget, status = form.querySelector("[data-agent-config-status]"), data = Object.fromEntries(new FormData(form)); data.enabled = form.enabled.checked; data.autonomy_level = Number(data.autonomy_level); status.textContent = "Salvando…"; try { const response = await api("/api/agent/config", { method: "PATCH", body: data }); agentState.config = { ...agentState.config, ...response.agent }; status.textContent = "Configuração salva."; } catch (error) { status.textContent = error.message; } });
  dashboardGrid.querySelector("[data-agent-compose]")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget, status = form.querySelector("[data-agent-status]"), message = form.message.value.trim(), button = form.querySelector("button"); if (!message) return; agentState.messages.push({ role: "user", text: message }); renderAgent(); const nextForm = dashboardGrid.querySelector("[data-agent-compose]"), nextStatus = nextForm?.querySelector("[data-agent-status]"), nextButton = nextForm?.querySelector("button"); if (nextStatus) nextStatus.textContent = "Consultando…"; if (nextButton) nextButton.disabled = true; try { const response = await api("/api/agent/respond", { method: "POST", body: { conversation_id: agentState.conversationId, message } }); agentState.conversationId = response.conversation_id; agentState.messages.push({ role: "assistant", text: response.response.reply }); renderAgent(); } catch (error) { if (nextStatus) nextStatus.textContent = error.message; } finally { const currentButton = dashboardGrid.querySelector("[data-agent-compose] button"); if (currentButton) currentButton.disabled = false; } });
}

async function loadAgent() { if (location.hash !== "#agente") return; dashboardGrid.innerHTML = stateBlock.loading("Carregando agente…"); try { agentState.config = (await api("/api/agent/config")).agent; renderAgent(); } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "agent-retry"); dashboardGrid.querySelector(".agent-retry")?.addEventListener("click", loadAgent); } }
registerRoutes({ agente: loadAgent }, { parent: "#agente", titles: { agente: "Agente Focussdev" } });
