/* Biblioteca de arquivos: links, vínculos, pesquisa e manutenção real. */
const fileEsc = (value) => escapeHtml(value ?? "");
const fileKind = { document: "Documento", image: "Imagem", video: "Vídeo", code: "Código", backup: "Backup", other: "Outro" };

async function renderFilesScreen() {
  const title = "Arquivos", description = "Documentos e links organizados por cliente e projeto.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-file-new type="button">+ Adicionar arquivo</button></section>${stateBlock.loading("Carregando arquivos...")}`;
  try {
    const [fileData, projectData, clientData] = await Promise.all([api("/api/files"), api("/api/projects"), api("/api/clients")]);
    const items = fileData.files || [], projects = projectData.projects || [], clients = clientData.clients || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-file-new type="button">+ Adicionar arquivo</button></section><section class="data-card operations-table"><div class="operations-toolbar"><input type="search" data-file-search placeholder="Buscar nome, cliente ou projeto" aria-label="Buscar arquivo"><select data-file-project aria-label="Filtrar projeto"><option value="">Todos os projetos</option>${projects.map((project) => `<option value="${project.id}">${fileEsc(project.name)}</option>`).join("")}</select><select data-file-kind aria-label="Filtrar tipo"><option value="">Todos os tipos</option>${Object.entries(fileKind).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div>${items.length ? `<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Projeto</th><th>Cliente</th><th>Enviado em</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr data-file-row data-project="${fileEsc(item.project_id || "")}" data-kind="${fileEsc(item.kind || "other")}"><td><a href="${fileEsc(item.url)}" target="_blank" rel="noopener">${fileEsc(item.name)}</a></td><td>${fileEsc(fileKind[item.kind] || item.kind || "Outro")}</td><td>${fileEsc(item.project_name || item.project_id || "—")}</td><td>${fileEsc(item.client_name || item.client_id || "—")}</td><td>${item.created_at ? new Date(item.created_at).toLocaleDateString("pt-BR") : "—"}</td><td><button class="compact-action" data-file-edit="${item.id}" type="button">Editar</button><button class="compact-action" data-file-delete="${item.id}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhum arquivo", "Adicione um link para começar.", "Adicionar arquivo", "file-empty")}</section>`;
    const prepare = () => { createConfig.arquivo.fields.find((field) => field.name === "project_id").options = [["", "Sem projeto"], ...projects.map((project) => [project.id, project.name])]; createConfig.arquivo.fields.find((field) => field.name === "client_id").options = [["", "Sem cliente"], ...clients.map((client) => [client.id, client.name])]; openCreateDialog("arquivo"); };
    dashboardGrid.querySelector("[data-file-new]")?.addEventListener("click", prepare); dashboardGrid.querySelector("[data-file-empty]")?.addEventListener("click", prepare);
    const filter = () => { const query = dashboardGrid.querySelector("[data-file-search]").value.toLocaleLowerCase("pt-BR"), project = dashboardGrid.querySelector("[data-file-project]").value, kind = dashboardGrid.querySelector("[data-file-kind]").value; dashboardGrid.querySelectorAll("[data-file-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (project && row.dataset.project !== project) || (kind && row.dataset.kind !== kind); }); };
    dashboardGrid.querySelector("[data-file-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-file-project]")?.addEventListener("change", filter); dashboardGrid.querySelector("[data-file-kind]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-file-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.fileEdit)); if (item) openEditDialog("arquivo", item, `/api/files/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-file-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir arquivo?", onConfirm: async () => { await api(`/api/files/${button.dataset.fileDelete}`, { method: "DELETE" }); toast("Arquivo excluído.", "success"); renderFilesScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "file-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderFilesScreen); }
}

registerRoutes({ arquivos: renderFilesScreen });
