const fileEsc = (value) => escapeHtml(value ?? "");
const fileKind = { document: "Documento", image: "Imagem", video: "Vídeo", code: "Código", backup: "Backup", other: "Outro" };
const fileFilter = { search: "", project_id: "", kind: "" };
function fileDetails(item) { if (!item) return; const hidden = new Set(["id", "organization_id"]); const value = (entry) => entry === null || entry === undefined || entry === "" ? "—" : typeof entry === "object" ? JSON.stringify(entry) : String(entry); const html = Object.entries(item).filter(([key]) => !hidden.has(key) && key !== "url").map(([key, entry]) => `<dt>${fileEsc(key.replaceAll("_", " "))}</dt><dd>${fileEsc(value(entry))}</dd>`).join(""); ui.drawer({ title: item.name || "Arquivo", subtitle: fileKind[item.kind] || item.kind || "Arquivo", html: `${html ? `<dl>${html}</dl>` : "<p>Sem detalhes disponiveis.</p>"}${item.url ? `<p><a class="compact-action" href="${fileEsc(item.url)}" target="_blank" rel="noopener">Abrir arquivo</a></p>` : ""}` }); }

async function renderFilesScreen() {
  const title = "Arquivos", description = "Documentos e links organizados por cliente e projeto.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-file-new type="button">+ Adicionar arquivo</button></section>${stateBlock.loading("Carregando arquivos...")}`;
  try {
    const params = new URLSearchParams(); if (fileFilter.search) params.set("search", fileFilter.search); if (fileFilter.project_id) params.set("project_id", fileFilter.project_id); if (fileFilter.kind) params.set("kind", fileFilter.kind);
    const [fileResult, projectResult, clientResult] = await Promise.allSettled([api(`/api/files?${params}`), api("/api/projects"), api("/api/clients")]);
    if (fileResult.status === "rejected") throw fileResult.reason;
    const items = fileResult.value.files || [], projects = projectResult.status === "fulfilled" ? projectResult.value.projects || [] : [], clients = clientResult.status === "fulfilled" ? clientResult.value.clients || [] : [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-file-new type="button">+ Adicionar arquivo</button></section><section class="data-card operations-table"><div class="operations-toolbar"><input type="search" data-file-search value="${fileEsc(fileFilter.search)}" placeholder="Buscar nome, cliente ou projeto" aria-label="Buscar arquivo"><select data-file-project aria-label="Filtrar projeto"><option value="">Todos os projetos</option>${projects.map((project) => `<option value="${fileEsc(project.id)}">${fileEsc(project.name)}</option>`).join("")}</select><select data-file-kind aria-label="Filtrar tipo"><option value="">Todos os tipos</option>${Object.entries(fileKind).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div>${items.length ? `<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Projeto</th><th>Cliente</th><th>Enviado em</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr><td><a href="${fileEsc(item.url)}" target="_blank" rel="noopener">${fileEsc(item.name)}</a></td><td>${fileEsc(fileKind[item.kind] || item.kind || "Outro")}</td><td>${fileEsc(item.project_name || item.project_id || "—")}</td><td>${fileEsc(item.client_name || item.client_id || "—")}</td><td>${item.created_at ? new Date(item.created_at).toLocaleDateString("pt-BR") : "—"}</td><td><button class="compact-action" data-file-edit="${fileEsc(item.id)}" type="button">Editar</button><button class="compact-action" data-file-delete="${fileEsc(item.id)}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhum arquivo", "Adicione um link para começar.", "Adicionar arquivo", "file-empty")}</section>`;
    const search = dashboardGrid.querySelector("[data-file-search]"), project = dashboardGrid.querySelector("[data-file-project]"), kind = dashboardGrid.querySelector("[data-file-kind]"); project.value = fileFilter.project_id; kind.value = fileFilter.kind; let timer;
    search?.addEventListener("input", () => { clearTimeout(timer); fileFilter.search = search.value.trim(); timer = setTimeout(renderFilesScreen, 250); }); project?.addEventListener("change", () => { fileFilter.project_id = project.value; renderFilesScreen(); }); kind?.addEventListener("change", () => { fileFilter.kind = kind.value; renderFilesScreen(); });
    const prepare = () => { createConfig.arquivo.fields.find((field) => field.name === "project_id").options = [["", "Sem projeto"], ...projects.map((item) => [item.id, item.name])]; createConfig.arquivo.fields.find((field) => field.name === "client_id").options = [["", "Sem cliente"], ...clients.map((item) => [item.id, item.name])]; openCreateDialog("arquivo"); };
    dashboardGrid.querySelector("[data-file-new]")?.addEventListener("click", prepare); dashboardGrid.querySelector(".file-empty")?.addEventListener("click", prepare);
    dashboardGrid.querySelectorAll("tbody tr").forEach((row, index) => { const details = document.createElement("button"); details.type = "button"; details.className = "compact-action"; details.textContent = "Detalhes"; details.addEventListener("click", () => fileDetails(items[index])); row.querySelector("td:last-child")?.prepend(details); });
    dashboardGrid.querySelectorAll("[data-file-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.fileEdit)); if (item) openEditDialog("arquivo", item, `/api/files/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-file-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir arquivo?", onConfirm: async () => { try { await api(`/api/files/${button.dataset.fileDelete}`, { method: "DELETE" }); toast("Arquivo excluído.", "success"); renderFilesScreen(); } catch (error) { toast(error.message, "error"); } } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "file-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderFilesScreen); }
}

registerRoutes({ arquivos: renderFilesScreen });
