/* Tela operacional de assinaturas recorrentes. */
const subEsc = (value) => escapeHtml(value ?? "");
const subMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const subDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const subStatus = { active: "Ativa", paused: "Pausada", cancelled: "Cancelada", pending: "Pagamento pendente" };
const subState = (kind, text) => stateBlock[kind](text);

async function renderSubscriptionsScreen() {
  const title = "Assinaturas", description = "Controle serviços recorrentes, cobranças e renovações.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-sub-new type="button">+ Nova assinatura</button></section>${subState("loading", "Carregando assinaturas...")}`;
  try {
    const items = (await api("/api/subscriptions")).subscriptions || [], active = items.filter((item) => item.status === "active");
    const mrr = active.reduce((sum, item) => sum + (item.interval === "yearly" ? Number(item.amount || 0) / 12 : Number(item.amount || 0)), 0);
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-sub-new type="button">+ Nova assinatura</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Ativas</span><strong>${active.length}</strong></article><article class="data-card finance-metric"><span>MRR estimado</span><strong>${subMoney(mrr)}</strong></article><article class="data-card finance-metric"><span>Pausadas</span><strong>${items.filter((item) => item.status === "paused").length}</strong></article><article class="data-card finance-metric"><span>Próximas em 7 dias</span><strong>${items.filter((item) => item.next_billing_on && new Date(item.next_billing_on) <= new Date(Date.now() + 7 * 864e5)).length}</strong></article></section><section class="data-card finance-list"><div class="finance-toolbar"><input type="search" data-sub-search placeholder="Buscar plano ou cliente" aria-label="Buscar assinatura"><select data-sub-filter aria-label="Filtrar status"><option value="">Todos os status</option><option value="active">Ativas</option><option value="paused">Pausadas</option><option value="cancelled">Canceladas</option></select></div>${items.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Plano</th><th>Cliente</th><th>Valor</th><th>Próxima cobrança</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr data-sub-row data-status="${subEsc(item.status || "")}"><td>${subEsc(item.plan)}</td><td>${subEsc(item.client_name || "Sem cliente")}</td><td>${subMoney(item.amount)} / ${item.interval === "yearly" ? "ano" : "mês"}</td><td>${subDate(item.next_billing_on)}</td><td><span class="finance-status ${item.status === "active" ? "positive" : "neutral"}">${subStatus[item.status] || subEsc(item.status)}</span></td><td>${item.status !== "cancelled" ? `<button class="compact-action" data-sub-status="${item.id}" data-next="${item.status === "active" ? "paused" : "active"}" type="button">${item.status === "active" ? "Pausar" : "Reativar"}</button>` : ""}<button class="compact-action" data-sub-delete="${item.id}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : subState("empty", "Nenhuma assinatura cadastrada.")}</section>`;
    dashboardGrid.querySelector("[data-sub-new]")?.addEventListener("click", async () => { const clients = (await api("/api/clients")).clients || []; createConfig.assinatura.fields.find((field) => field.name === "client_id").options = [["", "Sem cliente"], ...clients.map((client) => [client.id, client.name])]; openCreateDialog("assinatura"); });
    const filter = () => { const query = dashboardGrid.querySelector("[data-sub-search]").value.toLocaleLowerCase("pt-BR"), status = dashboardGrid.querySelector("[data-sub-filter]").value; dashboardGrid.querySelectorAll("[data-sub-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (status && row.dataset.status !== status); }); };
    dashboardGrid.querySelector("[data-sub-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-sub-filter]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-sub-status]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/subscriptions/${button.dataset.subStatus}`, { method: "PATCH", body: { status: button.dataset.next } }); toast("Assinatura atualizada.", "success"); renderSubscriptionsScreen(); } catch (error) { button.disabled = false; toast(error.message, "error"); } }));
    dashboardGrid.querySelectorAll("[data-sub-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir assinatura?", onConfirm: async () => { await api(`/api/subscriptions/${button.dataset.subDelete}`, { method: "DELETE" }); toast("Assinatura excluída.", "success"); renderSubscriptionsScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2></div></section>${subState("error", error.message)}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderSubscriptionsScreen); }
}

registerRoutes({ assinaturas: renderSubscriptionsScreen });
