/* Auditoria somente leitura: filtros e detalhes dos eventos persistidos no workspace. */
const auditEsc = (value) => escapeHtml(value ?? "");
const auditDate = (value) => value ? new Date(value).toLocaleString("pt-BR") : "—";
const auditJson = (value) => { try { return JSON.stringify(typeof value === "string" ? JSON.parse(value) : value || {}, null, 2); } catch { return String(value ?? "{}"); } };

async function renderAuditScreen() {
  const title = "Auditoria", description = "Acompanhe alterações, acessos e ações administrativas do workspace.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2><p>${description}</p></div></section>${stateBlock.loading("Carregando registros...")}`;
  try {
    const rows = (await api("/api/audit_events?limit=250")).audit_events || [];
    const actions = [...new Set(rows.map((row) => row.action).filter(Boolean))].sort();
    const entities = [...new Set(rows.map((row) => row.entity_type).filter(Boolean))].sort();
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2><p>${description}</p></div><span class="finance-status neutral">${rows.length} registro(s)</span></section><section class="data-card audit-panel"><div class="finance-toolbar"><input type="search" data-audit-search placeholder="Buscar ação, entidade ou usuário" aria-label="Buscar na auditoria"><select data-audit-action aria-label="Filtrar ação"><option value="">Todas as ações</option>${actions.map((item) => `<option value="${auditEsc(item)}">${auditEsc(item)}</option>`).join("")}</select><select data-audit-entity aria-label="Filtrar entidade"><option value="">Todas as entidades</option>${entities.map((item) => `<option value="${auditEsc(item)}">${auditEsc(item)}</option>`).join("")}</select><input type="date" data-audit-from aria-label="Data inicial"><input type="date" data-audit-to aria-label="Data final"></div>${rows.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>ID</th><th>Origem</th><th></th></tr></thead><tbody>${rows.map((row) => `<tr data-audit-row data-action="${auditEsc(row.action)}" data-entity="${auditEsc(row.entity_type)}" data-date="${auditEsc(row.created_at || "")}"><td>${auditEsc(auditDate(row.created_at))}</td><td>${auditEsc(row.actor_name || "Sistema")}</td><td><span class="finance-status neutral">${auditEsc(row.action)}</span></td><td>${auditEsc(row.entity_type)}</td><td>${auditEsc(row.entity_id || "—")}</td><td>${auditEsc(row.ip_address || "—")}</td><td><button type="button" class="compact-action" data-audit-details>Detalhes</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhum evento registrado", "As ações administrativas aparecerão aqui automaticamente.")}</section>`;
    const filter = () => { const search = dashboardGrid.querySelector("[data-audit-search]").value.toLocaleLowerCase("pt-BR"), action = dashboardGrid.querySelector("[data-audit-action]").value, entity = dashboardGrid.querySelector("[data-audit-entity]").value, from = dashboardGrid.querySelector("[data-audit-from]").value, to = dashboardGrid.querySelector("[data-audit-to]").value; dashboardGrid.querySelectorAll("[data-audit-row]").forEach((row) => { const date = row.dataset.date.slice(0, 10); row.hidden = (search && !row.textContent.toLocaleLowerCase("pt-BR").includes(search)) || (action && row.dataset.action !== action) || (entity && row.dataset.entity !== entity) || (from && date < from) || (to && date > to); }); };
    ["[data-audit-search]", "[data-audit-action]", "[data-audit-entity]", "[data-audit-from]", "[data-audit-to]"].forEach((selector) => dashboardGrid.querySelector(selector)?.addEventListener("input", filter));
    dashboardGrid.querySelectorAll("[data-audit-details]").forEach((button, index) => button.addEventListener("click", () => { const row = rows[index]; ui.drawer({ title: `${row.action || "Ação"} · ${row.entity_type || "registro"}`, subtitle: `${row.actor_name || "Sistema"} · ${auditDate(row.created_at)}`, html: ui.facts([["ID do registro", row.entity_id || "—"], ["IP", row.ip_address || "—"], ["Agente", row.user_agent || "—"]]) + `<h3>Alterações registradas</h3><pre class="audit-json">${auditEsc(auditJson(row.changes))}</pre>` }); }));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "audit-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderAuditScreen); }
}
registerRoutes({ auditoria: renderAuditScreen });
