const auditEsc = (value) => escapeHtml(value ?? "");
const auditDate = (value) => value ? new Date(value).toLocaleString("pt-BR") : "—";
const auditJson = (value) => { try { return JSON.stringify(typeof value === "string" ? JSON.parse(value) : value || {}, null, 2); } catch { return String(value ?? "{}"); } };
const auditState = { search: "", action: "", entity: "", from: "", to: "", offset: 0 };
let auditTimer;

async function renderAuditScreen() {
  const title = "Auditoria", description = "Acompanhe alterações, acessos e ações administrativas do workspace.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2><p>${description}</p></div></section>${stateBlock.loading("Carregando registros...")}`;
  const params = new URLSearchParams({ limit: "100", offset: String(auditState.offset) });
  for (const [key, value] of Object.entries(auditState)) if (key !== "offset" && value) params.set(key, value);
  try {
    const response = await api(`/api/audit_events?${params}`), rows = response.audit_events || [], pagination = response.pagination || {};
    const actions = [...new Set(rows.map((row) => row.action).filter(Boolean))].sort(), entities = [...new Set(rows.map((row) => row.entity_type).filter(Boolean))].sort();
    const option = (value, label, selected) => `<option value="${auditEsc(value)}"${selected === value ? " selected" : ""}>${auditEsc(label)}</option>`;
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2><p>${description}</p></div><span class="finance-status neutral">${pagination.returned ?? rows.length} registro(s)</span></section><section class="data-card audit-panel"><div class="finance-toolbar"><input type="search" data-audit-search value="${auditEsc(auditState.search)}" placeholder="Buscar ação, entidade ou usuário" aria-label="Buscar na auditoria"><select data-audit-action aria-label="Filtrar ação">${option("", "Todas as ações", auditState.action)}${actions.map((item) => option(item, item, auditState.action)).join("")}</select><select data-audit-entity aria-label="Filtrar entidade">${option("", "Todas as entidades", auditState.entity)}${entities.map((item) => option(item, item, auditState.entity)).join("")}</select><input type="date" data-audit-from value="${auditEsc(auditState.from)}" aria-label="Data inicial"><input type="date" data-audit-to value="${auditEsc(auditState.to)}" aria-label="Data final"></div>${rows.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>ID</th><th>Origem</th><th></th></tr></thead><tbody>${rows.map((row, index) => `<tr><td>${auditEsc(auditDate(row.created_at))}</td><td>${auditEsc(row.actor_name || "Sistema")}</td><td><span class="finance-status neutral">${auditEsc(row.action)}</span></td><td>${auditEsc(row.entity_type)}</td><td>${auditEsc(row.entity_id || "—")}</td><td>${auditEsc(row.ip_address || "—")}</td><td><button type="button" class="compact-action" data-audit-details="${index}">Detalhes</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhum evento registrado", "As ações administrativas aparecerão aqui automaticamente.")}<div class="table-pagination"><button type="button" class="compact-action" data-audit-prev ${auditState.offset === 0 ? "disabled" : ""}>Anterior</button><span>Página ${Math.floor(auditState.offset / 100) + 1}</span><button type="button" class="compact-action" data-audit-next ${(pagination.returned ?? rows.length) < 100 ? "disabled" : ""}>Próxima</button></div></section>`;
    const reload = () => { auditState.search = dashboardGrid.querySelector("[data-audit-search]").value.trim(); auditState.action = dashboardGrid.querySelector("[data-audit-action]").value; auditState.entity = dashboardGrid.querySelector("[data-audit-entity]").value; auditState.from = dashboardGrid.querySelector("[data-audit-from]").value; auditState.to = dashboardGrid.querySelector("[data-audit-to]").value; auditState.offset = 0; clearTimeout(auditTimer); auditTimer = setTimeout(renderAuditScreen, 250); };
    dashboardGrid.querySelector("[data-audit-search]")?.addEventListener("input", reload);
    ["[data-audit-action]", "[data-audit-entity]", "[data-audit-from]", "[data-audit-to]"].forEach((selector) => dashboardGrid.querySelector(selector)?.addEventListener("change", reload));
    dashboardGrid.querySelector("[data-audit-prev]")?.addEventListener("click", () => { auditState.offset = Math.max(0, auditState.offset - 100); renderAuditScreen(); });
    dashboardGrid.querySelector("[data-audit-next]")?.addEventListener("click", () => { auditState.offset += 100; renderAuditScreen(); });
    dashboardGrid.querySelectorAll("[data-audit-details]").forEach((button) => button.addEventListener("click", () => { const row = rows[Number(button.dataset.auditDetails)]; ui.drawer({ title: `${row.action || "Ação"} · ${row.entity_type || "registro"}`, subtitle: `${row.actor_name || "Sistema"} · ${auditDate(row.created_at)}`, html: ui.facts([["ID do registro", row.entity_id || "—"], ["IP", row.ip_address || "—"], ["Agente", row.user_agent || "—"]]) + `<h3>Alterações registradas</h3><pre class="audit-json">${auditEsc(auditJson(row.changes))}</pre>` }); }));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Segurança e controle</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "audit-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderAuditScreen); }
}
registerRoutes({ auditoria: renderAuditScreen });
dashboardGrid.addEventListener("click", (event) => { if (event.target.closest(".audit-retry")) renderAuditScreen(); });
