const types = { product: "Produto", service: "Serviço", package: "Pacote", plan: "Plano", subscription: "Assinatura", addon: "Serviço adicional" };
const esc = (value) => escapeHtml(value ?? "");
const catalogFilter = { search: "", kind: "", active: "" };
const cfg = { title: "Novo item", endpoint: "/api/catalog-items", fields: [{ name: "name", label: "Nome" }, { name: "kind", label: "Tipo", type: "select", options: Object.entries(types) }, { name: "price", label: "Preço", type: "number" }, { name: "unit", label: "Unidade", required: false }, { name: "description", label: "Descrição", required: false }] };
Object.assign(createConfig, { item: cfg });
cfg.fields.push(
  { name: "category", label: "Categoria", required: false }, { name: "short_description", label: "Descrição curta", required: false }, { name: "full_description", label: "Descrição completa", type: "textarea", required: false },
  { name: "billing_type", label: "Tipo de cobrança", required: false }, { name: "recurrence", label: "Recorrência", required: false }, { name: "min_price", label: "Preço mínimo", type: "number", required: false }, { name: "promotional_price", label: "Preço promocional", type: "number", required: false }, { name: "internal_cost", label: "Custo interno", type: "number", required: false },
  { name: "max_installments", label: "Parcelamento máximo", type: "number", required: false }, { name: "max_discount", label: "Desconto máximo", type: "number", required: false }, { name: "delivery_days", label: "Prazo médio (dias)", type: "number", required: false }, { name: "included_scope", label: "O que está incluído", type: "textarea", required: false }, { name: "excluded_scope", label: "O que não está incluído", type: "textarea", required: false },
  { name: "deliverables", label: "Entregáveis", type: "textarea", required: false }, { name: "features", label: "Funcionalidades", type: "textarea", required: false }, { name: "modules_count", label: "Páginas ou módulos", type: "number", required: false }, { name: "revisions_count", label: "Revisões incluídas", type: "number", required: false }, { name: "warranty_period", label: "Período de garantia", required: false }, { name: "support_included", label: "Suporte incluído", required: false },
  { name: "client_responsibilities", label: "Responsabilidades do cliente", type: "textarea", required: false }, { name: "technical_requirements", label: "Requisitos técnicos", type: "textarea", required: false }, { name: "active", label: "Item ativo", type: "checkbox", required: false }, { name: "public_visible", label: "Exibir no catálogo público", type: "checkbox", required: false },
);

const queryString = () => { const params = new URLSearchParams(); if (catalogFilter.search) params.set("search", catalogFilter.search); if (catalogFilter.kind) params.set("kind", catalogFilter.kind); if (catalogFilter.active) params.set("active", catalogFilter.active); return params.toString(); };
const card = (item) => `<article class="data-card catalog-card"><h3>${esc(item.name)}</h3><span>${esc(types[item.kind] || item.kind)}</span><strong>R$ ${Number(item.price || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong><p>${esc(item.description || item.short_description || "")}</p><div class="card-actions"><button class="compact-action" data-use="${esc(item.id)}" type="button">Usar em proposta</button><button class="compact-action" data-toggle="${esc(item.id)}" type="button">${item.active ? "Desativar" : "Ativar"}</button><button class="compact-action" data-delete="${esc(item.id)}" type="button">Excluir</button></div></article>`;

async function renderCatalog() {
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Catálogo</p><h2>Produtos e serviços</h2><p>Itens reutilizáveis para propostas, projetos e cobranças.</p></div><div class="page-actions"><button class="button button-secondary compact-action" data-public-catalog type="button">Abrir catálogo público</button><button class="button button-primary compact-action" data-new type="button">+ Novo item</button></div></section>${stateBlock.loading("Carregando catálogo...")}`;
  try {
    const [data, me] = await Promise.all([api(`/api/catalog-items?${queryString()}`), api("/api/auth/me")]);
    const rows = data.catalog_items || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Catálogo</p><h2>Produtos e serviços</h2><p>Itens reutilizáveis para propostas, projetos e cobranças.</p></div><div class="page-actions"><button class="button button-secondary compact-action" data-public-catalog type="button">Abrir catálogo público</button><button class="button button-primary compact-action" data-new type="button">+ Novo item</button></div></section><section class="catalog-toolbar"><input data-search value="${esc(catalogFilter.search)}" placeholder="Buscar item" aria-label="Buscar item"><select data-kind aria-label="Filtrar por tipo"><option value="">Todos os tipos</option>${Object.entries(types).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select><select data-active aria-label="Filtrar por status"><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></section><section class="catalog-grid">${rows.map(card).join("") || stateBlock.empty("Nenhum item", "Cadastre seu primeiro produto ou serviço.", "Criar agora", "catalog-empty")}</section>`;
    const search = dashboardGrid.querySelector("[data-search]"), kind = dashboardGrid.querySelector("[data-kind]"), active = dashboardGrid.querySelector("[data-active]");
    kind.value = catalogFilter.kind; active.value = catalogFilter.active;
    let timer; search.oninput = () => { clearTimeout(timer); catalogFilter.search = search.value.trim(); timer = setTimeout(renderCatalog, 250); };
    kind.onchange = () => { catalogFilter.kind = kind.value; renderCatalog(); }; active.onchange = () => { catalogFilter.active = active.value; renderCatalog(); };
    dashboardGrid.querySelector("[data-new]").onclick = () => openCreateDialog("item");
    dashboardGrid.querySelector("[data-public-catalog]")?.addEventListener("click", async () => { const link = `${location.origin}/catalog/${me.user.organization_id}`; await navigator.clipboard?.writeText(link); window.open(link, "_blank", "noopener"); toast("Catálogo público aberto e link copiado.", "success"); });
    dashboardGrid.querySelectorAll("[data-use]").forEach((button) => button.onclick = () => { sessionStorage.setItem("focusdev.catalogItemId", String(button.dataset.use)); location.hash = "#propostas"; });
    dashboardGrid.querySelectorAll("[data-toggle]").forEach((button) => button.onclick = async () => { const item = rows.find((row) => String(row.id) === button.dataset.toggle); if (!item) return; try { await api(`/api/catalog-items/${button.dataset.toggle}`, { method: "PATCH", body: { active: !item.active } }); toast("Status atualizado.", "success"); renderCatalog(); } catch (error) { toast(error.message, "error"); } });
    dashboardGrid.querySelectorAll("[data-delete]").forEach((button) => button.onclick = () => ui.confirmInline(button, { text: "Excluir item?", onConfirm: async () => { try { await api(`/api/catalog-items/${button.dataset.delete}`, { method: "DELETE" }); toast("Item excluído.", "success"); renderCatalog(); } catch (error) { toast(error.message, "error"); } } }));
  } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "catalog-retry"); }
}

registerRoutes({ catalogo: renderCatalog });
