/* Acompanhamento operacional das cobranças, sem simular gateway de pagamento. */
const chargeEsc = (value) => escapeHtml(value ?? "");
const chargeMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const chargeDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const chargeStatus = { draft: "Rascunho", generated: "Gerada", sent: "Enviada", viewed: "Visualizada", pending: "Pendente", paid: "Paga", overdue: "Vencida", cancelled: "Cancelada", refunded: "Reembolsada" };
const chargeTone = (status) => ["paid"].includes(status) ? "positive" : ["overdue", "cancelled"].includes(status) ? "warning" : "neutral";

async function renderChargesScreen() {
  const title = "Cobranças", description = "Acompanhe solicitações de pagamento ligadas às contas a receber.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-charge-new type="button">+ Nova cobrança</button></section>${stateBlock.loading("Carregando cobranças...")}`;
  try {
    const items = (await api("/api/charges")).charges || [];
    const amount = (status) => items.filter((item) => !status || item.status === status).reduce((sum, item) => sum + Number(item.amount || 0), 0);
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-charge-new type="button">+ Nova cobrança</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Total gerado</span><strong>${chargeMoney(amount())}</strong></article><article class="data-card finance-metric"><span>Pendentes</span><strong>${items.filter((item) => ["generated", "sent", "viewed", "pending"].includes(item.status)).length}</strong></article><article class="data-card finance-metric"><span>Pagas</span><strong>${chargeMoney(amount("paid"))}</strong></article><article class="data-card finance-metric"><span>Vencidas</span><strong>${items.filter((item) => item.status === "overdue").length}</strong></article></section><section class="data-card finance-list"><div class="finance-toolbar"><input type="search" data-charge-search placeholder="Buscar mensagem, cliente ou projeto" aria-label="Buscar cobrança"><select data-charge-filter aria-label="Filtrar status"><option value="">Todos os status</option>${Object.entries(chargeStatus).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div>${items.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Identificação</th><th>Canal</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr data-charge-row data-status="${chargeEsc(item.status || "")}"><td><strong>${chargeEsc(item.message || "Cobrança")}</strong><small>Recebível: ${chargeEsc(item.receivable_id || "não vinculado")}</small></td><td>${chargeEsc(item.channel || "link")}</td><td>${chargeMoney(item.amount)}</td><td>${chargeDate(item.due_at)}</td><td><span class="finance-status ${chargeTone(item.status)}">${chargeStatus[item.status] || chargeEsc(item.status || "Pendente")}</span></td><td><button class="compact-action" data-charge-edit="${item.id}" type="button">Editar</button><button class="compact-action" data-charge-delete="${item.id}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhuma cobrança registrada", "Gere uma cobrança a partir de uma conta a receber.", "Criar cobrança", "charge-empty")}</section>`;
    const openNew = async () => {
      const receivables = (await api("/api/receivables")).receivables || [];
      createConfig.cobranca.fields = [{ name: "receivable_id", label: "Conta a receber", type: "select", options: [["", "Sem vínculo"], ...receivables.map((item) => [item.id, `${item.description} · ${chargeMoney(item.amount)}`])] }, { name: "amount", label: "Valor", type: "number" }, { name: "channel", label: "Canal", type: "select", options: [["pix", "Pix"], ["boleto", "Boleto"], ["card", "Cartão"], ["link", "Link de pagamento"], ["transfer", "Transferência"]] }, { name: "due_at", label: "Vencimento", type: "date", required: false }, { name: "message", label: "Mensagem", required: false }];
      openCreateDialog("cobranca");
    };
    dashboardGrid.querySelector("[data-charge-new]")?.addEventListener("click", openNew);
    dashboardGrid.querySelector("[data-charge-empty]")?.addEventListener("click", openNew);
    const filter = () => { const query = dashboardGrid.querySelector("[data-charge-search]").value.toLocaleLowerCase("pt-BR"), status = dashboardGrid.querySelector("[data-charge-filter]").value; dashboardGrid.querySelectorAll("[data-charge-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (status && row.dataset.status !== status); }); };
    dashboardGrid.querySelector("[data-charge-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-charge-filter]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-charge-edit]").forEach((button) => button.addEventListener("click", () => { const record = items.find((item) => String(item.id) === String(button.dataset.chargeEdit)); if (record) openEditDialog("cobranca", record, `/api/charges/${record.id}`); }));
    dashboardGrid.querySelectorAll("[data-charge-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir cobrança?", onConfirm: async () => { await api(`/api/charges/${button.dataset.chargeDelete}`, { method: "DELETE" }); toast("Cobrança excluída.", "success"); renderChargesScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "charge-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderChargesScreen); }
}

registerRoutes({ cobrancas: renderChargesScreen });
