const chargeEsc = (value) => escapeHtml(value ?? "");
const chargeMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const chargeDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const chargeStatus = { draft: "Rascunho", generated: "Gerada", sent: "Enviada", viewed: "Visualizada", pending: "Pendente", paid: "Paga", overdue: "Vencida", cancelled: "Cancelada", refunded: "Reembolsada" };
const chargeTone = (status) => status === "paid" ? "positive" : ["overdue", "cancelled"].includes(status) ? "warning" : "neutral";
const chargeFilter = { search: "", status: "" };

async function renderChargesScreen() {
  const title = "Cobranças", description = "Acompanhe solicitações de pagamento ligadas às contas a receber.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-charge-new type="button">+ Nova cobrança</button></section>${stateBlock.loading("Carregando cobranças...")}`;
  try {
    const params = new URLSearchParams(); if (chargeFilter.search) params.set("search", chargeFilter.search); if (chargeFilter.status) params.set("status", chargeFilter.status); const items = (await api(`/api/charges?${params}`)).charges || [];
    const amount = (status) => items.filter((item) => !status || item.status === status).reduce((sum, item) => sum + Number(item.amount || 0), 0);
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-charge-new type="button">+ Nova cobrança</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Total gerado</span><strong>${chargeMoney(amount())}</strong></article><article class="data-card finance-metric"><span>Pendentes</span><strong>${items.filter((item) => ["generated", "sent", "viewed", "pending"].includes(item.status)).length}</strong></article><article class="data-card finance-metric"><span>Pagas</span><strong>${chargeMoney(amount("paid"))}</strong></article><article class="data-card finance-metric"><span>Vencidas</span><strong>${items.filter((item) => item.status === "overdue").length}</strong></article></section><section class="data-card finance-list"><div class="finance-toolbar"><input type="search" data-charge-search value="${chargeEsc(chargeFilter.search)}" placeholder="Buscar mensagem, cliente ou projeto" aria-label="Buscar cobrança"><select data-charge-filter aria-label="Filtrar status"><option value="">Todos os status</option>${Object.entries(chargeStatus).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div>${items.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Identificação</th><th>Canal</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr><td><strong>${chargeEsc(item.message || "Cobrança")}</strong><small>Recebível: ${chargeEsc(item.receivable_id || "não vinculado")}</small></td><td>${chargeEsc(item.channel || "link")}</td><td>${chargeMoney(item.amount)}</td><td>${chargeDate(item.due_at)}</td><td><span class="finance-status ${chargeTone(item.status)}">${chargeStatus[item.status] || chargeEsc(item.status || "Pendente")}</span></td><td><button class="compact-action" data-charge-edit="${chargeEsc(item.id)}" type="button">Editar</button><button class="compact-action" data-charge-delete="${chargeEsc(item.id)}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhuma cobrança registrada", "Gere uma cobrança a partir de uma conta a receber.")}</section>`;
    const search = dashboardGrid.querySelector("[data-charge-search]"), status = dashboardGrid.querySelector("[data-charge-filter]"); status.value = chargeFilter.status; let timer; search?.addEventListener("input", () => { clearTimeout(timer); chargeFilter.search = search.value.trim(); timer = setTimeout(renderChargesScreen, 250); }); status?.addEventListener("change", () => { chargeFilter.status = status.value; renderChargesScreen(); });
    const openNew = async () => { const receivables = (await api("/api/receivables")).receivables || []; createConfig.cobranca.fields = [{ name: "receivable_id", label: "Conta a receber", type: "select", options: [["", "Sem vínculo"], ...receivables.map((item) => [item.id, `${item.description} · ${chargeMoney(item.amount)}`])] }, { name: "amount", label: "Valor", type: "number" }, { name: "channel", label: "Canal", type: "select", options: [["pix", "Pix"], ["boleto", "Boleto"], ["card", "Cartão"], ["link", "Link de pagamento"], ["transfer", "Transferência"]] }, { name: "due_at", label: "Vencimento", type: "date", required: false }, { name: "message", label: "Mensagem", required: false }]; openCreateDialog("cobranca"); };
    dashboardGrid.querySelector("[data-charge-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-charge-empty]")?.addEventListener("click", openNew);
    dashboardGrid.querySelectorAll("[data-charge-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.chargeEdit)); if (item) openEditDialog("cobranca", item, `/api/charges/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-charge-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir cobrança?", onConfirm: async () => { try { await api(`/api/charges/${button.dataset.chargeDelete}`, { method: "DELETE" }); toast("Cobrança excluída.", "success"); renderChargesScreen(); } catch (error) { toast(error.message, "error"); } } })));
  } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "charge-retry"); dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderChargesScreen); }
}

registerRoutes({ cobrancas: renderChargesScreen });
dashboardGrid.addEventListener("click", (event) => { if (event.target.closest(".charge-retry")) renderChargesScreen(); });
const chargeDetailsObserver = new MutationObserver(async () => { if (location.hash.replace(/^#/, "") !== "cobrancas") return; const list = dashboardGrid.querySelector(".finance-list"); if (!list || list.dataset.detailsBound === "1") return; list.dataset.detailsBound = "1"; try { const items = (await api("/api/charges?limit=100")).charges || []; list.querySelectorAll("tbody tr").forEach((row, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "compact-action"; button.textContent = "Detalhes"; button.addEventListener("click", () => { const item = items[index]; if (!item) return; const html = Object.entries(item).filter(([key]) => !["id", "organization_id"].includes(key)).map(([key, value]) => `<dt>${chargeEsc(key.replaceAll("_", " "))}</dt><dd>${chargeEsc(value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : value)}</dd>`).join(""); ui.drawer({ title: item.message || "Cobranca", subtitle: chargeStatus[item.status] || item.status || "Sem status", html: `<dl>${html}</dl>` }); }); row.querySelector("td:last-child")?.prepend(button); }); } catch { list.dataset.detailsBound = ""; } });
chargeDetailsObserver.observe(dashboardGrid, { childList: true, subtree: true });
