/* Contas: contatos, empresas, clientes, CNPJ e portal. */
const contaEsc = (v) => escapeHtml(v ?? "");
const contaMoney = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const contaStatus = { active: "Ativo", inactive: "Inativo", churned: "Cancelado", draft: "Rascunho", paused: "Pausado", completed: "Concluído", cancelled: "Cancelado" };
const contaState = (kind, text) => `<div class="conta-state">${stateBlock[kind](text)}</div>`;
const contaIntro = (title, text, kind) => `<section class="page-intro contas-intro"><div><p class="card-kicker">Contas</p><h2>${contaEsc(title)}</h2><p>${contaEsc(text)}</p></div>${kind ? `<button class="button button-primary compact-action" data-create="${kind}" type="button">+ Novo</button>` : ""}</section>`;
const records = async (path, key) => (await api(path))[key] || [];
const field = (name, label, type = "text", extra = {}) => ({ name, label, type, ...extra });
createConfig.contato = { title: "Novo contato", endpoint: "/api/contacts", fields: [field("name", "Nome", "text", { required: true }), field("email", "E-mail", "email"), field("phone", "Telefone"), field("role", "Cargo"), field("notes", "Observações"), field("company_id", "Empresa", "select", { options: [] })] };
createConfig.empresa = { title: "Nova empresa", endpoint: "/api/companies", fields: [field("name", "Nome", "text", { required: true }), field("document", "CNPJ"), field("email", "E-mail", "email"), field("phone", "Telefone"), field("website", "Website", "url"), field("address", "Endereço")] };
createConfig.contato.fields.push(field("department", "Departamento"), field("document", "CPF"), field("birth_date", "Data de nascimento", "date", { required: false }), field("city", "Cidade"), field("state", "Estado"), field("preferred_channel", "Canal preferido"), field("contact_type", "Tipo de contato"), field("source", "Origem"), field("owner", "Responsável interno"), field("tags", "Etiquetas"), field("is_primary", "Contato principal", "checkbox"));
createConfig.empresa.fields.push(field("legal_name", "Razão social"), field("trade_name", "Nome fantasia"), field("state_registration", "Inscrição estadual"), field("municipal_registration", "Inscrição municipal"), field("status", "Situação"), field("founded_on", "Data de abertura", "date", { required: false }), field("size", "Porte"), field("segment", "Segmento"), field("primary_activity", "Atividade principal"), field("whatsapp", "WhatsApp"), field("zip_code", "CEP", "text", { required: false, cepLookup: true }), field("street", "Rua"), field("street_number", "Número"), field("city", "Cidade"), field("state", "Estado"), field("country", "País"), field("internal_owner", "Responsável interno"), field("source", "Origem"));
createConfig.cliente = { title: "Novo cliente", endpoint: "/api/clients", fields: [field("name", "Nome", "text", { required: true }), field("company_id", "Empresa", "select", { options: [] }), field("contact_id", "Contato", "select", { options: [] }), field("email", "E-mail", "email"), field("phone", "Telefone"), field("status", "Status", "select", { options: [["active", "Ativo"], ["inactive", "Inativo"], ["churned", "Cancelado"]] })] };
createConfig.cliente.fields[5].options = [["lead", "Lead"], ["prospecting", "Prospectando"], ["active", "Cliente ativo"], ["inactive", "Cliente inativo"], ["blocked", "Bloqueado"]];
createConfig.cliente.fields.push(field("legal_name", "Razão social", "text", { required: false }), field("trade_name", "Nome fantasia", "text", { required: false }), field("person_type", "Pessoa física ou jurídica", "select", { options: [["person", "Pessoa física"], ["company", "Pessoa jurídica"]] }), field("document", "CPF/CNPJ", "text", { required: false }), field("responsible_name", "Responsável", "text", { required: false }), field("responsible_role", "Cargo", "text", { required: false }), field("whatsapp", "WhatsApp", "tel", { required: false }), field("secondary_phone", "Telefone secundário", "tel", { required: false }), field("website", "Site", "url", { required: false }), field("instagram", "Instagram", "text", { required: false }), field("linkedin", "LinkedIn", "url", { required: false }), field("preferred_channel", "Canal preferido", "text", { required: false }), field("zip_code", "CEP", "text", { required: false, cepLookup: true }), field("street", "Rua", "text", { required: false }), field("street_number", "Número", "text", { required: false }), field("complement", "Complemento", "text", { required: false }), field("neighborhood", "Bairro", "text", { required: false }), field("city", "Cidade", "text", { required: false }), field("state", "Estado", "text", { required: false }), field("country", "País", "text", { required: false }), field("segment", "Segmento", "text", { required: false }), field("services_interest", "Serviços de interesse", "text", { required: false }), field("main_need", "Necessidade principal", "text", { required: false }), field("sales_owner", "Responsável comercial", "text", { required: false }), field("lead_temperature", "Temperatura", "select", { options: [["cold", "Frio"], ["warm", "Morno"], ["hot", "Quente"]] }), field("last_contact_at", "Último contato", "datetime-local", { required: false }), field("next_contact_at", "Próximo contato", "datetime-local", { required: false }), field("next_action", "Próxima ação", "text", { required: false }), field("estimated_budget", "Orçamento estimado", "number", { required: false }), field("monthly_fee", "Mensalidade", "number", { required: false }), field("financial_status", "Situação financeira", "text", { required: false }), field("internal_notes", "Observações internas", "text", { required: false }));
async function prepareCreate(kind, shouldOpen = true) { if (kind === "contato" || kind === "cliente") { const [companies, contacts] = await Promise.all([records("/api/companies", "companies"), kind === "cliente" ? records("/api/contacts", "contacts") : Promise.resolve([])]); const config = createConfig[kind]; config.fields.find((x) => x.name === "company_id").options = [["", "Sem empresa"], ...companies.map((x) => [x.id, x.name])]; if (kind === "cliente") config.fields.find((x) => x.name === "contact_id").options = [["", "Sem contato"], ...contacts.map((x) => [x.id, x.name])]; } if (shouldOpen) openCreateDialog(kind); }
function tableRows(rows, type) { return rows.map((r) => `<article class="conta-row" data-q="${contaEsc(`${r.name || ""} ${r.email || ""} ${r.document || ""}`.toLowerCase())}"><div><strong>${contaEsc(r.name)}</strong><small>${contaEsc(r.email || r.document || r.phone || "Sem dados adicionais")}</small></div>${type === "client" ? `<span class="status-pill">${contaStatus[r.status] || contaEsc(r.status)}</span>` : type === "company" ? `<small>${contaEsc(r.address || r.phone || "")}</small>` : `<small>${contaEsc(r.role || r.phone || "")}</small>`}<button class="compact-action" data-detail="${r.id}" data-detail-type="${type}" type="button">Detalhes</button>${type === "client" ? `<button class="compact-action" data-portal="${r.id}" type="button">Gerar link do portal</button>` : ""}<button class="compact-action" data-edit="${r.id}" data-edit-type="${type}" type="button">Editar</button><button class="compact-action" data-remove="${r.id}" data-remove-type="${type}" type="button">Excluir</button></article>`).join(""); }
async function renderList(kind, title, description, path, key, type) { dashboardGrid.innerHTML = contaIntro(title, description, kind) + contaState("loading", "Carregando..."); try { const rows = await records(path, key); dashboardGrid.innerHTML = contaIntro(title, description, kind) + `<section class="data-card contas-list"><div class="section-heading"><h2>${contaEsc(title)}</h2><input data-conta-search placeholder="Buscar..." aria-label="Buscar" /></div><div class="conta-rows">${rows.length ? tableRows(rows, type) : contaState("empty", `Nenhum registro de ${title.toLowerCase()}.`)}</div></section>`; bindList(rows, type, path); } catch (e) { dashboardGrid.innerHTML = contaIntro(title, description, kind) + contaState("error", e.message); bindCreateButtons(); } }
function bindCreateButtons() { dashboardGrid.querySelectorAll("[data-create]").forEach((b) => b.addEventListener("click", () => prepareCreate(b.dataset.create))); }
function bindList(rows, type, path) { bindCreateButtons(); const input = dashboardGrid.querySelector("[data-conta-search]"); input?.addEventListener("input", () => { const q = input.value.toLowerCase(); dashboardGrid.querySelectorAll(".conta-row").forEach((x) => { x.hidden = q && !x.dataset.q.includes(q); }); }); dashboardGrid.querySelectorAll("[data-portal]").forEach((b) => b.addEventListener("click", async () => { b.disabled = true; try { const d = await api(`/api/clients/${b.dataset.portal}/portal-link`, { method: "POST", body: {} }); const link = `${location.origin}/api/portal/${d.token}`; await navigator.clipboard?.writeText(link); b.textContent = "Link copiado"; const note = document.createElement("small"); note.textContent = link; b.parentElement.append(note); } catch (e) { b.disabled = false; b.textContent = e.message; } })); dashboardGrid.querySelectorAll("[data-remove]").forEach((b) => b.addEventListener("click", async () => { if (b.dataset.confirm !== "1") { b.dataset.confirm = "1"; b.textContent = "Confirmar"; return; } await api(`/api/${type === "contact" ? "contacts" : type === "company" ? "companies" : "clients"}/${b.dataset.remove}`, { method: "DELETE" }); renderHashRoute(); })); dashboardGrid.querySelectorAll("[data-edit]").forEach((b) => b.addEventListener("click", () => { const r = rows.find((x) => String(x.id) === b.dataset.edit); if (!r) return; const kind = type === "contact" ? "contato" : type === "company" ? "empresa" : "cliente"; openEditDialog(kind, r, `/api/${type === "contact" ? "contacts" : type === "company" ? "companies" : "clients"}/${r.id}`); })); dashboardGrid.querySelectorAll("[data-detail]").forEach((b) => b.addEventListener("click", () => { const record = rows.find((x) => String(x.id) === b.dataset.detail); type === "client" ? openClientDetails(record) : openDetails(record, type); })); }
function openDetails(record, type) { if (!record) return; const panel = document.createElement("aside"); panel.className = "conta-drawer"; panel.innerHTML = `<button class="conta-close" type="button">×</button><p class="card-kicker">Detalhes</p><h2>${contaEsc(record.name)}</h2><dl>${Object.entries(record).filter(([k]) => !["id", "organization_id"].includes(k)).map(([k, v]) => `<dt>${contaEsc(k.replaceAll("_", " "))}</dt><dd>${contaEsc(contaStatus[v] || v || "—")}</dd>`).join("")}</dl><div class="conta-related" data-related></div>`; document.body.append(panel); panel.querySelector(".conta-close").onclick = () => panel.remove(); if (type === "company") Promise.all([records("/api/contacts", "contacts"), records("/api/clients", "clients")]).then(([c, l]) => { panel.querySelector("[data-related]").innerHTML = `<h3>Vínculos</h3><p>Contatos: ${c.filter((x) => String(x.company_id) === String(record.id)).map((x) => contaEsc(x.name)).join(", ") || "Nenhum"}</p><p>Clientes: ${l.filter((x) => String(x.company_id) === String(record.id)).map((x) => contaEsc(x.name)).join(", ") || "Nenhum"}</p>`; }); if (type === "client") records(`/api/contracts?client_id=${record.id}`, "contracts").then((c) => { const total = c.reduce((a, x) => a + Number(x.value || 0), 0); panel.querySelector("[data-related]").innerHTML = `<h3>Contratos</h3><p>Total: ${contaMoney(total)}</p>${c.map((x) => `<p>${contaEsc(x.name)} — ${contaMoney(x.value)}</p>`).join("") || "<p>Nenhum contrato.</p>"}`; }); }
async function renderCnpj() { dashboardGrid.innerHTML = contaIntro("Consulta CNPJ", "Consulte dados cadastrais e salve uma empresa qualificada.") + `<section class="data-card cnpj-card"><form data-cnpj-form><label>CNPJ<input name="cnpj" inputmode="numeric" placeholder="00.000.000/0000-00" required /></label><button class="button button-primary" type="submit">Consultar</button></form><div data-cnpj-result>${contaState("empty", "Digite um CNPJ para consultar.")}</div></section>`; dashboardGrid.querySelector("[data-cnpj-form]").onsubmit = async (e) => { e.preventDefault(); const cnpj = e.target.cnpj.value; dashboardGrid.querySelector("[data-cnpj-result]").innerHTML = contaState("loading", "Consultando..."); try { const d = await api(`/api/cnpj/${encodeURIComponent(cnpj)}`); const name = d.nome_fantasia || d.razao_social; dashboardGrid.querySelector("[data-cnpj-result]").innerHTML = `<div class="cnpj-result"><h3>${contaEsc(name)}</h3><p>${contaEsc(d.razao_social)} · ${contaEsc(d.municipio)} / ${contaEsc(d.uf)}</p><p>${contaEsc(d.email || "")} ${contaEsc(d.telefone || "")}</p><button class="button button-secondary" data-save-cnpj type="button">Criar empresa com estes dados</button></div>`; dashboardGrid.querySelector("[data-save-cnpj]").onclick = async () => { const button = dashboardGrid.querySelector("[data-save-cnpj]"); button.disabled = true; try { await api("/api/companies", { method: "POST", body: { name: d.razao_social || name, trade_name: d.nome_fantasia, document: d.cnpj, email: d.email, phone: d.telefone, status: d.situacao, founded_on: d.abertura, primary_activity: d.cnae, zip_code: d.cep, street: d.logradouro, street_number: d.numero, complement: d.complemento, neighborhood: d.bairro, city: d.municipio, state: d.uf, country: "Brasil", address: [d.logradouro, d.numero, d.bairro, d.municipio, d.uf].filter(Boolean).join(", ") } }); button.textContent = "Empresa criada"; } catch (error) { button.disabled = false; button.textContent = error.message; } }; } catch (err) { dashboardGrid.querySelector("[data-cnpj-result]").innerHTML = contaState("error", err.message); } }; }
const contaOpenEditDialog = openEditDialog;
openEditDialog = function openContaEditDialog(kind, record, endpoint) {
  if (kind === "contato" || kind === "cliente") {
    prepareCreate(kind, false).then(() => contaOpenEditDialog(kind, record, endpoint)).catch((error) => window.ui?.toast?.(error.message, "error"));
    return;
  }
  contaOpenEditDialog(kind, record, endpoint);
};

async function openClientDetails(record) {
  if (!record) return;
  const panel = document.createElement("aside"); panel.className = "conta-drawer conta-drawer-wide";
  panel.innerHTML = `<button class="conta-close" type="button">&times;</button><p class="card-kicker">Visao 360</p><h2>${contaEsc(record.name)}</h2><div class="conta-overview" data-overview>${contaState("loading", "Carregando dados do cliente...")}</div>`;
  document.body.append(panel); panel.querySelector(".conta-close").onclick = () => panel.remove();
  try {
    const data = await api(`/api/clients/${record.id}/overview`); const money = (v) => contaMoney(v);
    const rows = (items, empty) => items.length ? items : `<p class="conta-muted">${empty}</p>`;
    panel.querySelector("[data-overview]").innerHTML = `<div class="conta-overview-stats"><div><small>Conversas</small><strong>${data.conversations.length}</strong></div><div><small>Projetos ativos</small><strong>${data.summary.active_projects}</strong></div><div><small>Tarefas</small><strong>${data.tasks.length}</strong></div><div><small>A receber</small><strong>${money(data.receivables.filter((x) => !x.paid_at).reduce((a, x) => a + Number(x.amount || 0), 0))}</strong></div></div><section><h3>Contato e empresa</h3><p>${contaEsc(data.client.contact_name || "Sem contato")} · ${contaEsc(data.client.contact_phone || data.client.phone || "Sem telefone")}</p><p>${contaEsc(data.client.company_name || "Sem empresa")}</p></section><section><h3>WhatsApp e conversas</h3>${rows(data.conversations.map((x) => `<p><strong>${contaEsc(x.subject)}</strong> · ${contaEsc(x.last_message || "Sem mensagens")}</p>`).join(""), "Nenhuma conversa vinculada.")}</section><section><h3>Projetos e tarefas</h3>${rows([...data.projects.map((x) => `<p><strong>${contaEsc(x.name)}</strong> · ${contaEsc(contaStatus[x.status] || x.status)} · ${Number(x.progress || 0)}%</p>`), ...data.tasks.slice(0, 10).map((x) => `<p>↳ ${contaEsc(x.title)} · ${contaEsc(x.status || "pendente")}</p>`)].join(""), "Nenhum projeto ou tarefa vinculada.")}</section><section><h3>Contratos</h3>${rows(data.contracts.map((x) => `<p><strong>${contaEsc(x.name)}</strong> · ${contaEsc(contaStatus[x.status] || x.status)} · ${money(x.value)}</p>`).join(""), "Nenhum contrato.")}</section><section><h3>Propostas</h3>${rows(data.proposals.map((x) => `<p><strong>${contaEsc(x.title)}</strong> · ${contaEsc(x.status)} · ${money(x.amount)}</p>`).join(""), "Nenhuma proposta.")}</section><section><h3>Contas a receber</h3>${rows(data.receivables.map((x) => `<p><strong>${contaEsc(x.description)}</strong> · ${money(x.amount)} · ${contaEsc(x.status)}</p>`).join(""), "Nenhuma conta encontrada.")}</section><section><h3>Histórico de atividades</h3>${rows(data.activities.map((x) => `<p><strong>${contaEsc(x.action)}</strong> · ${contaEsc(x.entity_type)} · ${new Date(x.created_at).toLocaleString("pt-BR")}</p>`).join(""), "Nenhuma atividade registrada.")}</section>`;
  } catch (error) { panel.querySelector("[data-overview]").innerHTML = contaState("error", error.message); }
}

async function renderPortal() { return renderList("cliente", "Portal do cliente", "Gere links seguros para clientes acompanharem contratos e contas em aberto.", "/api/clients", "clients", "client"); }
const portalAccessObserver = new MutationObserver(() => {
  if (location.hash.replace(/^#/, "") !== "portal-do-cliente") return;
  dashboardGrid.querySelectorAll("[data-portal]").forEach((source) => {
    if (source.parentElement.querySelector("[data-portal-access]")) return;
    const button = document.createElement("button"); button.type = "button"; button.className = "compact-action"; button.dataset.portalAccess = source.dataset.portal; button.textContent = "Configurar acesso";
    button.addEventListener("click", () => {
      const panel = document.createElement("aside"); panel.className = "conta-drawer"; panel.innerHTML = `<button class="conta-close" type="button">×</button><p class="card-kicker">Portal do cliente</p><h2>Acesso individual</h2><p class="conta-muted">Defina as credenciais do cliente. A senha é armazenada de forma protegida e nunca aparece novamente.</p><form data-portal-access-form><label>E-mail de acesso<input name="email" type="email" autocomplete="username" required></label><label>Nova senha<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirmar senha<input name="confirmation" type="password" minlength="8" autocomplete="new-password" required></label><button class="button button-primary" type="submit">Salvar acesso</button><output data-portal-access-result role="status"></output></form>`; document.body.append(panel); panel.querySelector(".conta-close").onclick = () => panel.remove(); panel.querySelector("form").onsubmit = async (event) => { event.preventDefault(); const form = event.currentTarget, values = Object.fromEntries(new FormData(form)); const result = panel.querySelector("[data-portal-access-result]"); if (values.password !== values.confirmation) { result.textContent = "As senhas não conferem."; return; } const submit = form.querySelector("button[type=submit]"); submit.disabled = true; result.textContent = "Salvando..."; try { await api(`/api/clients/${button.dataset.portalAccess}/portal-access`, { method: "PUT", body: { email: values.email, password: values.password } }); result.textContent = "Acesso configurado com sucesso."; form.reset(); } catch (error) { result.textContent = error.message; } finally { submit.disabled = false; } };
    }); source.parentElement.append(button);
  });
});
portalAccessObserver.observe(dashboardGrid, { childList: true, subtree: true });
registerRoutes({ contatos: () => renderList("contato", "Contatos", "Pessoas e vínculos da sua operação.", "/api/contacts", "contacts", "contact"), empresas: () => renderList("empresa", "Empresas", "Organizações conectadas ao workspace.", "/api/companies", "companies", "company"), clientes: () => renderList("cliente", "Clientes", "Saúde e relacionamento da sua carteira.", "/api/clients", "clients", "client"), "consulta-cnpj": renderCnpj, "portal-do-cliente": renderPortal });
