/* Tela operacional de contas a pagar. */
const payableEsc = (value) => escapeHtml(value ?? "");
const payableMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const payableDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const payableStatus = { pending: "Pendente", overdue: "Vencida", paid: "Paga", cancelled: "Cancelada" };

async function renderPayablesScreen() {
  const title = "Contas a pagar", description = "Controle compromissos futuros, vencimentos e pagamentos dos fornecedores.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-payable-new type="button">+ Nova conta</button></section>${stateBlock.loading("Carregando contas a pagar...")}`;
  try {
    const items = (await api("/api/payables")).payables || [], open = items.filter((item) => !["paid", "cancelled"].includes(item.status));
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-payable-new type="button">+ Nova conta</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Em aberto</span><strong>${payableMoney(open.reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></article><article class="data-card finance-metric"><span>Vencidas</span><strong>${payableMoney(items.filter((item) => item.status === "overdue").reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></article><article class="data-card finance-metric"><span>Pendentes</span><strong>${items.filter((item) => item.status === "pending").length}</strong></article><article class="data-card finance-metric"><span>Pagas</span><strong>${items.filter((item) => item.status === "paid").length}</strong></article></section><section class="data-card finance-list"><div class="finance-toolbar"><input type="search" data-payable-search placeholder="Buscar descrição ou fornecedor" aria-label="Buscar conta a pagar"><select data-payable-filter aria-label="Filtrar status"><option value="">Todos os status</option><option value="pending">Pendentes</option><option value="overdue">Vencidas</option><option value="paid">Pagas</option><option value="cancelled">Canceladas</option></select></div>${items.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Descrição</th><th>Fornecedor</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr data-payable-row data-status="${payableEsc(item.status || "")}"><td>${payableEsc(item.description)}</td><td>${payableEsc(item.supplier || "—")}</td><td>${payableMoney(item.amount)}</td><td>${payableDate(item.due_at)}</td><td><span class="finance-status ${item.status === "paid" ? "positive" : item.status === "overdue" ? "warning" : "neutral"}">${payableStatus[item.status] || payableEsc(item.status)}</span></td><td>${["pending", "overdue"].includes(item.status) ? `<button class="compact-action" data-payable-pay="${item.id}" type="button">Registrar pagamento</button>` : ""}<button class="compact-action" data-payable-delete="${item.id}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhuma conta a pagar", "Cadastre um compromisso para acompanhar o vencimento.", "Criar agora", "payable-empty")}</section>`;
    dashboardGrid.querySelector("[data-payable-new]")?.addEventListener("click", () => openCreateDialog("payable"));
    dashboardGrid.querySelector("[data-payable-empty]")?.addEventListener("click", () => openCreateDialog("payable"));
    const filter = () => { const query = dashboardGrid.querySelector("[data-payable-search]").value.toLocaleLowerCase("pt-BR"), status = dashboardGrid.querySelector("[data-payable-filter]").value; dashboardGrid.querySelectorAll("[data-payable-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (status && row.dataset.status !== status); }); };
    dashboardGrid.querySelector("[data-payable-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-payable-filter]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-payable-pay]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/payables/${button.dataset.payablePay}/record-payment`, { method: "POST", body: {} }); toast("Pagamento registrado e despesa confirmada.", "success"); renderPayablesScreen(); } catch (error) { button.disabled = false; toast(error.message, "error"); } }));
    dashboardGrid.querySelectorAll("[data-payable-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir conta a pagar?", onConfirm: async () => { await api(`/api/payables/${button.dataset.payableDelete}`, { method: "DELETE" }); toast("Conta excluída.", "success"); renderPayablesScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "payable-retry")}`; dashboardGrid.querySelector("[data-state-retry], .state-retry")?.addEventListener("click", renderPayablesScreen); }
}

registerRoutes({ "contas-a-pagar": renderPayablesScreen });
