/* ==========================================================================
   FocusDev — módulo "crm"
   Telas: CRM comercial, Leads, Campanhas, Funil, Oportunidades, Propostas, Follow-ups
   Carregado depois de app.js; usa os helpers globais do núcleo
   (dashboardGrid, escapeHtml, openCreateDialog, api, stateBlock, registerRoutes).
   Ownership: modules/crm.js
   ========================================================================== */

function renderLeadsView() {
  const stageConfig = [["new", "Novo lead", "#3b82f6"], ["contacted", "Contato", "#8b5cf6"], ["qualified", "Qualificação", "#8b5cf6"], ["proposal", "Proposta", "#f59e0b"], ["won", "Ganho", "#22c55e"], ["lost", "Perdido", "#f3132d"]];
  const stageLabels = Object.fromEntries(stageConfig.map(([status, label]) => [status, label]));
  const renderShell = (leads, message = "") => {
    const counts = leads.reduce((result, lead) => { result[lead.status] = (result[lead.status] || 0) + 1; return result; }, {});
    const stages = stageConfig.slice(0, 4).map(([status, name, color]) => [name, String(counts[status] || 0), color]);
    const rows = message ? `<p class="agenda-empty" role="${message.includes("Não foi") ? "alert" : "status"}">${escapeHtml(message)}</p>` : leads.length ? leads.map((lead) => {
      const name = String(lead.name || "Sem nome"), initials = name.split(" ").map((part) => part[0]).join("").slice(0, 2);
      const stage = stageLabels[lead.status] || lead.status || "Novo lead";
      const value = lead.amount == null || lead.amount === "" ? "—" : `R$ ${Number(lead.amount).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`;
      return `<article class="lead-row"><span class="lead-avatar">${escapeHtml(initials)}</span><div><strong>${escapeHtml(name)}</strong><small>${escapeHtml(lead.company || "Sem empresa")}</small></div><span class="lead-stage-name">${escapeHtml(stage)}</span><strong class="lead-value">${escapeHtml(value)}</strong><span class="inbox-tag">${escapeHtml(lead.source || "Sem origem")}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`;
    }).join("") : '<p class="agenda-empty" role="status">Nenhum lead cadastrado.</p>';
    dashboardGrid.innerHTML = `<section class="page-intro leads-intro"><div><p class="card-kicker">CRM</p><h2>Leads</h2><p>Transforme conversas em oportunidades e mantenha cada etapa sob controle.</p></div><button class="button button-primary compact-action lead-new" type="button">+ Novo lead</button></section><section class="lead-funnel">${stages.map(([name, count, color]) => `<article class="lead-stage" style="--stage-color:${color}"><span>${name}</span><strong>${count}</strong><small>oportunidades</small></article>`).join("")}</section><section class="data-card leads-card"><div class="section-heading"><div><p class="card-kicker">Pipeline comercial</p><h2>Oportunidades recentes</h2></div><button class="filter-button" type="button">Filtrar <span>⌄</span></button></div><div class="lead-list">${rows}</div></section>`;
    dashboardGrid.querySelector(".lead-new")?.addEventListener("click", () => openCreateDialog("lead"));
  };
  renderShell([], "Carregando leads...");
  fetch("/api/leads", { credentials: "same-origin" }).then(async (response) => {
    const data = response.ok ? await response.json() : {};
    if (!response.ok) throw new Error(data.error || "Não foi possível carregar os leads.");
    renderShell(Array.isArray(data.leads) ? data.leads : []);
  }).catch((error) => renderShell([], error.message || "Não foi possível carregar os leads."));
}

function renderLeadsLegacyView() {
  const leads = [
  ];
  const stages = [["Novo lead", "2", "#3b82f6"], ["Qualificacao", "4", "#8b5cf6"], ["Proposta", "2", "#f59e0b"], ["Negociacao", "1", "#f3132d"]];
  dashboardGrid.innerHTML = `<section class="page-intro leads-intro"><div><p class="card-kicker">CRM</p><h2>Leads</h2><p>Transforme conversas em oportunidades e mantenha cada etapa sob controle.</p></div><button class="button button-primary compact-action lead-new" type="button">+ Novo lead</button></section><section class="lead-funnel">${stages.map(([name, count, color]) => `<article class="lead-stage" style="--stage-color:${color}"><span>${name}</span><strong>${count}</strong><small>oportunidades</small></article>`).join("")}</section><section class="data-card leads-card"><div class="section-heading"><div><p class="card-kicker">Pipeline comercial</p><h2>Oportunidades recentes</h2></div><button class="filter-button" type="button">Filtrar <span>⌄</span></button></div><div class="lead-list">${leads.map(([name, company, stage, value, tag]) => `<article class="lead-row"><span class="lead-avatar">${name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div><strong>${name}</strong><small>${company}</small></div><span class="lead-stage-name">${stage}</span><strong class="lead-value">${value}</strong><span class="inbox-tag">${tag}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`).join("")}</div></section>`;
  dashboardGrid.querySelector(".lead-new")?.addEventListener("click", () => openCreateDialog("lead"));
}

function renderCampaignsView() {
  const campaigns = [["Lançamento FocusDev", "Instagram · Meta Ads", "R$ 12.400", "24,8%", "Ativa", "spiderman-card-hero.png"], ["Retargeting Nexum", "Google · Display", "R$ 8.960", "18,2%", "Ativa", "spiderman-card-web.png"], ["Conteúdo de autoridade", "LinkedIn · Orgânico", "R$ 0", "11,4%", "Rascunho", "spiderman-card-duo.png"]];
  dashboardGrid.innerHTML = `<section class="page-intro campaigns-intro"><div><p class="card-kicker">Marketing</p><h2>Campanhas</h2><p>Planeje, acompanhe e otimize suas ações em um só lugar.</p></div><button class="button button-primary compact-action campaign-new" type="button">+ Nova campanha</button></section><section class="campaign-metrics"><article class="data-card"><span>Investimento total</span><strong>R$ 21.360</strong><small class="positive">↑ 12,8% este mês</small></article><article class="data-card"><span>Conversões</span><strong>184</strong><small class="positive">↑ 8,4% contra o período anterior</small></article><article class="data-card"><span>ROI médio</span><strong>3,8x</strong><small class="neutral">Todas as campanhas</small></article></section><section class="data-card campaigns-card"><div class="section-heading"><div><p class="card-kicker">Visão geral</p><h2>Campanhas recentes</h2></div><button class="filter-button" type="button">Filtrar <span>⌄</span></button></div><div class="campaign-list">${campaigns.map(([name, channel, spend, ctr, status, image]) => `<article class="campaign-row" style="--campaign-image:url('assets/${image}')"><div class="campaign-thumb"></div><div class="campaign-main"><strong>${name}</strong><small>${channel}</small><div class="campaign-progress"><span style="width:${status === "Rascunho" ? "32" : "78"}%"></span></div></div><div class="campaign-stat"><small>Investimento</small><strong>${spend}</strong></div><div class="campaign-stat"><small>CTR</small><strong>${ctr}</strong></div><span class="campaign-status ${status === "Ativa" ? "is-active" : "is-draft"}">${status}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`).join("")}</div></section>`;
}

function renderFunnelView() {
  const stages = [
    ["Entrada", "12 leads", "R$ 86.400", "spiderman-card-web.png", [["Lucas Andrade", "Nexum", "R$ 12.000"], ["Marina Lopes", "Orbit", "R$ 8.400"]]],
    ["Qualificacao", "8 leads", "R$ 64.800", "spiderman-card-duo.png", [["Bruno Almeida", "Acme Inc.", "R$ 24.000"], ["Fernanda Reis", "Vertice", "R$ 18.500"]]],
    ["Proposta", "4 leads", "R$ 42.300", "spiderman-card-hero.png", [["Carolina Mendes", "Vértice", "R$ 18.500"], ["Diego Nunes", "Orbit", "R$ 23.800"]]],
    ["Fechamento", "2 leads", "R$ 31.200", "agenda-spider-red-emblem.png", [["Rafael Costa", "Nexum", "R$ 17.200"], ["Joana Silva", "Acme Inc.", "R$ 14.000"]]]
  ];
  dashboardGrid.innerHTML = `<section class="page-intro funnel-intro"><div><p class="card-kicker">CRM</p><h2>Funil de vendas</h2><p>Visualize o caminho de cada oportunidade e saiba onde agir agora.</p></div><button class="button button-primary compact-action funnel-new" type="button">+ Nova oportunidade</button></section><section class="funnel-toolbar"><div><strong>Pipeline comercial</strong><span>26 oportunidades em andamento</span></div><div><button class="filter-button funnel-filter" type="button">Todos os responsáveis</button><button class="filter-button funnel-view" type="button">▦ Compacto</button></div></section><section class="funnel-board">${stages.map(([name, count, total, image, cards]) => `<section class="funnel-column" style="--funnel-image:url('assets/${image}')"><header><div><h3>${name}</h3><span>${count}</span></div><strong>${total}</strong></header><div class="funnel-column-list">${cards.map(([person, company, value]) => `<article class="funnel-opportunity"><div class="funnel-opportunity-top"><span class="lead-avatar">${person.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></div><strong>${person}</strong><small>${company}</small><div><b>${value}</b><span>Atualizado hoje</span></div></article>`).join("")}<button class="funnel-add" type="button">+ Adicionar oportunidade</button></div></section>`).join("")}</section>`;
  dashboardGrid.querySelector(".funnel-new")?.addEventListener("click", () => openCreateDialog("lead"));
  dashboardGrid.querySelectorAll(".funnel-add").forEach((button) => button.addEventListener("click", () => openCreateDialog("lead")));
}

function renderOpportunitiesView() {
  const opportunities = [["Website institucional", "Acme Inc.", "R$ 24.000", "78%", "30 set", "Alta"], ["Aplicativo mobile", "Vertice", "R$ 42.800", "54%", "14 out", "Media"], ["Campanha de lancamento", "Nexum", "R$ 18.400", "32%", "22 out", "Baixa"], ["Portal do cliente", "Orbit", "R$ 31.200", "86%", "28 set", "Alta"]];
  dashboardGrid.innerHTML = `<section class="page-intro opportunities-intro"><div><p class="card-kicker">CRM</p><h2>Oportunidades</h2><p>Priorize negociações pelo valor, probabilidade e próximo passo.</p></div><button class="button button-primary compact-action opportunity-new" type="button">+ Nova oportunidade</button></section><section class="opportunity-summary"><article class="data-card"><span>Pipeline total</span><strong>R$ 116.400</strong><small class="positive">↑ 18,4% no mês</small></article><article class="data-card"><span>Valor ponderado</span><strong>R$ 72.860</strong><small class="neutral">Por probabilidade de fechamento</small></article><article class="data-card"><span>Fechamento previsto</span><strong>3</strong><small class="warning">Precisam de atenção</small></article></section><section class="data-card opportunities-card"><div class="section-heading"><div><p class="card-kicker">Negociações abertas</p><h2>Carteira comercial</h2></div><div class="opportunity-actions"><button class="filter-button" type="button">Filtros</button><button class="filter-button" type="button">Exportar</button></div></div><div class="opportunity-list">${opportunities.map(([name, company, value, probability, due, priority]) => `<article class="opportunity-row"><span class="opportunity-icon">◈</span><div class="opportunity-name"><strong>${name}</strong><small>${company}</small></div><div><small>Valor</small><strong>${value}</strong></div><div><small>Chance</small><strong>${probability}</strong></div><div><small>Próximo passo</small><strong>${due}</strong></div><span class="priority-pill priority-${priority.toLowerCase()}">${priority}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`).join("")}</div></section>`;
  dashboardGrid.querySelector(".opportunity-new")?.addEventListener("click", () => openCreateDialog("lead"));
}

function renderProposalsView() {
  const proposals = [["Proposta comercial · Website", "Acme Inc.", "R$ 24.000", "Enviada", "28 set", "spiderman-card-hero.png"], ["Escopo aplicativo mobile", "Vertice", "R$ 42.800", "Em revisao", "02 out", "spiderman-card-web.png"], ["Plano de crescimento Q4", "Nexum", "R$ 18.400", "Rascunho", "—", "spiderman-card-duo.png"]];
  dashboardGrid.innerHTML = `<section class="page-intro proposals-intro"><div><p class="card-kicker">CRM</p><h2>Propostas</h2><p>Crie propostas claras, acompanhe respostas e acelere o fechamento.</p></div><button class="button button-primary compact-action proposal-new" type="button">+ Nova proposta</button></section><section class="proposal-stats"><article class="data-card"><span>Em aberto</span><strong>02</strong><small>R$ 66.800 em negociação</small></article><article class="data-card"><span>Taxa de aceite</span><strong>68%</strong><small class="positive">↑ 6,2% este mês</small></article><article class="data-card"><span>Tempo médio</span><strong>4,2 dias</strong><small>Da criação ao envio</small></article></section><section class="data-card proposals-card"><div class="section-heading"><div><p class="card-kicker">Documentos comerciais</p><h2>Propostas recentes</h2></div><button class="filter-button" type="button">Filtrar <span>⌄</span></button></div><div class="proposal-list">${proposals.map(([name, client, value, status, due, image]) => `<article class="proposal-row"><div class="proposal-cover" style="--proposal-image:url('assets/${image}')"><span>PDF</span></div><div class="proposal-main"><strong>${name}</strong><small>${client}</small><div><span>${value}</span><em>${due === "—" ? "Sem prazo" : `Válida até ${due}`}</em></div></div><span class="proposal-status proposal-${status.toLowerCase().replace(" ", "-")}">${status}</span><button class="filter-button proposal-open" type="button">Abrir</button><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`).join("")}</div></section>`;
  dashboardGrid.querySelector(".proposal-new")?.addEventListener("click", () => openCreateDialog("projeto"));
  dashboardGrid.querySelectorAll(".proposal-open").forEach((button) => button.addEventListener("click", () => window.alert("Visualização da proposta pronta para receber o documento comercial.")));
}

function renderFollowupsView() {
  const followups = [["Ligar para Carolina Mendes", "Proposta do aplicativo mobile", "Hoje · 14:30", "Alta", "CM"], ["Enviar estudo de caso", "Bruno Almeida · Nexum", "Amanhã · 09:00", "Média", "BA"], ["Confirmar reunião de fechamento", "Diego Nunes · Orbit", "18 set · 16:00", "Alta", "DN"], ["Retomar contato", "Fernanda Reis · Acme Inc.", "20 set · 11:00", "Baixa", "FR"]];
  dashboardGrid.innerHTML = `<section class="page-intro followups-intro"><div><p class="card-kicker">CRM</p><h2>Follow-ups</h2><p>Nunca perca o momento certo de retomar uma conversa comercial.</p></div><button class="button button-primary compact-action followup-new" type="button">+ Novo follow-up</button></section><section class="followup-summary"><article class="data-card"><span>Para hoje</span><strong>01</strong><small class="warning">Prioridade alta</small></article><article class="data-card"><span>Próximos 7 dias</span><strong>04</strong><small>Todos os responsáveis</small></article><article class="data-card"><span>Concluídos no mês</span><strong>18</strong><small class="positive">↑ 22% de produtividade</small></article></section><section class="data-card followups-card"><div class="section-heading"><div><p class="card-kicker">Minha fila</p><h2>Próximos contatos</h2></div><button class="filter-button" type="button">Todos os status</button></div><div class="followup-list">${followups.map(([title, detail, date, priority, initials]) => `<article class="followup-row"><label class="followup-check"><input type="checkbox" /><span></span></label><span class="followup-avatar">${initials}</span><div class="followup-main"><strong>${title}</strong><small>${detail}</small></div><div class="followup-date"><small>Retorno</small><strong>${date}</strong></div><span class="priority-pill priority-${priority.toLowerCase()}">${priority}</span><button class="inbox-more" type="button" aria-label="Mais opcoes">•••</button></article>`).join("")}</div></section>`;
  dashboardGrid.querySelector(".followup-new")?.addEventListener("click", () => openCreateDialog("tarefa"));
}

function renderCRMView() {
  const modules = [["leads", "Leads", "Organize contatos e novas oportunidades.", "spiderman-card-web.png"], ["campanhas", "Campanhas", "Acompanhe desempenho e investimento.", "spiderman-card-hero.png"], ["funil", "Funil", "Veja cada oportunidade avançar.", "spiderman-card-duo.png"], ["oportunidades", "Oportunidades", "Priorize negociações importantes.", "agenda-spider-red-emblem.png"], ["propostas", "Propostas", "Crie e acompanhe documentos comerciais.", "agenda-spider-mask.png"], ["follow-ups", "Follow-ups", "Controle todos os próximos contatos.", "spiderman-hanging.png"]];
  dashboardGrid.innerHTML = `<section class="page-intro crm-intro"><div><p class="card-kicker">Workspace comercial</p><h2>CRM FocusDev</h2><p>Um centro único para controlar relacionamento, pipeline e fechamento.</p></div><button class="button button-primary compact-action" type="button" data-crm-module="leads">+ Novo lead</button></section><section class="crm-overview"><article class="data-card"><span>Pipeline total</span><strong>R$ 116.400</strong><small>26 oportunidades em andamento</small></article><article class="data-card"><span>Próximos contatos</span><strong>04</strong><small>1 prioridade para hoje</small></article><article class="data-card"><span>Propostas abertas</span><strong>02</strong><small>R$ 66.800 em negociação</small></article></section><section class="data-card crm-hub"><div class="section-heading"><div><p class="card-kicker">Módulos do CRM</p><h2>Escolha uma área para continuar</h2></div></div><div class="crm-module-grid">${modules.map(([key, title, description, image]) => `<button class="crm-module-card" type="button" data-crm-module="${key}" style="--crm-image:url('assets/${image}')"><span class="crm-module-icon">✦</span><strong>${title}</strong><small>${description}</small><b>Abrir →</b></button>`).join("")}</div></section>`;
  const actions = { leads: renderLeadsView, campanhas: renderCampaignsView, funil: renderFunnelView, oportunidades: renderOpportunitiesView, propostas: renderProposalsView, "follow-ups": renderFollowupsView };
  dashboardGrid.querySelectorAll("[data-crm-module]").forEach((button) => button.addEventListener("click", () => { const key = button.dataset.crmModule; history.replaceState({}, "", `#${key}`); actions[key]?.(); }));
}


registerRoutes({
  "crm": () => renderCRMView(),
  "leads": () => renderLeadsView(),
  "campanhas": () => renderCampaignsView(),
  "funil": () => renderFunnelView(),
  "oportunidades": () => renderOpportunitiesView(),
  "propostas": () => renderProposalsView(),
  "follow-ups": () => renderFollowupsView(),
});
