/* CRM: telas orientadas a dados reais. */
const CRM_STAGES = ["prospecting", "proposal", "negotiation", "won", "lost"];
const LEAD_STATUS = [["new", "Novo"], ["contacted", "Contatado"], ["qualified", "Qualificado"], ["won", "Ganho"], ["lost", "Perdido"]];
const stageLabel = { prospecting: "Prospecção", proposal: "Proposta", negotiation: "Negociação", won: "Ganho", lost: "Perdido" };
const money = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateBR = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "—";
const esc = (v) => escapeHtml(v == null ? "" : String(v));
const set = (html) => { dashboardGrid.innerHTML = html; };
const statusError = (e) => `<p class="agenda-empty" role="alert">${esc(e.message || "Não foi possível carregar os dados.")} <button class="button button-secondary compact-action" data-retry>Tentar novamente</button></p>`;
const load = (label) => `<p class="agenda-empty" role="status">${esc(label)}</p>`;
function config() {
  createConfig.lead = { title: "Novo lead", endpoint: "/api/leads", fields: [{ name: "name", label: "Nome", type: "text" }, { name: "company", label: "Empresa", type: "text" }, { name: "source", label: "Origem", type: "text" }, { name: "status", label: "Status", type: "select", options: LEAD_STATUS }] };
  createConfig.oportunidade = { title: "Nova oportunidade", endpoint: "/api/opportunities", fields: [{ name: "name", label: "Nome", type: "text" }, { name: "amount", label: "Valor", type: "number" }, { name: "stage", label: "Estágio", type: "select", options: CRM_STAGES.map(x => [x, stageLabel[x]]) }, { name: "expected_close", label: "Previsão", type: "date" }] };
  createConfig.campanha = { title: "Nova campanha", endpoint: "/api/campaigns", fields: [{ name: "name", label: "Nome", type: "text" }, { name: "channel", label: "Canal", type: "select", options: [["email", "E-mail"], ["whatsapp", "WhatsApp"], ["ads", "Ads"], ["social", "Social"], ["other", "Outro"]] }, { name: "budget", label: "Orçamento", type: "number" }, { name: "starts_on", label: "Início", type: "date" }, { name: "ends_on", label: "Fim", type: "date" }] };
  createConfig.proposta = { title: "Nova proposta", endpoint: "/api/proposals", fields: [{ name: "title", label: "Título", type: "text" }, { name: "opportunity_id", label: "Oportunidade", type: "number" }, { name: "amount", label: "Valor", type: "number" }, { name: "valid_until", label: "Válida até", type: "date" }, { name: "notes", label: "Observações", type: "textarea" }] };
  createConfig.followup = { title: "Novo follow-up", endpoint: "/api/followups", fields: [{ name: "lead_id", label: "Lead", type: "number" }, { name: "due_at", label: "Quando", type: "datetime-local" }, { name: "channel", label: "Canal", type: "text" }, { name: "note", label: "Nota", type: "textarea" }] };
}
async function fetchData(path, key) { const d = await api(path); return d[key] || []; }
function intro(kicker, title, text, kind) { return `<section class="page-intro leads-intro"><div><p class="card-kicker">${esc(kicker)}</p><h2>${esc(title)}</h2><p>${esc(text)}</p></div>${kind ? `<button class="button button-primary compact-action" data-create="${kind}">+ Novo</button>` : ""}</section>`; }
function wire() { dashboardGrid.querySelectorAll("[data-create]").forEach(b => b.onclick = () => openCreateDialog(b.dataset.create)); dashboardGrid.querySelector("[data-retry]")?.addEventListener("click", () => renderHashRoute(location.hash)); }
async function renderLeadsView() { set(intro("CRM", "Leads", "Transforme conversas em oportunidades.", "lead") + `<section class="data-card leads-card"><div class="section-heading"><h2>Leads</h2><input class="filter-button" id="lead-search" placeholder="Buscar"/><select class="filter-button" id="lead-filter"><option value="">Todos os status</option>${LEAD_STATUS.map(x => `<option value="${x[0]}">${x[1]}</option>`).join("")}</select></div><div class="lead-list">${load("Carregando leads...")}</div></section>`); wire(); try { const leads = await fetchData("/api/leads", "leads"); const list = dashboardGrid.querySelector(".lead-list"); const draw = () => { const q = (dashboardGrid.querySelector("#lead-search")?.value || "").toLowerCase(), f = dashboardGrid.querySelector("#lead-filter")?.value; const rows = leads.filter(l => (!f || l.status === f) && (!q || `${l.name} ${l.company || ""}`.toLowerCase().includes(q))); list.innerHTML = rows.length ? rows.map(l => `<article class="lead-row"><span class="lead-avatar">${esc((l.name || "?").slice(0, 2).toUpperCase())}</span><div><strong>${esc(l.name)}</strong><small>${esc(l.company || "Sem empresa")}</small></div><select data-status="${l.id}" class="filter-button">${LEAD_STATUS.map(x => `<option value="${x[0]}" ${x[0] === l.status ? "selected" : ""}>${x[1]}</option>`).join("")}</select><button class="button button-secondary compact-action" data-convert="${l.id}">Converter</button><button class="button button-secondary compact-action" data-delete="${l.id}">Excluir</button></article>`).join("") : `<p class="agenda-empty" role="status">Nenhum lead encontrado.</p>`; list.querySelectorAll("[data-status]").forEach(x => x.onchange = async () => { await api(`/api/leads/${x.dataset.status}`, { method: "PATCH", body: { status: x.value } }); }); list.querySelectorAll("[data-convert]").forEach(x => x.onclick = async () => { await api("/api/opportunities", { method: "POST", body: { lead_id: Number(x.dataset.convert), name: "Oportunidade — " + (leads.find(l => l.id == x.dataset.convert)?.name || "Lead"), stage: "prospecting", amount: 0 } }); x.textContent = "Convertido"; x.disabled = true; }); list.querySelectorAll("[data-delete]").forEach(x => x.onclick = async () => { if (x.dataset.confirm !== "1") { x.dataset.confirm = "1"; x.textContent = "Confirmar?"; return; } await api(`/api/leads/${x.dataset.delete}`, { method: "DELETE" }); renderLeadsView(); }); }; draw(); dashboardGrid.querySelector("#lead-search").oninput = draw; dashboardGrid.querySelector("#lead-filter").onchange = draw; } catch (e) { dashboardGrid.querySelector(".lead-list").innerHTML = statusError(e); wire(); } }
async function renderFunnelView() { set(intro("CRM", "Funil de vendas", "Arraste oportunidades entre os estágios.", "oportunidade") + `<section class="funnel-board">${load("Carregando funil...")}</section>`); wire(); try { const ops = await fetchData("/api/opportunities", "opportunities"), board = dashboardGrid.querySelector(".funnel-board"); board.innerHTML = CRM_STAGES.map(s => { const items = ops.filter(o => o.stage === s); return `<section class="funnel-column" data-stage="${s}"><header><h3>${stageLabel[s]}</h3><strong>${money(items.reduce((a,o) => a + Number(o.amount || 0), 0))}</strong></header><div class="funnel-column-list">${items.map(o => `<article class="funnel-opportunity" draggable="true" data-id="${o.id}"><strong>${esc(o.name)}</strong><small>${esc(o.company_name || "")}</small><b>${money(o.amount)}</b></article>`).join("")}</div></section>`; }).join(""); board.querySelectorAll(".funnel-opportunity").forEach(c => c.ondragstart = e => e.dataTransfer.setData("text/plain", c.dataset.id)); board.querySelectorAll(".funnel-column").forEach(col => { col.ondragover = e => e.preventDefault(); col.ondrop = async e => { await api(`/api/opportunities/${e.dataTransfer.getData("text/plain")}`, { method: "PATCH", body: { stage: col.dataset.stage } }); renderFunnelView(); }; }); } catch (e) { dashboardGrid.querySelector(".funnel-board").innerHTML = statusError(e); wire(); } }
async function renderOpportunitiesView() { set(intro("CRM", "Oportunidades", "Priorize negociações pelo valor e previsão.", "oportunidade") + `<section class="data-card opportunities-card"><div class="opportunity-list">${load("Carregando oportunidades...")}</div></section>`); wire(); try { const ops = await fetchData("/api/opportunities", "opportunities"), list = dashboardGrid.querySelector(".opportunity-list"); list.innerHTML = ops.length ? ops.map(o => `<article class="opportunity-row"><div class="opportunity-name"><strong>${esc(o.name)}</strong><small>${esc(o.company_name || "Sem empresa")}</small></div><div><small>Valor</small><strong>${money(o.amount)}</strong></div><div><small>Estágio</small><strong>${esc(stageLabel[o.stage] || o.stage)}</strong></div><div><small>Previsão</small><strong>${dateBR(o.expected_close)}</strong></div></article>`).join("") : `<p class="agenda-empty" role="status">Nenhuma oportunidade cadastrada.</p>`; } catch(e) { dashboardGrid.querySelector(".opportunity-list").innerHTML = statusError(e); wire(); } }
async function renderCampaignsView() { set(intro("Marketing", "Campanhas", "Planeje suas ações comerciais.", "campanha") + `<section class="data-card campaigns-card"><div class="campaign-list">${load("Carregando campanhas...")}</div></section>`); wire(); try { const rows = await fetchData("/api/campaigns", "campaigns"), list = dashboardGrid.querySelector(".campaign-list"); list.innerHTML = rows.length ? rows.map(c => `<article class="campaign-row"><div class="campaign-main"><strong>${esc(c.name)}</strong><small>${esc(c.channel)} · ${money(c.budget)}</small></div><span class="campaign-status">${esc(c.status)}</span><button class="button button-secondary compact-action" data-campaign="${c.id}" data-next="${c.status === "active" ? "paused" : c.status === "paused" ? "active" : "active"}">${c.status === "active" ? "Pausar" : "Ativar"}</button><button class="button button-secondary compact-action" data-done="${c.id}">Concluir</button></article>`).join("") : `<p class="agenda-empty" role="status">Nenhuma campanha cadastrada.</p>`; list.querySelectorAll("[data-campaign]").forEach(b => b.onclick = async () => { await api(`/api/campaigns/${b.dataset.campaign}`, { method: "PATCH", body: { status: b.dataset.next } }); renderCampaignsView(); }); list.querySelectorAll("[data-done]").forEach(b => b.onclick = async () => { await api(`/api/campaigns/${b.dataset.done}`, { method: "PATCH", body: { status: "done" } }); renderCampaignsView(); }); } catch(e) { dashboardGrid.querySelector(".campaign-list").innerHTML = statusError(e); wire(); } }
async function renderProposalsView() { set(intro("CRM", "Propostas", "Acompanhe documentos e respostas.", "proposta") + `<section class="data-card proposals-card"><div class="proposal-list">${load("Carregando propostas...")}</div></section>`); wire(); try { const rows = await fetchData("/api/proposals", "proposals"), list = dashboardGrid.querySelector(".proposal-list"); list.innerHTML = rows.length ? rows.map(p => `<article class="proposal-row"><div class="proposal-main"><strong>${esc(p.title)}</strong><small>${money(p.amount)} · ${esc(p.status)}</small></div>${p.status === "draft" ? `<button class="button button-secondary compact-action" data-prop="${p.id}" data-status="sent">Enviar</button>` : ""}${p.status === "sent" ? `<button class="button button-primary compact-action" data-prop="${p.id}" data-status="accepted">Aceitar</button><button class="button button-secondary compact-action" data-prop="${p.id}" data-status="rejected">Rejeitar</button>` : ""}</article>`).join("") : `<p class="agenda-empty" role="status">Nenhuma proposta cadastrada.</p>`; list.querySelectorAll("[data-prop]").forEach(b => b.onclick = async () => { await api(`/api/proposals/${b.dataset.prop}`, { method: "PATCH", body: { status: b.dataset.status } }); renderProposalsView(); }); } catch(e) { dashboardGrid.querySelector(".proposal-list").innerHTML = statusError(e); wire(); } }
async function renderFollowupsView() {
  set(intro("CRM", "Follow-ups", "Nunca perca o momento certo.", "followup") + `<section class="data-card followups-card"><div class="followup-list">${load("Carregando follow-ups...")}</div></section>`);
  wire();
  try {
    const rows = await fetchData("/api/followups", "followups");
    const list = dashboardGrid.querySelector(".followup-list");
    const now = Date.now();
    const day = 86400000;
    const groups = [
      ["Atrasados", rows.filter((x) => !x.done_at && new Date(x.due_at) < now - day)],
      ["Hoje", rows.filter((x) => !x.done_at && new Date(x.due_at) >= now - day && new Date(x.due_at) < now + day)],
      ["Próximos", rows.filter((x) => !x.done_at && new Date(x.due_at) >= now + day)]
    ];
    list.innerHTML = groups.map(([group, items]) => {
      const markup = items.map((x) => `<article class="followup-row"><div class="followup-main"><strong>${esc(x.note || "Follow-up")}</strong><small>${esc(x.channel || "")} · ${new Date(x.due_at).toLocaleString("pt-BR")}</small></div><button class="button button-secondary compact-action" data-done="${x.id}">Marcar feito</button></article>`).join("");
      return `<h3>${group}</h3>${markup || `<p class="agenda-empty" role="status">Nenhum follow-up pendente.</p>`}`;
    }).join("");
    list.querySelectorAll("[data-done]").forEach((button) => button.onclick = async () => {
      await api(`/api/followups/${button.dataset.done}`, { method: "PATCH", body: { done_at: new Date().toISOString() } });
      renderFollowupsView();
    });
  } catch (error) {
    dashboardGrid.querySelector(".followup-list").innerHTML = statusError(error);
    wire();
  }
}
async function renderCRMView() { set(intro("Workspace comercial", "CRM FocusDev", "Relacionamento, pipeline e fechamento.", "lead") + `<section class="crm-overview">${load("Carregando resumo...")}</section><section class="data-card crm-hub"><h2>Módulos do CRM</h2><div class="crm-module-grid">${["leads", "funil", "oportunidades", "campanhas", "propostas", "follow-ups"].map(k => `<button class="crm-module-card" data-crm-module="${k}"><strong>${k[0].toUpperCase() + k.slice(1)}</strong><small>Abrir área</small></button>`).join("")}</div></section>`); wire(); dashboardGrid.querySelectorAll("[data-crm-module]").forEach(b => b.onclick = () => { location.hash = b.dataset.crmModule; }); try { const [leads, ops] = await Promise.all([fetchData("/api/leads", "leads"), fetchData("/api/opportunities", "opportunities")]); dashboardGrid.querySelector(".crm-overview").innerHTML = `<article class="data-card"><span>Leads</span><strong>${leads.length}</strong><small>${LEAD_STATUS.map(x => `${x[1]}: ${leads.filter(l => l.status === x[0]).length}`).join(" · ")}</small></article><article class="data-card"><span>Funil total</span><strong>${money(ops.reduce((a,o) => a + Number(o.amount || 0), 0))}</strong><small>${ops.length} oportunidades</small></article><article class="data-card"><span>Estágios</span><strong>${ops.filter(o => ["won", "lost"].includes(o.stage)).length}</strong><small>${CRM_STAGES.map(s => `${stageLabel[s]}: ${ops.filter(o => o.stage === s).length}`).join(" · ")}</small></article>`; } catch(e) { dashboardGrid.querySelector(".crm-overview").innerHTML = statusError(e); } }
config(); registerRoutes({ crm: renderCRMView, leads: renderLeadsView, funil: renderFunnelView, oportunidades: renderOpportunitiesView, campanhas: renderCampaignsView, propostas: renderProposalsView, "follow-ups": renderFollowupsView });
