/* ==========================================================================
   FocusDev — módulo "financeiro"
   Telas: Visão financeira, Receitas, Contas a receber, Despesas, Cobranças, Assinaturas, Relatórios
   Carregado depois de app.js; usa os helpers globais do núcleo
   (dashboardGrid, escapeHtml, openCreateDialog, api, stateBlock, registerRoutes).
   Ownership: modules/financeiro.js
   ========================================================================== */

const financeMoney = (value) => `R$ ${Number(value).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`;
const financeRows = {
  receitas: [["Mensalidade · Website", "Acme Inc.", "Hoje", 8400, "Recebida"], ["Projeto · Aplicativo mobile", "Vértice", "22 Jun", 14800, "Pendente"], ["Suporte mensal", "Nexum", "30 Jun", 5200, "Agendada"], ["Consultoria estratégica", "Orbit", "05 Jul", 3900, "Pendente"], ["Implantação CRM", "Lumen", "12 Jul", 11200, "Agendada"]],
  despesas: [["Mídia paga", "Marketing", "13 Jun", 3240, "Pago"], ["Software e ferramentas", "Operação", "15 Jun", 1860, "Pago"], ["Freelancers", "Projetos", "18 Jun", 4750, "Agendado"], ["Infraestrutura cloud", "Tecnologia", "20 Jun", 2280, "Pendente"], ["Impostos e taxas", "Administrativo", "25 Jun", 3960, "Pendente"]]
};

function financeIntro(kicker, title, description, action = "+ Nova movimentação") {
  return `<section class="page-intro finance-intro"><div><p class="card-kicker">${kicker}</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action finance-action" type="button">${action}</button></section>`;
}
function financeMetric(label, value, detail, tone = "positive") { return `<article class="data-card finance-metric"><span>${label}</span><strong>${value}</strong><small class="${tone}">${detail}</small></article>`; }
function financeTable(rows, headers = ["Descrição", "Categoria", "Vencimento", "Valor", "Status"]) {
  return `<div class="table-wrap finance-table-wrap"><table class="finance-table"><thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell, i) => `<td class="${i === row.length - 1 ? "status-cell" : i === row.length - 2 ? "money-cell" : ""}">${i === row.length - 2 ? financeMoney(cell) : cell}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
}

function renderFinanceOverview() {
  const bars = [["Jan", 61], ["Fev", 74], ["Mar", 57], ["Abr", 82], ["Mai", 69], ["Jun", 91]];
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Visão financeira", "Uma leitura rápida da saúde financeira, fluxo de caixa e previsões.", "Exportar relatório")}<section class="finance-metrics">${financeMetric("Saldo disponível", "R$ 84.620,00", "↑ 12,4% vs. mês anterior")} ${financeMetric("Receitas no mês", "R$ 42.300,00", "↑ 8,6% realizado")} ${financeMetric("Despesas no mês", "R$ 18.740,00", "↓ 4,2% sob controle", "neutral")} ${financeMetric("Resultado projetado", "R$ 23.560,00", "Margem de 55,7%", "warning")}</section><section class="finance-overview-grid"><article class="data-card finance-chart-card"><div class="section-heading"><div><p class="card-kicker">Fluxo de caixa</p><h2>Entradas x saídas</h2></div><span class="finance-period">Últimos 6 meses⌄</span></div><div class="finance-chart"><div class="chart-y"><span>50k</span><span>25k</span><span>0</span></div><div class="chart-bars">${bars.map(([month, height]) => `<div class="chart-column"><div class="chart-bar-stack"><i style="height:${height}%"></i><b style="height:${Math.max(18, height - 32)}%"></b></div><span>${month}</span></div>`).join("")}</div></div><div class="chart-legend"><span><i class="legend-income"></i> Receitas</span><span><i class="legend-expense"></i> Despesas</span></div></article><article class="data-card finance-health-card"><div class="section-heading"><div><p class="card-kicker">Saúde financeira</p><h2>Distribuição do mês</h2></div></div><div class="finance-donut"><div><strong>55,7%</strong><small>margem líquida</small></div></div><div class="finance-breakdown"><span><i class="dot blue"></i> Operação <b>42%</b></span><span><i class="dot pink"></i> Marketing <b>21%</b></span><span><i class="dot orange"></i> Pessoas <b>37%</b></span></div></article></section><section class="data-card finance-activity-card"><div class="section-heading"><div><p class="card-kicker">Movimentações</p><h2>Atividade financeira recente</h2></div><button class="filter-button" type="button">Ver tudo →</button></div>${financeTable(financeRows.receitas.slice(0, 4))}</section>`;
}

function renderReceitasView() {
  const rows = financeRows.receitas;
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Receitas", "Acompanhe entradas, vencimentos e a previsibilidade do seu faturamento.", "+ Nova receita")}<section class="finance-metrics">${financeMetric("Faturado no mês", "R$ 42.300,00", "↑ 8,6% vs. mês anterior")} ${financeMetric("A receber", "R$ 38.940,00", "12 lançamentos pendentes", "warning")} ${financeMetric("Recebido", "R$ 31.600,00", "74,7% do faturado", "positive")}</section><section class="data-card revenue-forecast-card"><div class="section-heading"><div><p class="card-kicker">Previsibilidade</p><h2>Receita projetada</h2></div><span class="finance-badge">Próximos 90 dias</span></div><div class="revenue-forecast"><div><strong>R$ 126.800</strong><small>previsão acumulada</small></div><div class="forecast-line"><i style="height:34%"></i><i style="height:48%"></i><i style="height:43%"></i><i style="height:67%"></i><i style="height:61%"></i><i style="height:86%"></i><i style="height:76%"></i><i style="height:100%"></i></div></div></section><section class="data-card finance-activity-card"><div class="section-heading"><div><p class="card-kicker">Faturamento</p><h2>Receitas recentes</h2></div><div class="receivable-filters"><button class="filter-button is-active" type="button">Todas</button><button class="filter-button" type="button">Pendentes</button></div></div>${financeTable(rows)}</section>`;
}

function renderExpensesView() {
  const categories = [["Pessoas", "R$ 8.240", 44, "blue"], ["Operação", "R$ 4.980", 27, "pink"], ["Marketing", "R$ 3.240", 17, "orange"], ["Tecnologia", "R$ 2.280", 12, "green"]];
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Despesas", "Controle custos, compromissos e o impacto de cada categoria no resultado.")}<section class="finance-metrics">${financeMetric("Total no mês", "R$ 18.740,00", "↓ 4,2% vs. mês anterior", "neutral")} ${financeMetric("Contas pendentes", "R$ 6.240,00", "3 vencem esta semana", "warning")} ${financeMetric("Orçamento utilizado", "68,4%", "Dentro do planejado", "positive")}</section><section class="finance-overview-grid expenses-overview"><article class="data-card expense-category-card"><div class="section-heading"><div><p class="card-kicker">Onde estamos investindo</p><h2>Por categoria</h2></div></div><div class="expense-categories">${categories.map(([name, value, percent, color]) => `<div class="expense-category"><div><span><i class="dot ${color}"></i>${name}</span><strong>${value}</strong></div><div class="expense-track"><i class="${color}" style="width:${percent}%"></i></div><small>${percent}% do total</small></div>`).join("")}</div></article><article class="data-card budget-card"><div class="section-heading"><div><p class="card-kicker">Planejamento</p><h2>Orçamento mensal</h2></div><span class="finance-badge">Junho</span></div><strong class="budget-value">R$ 27.400 <small>de R$ 40.000</small></strong><div class="budget-track"><i style="width:68%"></i></div><p>Você ainda pode investir <b>R$ 12.600</b> neste ciclo.</p><button class="filter-button" type="button">Ajustar orçamento</button></article></section><section class="data-card finance-activity-card"><div class="section-heading"><div><p class="card-kicker">Lançamentos</p><h2>Despesas recentes</h2></div><button class="filter-button" type="button">Filtrar</button></div>${financeTable(financeRows.despesas)}</section>`;
}

function renderReceivablesView() {
  const timeline = [["Hoje", "Acme Inc.", "Mensalidade · Website", "R$ 8.400", "Recebido", "green"], ["22 Jun", "Vértice", "Parcela 2/4 · Aplicativo", "R$ 7.400", "Vence em 3 dias", "blue"], ["30 Jun", "Nexum", "Suporte mensal", "R$ 5.200", "Agendado", "orange"], ["05 Jul", "Orbit", "Consultoria estratégica", "R$ 3.900", "Agendado", "pink"]];
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Contas a receber", "Acompanhe vencimentos, recebimentos previstos e risco de inadimplência.", "+ Nova conta a receber")}<section class="finance-metrics">${financeMetric("Total a receber", "R$ 38.940,00", "↑ 14,8% no ciclo")} ${financeMetric("Em atraso", "R$ 4.280,00", "2 contas precisam de ação", "warning")} ${financeMetric("Recebido no mês", "R$ 31.600,00", "81,1% do previsto", "positive")} </section><section class="data-card receivables-card"><div class="section-heading"><div><p class="card-kicker">Agenda de recebimentos</p><h2>Próximos vencimentos</h2></div><div class="receivable-filters"><button class="filter-button is-active" type="button">Todos</button><button class="filter-button" type="button">Em atraso</button></div></div><div class="receivable-timeline">${timeline.map(([date, client, detail, value, status, tone]) => `<article class="receivable-item"><div class="timeline-date"><strong>${date}</strong><span>Jun · 2024</span></div><i class="timeline-dot ${tone}"></i><div class="receivable-main"><strong>${client}</strong><small>${detail}</small></div><strong class="receivable-value">${value}</strong><span class="finance-status ${tone}">${status}</span><button class="inbox-more" type="button" aria-label="Mais opções">•••</button></article>`).join("")}</div></section><section class="receivable-aging"><article class="data-card"><p class="card-kicker">Aging de recebíveis</p><h2>Por período</h2><div class="aging-grid"><span><b>R$ 31.600</b><small>A vencer</small></span><span><b>R$ 3.060</b><small>1–30 dias</small></span><span><b>R$ 1.220</b><small>31–60 dias</small></span></div></article></section>`;
}

function renderChargesView() {
  const events = [["13 Jun · 09:42", "Lembrete enviado", "Acme Inc. recebeu o link de pagamento da mensalidade.", "Concluído", "green"], ["12 Jun · 16:18", "Pagamento confirmado", "Nexum confirmou o pagamento de R$ 5.200,00.", "Pago", "blue"], ["11 Jun · 10:05", "Cobrança criada", "Parcela 2/4 do projeto Aplicativo mobile.", "Aguardando", "orange"], ["09 Jun · 14:30", "Vencimento ultrapassado", "Orbit ainda não visualizou a cobrança de R$ 4.280,00.", "Ação necessária", "pink"]];
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Cobranças", "Centralize lembretes, links de pagamento e o histórico de cada cobrança.", "+ Nova cobrança")}<section class="finance-metrics">${financeMetric("Em aberto", "08", "R$ 14.860,00 em cobrança", "warning")} ${financeMetric("Taxa de recebimento", "92,4%", "↑ 3,1% este mês")} ${financeMetric("Tempo médio", "2,8 dias", "Até a confirmação", "neutral")}</section><section class="data-card charges-card"><div class="section-heading"><div><p class="card-kicker">Linha do tempo</p><h2>Atividade de cobranças</h2></div><button class="filter-button" type="button">Últimos 30 dias⌄</button></div><div class="charge-timeline">${events.map(([date, title, text, status, tone]) => `<article class="charge-event"><div class="charge-marker ${tone}"></div><div class="charge-event-body"><small>${date}</small><strong>${title}</strong><p>${text}</p></div><span class="finance-status ${tone}">${status}</span><button class="inbox-more" type="button" aria-label="Mais opções">•••</button></article>`).join("")}</div></section>`;
}

function renderSubscriptionsView() {
  const subscriptions = [["Acme Inc.", "Plano Growth", "R$ 2.400,00", "18 Jun 2024", "Ativa", "blue"], ["Nexum", "Plano Scale", "R$ 1.800,00", "22 Jun 2024", "Ativa", "green"], ["Orbit", "Plano Starter", "R$ 890,00", "03 Jul 2024", "Trial", "orange"], ["Vértice", "Plano Growth", "R$ 2.400,00", "10 Jul 2024", "Ativa", "blue"], ["Lumen", "Plano Scale", "R$ 1.800,00", "15 Jul 2024", "Pausada", "pink"]];
  dashboardGrid.innerHTML = `${financeIntro("Financeiro", "Assinaturas", "Gerencie receita recorrente, planos ativos e os próximos ciclos de cobrança.", "+ Nova assinatura")}<section class="finance-metrics">${financeMetric("MRR", "R$ 18.460,00", "↑ 9,8% no mês")} ${financeMetric("Assinaturas ativas", "42", "3 novas este mês")} ${financeMetric("Churn mensal", "2,4%", "↓ 0,8% vs. anterior", "positive")} ${financeMetric("Ticket médio", "R$ 439,00", "↑ 4,2% no período", "neutral")}</section><section class="data-card subscriptions-card"><div class="section-heading"><div><p class="card-kicker">Receita recorrente</p><h2>Carteira de assinaturas</h2></div><div class="receivable-filters"><button class="filter-button is-active" type="button">Todas</button><button class="filter-button" type="button">Ativas</button><button class="filter-button" type="button">Em risco</button></div></div><div class="subscription-list">${subscriptions.map(([client, plan, value, date, status, tone]) => `<article class="subscription-row"><span class="lead-avatar">${client.split(" ").map((p) => p[0]).join("").slice(0, 2)}</span><div class="subscription-client"><strong>${client}</strong><small>${plan}</small></div><div><small>Valor mensal</small><strong>${value}</strong></div><div><small>Próxima cobrança</small><strong>${date}</strong></div><span class="finance-status ${tone}">${status}</span><button class="inbox-more" type="button" aria-label="Mais opções">•••</button></article>`).join("")}</div></section>`;
}

const financeiroModules = {
  relatorios: { kicker: "Visão financeira", title: "Relatórios", intro: "Transforme os dados do workspace em decisões mais rápidas.", art: "agenda-spider-split.png", action: "Criar relatório", metrics: [["Relatórios salvos", "16", "4 favoritos da equipe", "neutral"], ["Agendados", "07", "Próximo: segunda, 08:00", "positive"], ["Visualizações", "1.284", "↑ 22% no período", "positive"]], columns: ["Relatório", "Área", "Última execução", "Status"], rows: [["Receita por cliente", "Financeiro", "Hoje, 08:00", "Atualizado"], ["Performance de projetos", "Operação", "Ontem, 18:30", "Agendado"], ["Pipeline comercial", "CRM", "12 set 2026", "Atualizado"], ["SLA de atendimento", "Tickets", "10 set 2026", "Precisa revisão"]] },
};


registerRoutes({
  "visao-financeira": () => renderFinanceOverview(),
  "receitas": () => renderReceitasView(),
  "contas-a-receber": () => renderReceivablesView(),
  "despesas": () => renderExpensesView(),
  "cobrancas": () => renderChargesView(),
  "assinaturas": () => renderSubscriptionsView(),
  "relatorios": () => renderModulePage("relatorios", financeiroModules["relatorios"]),
});
