/* Biblioteca de formulários com manutenção e acesso público real. */
const formEsc = (value) => escapeHtml(value ?? "");
const formFilterState = { search: "", status: "" };
const formStatus = { draft: "Rascunho", published: "Publicado", active: "Ativo", inactive: "Inativo", archived: "Arquivado" };
const formKind = { capture: "Captação", quote: "Orçamento", briefing: "Briefing", support: "Suporte", satisfaction: "Pesquisa de satisfação", onboarding: "Onboarding" };

async function renderFormsScreen() {
  const title = "Formulários", description = "Capte informações e transforme respostas em leads, oportunidades, tickets ou tarefas.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-form-new type="button">+ Novo formulário</button></section>${stateBlock.loading("Carregando formulários...")}`;
  try {
    const params = new URLSearchParams(); if (formFilterState.search) params.set("search", formFilterState.search); if (formFilterState.status) params.set("status", formFilterState.status); const items = (await api(`/api/forms?${params}`)).forms || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-form-new type="button">+ Novo formulário</button></section><section class="data-card automation-list"><div class="finance-toolbar"><input type="search" data-form-search placeholder="Buscar nome ou tipo" aria-label="Buscar formulário"><select data-form-filter aria-label="Filtrar status"><option value="">Todos os status</option>${Object.entries(formStatus).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div><div class="template-grid">${items.length ? items.map((item) => { const schema = Array.isArray(item.schema) ? item.schema : Array.isArray(item.schema?.fields) ? item.schema.fields : []; return `<article class="data-card template-card" data-form-row data-status="${formEsc(item.status || "draft")}"><div class="section-heading"><div><h3>${formEsc(item.name)}</h3><small>${formEsc(formKind[item.kind] || item.kind || "Formulário")} · ${schema.length} campo(s)</small></div><span class="finance-status ${item.status === "published" || item.status === "active" ? "positive" : "neutral"}">${formStatus[item.status] || formEsc(item.status || "Rascunho")}</span></div><p class="template-preview-text">${schema.length ? formEsc(schema.map((field) => typeof field === "string" ? field : field?.label || field?.name || "Campo").join(" · ")) : "Nenhum campo configurado"}</p><div class="template-actions"><button class="compact-action" data-form-preview="${item.id}" type="button">Ver campos</button>${item.public_token ? `<button class="compact-action" data-form-open="${formEsc(item.public_token)}" type="button">Abrir formulário</button>` : ""}<button class="compact-action" data-form-edit="${item.id}" type="button">Editar</button><button class="compact-action" data-form-delete="${item.id}" type="button">Excluir</button></div></article>`; }).join("") : stateBlock.empty("Nenhum formulário", "Crie um formulário para captar informações do cliente.", "Criar formulário", "form-empty")}</div></section>`;
    const openNew = () => openCreateDialog("form"); dashboardGrid.querySelector("[data-form-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-form-empty]")?.addEventListener("click", openNew);
    const filter = () => { const query = dashboardGrid.querySelector("[data-form-search]").value.toLocaleLowerCase("pt-BR"), status = dashboardGrid.querySelector("[data-form-filter]").value; dashboardGrid.querySelectorAll("[data-form-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (status && row.dataset.status !== status); }); };
    dashboardGrid.querySelector("[data-form-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-form-filter]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-form-preview]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.formPreview)); if (!item) return; const schema = Array.isArray(item.schema) ? item.schema : Array.isArray(item.schema?.fields) ? item.schema.fields : []; ui.drawer({ title: item.name, subtitle: formKind[item.kind] || item.kind || "Formulário", html: `<div class="template-drawer-content"><h3>Campos</h3>${schema.length ? `<ol>${schema.map((field) => `<li>${formEsc(typeof field === "string" ? field : field?.label || field?.name || "Campo")}</li>`).join("")}</ol>` : "<p>Nenhum campo configurado.</p>"}${item.automation_config ? `<h3>Automação</h3><pre>${formEsc(JSON.stringify(item.automation_config, null, 2))}</pre>` : ""}</div>` }); }));
    dashboardGrid.querySelectorAll("[data-form-responses]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { const data = await api(`/api/forms/${button.dataset.formResponses}/responses`), rows = data.responses || []; const html = rows.length ? rows.map((entry, index) => `<article class="data-card"><h4>Envio ${data.pagination.total - data.pagination.offset - index}</h4><pre>${formEsc(JSON.stringify(entry.responses || {}, null, 2))}</pre></article>`).join("") : "<p>Nenhuma resposta recebida ainda.</p>"; ui.drawer({ title: data.form?.name || "Respostas", subtitle: `${data.pagination.total || 0} envio(s)`, html: `<div class="template-drawer-content">${html}</div>` }); } catch (error) { toast(error.message, "error"); } finally { button.disabled = false; } }));
    dashboardGrid.querySelectorAll("[data-form-open]").forEach((button) => button.addEventListener("click", () => window.open(`${location.origin}/form/${encodeURIComponent(button.dataset.formOpen)}`, "_blank", "noopener,noreferrer")));
    dashboardGrid.querySelectorAll("[data-form-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.formEdit)); if (item) openEditDialog("form", item, `/api/forms/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-form-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir formulário?", onConfirm: async () => { await api(`/api/forms/${button.dataset.formDelete}`, { method: "DELETE" }); toast("Formulário excluído.", "success"); renderFormsScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "form-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderFormsScreen); }
}

registerRoutes({ formularios: renderFormsScreen });

const formPublishObserver = new MutationObserver(() => {
  if (location.hash.replace(/^#/, "") !== "formularios") return;
  dashboardGrid.querySelectorAll("[data-form-row]").forEach((row) => {
    const actions = row.querySelector(".template-actions"); if (!actions || actions.querySelector("[data-form-publish]")) return;
    const edit = row.querySelector("[data-form-edit]"); if (!edit) return;
    const responseButton = document.createElement("button"); responseButton.type = "button"; responseButton.className = "compact-action"; responseButton.dataset.formResponses = edit.dataset.formEdit; responseButton.textContent = "Ver respostas";
    responseButton.addEventListener("click", async () => { responseButton.disabled = true; try { const data = await api(`/api/forms/${responseButton.dataset.formResponses}/responses`), rows = data.responses || []; const html = rows.length ? rows.map((entry, index) => `<article class="data-card"><h4>Envio ${data.pagination.total - data.pagination.offset - index}</h4><pre>${formEsc(JSON.stringify(entry.responses || {}, null, 2))}</pre></article>`).join("") : "<p>Nenhuma resposta recebida ainda.</p>"; ui.drawer({ title: data.form?.name || "Respostas", subtitle: `${data.pagination.total || 0} envio(s)`, html: `<div class="template-drawer-content">${html}</div>` }); } catch (error) { toast(error.message, "error"); } finally { responseButton.disabled = false; } }); actions.append(responseButton);
    const button = document.createElement("button"); button.type = "button"; button.className = "compact-action"; button.dataset.formPublish = edit.dataset.formEdit; button.textContent = "Publicar e gerar link";
    button.addEventListener("click", async () => { button.disabled = true; button.textContent = "Publicando..."; try { const data = await api(`/api/forms/${button.dataset.formPublish}/public-link`, { method: "POST", body: {} }); const link = `${location.origin}${data.path}`; await navigator.clipboard?.writeText(link); window.open(link, "_blank", "noopener,noreferrer"); toast("Formulário publicado; link copiado.", "success"); button.textContent = "Link copiado"; } catch (error) { toast(error.message, "error"); button.disabled = false; button.textContent = "Publicar e gerar link"; } }); actions.append(button);
  });
});
formPublishObserver.observe(dashboardGrid, { childList: true, subtree: true });
let formReloadTimer;
dashboardGrid.addEventListener("input", (event) => { if (!event.target.matches("[data-form-search]")) return; formFilterState.search = event.target.value.trim(); clearTimeout(formReloadTimer); formReloadTimer = setTimeout(renderFormsScreen, 250); });
dashboardGrid.addEventListener("change", (event) => { if (!event.target.matches("[data-form-filter]")) return; formFilterState.status = event.target.value; renderFormsScreen(); });
