/* Gestão operacional: metas, horas, comissões e ausências com dados persistidos. */
const mgEsc = (value) => escapeHtml(value ?? "");
const mgDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const mgMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const mgConfig = {
  metas: { title: "Metas", table: "team_goals", key: "name", fields: [{ name: "name", label: "Meta" }, { name: "category", label: "Categoria", required: false }, { name: "period_start", label: "Início", type: "date", required: false }, { name: "period_end", label: "Fim", type: "date", required: false }, { name: "target", label: "Valor esperado", type: "number", min: 0, required: false }, { name: "current_value", label: "Resultado atual", type: "number", min: 0, required: false }, { name: "notes", label: "Observações", type: "textarea", required: false }] },
  comissoes: { title: "Comissões", table: "commissions", key: "description", fields: [{ name: "description", label: "Descrição" }, { name: "responsible", label: "Responsável", required: false }, { name: "base_amount", label: "Base da venda", type: "number", min: 0, required: false }, { name: "rate", label: "Percentual", type: "number", min: 0, max: 100, required: false }, { name: "amount", label: "Valor da comissão", type: "number", min: 0 }, { name: "status", label: "Status", type: "select", options: [["pending", "Pendente"], ["approved", "Aprovada"], ["paid", "Paga"], ["cancelled", "Cancelada"]], required: false }] },
  ausencias: { title: "Ausências", table: "absences", key: "kind", fields: [{ name: "user_id", label: "Membro (ID)" }, { name: "kind", label: "Tipo", type: "select", options: [["vacation", "Férias"], ["sick_leave", "Licença médica"], ["day_off", "Folga"], ["remote", "Remoto"], ["personal", "Pessoal"], ["training", "Treinamento"], ["other", "Outro"]] }, { name: "starts_on", label: "Início", type: "date" }, { name: "ends_on", label: "Fim", type: "date" }, { name: "status", label: "Status", type: "select", options: [["scheduled", "Agendada"], ["active", "Em andamento"], ["completed", "Concluída"], ["cancelled", "Cancelada"]], required: false }, { name: "notes", label: "Observações", type: "textarea", required: false }] },
  horas: { title: "Horas trabalhadas", table: "time_entries", key: "notes", fields: [{ name: "user_id", label: "Membro (ID)" }, { name: "project_id", label: "Projeto (ID)", required: false }, { name: "task_id", label: "Tarefa (ID)", required: false }, { name: "minutes", label: "Minutos", type: "number", min: 1 }, { name: "billable", label: "Faturável", type: "checkbox", required: false }, { name: "status", label: "Status", type: "select", options: [["pending", "Pendente"], ["approved", "Aprovada"], ["rejected", "Rejeitada"]], required: false }, { name: "notes", label: "Observações", type: "textarea", required: false }] }
};
const mgValue = (kind, row) => kind === "metas" ? `${Number(row.current_value || 0)} / ${Number(row.target || 0)}` : kind === "comissoes" ? mgMoney(row.amount) : kind === "horas" ? `${Math.floor(Number(row.minutes || 0) / 60)}h ${Number(row.minutes || 0) % 60}min` : `${mgDate(row.starts_on)} → ${mgDate(row.ends_on)}`;
const mgStatusLabels = { scheduled: "Agendada", active: "Em andamento", completed: "Concluída", approved: "Aprovada", pending: "Pendente", paid: "Paga", cancelled: "Cancelada", rejected: "Recusada", in_progress: "Em andamento", done: "Concluída", open: "Aberta", running: "Em execução", billed: "Faturada" };
const mgStatusTone = { scheduled: "blue", active: "green", in_progress: "blue", running: "blue", completed: "green", done: "green", approved: "green", paid: "green", billed: "green", pending: "orange", open: "orange", cancelled: "red", rejected: "red" };
const mgKindLabels = { vacation: "Férias", sick_leave: "Licença médica", sick: "Licença médica", day_off: "Folga", dayoff: "Folga", remote: "Remoto", personal: "Pessoal", training: "Treinamento", other: "Outro" };
const mgState = Object.fromEntries(Object.keys(mgConfig).map((kind) => [kind, { search: "", status: "", offset: 0 }]));
const mgTimers = {};

async function renderManagement(kind) {
  const cfg = mgConfig[kind];
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Gestão</p><h2>${cfg.title}</h2><p>Registros vinculados ao workspace, com histórico e permissões aplicadas.</p></div></section>${stateBlock.loading("Carregando...")}`;
  try {
    const state = mgState[kind], params = new URLSearchParams({ limit: "100", offset: String(state.offset) });
    if (state.search) params.set("search", state.search); if (state.status) params.set("status", state.status);
    const response = await api(`/api/${cfg.table}?${params}`), rows = response[cfg.table] || [], pagination = response.pagination || {};
    const total = kind === "horas" ? rows.reduce((sum, row) => sum + Number(row.minutes || 0), 0) : kind === "comissoes" ? rows.reduce((sum, row) => sum + Number(row.amount || 0), 0) : rows.length;
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Gestão</p><h2>${cfg.title}</h2><p>Registros vinculados ao workspace, com histórico e permissões aplicadas.</p></div><button type="button" class="button button-primary compact-action" data-mg-new>+ Novo</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Total de registros</span><strong>${rows.length}</strong></article><article class="data-card finance-metric"><span>${kind === "horas" ? "Tempo registrado" : kind === "comissoes" ? "Valor acumulado" : kind === "metas" ? "Metas em andamento" : "Programadas"}</span><strong>${kind === "horas" ? `${Math.floor(total / 60)}h` : kind === "comissoes" ? mgMoney(total) : rows.filter((row) => !["completed", "cancelled", "paid"].includes(row.status)).length}</strong></article></section><section class="data-card"><div class="finance-toolbar"><input type="search" data-mg-search value="${mgEsc(state.search)}" placeholder="Buscar registro" aria-label="Buscar registro"><select data-mg-status aria-label="Filtrar status"><option value="">Todos os status</option>${[...new Set(rows.map((row) => row.status).filter(Boolean))].sort().map((status) => `<option value="${mgEsc(status)}"${state.status === status ? " selected" : ""}>${mgEsc(status)}</option>`).join("")}</select></div>${rows.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>${kind === "metas" ? "Meta" : kind === "comissoes" ? "Comissão" : kind === "ausencias" ? "Tipo" : "Registro"}</th><th>Resumo</th><th>Status</th><th>Data</th><th></th></tr></thead><tbody>${rows.map((row) => `<tr data-mg-row><td><strong>${mgEsc(kind === "ausencias" ? (mgKindLabels[row.kind] || row.kind || "Ausência") : row[cfg.key] || row.name || `Registro #${row.id}`)}</strong>${kind === "ausencias" && row.notes ? `<small>${mgEsc(row.notes)}</small>` : ""}</td><td>${mgEsc(mgValue(kind, row))}</td><td>${row.status ? ui.badge(mgStatusLabels[row.status] || row.status, mgStatusTone[row.status] || "gray") : `<span class="muted">—</span>`}</td><td>${mgEsc(mgDate(row.created_at || row.starts_on))}</td><td><button type="button" class="compact-action" data-mg-edit="${row.id}">Editar</button><button type="button" class="compact-action" data-mg-delete="${row.id}">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty(`Nenhum registro em ${cfg.title.toLowerCase()}`, "Cadastre o primeiro registro para acompanhar este indicador.", "Criar agora", "mg-empty")}<div class="table-pagination"><button type="button" class="compact-action" data-mg-prev ${state.offset === 0 ? "disabled" : ""}>Anterior</button><span>Página ${Math.floor(state.offset / 100) + 1}</span><button type="button" class="compact-action" data-mg-next ${(pagination.returned ?? rows.length) < 100 ? "disabled" : ""}>Próxima</button></div></section>`;
    const reload = () => { state.search = dashboardGrid.querySelector("[data-mg-search]").value.trim(); state.status = dashboardGrid.querySelector("[data-mg-status]").value; state.offset = 0; clearTimeout(mgTimers[kind]); mgTimers[kind] = setTimeout(() => renderManagement(kind), 250); };
    dashboardGrid.querySelector("[data-mg-search]")?.addEventListener("input", reload); dashboardGrid.querySelector("[data-mg-status]")?.addEventListener("change", reload);
    dashboardGrid.querySelector("[data-mg-prev]")?.addEventListener("click", () => { state.offset = Math.max(0, state.offset - 100); renderManagement(kind); }); dashboardGrid.querySelector("[data-mg-next]")?.addEventListener("click", () => { state.offset += 100; renderManagement(kind); });
    const openForm = (row = {}) => ui.form({ title: row.id ? `Editar ${cfg.title.toLowerCase()}` : `Novo registro · ${cfg.title}`, subtitle: "Gestão", values: row, fields: cfg.fields, submitLabel: row.id ? "Salvar alterações" : "Cadastrar", onSubmit: async (values) => { await api(row.id ? `/api/${cfg.table}/${row.id}` : `/api/${cfg.table}`, { method: row.id ? "PATCH" : "POST", body: values }); toast("Registro salvo.", "success"); renderManagement(kind); } });
    dashboardGrid.querySelector("[data-mg-new], .mg-empty")?.addEventListener("click", () => openForm());
    dashboardGrid.querySelectorAll("[data-mg-edit]").forEach((button) => button.addEventListener("click", () => openForm(rows.find((row) => String(row.id) === button.dataset.mgEdit))));
    dashboardGrid.querySelectorAll("[data-mg-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir este registro?", onConfirm: async () => { await api(`/api/${cfg.table}/${button.dataset.mgDelete}`, { method: "DELETE" }); toast("Registro movido para a lixeira.", "success"); renderManagement(kind); } })));
  } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "mg-retry"); dashboardGrid.querySelector(".state-retry")?.addEventListener("click", () => renderManagement(kind)); }
}
registerRoutes({ metas: () => renderManagement("metas"), comissoes: () => renderManagement("comissoes"), ausencias: () => renderManagement("ausencias"), horas: () => renderManagement("horas") });
dashboardGrid.addEventListener("click", (event) => { if (!event.target.closest(".mg-retry")) return; const key = location.hash.replace(/^#/, ""); if (mgConfig[key]) renderManagement(key); });
