/* Inbox: conversas reais e threads compartilhadas entre as duas rotas. */
let inboxRoute = "caixa-de-entrada";
let inboxFilter = "all";
let inboxSearch = "";
let inboxSelected = null;
let inboxConversations = [];
const inboxText = (value) => escapeHtml(value ?? "");
const inboxName = (conversation) => conversation.contact_name || conversation.client_name || "Sem contato";
const inboxDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const inboxState = (type, label) => `<div class="inbox-state">${stateBlock[type](label)}</div>`;

async function inboxContacts() { const result = await api("/api/contacts"); return result.contacts || []; }
async function loadInbox() { const status = inboxFilter === "archived" ? "archived" : "open"; const result = await api(`/api/conversations?status=${status}`); inboxConversations = result.conversations || []; }
function conversationRows() { return inboxConversations.filter((c) => { const haystack = `${c.subject} ${inboxName(c)}`.toLowerCase(); return (inboxFilter !== "unread" || Number(c.unread_count) > 0) && (!inboxSearch || haystack.includes(inboxSearch.toLowerCase())); }).map((c) => `<button class="inbox-conversation ${inboxSelected === c.id ? "is-selected" : ""}" data-conversation="${c.id}" type="button"><span class="inbox-avatar">${inboxText(inboxName(c).slice(0, 2).toUpperCase())}</span><span><strong>${inboxText(c.subject)}</strong><small>${inboxText(inboxName(c))} · ${inboxDate(c.last_message_at)}</small></span>${Number(c.unread_count) > 0 ? `<b class="inbox-unread">${c.unread_count}</b>` : ""}</button>`).join(""); }
function shellMarkup() { const unread = inboxConversations.reduce((total, c) => total + Number(c.unread_count || 0), 0); return `<section class="page-intro inbox-intro"><div><p class="card-kicker">Comunicação</p><h2>${inboxRoute === "conversas" ? "Conversas" : "Caixa de entrada"}</h2><p>Centralize conversas, atualizações e avisos importantes do workspace.</p></div><button class="button button-primary compact-action" data-new-conversation type="button">+ Nova conversa</button></section><section class="inbox-layout"><aside class="data-card inbox-sidebar"><div class="section-heading"><div><p class="card-kicker">Pastas</p><h2>Conversas</h2></div><span class="task-count">${unread} não lida${unread === 1 ? "" : "s"}</span></div><button class="inbox-folder ${inboxFilter === "all" ? "is-active" : ""}" data-filter="all" type="button">Todas</button><button class="inbox-folder ${inboxFilter === "unread" ? "is-active" : ""}" data-filter="unread" type="button">Não lidas <b>${unread}</b></button><button class="inbox-folder ${inboxFilter === "archived" ? "is-active" : ""}" data-filter="archived" type="button">Arquivadas</button><div class="inbox-note"><strong>Foco do dia</strong><span>Acompanhe os próximos passos de cada relacionamento.</span></div></aside><section class="data-card inbox-card"><div class="section-heading"><div><p class="card-kicker">Atualizações recentes</p><h2>${inboxRoute === "conversas" ? "Contatos e clientes" : "Sua conversa"}</h2></div><label class="inline-search"><span>⌕</span><input data-search value="${inboxText(inboxSearch)}" placeholder="Buscar conversa" /></label></div><div class="inbox-list">${conversationRows() || inboxState("empty", "Nenhuma conversa encontrada.")}</div></section><section class="data-card inbox-thread" data-thread></section></section>`; }
async function renderThread() { const target = dashboardGrid.querySelector("[data-thread]"); if (!target || !inboxSelected) { if (target) target.innerHTML = inboxState("empty", "Selecione uma conversa para ver as mensagens."); return; } target.innerHTML = inboxState("loading", "Carregando mensagens..."); try { const c = inboxConversations.find((item) => String(item.id) === String(inboxSelected)); const result = await api(`/api/conversations/${inboxSelected}/messages`); target.innerHTML = `<div class="section-heading"><div><p class="card-kicker">${inboxText(inboxName(c))}</p><h2>${inboxText(c.subject)}</h2></div><button class="filter-button" data-archive type="button">${c.status === "archived" ? "Desarquivar" : "Arquivar"}</button></div><div class="inbox-messages">${(result.messages || []).map((m) => `<div class="inbox-bubble ${m.direction === "out" ? "is-out" : "is-in"}"><p>${inboxText(m.body).replace(/\n/g, "<br>")}</p><small>${inboxDate(m.created_at)}</small></div>`).join("") || inboxState("empty", "Nenhuma mensagem ainda.")}</div><form class="inbox-reply"><textarea name="body" placeholder="Escreva uma resposta…" required></textarea><button class="button button-primary" type="submit">Enviar</button></form>`; if (Number(c.unread_count)) await api(`/api/conversations/${c.id}`, { method: "PATCH", body: { status: c.status, read: true } }); const form = target.querySelector("form"); form?.querySelector("textarea")?.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); form.requestSubmit(); } }); form?.addEventListener("submit", async (event) => { event.preventDefault(); const body = new FormData(event.currentTarget).get("body"); await api(`/api/conversations/${c.id}/messages`, { method: "POST", body: { body } }); await renderInbox(); }); target.querySelector("[data-archive]")?.addEventListener("click", async () => { await api(`/api/conversations/${c.id}`, { method: "PATCH", body: { status: c.status === "archived" ? "open" : "archived" } }); inboxSelected = null; await renderInbox(); }); } catch (e) { target.innerHTML = inboxState("error", e.message); } }
function bindInbox() { dashboardGrid.querySelectorAll("[data-filter]").forEach((button) => button.addEventListener("click", async () => { inboxFilter = button.dataset.filter; inboxSelected = null; await renderInbox(); })); dashboardGrid.querySelector("[data-search]")?.addEventListener("input", async (event) => { inboxSearch = event.target.value; dashboardGrid.querySelector(".inbox-list").innerHTML = conversationRows() || inboxState("empty", "Nenhuma conversa encontrada."); bindRows(); }); dashboardGrid.querySelector("[data-new-conversation]")?.addEventListener("click", showNewConversation); bindRows(); }
function bindRows() { dashboardGrid.querySelectorAll("[data-conversation]").forEach((button) => button.addEventListener("click", async () => { inboxSelected = button.dataset.conversation; await renderInbox(); })); }
async function showNewConversation() { const contacts = await inboxContacts(); const host = dashboardGrid.querySelector(".inbox-card"); host.insertAdjacentHTML("afterbegin", `<form class="inbox-new-form data-card"><h3>Nova conversa</h3><input name="subject" placeholder="Assunto" required><select name="contact_id"><option value="">Sem contato</option>${contacts.map((c) => `<option value="${c.id}">${inboxText(c.name)}</option>`).join("")}</select><select name="channel"><option value="internal">Interno</option><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option></select><textarea name="message" placeholder="Primeira mensagem"></textarea><button class="button button-primary" type="submit">Criar conversa</button></form>`); host.querySelector("form")?.addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await api("/api/conversations", { method: "POST", body: data }); await renderInbox(); }); }
async function renderInbox() { dashboardGrid.innerHTML = inboxState("loading", "Carregando conversas..."); try { await loadInbox(); dashboardGrid.innerHTML = shellMarkup(); bindInbox(); await renderThread(); } catch (e) { dashboardGrid.innerHTML = inboxState("error", e.message); } }
window.FocusInbox = { unreadCount: async () => { const result = await api("/api/conversations?status=open"); return (result.conversations || []).reduce((sum, c) => sum + Number(c.unread_count || 0), 0); } };
registerRoutes({ "caixa-de-entrada": () => { inboxRoute = "caixa-de-entrada"; return renderInbox(); }, "conversas": () => { inboxRoute = "conversas"; return renderInbox(); } });
