/* Painel inicial conectado ao workspace. */
const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

const profileKey = "focusdev_dashboard_profile";
const brl = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dayStart = () => { const d = new Date(); d.setHours(0, 0, 0, 0); return d; };
const sameMonth = (v) => { const d = new Date(v); const n = new Date(); return d.getMonth() === n.getMonth() && d.getFullYear() === n.getFullYear(); };
const dateText = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "Sem data";
const safe = (v) => escapeHtml(v == null ? "" : String(v));
const rows = (result, key) => result.status === "fulfilled" ? (result.value[key] || []) : null;
function renderHome() {
  dashboardGrid.innerHTML = initialDashboardMarkup;
  const metric = (key, value) => { const el = dashboardGrid.querySelector(`[data-metric="${key}"]`); if (el) el.textContent = value; };
  const metricNote = (key, value) => { const el = dashboardGrid.querySelector(`[data-metric="${key}"]`); const note = el?.closest(".metric-card")?.querySelector("small"); if (note) note.textContent = value; };
  ["revenue", "leads", "tasks", "projects", "receivables", "overdue", "cashflow", "tickets"].forEach(k => metric(k, "Carregando…"));
  dashboardGrid.querySelector(".button-light")?.addEventListener("click", () => { location.hash = "#tarefas"; });
  dashboardGrid.querySelector(".hero-link")?.addEventListener("click", () => { const p = document.createElement("aside"); p.className = "data-card inicio-help-panel"; p.innerHTML = "<strong>Como funciona</strong><p>Use os indicadores para acompanhar finanças, vendas, tarefas, projetos e atendimento do workspace.</p><button class=\"button button-secondary compact-action\">Fechar</button>"; p.querySelector("button").onclick = () => p.remove(); dashboardGrid.querySelector(".dashboard-hero")?.after(p); });
  dashboardGrid.querySelector("#dashboard-profile")?.addEventListener("change", e => { localStorage.setItem(profileKey, e.target.value); window.applyDashboardProfile?.(e.target.value); });
  if (dashboardGrid.querySelector("#dashboard-profile")) { dashboardGrid.querySelector("#dashboard-profile").value = localStorage.getItem(profileKey) || "manager"; window.applyDashboardProfile?.(); }
  const endpoints = ["/api/revenues", "/api/leads", "/api/tasks", "/api/projects", "/api/receivables", "/api/expenses", "/api/tickets", "/api/events"];
  Promise.allSettled(endpoints.map(path => api(path))).then(results => {
    const [revR, leadR, taskR, projR, recR, expR, ticketR, eventR] = results;
    const rev = rows(revR, "revenues"), leads = rows(leadR, "leads"), tasks = rows(taskR, "tasks"), projects = rows(projR, "projects"), rec = rows(recR, "receivables"), exp = rows(expR, "expenses"), tickets = rows(ticketR, "tickets"), events = rows(eventR, "events");
    const pending = x => !["paid", "done", "cancelled", "canceled"].includes(String(x.status || "").toLowerCase()) && !x.paid_at;
    if (rev) { const current = rev.filter(x => x.paid_at && sameMonth(x.paid_at)).reduce((a,x) => a + Number(x.amount || 0), 0), now = new Date(), previous = rev.filter(x => { const d = new Date(x.paid_at); return x.paid_at && d.getMonth() === (now.getMonth() + 11) % 12 && d.getFullYear() === (now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear()); }).reduce((a,x) => a + Number(x.amount || 0), 0); metric("revenue", brl(current)); metricNote("revenue", previous ? `${current >= previous ? "↑" : "↓"} ${Math.abs((current - previous) / previous * 100).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% vs. mês anterior` : "Sem base de comparação"); } else { metric("revenue", "Indisponível"); metricNote("revenue", "Dados indisponíveis"); }
    if (leads) { const week = new Date(); week.setDate(week.getDate() - 7); metric("leads", leads.filter(x => !["won", "lost"].includes(x.status)).length); metricNote("leads", `${plural(leads.filter(x => x.created_at && new Date(x.created_at) >= week).length, "novo nesta semana", "novos nesta semana")}`); } else { metric("leads", "Indisponível"); metricNote("leads", "Dados indisponíveis"); }
    if (tasks) { const open = tasks.filter(pending), today = new Date().toDateString(); metric("tasks", open.length); metricNote("tasks", `${plural(open.filter(x => new Date(x.due_at || x.due_date || 0).toDateString() === today).length, "para hoje", "para hoje")}`); } else { metric("tasks", "Indisponível"); metricNote("tasks", "Dados indisponíveis"); }
    if (projects) { const active = projects.filter(x => x.status === "active"), overdue = active.filter(x => x.ends_on && new Date(x.ends_on) < new Date()); metric("projects", active.length); metricNote("projects", overdue.length ? `${plural(overdue.length, "atrasado", "atrasados")}` : "Todos em dia"); } else { metric("projects", "Indisponível"); metricNote("projects", "Dados indisponíveis"); }
    if (rec) { const open = rec.filter(pending), late = open.filter(x => x.due_at && new Date(x.due_at) < new Date()); metric("receivables", brl(open.reduce((a,x) => a + Number(x.amount || 0), 0))); metricNote("receivables", `${plural(open.length, "lançamento pendente", "lançamentos pendentes")}`); metric("overdue", brl(late.reduce((a,x) => a + Number(x.amount || 0), 0))); metricNote("overdue", `${plural(late.length, "precisa de ação", "precisam de ação")}`); } else { metric("receivables", "Indisponível"); metricNote("receivables", "Dados indisponíveis"); metric("overdue", "Indisponível"); metricNote("overdue", "Dados indisponíveis"); }
    if (rev && exp) { const income = rev.filter(x => pending(x) && sameMonth(x.due_at || x.created_at)).reduce((a,x) => a + Number(x.amount || 0), 0), outgoing = exp.filter(x => pending(x) && sameMonth(x.due_at || x.created_at)).reduce((a,x) => a + Number(x.amount || 0), 0); metric("cashflow", brl(income - outgoing)); metricNote("cashflow", `${brl(income)} pendentes − ${brl(outgoing)} pendentes`); } else { metric("cashflow", "Indisponível"); metricNote("cashflow", "Dados indisponíveis"); }
    if (tickets) { const open = tickets.filter(x => x.status !== "done"), urgent = open.filter(x => ["urgent", "high", "alta"].includes(String(x.priority || x.urgency || "").toLowerCase())); metric("tickets", open.length); metricNote("tickets", `${plural(urgent.length, "urgente", "urgentes")}`); } else { metric("tickets", "Indisponível"); metricNote("tickets", "Dados indisponíveis"); }
    const pulse = dashboardGrid.querySelectorAll(".dashboard-pulse .pulse-card strong"); if (pulse[0]) pulse[0].textContent = opsUnavailable(leads, "—"); if (pulse[1]) pulse[1].textContent = tasks ? tasks.filter(x => x.status !== "done" && new Date(x.due_at || x.due_date || 0) < new Date()).length : "Indisponível"; if (pulse[2]) pulse[2].textContent = events ? events.filter(x => new Date(x.starts_at || x.start_at || x.date).toDateString() === new Date().toDateString()).length : "Indisponível";
    const taskCount = dashboardGrid.querySelector(".task-count"); if (taskCount) taskCount.textContent = tasks ? `${tasks.filter(x => x.status !== "done").length} tarefas` : "Indisponível";
    const unavailable = results.filter(x => x.status === "rejected").length, availability = dashboardGrid.querySelector(".workspace-availability p"); if (availability) availability.textContent = unavailable ? `Workspace parcialmente indisponível (${unavailable} fonte${unavailable > 1 ? "s" : ""} sem resposta).` : "Workspace conectado e dados sincronizados.";
    renderPriorities(tasks); renderAgenda(events); renderActivity(tasks, leads, rec);
  });
}
function opsUnavailable(leads, fallback) { return leads ? leads.filter(x => !["won", "lost"].includes(x.status)).length : fallback; }
function renderPriorities(tasks) { const box = dashboardGrid.querySelector(".priority-list"), list = (tasks || []).filter(x => x.status !== "done").sort((a,b) => new Date(a.due_at || a.due_date || 0) - new Date(b.due_at || b.due_date || 0)).slice(0,5); if (!box) return; box.innerHTML = list.length ? list.map(x => `<label class="priority-item"><input type="checkbox" data-task="${safe(x.id)}"/><span class="checkmark"></span><span class="priority-text"><strong>${safe(x.title || x.name || "Tarefa")}</strong><small>${dateText(x.due_at || x.due_date)}</small></span></label>`).join("") : `<p class="agenda-empty" role="status">Nenhuma tarefa aberta.</p>`; box.querySelectorAll("[data-task]").forEach(c => c.onchange = async () => { await api(`/api/tasks/${c.dataset.task}`, { method: "PATCH", body: { status: "done" } }); renderHome(); }); }
function renderAgenda(events) { const box = dashboardGrid.querySelector(".agenda-list"); if (!box || !events) { if (box) box.innerHTML = `<p class="agenda-empty" role="status">Agenda indisponível.</p>`; return; } const today = new Date().toDateString(), list = events.filter(x => new Date(x.starts_at || x.start_at || x.date).toDateString() === today); box.innerHTML = list.length ? list.map(x => `<article class="agenda-item"><time>${safe(new Date(x.starts_at || x.start_at || x.date).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }))}</time><div><strong>${safe(x.title || x.name || "Evento")}</strong><small>${safe(x.description || "")}</small></div></article>`).join("") : `<p class="agenda-empty" role="status">Nenhum evento hoje.</p>`; }
function renderActivity(tasks, leads, rec) { const box = dashboardGrid.querySelector(".activity-list"), all = [...(tasks || []).map(x => ({ ...x, kind: "Tarefa", label: x.title || x.name })), ...(leads || []).map(x => ({ ...x, kind: "Lead", label: x.name })), ...(rec || []).map(x => ({ ...x, kind: "Recebível", label: x.description || x.name }))].sort((a,b) => new Date(b.created_at || 0) - new Date(a.created_at || 0)).slice(0,5); if (!box) return; box.innerHTML = all.length ? all.map(x => `<article class="activity-item"><span class="activity-avatar blue">${safe((x.label || "?").slice(0,2).toUpperCase())}</span><div><strong>${safe(x.label || "Registro")}</strong><small>${safe(x.kind)} · ${dateText(x.created_at)}</small></div><span class="activity-dot"></span></article>`).join("") : `<p class="agenda-empty" role="status">Nenhuma atividade recente.</p>`; }
registerRoutes({ inicio: renderHome });
