/* Integrações: configuração explícita e estado separado de teste de conectividade. */
const toast = (...args) => ui.toast(...args);
const integrationEsc = (value) => escapeHtml(value ?? "");
const integrationLabel = { whatsapp: "WhatsApp / Evolution API", email: "Gmail", smtp: "SMTP", google_calendar: "Google Calendar", google_drive: "Google Drive", github: "GitHub", n8n: "n8n", asaas: "Asaas", stripe: "Stripe", firebase: "Firebase", supabase: "Supabase", cnpj: "Consulta CNPJ", esign: "Assinatura eletrônica", webhook: "Webhook", api: "API própria" };
const integrationState = { search: "", status: "", offset: 0 };
let integrationTimer;

const integrationMetric = (label, value) => `<article class="data-card finance-metric"><span>${integrationEsc(label)}</span><strong>${integrationEsc(value)}</strong></article>`;
const integrationDetails = (item) => { if (!item) return; const value = (entry) => entry === null || entry === undefined || entry === "" ? "—" : typeof entry === "object" ? JSON.stringify(entry, null, 2) : String(entry); const html = Object.entries(item).filter(([key]) => !["id", "organization_id"].includes(key)).map(([key, entry]) => `<dt>${integrationEsc(key.replaceAll("_", " "))}</dt><dd>${integrationEsc(value(entry))}</dd>`).join(""); ui.drawer({ title: integrationLabel[item.provider] || item.provider || "Integracao", subtitle: item.account_name || "Configuracao", html: `<dl>${html || "<dd>Sem detalhes disponiveis.</dd>"}</dl>` }); };
async function renderIntegrationsScreen() {
  const title = "Integrações", description = "Configure serviços externos e acompanhe o estado informado pelo sistema.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-integration-new type="button">+ Nova integração</button></section>${stateBlock.loading("Carregando integrações...")}`;
  try {
    const params = new URLSearchParams({ limit: "100", offset: String(integrationState.offset) }); if (integrationState.search) params.set("search", integrationState.search); if (integrationState.status) params.set("status", integrationState.status);
    const response = await api(`/api/integrations?${params}`), items = response.integrations || [], pagination = response.pagination || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-integration-new type="button">+ Nova integração</button></section><section class="data-card automation-list"><p class="muted">“Conectada” só deve ser usada quando o provedor confirmou a conexão. O cadastro da configuração, sozinho, não executa autenticação externa.</p><div class="finance-toolbar"><input type="search" data-integration-search value="${integrationEsc(integrationState.search)}" placeholder="Buscar provedor, categoria ou conta" aria-label="Buscar integração"><select data-integration-status aria-label="Filtrar status"><option value="">Todos os status</option><option value="connected"${integrationState.status === "connected" ? " selected" : ""}>Conectadas</option><option value="disconnected"${integrationState.status === "disconnected" ? " selected" : ""}>Desconectadas</option><option value="error"${integrationState.status === "error" ? " selected" : ""}>Com erro</option></select></div><div class="integration-grid">${items.length ? items.map((item) => `<article class="data-card" data-integration-row><div class="section-heading"><div><h3>${integrationEsc(integrationLabel[item.provider] || item.provider)}</h3><small>${integrationEsc(item.account_name || "Conta não informada")}${item.environment ? ` · ${integrationEsc(item.environment)}` : ""}</small></div><span class="finance-status ${item.status === "connected" ? "positive" : item.status === "error" ? "warning" : "neutral"}">${item.status === "connected" ? "Conectada" : item.status === "error" ? "Com erro" : "Desconectada"}</span></div>${item.last_sync_at ? `<small>Última sincronização: ${new Date(item.last_sync_at).toLocaleString("pt-BR")}</small>` : ""}<div class="template-actions"><button class="compact-action" data-integration-edit="${item.id}" type="button">Configurar</button>${item.status === "connected" ? `<button class="compact-action" data-integration-disconnect="${item.id}" type="button">Desconectar</button>` : ""}${item.provider === "webhook" ? `<button class="compact-action" data-integration-test="${item.id}" type="button">Testar webhook</button>` : ""}<button class="compact-action" data-integration-delete="${item.id}" type="button">Excluir</button></div><small data-integration-result="${item.id}" role="status"></small></article>`).join("") : stateBlock.empty("Nenhuma integração", "Cadastre uma configuração para começar.", "Criar integração", "integration-empty")}</div><div class="table-pagination"><button type="button" class="compact-action" data-integration-prev ${integrationState.offset === 0 ? "disabled" : ""}>Anterior</button><span>Página ${Math.floor(integrationState.offset / 100) + 1}</span><button type="button" class="compact-action" data-integration-next ${(pagination.returned ?? items.length) < 100 ? "disabled" : ""}>Próxima</button></div></section>`;
    const reload = () => { integrationState.search = dashboardGrid.querySelector("[data-integration-search]").value.trim(); integrationState.status = dashboardGrid.querySelector("[data-integration-status]").value; integrationState.offset = 0; clearTimeout(integrationTimer); integrationTimer = setTimeout(renderIntegrationsScreen, 250); };
    dashboardGrid.querySelector("[data-integration-search]")?.addEventListener("input", reload); dashboardGrid.querySelector("[data-integration-status]")?.addEventListener("change", reload); dashboardGrid.querySelector("[data-integration-prev]")?.addEventListener("click", () => { integrationState.offset = Math.max(0, integrationState.offset - 100); renderIntegrationsScreen(); }); dashboardGrid.querySelector("[data-integration-next]")?.addEventListener("click", () => { integrationState.offset += 100; renderIntegrationsScreen(); });
    const openNew = () => openCreateDialog("integration"); dashboardGrid.querySelector("[data-integration-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-integration-empty]")?.addEventListener("click", openNew);
    dashboardGrid.querySelectorAll("[data-integration-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.integrationEdit)); if (item) openEditDialog("integration", item, `/api/integrations/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-integration-disconnect]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Desconectar integração?", onConfirm: async () => { await api(`/api/integrations/${button.dataset.integrationDisconnect}`, { method: "PATCH", body: { status: "disconnected" } }); toast("Integração desconectada.", "success"); renderIntegrationsScreen(); } })));
    dashboardGrid.querySelectorAll("[data-integration-test]").forEach((button) => button.addEventListener("click", async () => { const result = dashboardGrid.querySelector(`[data-integration-result="${button.dataset.integrationTest}"]`); button.disabled = true; if (result) result.textContent = "Testando..."; try { const data = await api(`/api/integrations/${button.dataset.integrationTest}/test`, { method: "POST" }); if (result) result.textContent = data.ok ? `Webhook respondeu HTTP ${data.status}.` : `Webhook respondeu HTTP ${data.status}.`; } catch (error) { if (result) result.textContent = error.message; } finally { button.disabled = false; } }));
    dashboardGrid.querySelectorAll("[data-integration-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir integração?", onConfirm: async () => { await api(`/api/integrations/${button.dataset.integrationDelete}`, { method: "DELETE" }); toast("Integração excluída.", "success"); renderIntegrationsScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "integration-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderIntegrationsScreen); }
}

registerRoutes({ integracoes: renderIntegrationsScreen });
dashboardGrid.addEventListener("click", (event) => { if (event.target.closest(".integration-retry")) renderIntegrationsScreen(); });
const integrationEnhancementObserver = new MutationObserver(async () => { if (location.hash.replace(/^#/, "") !== "integracoes") return; const list = dashboardGrid.querySelector(".automation-list"), cards = [...dashboardGrid.querySelectorAll("[data-integration-row]")]; if (!list || !cards.length || list.dataset.enhanced === "1") return; list.dataset.enhanced = "1"; try { const items = (await api("/api/integrations?limit=100")).integrations || []; list.insertAdjacentHTML("beforebegin", `<section class="finance-metrics">${integrationMetric("Total", items.length)}${integrationMetric("Conectadas", items.filter((item) => item.status === "connected").length)}${integrationMetric("Desconectadas", items.filter((item) => item.status !== "connected" && item.status !== "error").length)}${integrationMetric("Com erro", items.filter((item) => item.status === "error").length)}</section>`); cards.forEach((card, index) => { const actions = card.querySelector(".template-actions"), button = document.createElement("button"); if (!actions || actions.querySelector("[data-integration-details]")) return; button.type = "button"; button.className = "compact-action"; button.dataset.integrationDetails = "1"; button.textContent = "Detalhes"; button.addEventListener("click", () => integrationDetails(items[index])); actions.prepend(button); }); } catch { list.dataset.enhanced = ""; } });
integrationEnhancementObserver.observe(dashboardGrid, { childList: true, subtree: true });
