/* Integrações: configuração explícita e estado separado de teste de conectividade. */
const integrationEsc = (value) => escapeHtml(value ?? "");
const integrationLabel = { whatsapp: "WhatsApp / Evolution API", email: "Gmail", smtp: "SMTP", google_calendar: "Google Calendar", google_drive: "Google Drive", github: "GitHub", n8n: "n8n", mercado_pago: "Mercado Pago", asaas: "Asaas", stripe: "Stripe", firebase: "Firebase", supabase: "Supabase", cnpj: "Consulta CNPJ", esign: "Assinatura eletrônica", webhook: "Webhook", api: "API própria" };

async function renderIntegrationsScreen() {
  const title = "Integrações", description = "Configure serviços externos e acompanhe o estado informado pelo sistema.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-integration-new type="button">+ Nova integração</button></section>${stateBlock.loading("Carregando integrações...")}`;
  try {
    const items = (await api("/api/integrations")).integrations || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-integration-new type="button">+ Nova integração</button></section><section class="data-card automation-list"><p class="muted">“Conectada” só deve ser usada quando o provedor confirmou a conexão. O cadastro da configuração, sozinho, não executa autenticação externa.</p><div class="integration-grid">${items.length ? items.map((item) => `<article class="data-card" data-integration-row data-status="${integrationEsc(item.status || "disconnected")}"><div class="section-heading"><div><h3>${integrationEsc(integrationLabel[item.provider] || item.provider)}</h3><small>${integrationEsc(item.account_name || "Conta não informada")}${item.environment ? ` · ${integrationEsc(item.environment)}` : ""}</small></div><span class="finance-status ${item.status === "connected" ? "positive" : item.status === "error" ? "warning" : "neutral"}">${item.status === "connected" ? "Conectada" : item.status === "error" ? "Com erro" : "Desconectada"}</span></div>${item.last_sync_at ? `<small>Última sincronização: ${new Date(item.last_sync_at).toLocaleString("pt-BR")}</small>` : ""}<div class="template-actions"><button class="compact-action" data-integration-edit="${item.id}" type="button">Configurar</button>${item.status === "connected" ? `<button class="compact-action" data-integration-disconnect="${item.id}" type="button">Desconectar</button>` : ""}${item.provider === "webhook" ? `<button class="compact-action" data-integration-test="${item.id}" type="button">Testar webhook</button>` : ""}<button class="compact-action" data-integration-delete="${item.id}" type="button">Excluir</button></div><small data-integration-result="${item.id}" role="status"></small></article>`).join("") : stateBlock.empty("Nenhuma integração", "Cadastre uma configuração para começar.", "Criar integração", "integration-empty")}</div></section>`;
    const openNew = () => openCreateDialog("integration"); dashboardGrid.querySelector("[data-integration-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-integration-empty]")?.addEventListener("click", openNew);
    dashboardGrid.querySelectorAll("[data-integration-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.integrationEdit)); if (item) openEditDialog("integration", item, `/api/integrations/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-integration-disconnect]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Desconectar integração?", onConfirm: async () => { await api(`/api/integrations/${button.dataset.integrationDisconnect}`, { method: "PATCH", body: { status: "disconnected" } }); toast("Integração desconectada.", "success"); renderIntegrationsScreen(); } })));
    dashboardGrid.querySelectorAll("[data-integration-test]").forEach((button) => button.addEventListener("click", async () => { const result = dashboardGrid.querySelector(`[data-integration-result="${button.dataset.integrationTest}"]`); button.disabled = true; if (result) result.textContent = "Testando..."; try { const data = await api(`/api/integrations/${button.dataset.integrationTest}/test`, { method: "POST" }); if (result) result.textContent = data.ok ? `Webhook respondeu HTTP ${data.status}.` : `Webhook respondeu HTTP ${data.status}.`; } catch (error) { if (result) result.textContent = error.message; } finally { button.disabled = false; } }));
    dashboardGrid.querySelectorAll("[data-integration-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir integração?", onConfirm: async () => { await api(`/api/integrations/${button.dataset.integrationDelete}`, { method: "DELETE" }); toast("Integração excluída.", "success"); renderIntegrationsScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "integration-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderIntegrationsScreen); }
}

registerRoutes({ integracoes: renderIntegrationsScreen });
