const trashEsc = (value) => escapeHtml(value ?? "");
const trashDate = (value) => value ? new Date(value).toLocaleString("pt-BR") : "Sem prazo";
const trashState = { search: "", entity_type: "", offset: 0 };
let trashTimer;

async function renderTrashScreen() {
  const title = "Lixeira", description = "Registros excluídos ficam recuperáveis por até 30 dias.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Configurações</p><h2>${title}</h2><p>${description}</p></div></section>${stateBlock.loading("Carregando lixeira...")}`;
  const params = new URLSearchParams({ limit: "100", offset: String(trashState.offset), active: "true" });
  if (trashState.search) params.set("search", trashState.search); if (trashState.entity_type) params.set("entity_type", trashState.entity_type);
  try {
    const response = await api(`/api/trash?${params}`), items = response.trash || [], pagination = response.pagination || {}, types = [...new Set(items.map((item) => item.entity_type).filter(Boolean))].sort();
    const option = (value, label, selected) => `<option value="${trashEsc(value)}"${selected === value ? " selected" : ""}>${trashEsc(label)}</option>`;
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Configurações</p><h2>${title}</h2><p>${description}</p></div><span class="finance-status neutral">${pagination.returned ?? items.length} registro(s)</span></section><section class="data-card automation-list"><div class="finance-toolbar"><input type="search" data-trash-search value="${trashEsc(trashState.search)}" placeholder="Buscar tipo ou registro" aria-label="Buscar na lixeira"><select data-trash-filter aria-label="Filtrar tipo">${option("", "Todos os tipos", trashState.entity_type)}${types.map((type) => option(type, type, trashState.entity_type)).join("")}</select></div>${items.length ? `<div class="template-grid">${items.map((item) => { const expires = item.restore_until ? new Date(item.restore_until) : null; const remaining = expires ? Math.max(0, Math.ceil((expires - Date.now()) / 864e5)) : null; return `<article class="data-card template-card"><div class="section-heading"><div><h3>${trashEsc(item.entity_type || "Registro")}</h3><small>ID original: ${trashEsc(item.entity_id)}</small></div><span class="finance-status ${remaining !== null && remaining < 7 ? "warning" : "neutral"}">${remaining === null ? "Sem prazo" : `${remaining} dia(s)`}</span></div><p>Excluído em: ${trashEsc(trashDate(item.created_at))}</p><p>Recuperável até: ${trashEsc(trashDate(item.restore_until))}</p><p>Por: ${trashEsc(item.deleted_by_name || "Sistema")}</p><button class="compact-action" data-trash-restore="${trashEsc(item.id)}" type="button">Restaurar registro</button></article>`; }).join("")}</div>` : stateBlock.empty("Lixeira vazia", "Registros excluídos aparecerão aqui para recuperação.")}<div class="table-pagination"><button type="button" class="compact-action" data-trash-prev ${trashState.offset === 0 ? "disabled" : ""}>Anterior</button><span>Página ${Math.floor(trashState.offset / 100) + 1}</span><button type="button" class="compact-action" data-trash-next ${(pagination.returned ?? items.length) < 100 ? "disabled" : ""}>Próxima</button></div></section>`;
    const reload = () => { trashState.search = dashboardGrid.querySelector("[data-trash-search]").value.trim(); trashState.entity_type = dashboardGrid.querySelector("[data-trash-filter]").value; trashState.offset = 0; clearTimeout(trashTimer); trashTimer = setTimeout(renderTrashScreen, 250); };
    dashboardGrid.querySelector("[data-trash-search]")?.addEventListener("input", reload); dashboardGrid.querySelector("[data-trash-filter]")?.addEventListener("change", reload);
    dashboardGrid.querySelector("[data-trash-prev]")?.addEventListener("click", () => { trashState.offset = Math.max(0, trashState.offset - 100); renderTrashScreen(); });
    dashboardGrid.querySelector("[data-trash-next]")?.addEventListener("click", () => { trashState.offset += 100; renderTrashScreen(); });
    dashboardGrid.querySelectorAll("[data-trash-restore]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Restaurar este registro?", onConfirm: async () => { await api(`/api/trash/${button.dataset.trashRestore}/restore`, { method: "POST", body: {} }); toast("Registro restaurado.", "success"); renderTrashScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Configurações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "trash-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderTrashScreen); }
}
registerRoutes({ lixeira: renderTrashScreen });
