/* Agenda e tarefas reais, com estados e ações inline. */
const esc = (v) => escapeHtml(v ?? "");
const dateBR = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "Sem prazo";
const state = (kind, label) => `<div class="module-state">${stateBlock[kind](label)}</div>`;
const taskPriorityLabel = (v) => ({ high: "Alta", low: "Baixa", medium: "Média" }[v || "medium"] || "Média");

async function renderTasksView() {
  let tasks; try { tasks = (await api("/api/tasks")).tasks || []; } catch (e) { dashboardGrid.innerHTML = state("error", e.message); return; }
  const visible = tasks.filter((t) => (taskStatus === "all" || t.status === taskStatus) && (taskPriority === "all" || (t.priority || "medium") === taskPriority) && (!taskSearch || `${t.title} ${(t.tags || []).join(" ")}`.toLowerCase().includes(taskSearch.toLowerCase())));
  const subtasks = (task) => tasks.filter((x) => String(x.parent_id) === String(task.id));
  const renderTask = (t) => { const children = subtasks(t); return `<article class="kanban-task" draggable="true" data-kanban-id="${t.id}"><strong>${esc(t.title)}</strong><small>${dateBR(t.due_at)}</small>${children.length ? `<small>${children.filter((x) => x.status === "done").length}/${children.length} subtarefas</small><div class="task-subtasks">${children.map((x) => `<span>${esc(x.title)}</span>`).join("")}</div>` : ""}<span class="task-status priority-${esc(t.priority || "medium")}">${taskPriorityLabel(t.priority)}</span><div><button class="task-subtask" data-subtask-task="${t.id}" type="button">+</button><button class="task-edit" data-edit-task="${t.id}" type="button">✎</button><button class="task-delete" data-delete-task="${t.id}" type="button">×</button></div></article>`; };
  const rows = visible.map((t) => `<li class="task-row ${t.status === "done" ? "is-done" : ""}"><label class="task-check"><input type="checkbox" data-task-id="${t.id}" ${t.status === "done" ? "checked" : ""}><span></span></label><div><strong>${esc(t.title)}</strong><small>${dateBR(t.due_at)}</small>${subtasks(t).map((x) => `<small class="task-subtask-row">↳ ${esc(x.title)}</small>`).join("")}</div><em class="task-status priority-${esc(t.priority || "medium")}">${taskPriorityLabel(t.priority)}</em><button class="task-subtask" data-subtask-task="${t.id}" type="button">+</button><button class="task-edit" data-edit-task="${t.id}" type="button">✎</button><button class="task-delete" data-delete-task="${t.id}" type="button">×</button></li>`).join("");
  const columns = [["todo", "A fazer"], ["doing", "Em andamento"], ["blocked", "Bloqueadas"], ["done", "Concluídas"]].map(([status, label]) => `<section class="kanban-column" data-kanban-status="${status}"><h3>${label}<span>${visible.filter((t) => t.status === status).length}</span></h3>${visible.filter((t) => t.status === status).map(renderTask).join("") || `<p class="task-empty">Vazio</p>`}</section>`).join("");
  const content = visible.length ? (taskMode === "list" ? `<ul class="task-list">${rows}</ul>` : `<div class="kanban-board">${columns}</div>`) : state("empty", "Nenhuma tarefa encontrada. Crie a primeira tarefa.");
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Meu dia</p><h2>Tarefas</h2><p>Organize prioridades e acompanhe o trabalho da equipe.</p></div><button class="button button-primary compact-action task-new" type="button">+ Nova tarefa</button></section><section class="task-summary"><article class="data-card"><span>Em aberto</span><strong>${tasks.filter((t) => t.status !== "done").length}</strong></article><article class="data-card"><span>Concluídas</span><strong>${tasks.filter((t) => t.status === "done").length} de ${tasks.length} concluídas</strong></article><article class="data-card"><span>Total</span><strong>${tasks.length}</strong></article></section><section class="data-card tasks-card"><div class="section-heading"><h2>Minhas tarefas</h2><div class="task-toolbar"><input class="task-search" placeholder="Buscar tarefa" value="${esc(taskSearch)}"><select class="task-filter"><option value="all">Todas</option><option value="todo">A fazer</option><option value="doing">Em andamento</option><option value="blocked">Bloqueadas</option><option value="done">Concluídas</option></select><select class="task-priority-filter"><option value="all">Todas prioridades</option><option value="high">Alta</option><option value="medium">Média</option><option value="low">Baixa</option></select><button class="filter-button task-mode" type="button">${taskMode === "list" ? "Kanban" : "Lista"}</button></div></div>${pendingDelete ? `<div class="task-confirmation">Excluir esta tarefa? <button class="button button-primary compact-action" data-confirm-delete type="button">Confirmar excluir</button><button class="button button-secondary compact-action" data-cancel-delete type="button">Cancelar</button></div>` : ""}${content}</section>`;
  dashboardGrid.querySelector(".task-filter").value = taskStatus; dashboardGrid.querySelector(".task-priority-filter").value = taskPriority;
  dashboardGrid.querySelector(".task-new").onclick = () => openCreateDialog("tarefa"); dashboardGrid.querySelector(".task-mode").onclick = () => { taskMode = taskMode === "list" ? "kanban" : "list"; renderTasksView(); }; dashboardGrid.querySelector(".task-filter").onchange = (e) => { taskStatus = e.target.value; renderTasksView(); }; dashboardGrid.querySelector(".task-priority-filter").onchange = (e) => { taskPriority = e.target.value; renderTasksView(); }; dashboardGrid.querySelector(".task-search").oninput = (e) => { taskSearch = e.target.value; renderTasksView(); };
  dashboardGrid.querySelectorAll("[data-task-id]").forEach((input) => input.onchange = async () => { try { await api(`/api/tasks/${input.dataset.taskId}`, { method: "PATCH", body: { status: input.checked ? "done" : "doing" } }); renderTasksView(); } catch (e) { input.checked = !input.checked; dashboardGrid.querySelector(".tasks-card").insertAdjacentHTML("afterbegin", `<p class="task-inline-error">${esc(e.message)}</p>`); } });
  dashboardGrid.querySelectorAll("[data-delete-task]").forEach((b) => b.onclick = () => { pendingDelete = b.dataset.deleteTask; renderTasksView(); }); dashboardGrid.querySelector("[data-cancel-delete]")?.addEventListener("click", () => { pendingDelete = null; renderTasksView(); }); dashboardGrid.querySelector("[data-confirm-delete]")?.addEventListener("click", async () => { await api(`/api/tasks/${pendingDelete}`, { method: "DELETE" }); pendingDelete = null; renderTasksView(); });
  dashboardGrid.querySelectorAll("[data-edit-task]").forEach((b) => b.onclick = () => { const t = tasks.find((x) => String(x.id) === b.dataset.editTask); openEditDialog("tarefa", { title: t.title, priority: t.priority || "medium", tags: (t.tags || []).join(", "), dueAt: t.due_at || "" }, `/api/tasks/${t.id}`); }); dashboardGrid.querySelectorAll("[data-subtask-task]").forEach((b) => b.onclick = () => openSubtaskDialog(tasks.find((x) => String(x.id) === b.dataset.subtaskTask)));
  dashboardGrid.querySelectorAll("[data-kanban-id]").forEach((b) => b.ondragstart = (e) => e.dataTransfer.setData("text/plain", b.dataset.kanbanId)); dashboardGrid.querySelectorAll("[data-kanban-status]").forEach((col) => { col.ondragover = (e) => e.preventDefault(); col.ondrop = async (e) => { const id = e.dataTransfer.getData("text/plain"); if (id) { await api(`/api/tasks/${id}`, { method: "PATCH", body: { status: col.dataset.kanbanStatus } }); renderTasksView(); } }; });
}

registerRoutes({ "tarefas": renderTasksView });
