/* Agenda e tarefas reais, com estados e ações inline. */
let agendaDate = new Date(), agendaMode = "month", taskMode = "list", taskStatus = "all", taskPriority = "all", taskSearch = "", pendingDelete = null;
const esc = (v) => escapeHtml(v ?? "");
const dateBR = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "Sem prazo";
const state = (kind, label) => `<div class="module-state">${stateBlock[kind](label)}</div>`;
const taskPriorityLabel = (v) => ({ high: "Alta", low: "Baixa", medium: "Média" }[v || "medium"] || "Média");

async function renderTasksView() {
  let tasks; try { tasks = (await api("/api/tasks")).tasks || []; } catch (e) { dashboardGrid.innerHTML = state("error", e.message); return; }
  const visible = tasks.filter((t) => (taskStatus === "all" || t.status === taskStatus) && (taskPriority === "all" || (t.priority || "medium") === taskPriority) && (!taskSearch || `${t.title} ${(t.tags || []).join(" ")}`.toLowerCase().includes(taskSearch.toLowerCase())));
  const subtasks = (task) => tasks.filter((x) => String(x.parent_id) === String(task.id));
  const renderTask = (t) => { const children = subtasks(t); return `<article class="kanban-task" draggable="true" data-kanban-id="${t.id}"><strong>${esc(t.title)}</strong><small>${dateBR(t.due_at)}</small>${children.length ? `<small>${children.filter((x) => x.status === "done").length}/${children.length} subtarefas</small><div class="task-subtasks">${children.map((x) => `<span>${esc(x.title)}</span>`).join("")}</div>` : ""}<span class="task-status priority-${esc(t.priority || "medium")}">${taskPriorityLabel(t.priority)}</span><div><button class="task-subtask" data-subtask-task="${t.id}" type="button">+</button><button class="task-edit" data-edit-task="${t.id}" type="button">✎</button><button class="task-delete" data-delete-task="${t.id}" type="button">×</button></div></article>`; };
  const rows = visible.map((t) => `<li class="task-row ${t.status === "done" ? "is-done" : ""}"><label class="task-check"><input type="checkbox" data-task-id="${t.id}" ${t.status === "done" ? "checked" : ""}><span></span></label><div><strong>${esc(t.title)}</strong><small>${dateBR(t.due_at)}</small>${subtasks(t).map((x) => `<small class="task-subtask-row">↳ ${esc(x.title)}</small>`).join("")}</div><em class="task-status priority-${esc(t.priority || "medium")}">${taskPriorityLabel(t.priority)}</em><button class="task-subtask" data-subtask-task="${t.id}" type="button">+</button><button class="task-edit" data-edit-task="${t.id}" type="button">✎</button><button class="task-delete" data-delete-task="${t.id}" type="button">×</button></li>`).join("");
  const columns = [["todo", "A fazer"], ["doing", "Em andamento"], ["blocked", "Bloqueadas"], ["done", "Concluídas"]].map(([status, label]) => `<section class="kanban-column" data-kanban-status="${status}"><h3>${label}<span>${visible.filter((t) => t.status === status).length}</span></h3>${visible.filter((t) => t.status === status).map(renderTask).join("") || `<p class="task-empty">Vazio</p>`}</section>`).join("");
  const content = visible.length ? (taskMode === "list" ? `<ul class="task-list">${rows}</ul>` : `<div class="kanban-board">${columns}</div>`) : state("empty", "Nenhuma tarefa encontrada. Crie a primeira tarefa.");
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Meu dia</p><h2>Tarefas</h2><p>Organize prioridades e acompanhe o trabalho da equipe.</p></div><button class="button button-primary compact-action task-new" type="button">+ Nova tarefa</button></section><section class="task-summary"><article class="data-card"><span>Em aberto</span><strong>${tasks.filter((t) => t.status !== "done").length}</strong></article><article class="data-card"><span>Concluídas</span><strong>${tasks.filter((t) => t.status === "done").length} de ${tasks.length} concluídas</strong></article><article class="data-card"><span>Total</span><strong>${tasks.length}</strong></article></section><section class="data-card tasks-card"><div class="section-heading"><h2>Minhas tarefas</h2><div class="task-toolbar"><input class="task-search" placeholder="Buscar tarefa" value="${esc(taskSearch)}"><select class="task-filter"><option value="all">Todas</option><option value="todo">A fazer</option><option value="doing">Em andamento</option><option value="blocked">Bloqueadas</option><option value="done">Concluídas</option></select><select class="task-priority-filter"><option value="all">Todas prioridades</option><option value="high">Alta</option><option value="medium">Média</option><option value="low">Baixa</option></select><button class="filter-button task-mode" type="button">${taskMode === "list" ? "Kanban" : "Lista"}</button></div></div>${pendingDelete ? `<div class="task-confirmation">Excluir esta tarefa? <button class="button button-primary compact-action" data-confirm-delete type="button">Confirmar excluir</button><button class="button button-secondary compact-action" data-cancel-delete type="button">Cancelar</button></div>` : ""}${content}</section>`;
  dashboardGrid.querySelector(".task-filter").value = taskStatus; dashboardGrid.querySelector(".task-priority-filter").value = taskPriority;
  dashboardGrid.querySelector(".task-new").onclick = () => openCreateDialog("tarefa"); dashboardGrid.querySelector(".task-mode").onclick = () => { taskMode = taskMode === "list" ? "kanban" : "list"; renderTasksView(); }; dashboardGrid.querySelector(".task-filter").onchange = (e) => { taskStatus = e.target.value; renderTasksView(); }; dashboardGrid.querySelector(".task-priority-filter").onchange = (e) => { taskPriority = e.target.value; renderTasksView(); }; dashboardGrid.querySelector(".task-search").oninput = (e) => { taskSearch = e.target.value; renderTasksView(); };
  dashboardGrid.querySelectorAll("[data-task-id]").forEach((input) => input.onchange = async () => { try { await api(`/api/tasks/${input.dataset.taskId}`, { method: "PATCH", body: { status: input.checked ? "done" : "doing" } }); renderTasksView(); } catch (e) { input.checked = !input.checked; dashboardGrid.querySelector(".tasks-card").insertAdjacentHTML("afterbegin", `<p class="task-inline-error">${esc(e.message)}</p>`); } });
  dashboardGrid.querySelectorAll("[data-delete-task]").forEach((b) => b.onclick = () => { pendingDelete = b.dataset.deleteTask; renderTasksView(); }); dashboardGrid.querySelector("[data-cancel-delete]")?.addEventListener("click", () => { pendingDelete = null; renderTasksView(); }); dashboardGrid.querySelector("[data-confirm-delete]")?.addEventListener("click", async () => { await api(`/api/tasks/${pendingDelete}`, { method: "DELETE" }); pendingDelete = null; renderTasksView(); });
  dashboardGrid.querySelectorAll("[data-edit-task]").forEach((b) => b.onclick = () => { const t = tasks.find((x) => String(x.id) === b.dataset.editTask); openEditDialog("tarefa", { title: t.title, priority: t.priority || "medium", tags: (t.tags || []).join(", "), dueAt: t.due_at || "" }, `/api/tasks/${t.id}`); }); dashboardGrid.querySelectorAll("[data-subtask-task]").forEach((b) => b.onclick = () => openSubtaskDialog(tasks.find((x) => String(x.id) === b.dataset.subtaskTask)));
  dashboardGrid.querySelectorAll("[data-kanban-id]").forEach((b) => b.ondragstart = (e) => e.dataTransfer.setData("text/plain", b.dataset.kanbanId)); dashboardGrid.querySelectorAll("[data-kanban-status]").forEach((col) => { col.ondragover = (e) => e.preventDefault(); col.ondrop = async (e) => { const id = e.dataTransfer.getData("text/plain"); if (id) { await api(`/api/tasks/${id}`, { method: "PATCH", body: { status: col.dataset.kanbanStatus } }); renderTasksView(); } }; });
}

async function renderAgendaView() {
  let events; try { events = (await api("/api/events")).events || []; } catch (e) { dashboardGrid.innerHTML = state("error", e.message); return; } const now = new Date(), y = agendaDate.getFullYear(), m = agendaDate.getMonth(), start = new Date(y, m, 1), days = new Date(y, m + 1, 0).getDate(), first = start.getDay();
  const dayCell = (d) => `<button class="calendar-day" data-day="${d}" type="button">${d}${events.some((e) => new Date(e.starts_at).toDateString() === new Date(y, m, d).toDateString()) ? " •" : ""}</button>`; const cells = Array.from({ length: 42 }, (_, i) => { const d = i - first + 1; return d < 1 || d > days ? `<span class="calendar-day is-empty"></span>` : dayCell(d); }).join(""); const selected = events.filter((e) => new Date(e.starts_at).toDateString() === agendaDate.toDateString()); const eventMarkup = selected.map((e) => `<article class="day-event" draggable="true" data-event-id="${e.id}"><time>${new Date(e.starts_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</time><div><strong>${esc(e.title)}</strong><small>${esc(e.description || "Compromisso")}${e.recurrence && e.recurrence !== "none" ? ` · Recorrência: ${esc(e.recurrence)}` : ""}${Number(e.reminder_minutes) ? ` · Lembrete: ${e.reminder_minutes} min` : ""}</small></div><button class="event-edit" data-edit-event="${e.id}" type="button">✎</button><button class="event-delete" data-delete-event="${e.id}" type="button">×</button></article>`).join("") || state("empty", "Nenhum evento neste dia."); const upcoming = events.filter((e) => new Date(e.starts_at) >= now && new Date(e.starts_at) < new Date(now.getTime() + 7 * 86400000)).slice(0, 8);
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Organização</p><h2>Agenda</h2><p>Planeje compromissos, reuniões e os próximos passos.</p></div><button class="button button-primary compact-action agenda-new" type="button">+ Novo evento</button></section><section class="agenda-layout"><section class="data-card calendar-card"><div class="calendar-toolbar"><button class="calendar-nav" data-shift="-1" type="button">‹</button><h2>${agendaDate.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })}</h2><button class="calendar-nav" data-shift="1" type="button">›</button><button class="filter-button" data-today type="button">Hoje</button><button class="filter-button agenda-view-toggle" type="button">${agendaMode === "month" ? "Semana" : "Mês"}</button></div><div class="calendar-grid">${cells}</div></section><aside class="data-card day-agenda"><h2>${agendaDate.toLocaleDateString("pt-BR")}</h2><div class="day-event-list">${eventMarkup}</div></aside><aside class="data-card agenda-upcoming"><h2>Próximos 7 dias</h2>${upcoming.map((e) => `<p><strong>${esc(e.title)}</strong><small>${dateBR(e.starts_at)}</small></p>`).join("") || state("empty", "Nenhum próximo evento.")}</aside></section>`;
  dashboardGrid.querySelector(".agenda-new").onclick = () => openCreateDialog("evento"); dashboardGrid.querySelector("[data-today]").onclick = () => { agendaDate = new Date(); renderAgendaView(); }; dashboardGrid.querySelector(".agenda-view-toggle").onclick = () => { agendaMode = agendaMode === "month" ? "week" : "month"; renderAgendaView(); }; dashboardGrid.querySelectorAll("[data-shift]").forEach((b) => b.onclick = () => { agendaDate.setMonth(agendaDate.getMonth() + Number(b.dataset.shift)); renderAgendaView(); }); dashboardGrid.querySelectorAll("[data-day]").forEach((b) => b.onclick = () => { agendaDate = new Date(y, m, Number(b.dataset.day)); renderAgendaView(); }); dashboardGrid.querySelectorAll("[data-edit-event]").forEach((b) => b.onclick = () => { const e = events.find((x) => String(x.id) === b.dataset.editEvent); openEditDialog("evento", { title: e.title, startsAt: e.starts_at, description: e.description || "", recurrence: e.recurrence || "none", reminderMinutes: e.reminder_minutes || 0 }, `/api/events/${e.id}`); });
  dashboardGrid.querySelectorAll("[data-delete-event]").forEach((b) => b.onclick = () => { b.insertAdjacentHTML("afterend", `<span class="event-confirm"><button data-confirm-event="${b.dataset.deleteEvent}" type="button">Confirmar excluir</button><button data-cancel-event type="button">Cancelar</button></span>`); b.remove(); }); dashboardGrid.querySelectorAll("[data-confirm-event]").forEach((b) => b.onclick = async () => { await api(`/api/events/${b.dataset.confirmEvent}`, { method: "DELETE" }); renderAgendaView(); });
}
registerRoutes({ "agenda": renderAgendaView, "tarefas": renderTasksView });
