/* ==========================================================================
   FocusDev — módulo "meu-dia"
   Telas: Agenda, Tarefas
   Carregado depois de app.js; usa os helpers globais do núcleo
   (dashboardGrid, escapeHtml, openCreateDialog, api, stateBlock, registerRoutes).
   Ownership: modules/meu-dia.js
   ========================================================================== */

let agendaMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
let agendaSelectedDate = new Date();
let agendaViewMode = "month";
let taskViewMode = "list";
let taskPriorityFilter = "all";
async function renderTasksView(filter = "all", mode = taskViewMode) {
  let tasks = [];
  try { const response = await fetch("/api/tasks"); if (response.ok) tasks = (await response.json()).tasks || []; } catch { /* mantém a tela utilizável sem a API */ }
  const visible = tasks.filter((task) => (filter === "all" || task.status === filter) && (taskPriorityFilter === "all" || (task.priority || "medium") === taskPriorityFilter));
  const open = tasks.filter((task) => task.status !== "done").length, done = tasks.length - open;
  const tags = (task) => (task.tags || []).map((tag) => `<span class="task-tag">${escapeHtml(tag)}</span>`).join(""), progress = (task) => { const children = tasks.filter((item) => String(item.parent_id) === String(task.id)); return children.length ? `<small class="task-progress-label">${children.filter((item) => item.status === "done").length}/${children.length} subtarefas</small>` : ""; };
  const card = (task) => { const priority = task.priority || "medium"; return `<article class="kanban-task" draggable="true" data-kanban-id="${task.id}"><strong>${escapeHtml(task.title)}</strong><small>${task.due_at ? new Date(task.due_at).toLocaleDateString("pt-BR") : "Sem prazo"}</small>${progress(task)}<div class="task-tags">${tags(task)}</div><span class="task-status priority-${priority}">${priority === "high" ? "Alta" : priority === "low" ? "Baixa" : "Média"}</span><div><button class="task-subtask" type="button" data-subtask-task="${task.id}">+</button><button class="task-edit" type="button" data-edit-task="${task.id}">✎</button><button class="task-delete" type="button" data-delete-task="${task.id}">×</button></div></article>`; };
  const rows = visible.length ? visible.map((task) => { const due = task.due_at ? new Date(task.due_at).toLocaleString("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "Sem prazo"; const priority = task.priority || "medium"; return `<li class="task-row ${task.status === "done" ? "is-done" : ""}"><label class="task-check"><input type="checkbox" data-task-id="${task.id}" ${task.status === "done" ? "checked" : ""} /><span></span></label><div><strong>${escapeHtml(task.title)}</strong><small>${due}</small>${progress(task)}<span class="task-tags">${tags(task)}</span></div><em class="task-status priority-${priority}">${priority === "high" ? "Alta" : priority === "low" ? "Baixa" : "Média"}</em><button class="task-subtask" type="button" data-subtask-task="${task.id}" aria-label="Adicionar subtarefa">+</button><button class="task-edit" type="button" data-edit-task="${task.id}" aria-label="Editar ${escapeHtml(task.title)}">✎</button><button class="task-delete" type="button" data-delete-task="${task.id}" aria-label="Excluir ${escapeHtml(task.title)}">×</button></li>`; }).join("") : '<li class="task-empty">Nenhuma tarefa encontrada.</li>';
  const columns = [["todo", "A fazer"], ["doing", "Em andamento"], ["blocked", "Bloqueadas"], ["done", "Concluídas"]].map(([status, label]) => `<section class="kanban-column" data-kanban-status="${status}"><h3>${label}<span>${visible.filter((task) => task.status === status).length}</span></h3>${visible.filter((task) => task.status === status).map(card).join("") || '<p class="task-empty">Vazio</p>'}</section>`).join("");
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Meu dia</p><h2>Tarefas</h2><p>Organize prioridades e acompanhe o trabalho da equipe.</p></div><button class="button button-primary compact-action task-new" type="button">+ Nova tarefa</button></section><section class="task-summary"><article class="data-card"><span>Em aberto</span><strong>${open}</strong></article><article class="data-card"><span>Concluídas</span><strong>${done}</strong></article><article class="data-card"><span>Total</span><strong>${tasks.length}</strong></article></section><section class="data-card tasks-card"><div class="section-heading"><div><p class="card-kicker">Organização</p><h2>Minhas tarefas</h2></div><div class="task-toolbar"><select class="task-filter" aria-label="Filtrar tarefas"><option value="all" ${filter === "all" ? "selected" : ""}>Todas</option><option value="todo" ${filter === "todo" ? "selected" : ""}>A fazer</option><option value="doing" ${filter === "doing" ? "selected" : ""}>Em andamento</option><option value="blocked" ${filter === "blocked" ? "selected" : ""}>Bloqueadas</option><option value="done" ${filter === "done" ? "selected" : ""}>Concluídas</option></select><select class="task-priority-filter" aria-label="Filtrar prioridade"><option value="all" ${taskPriorityFilter === "all" ? "selected" : ""}>Todas prioridades</option><option value="high" ${taskPriorityFilter === "high" ? "selected" : ""}>Alta</option><option value="medium" ${taskPriorityFilter === "medium" ? "selected" : ""}>Média</option><option value="low" ${taskPriorityFilter === "low" ? "selected" : ""}>Baixa</option></select><button class="filter-button task-mode" type="button">${mode === "list" ? "Kanban" : "Lista"}</button></div></div>${mode === "list" ? `<ul class="task-list">${rows}</ul>` : `<div class="kanban-board">${columns}</div>`}</section>`;
  dashboardGrid.querySelector(".task-new").addEventListener("click", () => openCreateDialog("tarefa"));
  dashboardGrid.querySelector(".task-filter").addEventListener("change", (event) => renderTasksView(event.target.value, mode));
  dashboardGrid.querySelector(".task-priority-filter").addEventListener("change", (event) => { taskPriorityFilter = event.target.value; renderTasksView(filter, mode); });
  dashboardGrid.querySelector(".task-mode").addEventListener("click", () => { taskViewMode = mode === "list" ? "kanban" : "list"; renderTasksView(filter, taskViewMode); });
  dashboardGrid.querySelectorAll("[data-task-id]").forEach((input) => input.addEventListener("change", async () => { input.disabled = true; try { const response = await fetch(`/api/tasks/${input.dataset.taskId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: input.checked ? "done" : "doing" }) }); if (!response.ok) throw new Error(); await renderTasksView(filter); } catch { input.disabled = false; input.checked = !input.checked; window.alert("Não foi possível atualizar a tarefa."); } }));
  dashboardGrid.querySelectorAll("[data-delete-task]").forEach((button) => button.addEventListener("click", async () => { if (!window.confirm("Excluir esta tarefa?")) return; const response = await fetch(`/api/tasks/${button.dataset.deleteTask}`, { method: "DELETE" }); if (response.ok) renderTasksView(filter); }));
  dashboardGrid.querySelectorAll("[data-edit-task]").forEach((button) => button.addEventListener("click", () => { const task = tasks.find((item) => String(item.id) === button.dataset.editTask); if (task) openEditDialog("tarefa", { title: task.title, priority: task.priority || "medium", tags: (task.tags || []).join(", "), dueAt: task.due_at }, `/api/tasks/${task.id}/details`); }));
  dashboardGrid.querySelectorAll("[data-subtask-task]").forEach((button) => button.addEventListener("click", () => { const task = tasks.find((item) => String(item.id) === button.dataset.subtaskTask); if (task) openSubtaskDialog(task); }));
  dashboardGrid.querySelectorAll("[data-kanban-status]").forEach((column) => { column.addEventListener("dragover", (event) => event.preventDefault()); column.addEventListener("drop", async (event) => { const id = event.dataTransfer.getData("text/plain"); if (!id) return; await fetch(`/api/tasks/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: column.dataset.kanbanStatus }) }); renderTasksView(filter, mode); }); });
  dashboardGrid.querySelectorAll("[data-kanban-id]").forEach((task) => task.addEventListener("dragstart", (event) => event.dataTransfer.setData("text/plain", task.dataset.kanbanId)));
}

async function renderAgendaView() {
  const now = new Date(), year = agendaMonth.getFullYear(), month = agendaMonth.getMonth();
  let events = [];
  try { const response = await fetch("/api/events"); if (response.ok) events = (await response.json()).events || []; } catch { /* permite usar a agenda vazia durante o desenvolvimento */ }
  const monthEvents = events.filter((event) => { const date = new Date(event.starts_at); return date.getFullYear() === year && date.getMonth() === month; });
  const eventsByDay = new Map(monthEvents.map((event) => [new Date(event.starts_at).getDate(), true]));
  const firstDay = new Date(year, month, 1).getDay(), days = new Date(year, month + 1, 0).getDate();
  const cells = Array.from({ length: 42 }, (_, index) => { const day = index - firstDay + 1; if (day < 1 || day > days) return '<span class="calendar-day is-empty"></span>'; const isToday = year === now.getFullYear() && month === now.getMonth() && day === now.getDate(); return `<button class="calendar-day${isToday ? " is-today" : ""}" type="button" data-day="${day}">${day}${eventsByDay.has(day) ? '<i></i>' : ""}</button>`; }).join("");
  const weekStart = new Date(agendaSelectedDate); weekStart.setDate(weekStart.getDate() - weekStart.getDay());
  const weekCells = Array.from({ length: 7 }, (_, index) => { const date = new Date(weekStart); date.setDate(weekStart.getDate() + index); const isToday = date.toDateString() === now.toDateString(), hasEvents = events.some((event) => new Date(event.starts_at).toDateString() === date.toDateString()); return `<button class="calendar-day calendar-week-day${isToday ? " is-today" : ""}${date.toDateString() === agendaSelectedDate.toDateString() ? " is-selected" : ""}" type="button" data-date="${date.toISOString()}"><span>${date.toLocaleDateString("pt-BR", { weekday: "short" })}</span><strong>${date.getDate()}</strong>${hasEvents ? '<i></i>' : ""}</button>`; }).join("");
  const selectedEvents = events.filter((event) => { const date = new Date(event.starts_at); return date.toDateString() === agendaSelectedDate.toDateString(); });
  const eventMarkup = selectedEvents.length ? selectedEvents.map((event, index) => { const date = new Date(event.starts_at), recurrenceLabel = event.recurrence && event.recurrence !== "none" ? ` · ${event.recurrence === "daily" ? "Diário" : event.recurrence === "weekly" ? "Semanal" : "Mensal"}` : "", reminderLabel = Number(event.reminder_minutes) ? ` · Lembrete ${event.reminder_minutes} min` : ""; return `<article class="day-event" draggable="true" data-event-id="${event.id}"><time>${date.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</time><div><strong>${escapeHtml(event.title)}</strong><small>${escapeHtml(event.description || "Compromisso da agenda")}${recurrenceLabel}${reminderLabel}</small></div><i class="event-dot ${["blue", "pink", "orange"][index % 3]}"></i><button class="event-edit" type="button" data-edit-event="${event.id}" aria-label="Editar evento">✎</button><button class="event-delete" type="button" data-delete-event="${event.id}" aria-label="Excluir evento">×</button></article>`; }).join("") : '<p class="agenda-empty">Nenhum evento neste dia.</p>';
  const historyEvents = events.filter((event) => new Date(event.starts_at) < now).sort((a, b) => new Date(b.starts_at) - new Date(a.starts_at)).slice(0, 8);
  const historyMarkup = historyEvents.map((event) => { const date = new Date(event.starts_at); return `<article><span class="history-date">${date.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" })}<strong>${date.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</strong></span><div><strong>${escapeHtml(event.title)}</strong><small>${escapeHtml(event.description || "Compromisso da agenda")}</small></div><span class="history-status">Concluído</span></article>`; }).join("") || '<p class="agenda-empty">Nenhum compromisso concluído.</p>';
  dashboardGrid.innerHTML = `<section class="page-intro agenda-intro"><div><p class="card-kicker">Organização</p><h2>Agenda</h2><p>Planeje compromissos, reuniões e os próximos passos da equipe.</p></div><button class="button button-primary compact-action agenda-new" type="button">+ Novo evento</button></section><section class="agenda-layout"><section class="data-card calendar-card"><div class="calendar-toolbar"><button class="calendar-nav" type="button" data-agenda-shift="-1" aria-label="Período anterior">‹</button><h2>${agendaViewMode === "month" ? agendaMonth.toLocaleDateString("pt-BR", { month: "long", year: "numeric" }) : "Semana de " + weekStart.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" })}</h2><div><button class="calendar-nav" type="button" data-agenda-shift="1" aria-label="Próximo período">›</button><button class="filter-button agenda-view-toggle" type="button">${agendaViewMode === "month" ? "Semanal" : "Mensal"}</button></div></div><div class="calendar-weekdays" ${agendaViewMode === "week" ? "hidden" : ""}><span>Dom</span><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span></div><div class="calendar-grid ${agendaViewMode === "week" ? "is-week-view" : ""}">${agendaViewMode === "month" ? cells : weekCells}</div></section><aside class="data-card day-agenda"><div class="section-heading"><div><p class="card-kicker">${agendaSelectedDate.toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" })}</p><h2>Agenda do dia</h2></div><span class="task-count">${selectedEvents.length} evento${selectedEvents.length === 1 ? "" : "s"}</span></div><div class="day-event-list">${eventMarkup}</div><button class="agenda-add-link" type="button">+ Adicionar compromisso</button></aside></section><section class="data-card agenda-upcoming"><div class="section-heading"><div><p class="card-kicker">Visão geral</p><h2>Próximos compromissos</h2></div><button class="filter-button agenda-export" type="button">Exportar .ics</button></div><div class="upcoming-list">${events.filter((event) => new Date(event.starts_at) >= now).slice(0, 5).map((event) => { const date = new Date(event.starts_at); return `<article><span class="upcoming-date">${date.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" })}<strong>${date.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</strong></span><div><strong>${escapeHtml(event.title)}</strong><small>${escapeHtml(event.description || "Compromisso da agenda")}</small></div></article>`; }).join("") || '<p class="agenda-empty">Nenhum próximo compromisso.</p>'}</div></section>`;
  const historyCard = document.createElement("section"); historyCard.className = "data-card agenda-history"; historyCard.innerHTML = `<div class="section-heading"><div><p class="card-kicker">Arquivo</p><h2>Histórico de compromissos</h2></div><span class="task-count">${historyEvents.length} registro${historyEvents.length === 1 ? "" : "s"}</span></div><div class="history-list">${historyMarkup}</div>`; dashboardGrid.append(historyCard);
  dashboardGrid.querySelectorAll(".agenda-new, .agenda-add-link").forEach((button) => button.addEventListener("click", () => { openCreateDialog("evento"); const input = dialogFields.querySelector('[name="startsAt"]'); const date = new Date(agendaSelectedDate); date.setHours(9, 0, 0, 0); if (input) input.value = new Date(date - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }));
  dashboardGrid.querySelectorAll("[data-delete-event]").forEach((button) => button.addEventListener("click", async () => { if (!window.confirm("Excluir este evento?")) return; const response = await fetch(`/api/events/${button.dataset.deleteEvent}`, { method: "DELETE" }); if (response.ok) renderAgendaView(); }));
  dashboardGrid.querySelectorAll("[data-edit-event]").forEach((button) => button.addEventListener("click", () => { const event = selectedEvents.find((item) => String(item.id) === button.dataset.editEvent); if (event) openEditDialog("evento", { title: event.title, startsAt: event.starts_at, description: event.description || "", recurrence: event.recurrence || "none", reminderMinutes: String(event.reminder_minutes || 0) }, `/api/events/${event.id}/schedule`); }));
  dashboardGrid.querySelectorAll("[data-agenda-shift]").forEach((button) => button.addEventListener("click", () => { agendaMonth.setMonth(agendaMonth.getMonth() + Number(button.dataset.agendaShift)); renderAgendaView(); }));
  dashboardGrid.querySelector(".agenda-view-toggle").addEventListener("click", () => { agendaViewMode = agendaViewMode === "month" ? "week" : "month"; renderAgendaView(); });
  dashboardGrid.querySelector(".agenda-export").addEventListener("click", () => { const lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//FocusDev//Agenda//PT-BR", ...events.map((event) => { const start = new Date(event.starts_at).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); return `BEGIN:VEVENT\nUID:${event.id}@focusdev\nDTSTART:${start}\nSUMMARY:${String(event.title).replace(/[\\,;]/g, "\\$&")}\nDESCRIPTION:${String(event.description || "").replace(/[\\,;]/g, "\\$&")}\nEND:VEVENT`; }), "END:VCALENDAR"].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([lines], { type: "text/calendar" })); link.download = "focusdev-agenda.ics"; link.click(); URL.revokeObjectURL(link.href); });
  dashboardGrid.querySelectorAll(".calendar-day:not(.is-empty):not(.calendar-week-day)").forEach((day) => day.addEventListener("click", () => { agendaSelectedDate = new Date(year, month, Number(day.dataset.day)); renderAgendaView(); }));
  dashboardGrid.querySelectorAll(".calendar-week-day").forEach((day) => day.addEventListener("click", () => { agendaSelectedDate = new Date(day.dataset.date); renderAgendaView(); }));
  dashboardGrid.querySelectorAll(".day-event").forEach((event) => event.addEventListener("dragstart", (drag) => { drag.dataTransfer.setData("text/plain", event.dataset.eventId); event.classList.add("is-dragging"); }));
  dashboardGrid.querySelectorAll(".day-event").forEach((event) => event.addEventListener("dragend", () => event.classList.remove("is-dragging")));
  dashboardGrid.querySelectorAll(".calendar-day:not(.is-empty):not(.calendar-week-day)").forEach((day) => {
    day.addEventListener("dragover", (drag) => { drag.preventDefault(); day.classList.add("is-drop-target"); });
    day.addEventListener("dragleave", () => day.classList.remove("is-drop-target"));
    day.addEventListener("drop", async (drop) => {
      drop.preventDefault(); day.classList.remove("is-drop-target");
      const eventId = drop.dataTransfer.getData("text/plain"); if (!eventId) return;
      const startsAt = new Date(year, month, Number(day.dataset.day), 9, 0);
      try { const response = await fetch(`/api/events/${eventId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startsAt: startsAt.toISOString() }) }); if (!response.ok) throw new Error(); await renderAgendaView(); } catch { window.alert("Não foi possível mover o evento."); }
    });
  });
}


registerRoutes({
  "agenda": () => renderAgendaView(),
  "tarefas": () => renderTasksView(),
});
