const invoiceEsc = (value) => escapeHtml(value ?? "");
const invoiceMoney = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const invoiceDate = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const invoiceStatus = { draft: "Rascunho", issued: "Emitida", cancelled: "Cancelada", error: "Com erro", pending: "Pendente" };
const invoiceFilter = { search: "", status: "" };

async function renderInvoicesScreen() {
  const title = "Notas fiscais", description = "Acompanhe documentos fiscais e o status de cada emissão.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-invoice-new type="button">+ Nova nota</button></section>${stateBlock.loading("Carregando notas fiscais...")}`;
  try {
    const params = new URLSearchParams(); if (invoiceFilter.search) params.set("search", invoiceFilter.search); if (invoiceFilter.status) params.set("status", invoiceFilter.status); const items = (await api(`/api/invoices?${params}`)).invoices || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Financeiro</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-invoice-new type="button">+ Nova nota</button></section><section class="finance-metrics"><article class="data-card finance-metric"><span>Total registrado</span><strong>${invoiceMoney(items.reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></article><article class="data-card finance-metric"><span>Emitidas</span><strong>${items.filter((item) => item.status === "issued").length}</strong></article><article class="data-card finance-metric"><span>Rascunhos</span><strong>${items.filter((item) => item.status === "draft").length}</strong></article><article class="data-card finance-metric"><span>Com erro</span><strong>${items.filter((item) => item.status === "error").length}</strong></article></section><section class="data-card finance-list"><div class="finance-toolbar"><input type="search" data-invoice-search value="${invoiceEsc(invoiceFilter.search)}" placeholder="Buscar número ou cliente" aria-label="Buscar nota fiscal"><select data-invoice-filter aria-label="Filtrar status"><option value="">Todos os status</option><option value="draft">Rascunhos</option><option value="issued">Emitidas</option><option value="cancelled">Canceladas</option><option value="error">Com erro</option></select></div>${items.length ? `<div class="table-wrap"><table class="finance-table"><thead><tr><th>Número</th><th>Cliente</th><th>Valor</th><th>Emissão</th><th>Status</th><th>Documentos</th><th>Ações</th></tr></thead><tbody>${items.map((item) => `<tr><td>${invoiceEsc(item.number || "Sem número")}</td><td>${invoiceEsc(item.client_name || item.client_id || "Sem cliente")}</td><td>${invoiceMoney(item.amount)}</td><td>${invoiceDate(item.issued_on)}</td><td><span class="finance-status ${item.status === "issued" ? "positive" : item.status === "error" ? "warning" : "neutral"}">${invoiceStatus[item.status] || invoiceEsc(item.status)}</span>${item.error ? `<small>${invoiceEsc(item.error)}</small>` : ""}</td><td>${item.pdf_url ? `<a href="${invoiceEsc(item.pdf_url)}" target="_blank" rel="noopener">PDF</a>` : "—"}${item.xml_url ? ` · <a href="${invoiceEsc(item.xml_url)}" target="_blank" rel="noopener">XML</a>` : ""}</td><td><button class="compact-action" data-invoice-edit="${invoiceEsc(item.id)}" type="button">Editar</button><button class="compact-action" data-invoice-delete="${invoiceEsc(item.id)}" type="button">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : stateBlock.empty("Nenhuma nota fiscal", "Cadastre um documento ou conecte um emissor fiscal.")}</section>`;
    const search = dashboardGrid.querySelector("[data-invoice-search]"), status = dashboardGrid.querySelector("[data-invoice-filter]"); status.value = invoiceFilter.status; let timer; search?.addEventListener("input", () => { clearTimeout(timer); invoiceFilter.search = search.value.trim(); timer = setTimeout(renderInvoicesScreen, 250); }); status?.addEventListener("change", () => { invoiceFilter.status = status.value; renderInvoicesScreen(); });
    const openNew = () => openCreateDialog("invoice"); dashboardGrid.querySelector("[data-invoice-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-invoice-empty]")?.addEventListener("click", openNew);
    dashboardGrid.querySelectorAll("[data-invoice-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.invoiceEdit)); if (item) openEditDialog("invoice", item, `/api/invoices/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-invoice-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir nota fiscal?", onConfirm: async () => { try { await api(`/api/invoices/${button.dataset.invoiceDelete}`, { method: "DELETE" }); toast("Nota fiscal excluída.", "success"); renderInvoicesScreen(); } catch (error) { toast(error.message, "error"); } } })));
  } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "invoice-retry"); dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderInvoicesScreen); }
}

registerRoutes({ "notas-fiscais": renderInvoicesScreen });
dashboardGrid.addEventListener("click", (event) => { if (event.target.closest(".invoice-retry")) renderInvoicesScreen(); });
const invoiceDetailsObserver = new MutationObserver(async () => { if (location.hash.replace(/^#/, "") !== "notas-fiscais") return; const list = dashboardGrid.querySelector(".finance-list"); if (!list || list.dataset.detailsBound === "1") return; list.dataset.detailsBound = "1"; try { const items = (await api("/api/invoices?limit=100")).invoices || []; list.querySelectorAll("tbody tr").forEach((row, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "compact-action"; button.textContent = "Detalhes"; button.addEventListener("click", () => { const item = items[index]; if (!item) return; const html = Object.entries(item).filter(([key]) => !["id", "organization_id"].includes(key)).map(([key, value]) => `<dt>${invoiceEsc(key.replaceAll("_", " "))}</dt><dd>${invoiceEsc(value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : value)}</dd>`).join(""); ui.drawer({ title: item.number || "Nota fiscal", subtitle: invoiceStatus[item.status] || item.status || "Sem status", html: `<dl>${html}</dl>` }); }); row.querySelector("td:last-child")?.prepend(button); }); } catch { list.dataset.detailsBound = ""; } });
invoiceDetailsObserver.observe(dashboardGrid, { childList: true, subtree: true });
