/* Operação: telas reais de contratos, projetos, arquivos e tickets. */
const labels = { draft: "Rascunho", active: "Ativo", expired: "Expirado", cancelled: "Cancelado", planning: "Planejamento", paused: "Pausado", done: "Concluído", open: "Aberto", in_progress: "Em andamento", waiting: "Aguardando", low: "Baixa", medium: "Média", high: "Alta", urgent: "Urgente" };
const esc = (v) => escapeHtml(v ?? "");
const date = (v) => v ? new Date(v).toLocaleDateString("pt-BR") : "—";
const money = (v) => Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(v || 0));
const state = (kind, title, description = "") => kind === "loading" ? stateBlock.loading(title) : kind === "error" ? stateBlock.error(title, "operations-retry") : stateBlock.empty(title, description, "Criar agora", "operations-empty-action");
let clients = [];
const config = {
  contrato: { title: "Novo contrato", endpoint: "/api/contracts", fields: [{ name: "name", label: "Nome", required: true }, { name: "client_id", label: "Cliente", type: "select", options: [] }, { name: "value", label: "Valor", type: "number" }, { name: "starts_on", label: "Início", type: "date" }, { name: "ends_on", label: "Fim", type: "date" }, { name: "status", label: "Status", type: "select", options: Object.entries({ draft: "Rascunho", active: "Ativo", expired: "Expirado", cancelled: "Cancelado" }) } ] },
  projeto: { title: "Novo projeto", endpoint: "/api/projects", fields: [{ name: "name", label: "Nome" }, { name: "client_id", label: "Cliente", type: "select", options: [] }, { name: "contract_id", label: "Contrato (ID)", required: false }, { name: "status", label: "Status", type: "select", options: Object.entries({ planning: "Planejamento", active: "Ativo", paused: "Pausado", done: "Concluído" }) }, { name: "progress", label: "Progresso", type: "number" }] },
  arquivo: { title: "Adicionar arquivo", endpoint: "/api/files", fields: [{ name: "name", label: "Nome" }, { name: "url", label: "URL externa", type: "url" }, { name: "kind", label: "Tipo", type: "select", options: [["document", "Documento"], ["image", "Imagem"], ["other", "Outro"]] }, { name: "project_id", label: "Projeto (ID)", required: false }, { name: "client_id", label: "Cliente", type: "select", options: [] }] },
  ticket: { title: "Novo ticket", endpoint: "/api/tickets", fields: [{ name: "title", label: "Título" }, { name: "description", label: "Descrição", required: false }, { name: "client_id", label: "Cliente", type: "select", options: [] }, { name: "priority", label: "Prioridade", type: "select", options: Object.entries({ low: "Baixa", medium: "Média", high: "Alta", urgent: "Urgente" }) }, { name: "status", label: "Status", type: "select", options: Object.entries({ open: "Aberto", in_progress: "Em andamento", waiting: "Aguardando", done: "Concluído" }) }, { name: "due_at", label: "Prazo", type: "datetime-local", required: false }] }
};
Object.assign(createConfig, config);
const projectContractField = config.projeto.fields.find((field) => field.name === "contract_id");
if (projectContractField) { projectContractField.type = "select"; projectContractField.options = [["", "Sem contrato"]]; }
config.contrato.fields.push({ name: "proposal_id", label: "Proposta aprovada (ID)", required: false }, { name: "project_id", label: "Projeto vinculado (ID)", required: false }, { name: "contract_type", label: "Tipo de contrato", required: false }, { name: "contract_number", label: "Número do contrato", required: false }, { name: "issued_on", label: "Data de emissão", type: "date", required: false }, { name: "description", label: "Objeto e descrição", required: false }, { name: "scope_included", label: "Escopo incluído", required: false }, { name: "scope_excluded", label: "Escopo não incluído", required: false }, { name: "deliverables", label: "Entregáveis", required: false }, { name: "technologies", label: "Tecnologias", required: false }, { name: "milestones", label: "Etapas e cronograma", required: false }, { name: "installments", label: "Quantidade de parcelas", type: "number", required: false }, { name: "installment_value", label: "Valor das parcelas", type: "number", required: false }, { name: "payment_method", label: "Forma de pagamento", required: false }, { name: "payment_due_dates", label: "Datas de vencimento", required: false }, { name: "maintenance_monthly", label: "Manutenção mensal", type: "number", required: false }, { name: "hosting_monthly", label: "Hospedagem mensal", type: "number", required: false }, { name: "server_monthly", label: "Servidor/VPS mensal", type: "number", required: false }, { name: "domain_monthly", label: "Domínio mensal", type: "number", required: false }, { name: "apis_monthly", label: "APIs mensal", type: "number", required: false }, { name: "licenses_monthly", label: "Licenças mensal", type: "number", required: false }, { name: "warranty_period", label: "Garantia", required: false }, { name: "support_period", label: "Suporte", required: false }, { name: "intellectual_property", label: "Propriedade intelectual", required: false }, { name: "cancellation_terms", label: "Cancelamento e rescisão", required: false }, { name: "data_protection_terms", label: "Proteção de dados/LGPD", required: false });
config.projeto.fields.push(
  { name: "description", label: "Descrição", required: false },
  { name: "current_stage", label: "Etapa atual", required: false },
  { name: "starts_on", label: "Data de início", type: "date", required: false },
  { name: "due_on", label: "Prazo previsto", type: "date", required: false },
  { name: "next_action", label: "Próxima ação", required: false },
  { name: "next_action_at", label: "Data da próxima ação", type: "datetime-local", required: false },
  { name: "technologies", label: "Tecnologias", required: false },
  { name: "repository_url", label: "Repositório GitHub", type: "url", required: false, githubAutoFill: true },
  { name: "development_url", label: "Link de desenvolvimento", type: "url", required: false },
  { name: "staging_url", label: "Link de homologação", type: "url", required: false },
  { name: "production_url", label: "Link de produção", type: "url", required: false },
  { name: "domain", label: "Domínio", required: false },
  { name: "hosting_provider", label: "Provedor de hospedagem", required: false },
  { name: "database_provider", label: "Banco/Firebase/Supabase", required: false },
  { name: "external_apis", label: "APIs e serviços externos", required: false },
  { name: "access_storage_reference", label: "Onde os acessos estão guardados", placeholder: "Ex.: 1Password do cliente", required: false },
  { name: "total_value", label: "Valor total", type: "number", required: false },
  { name: "down_payment", label: "Valor de entrada", type: "number", required: false },
  { name: "payment_status", label: "Situação do pagamento", required: false },
  { name: "pending_items", label: "Pendências", required: false },
  { name: "observations", label: "Observações", required: false }
);
async function setup(kind) { const c = config[kind]; if (c.fields.some((f) => f.name.endsWith("_id"))) { const [clientData, contractData] = await Promise.all([api("/api/clients"), kind === "projeto" ? api("/api/contracts") : Promise.resolve({ contracts: [] })]); clients = clientData.clients || []; c.fields.forEach((f) => { if (f.name === "client_id") f.options = [["", "Sem cliente"], ...clients.map((x) => [x.id, x.name])]; if (f.name === "contract_id" && f.type === "select") f.options = [["", "Sem contrato"], ...(contractData.contracts || []).map((x) => [x.id, x.name])]; }); } openCreateDialog(kind); }
function intro(title, description, kind) { return `<section class="page-intro operations-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action operations-new" data-create="${kind}" type="button">+ Novo</button></section>`; }
function bindCommon(kind, rows, endpoint) { dashboardGrid.querySelector(".operations-new")?.addEventListener("click", () => setup(kind)); dashboardGrid.querySelectorAll("[data-delete]").forEach((b) => b.addEventListener("click", async () => { b.disabled = true; await api(`${endpoint}/${b.dataset.delete}`, { method: "DELETE" }); renderHashRoute(); })); dashboardGrid.querySelectorAll("[data-edit]").forEach((b) => b.addEventListener("click", () => { const item = rows.find((x) => String(x.id) === b.dataset.edit); if (!item) return; setup(kind).then(() => { const form = document.querySelector("#create-form"); if (!form) return; Object.entries(item).forEach(([k, v]) => { const field = form.elements[k]; if (field && v != null) field.value = String(v); }); form.dataset.method = "PATCH"; form.dataset.endpoint = `${endpoint}/${item.id}`; }); })); }
async function renderContracts() { const title = "Contratos"; dashboardGrid.innerHTML = intro(title, "Controle vigências, valores e o relacionamento com cada cliente.", "contrato") + state("loading", "Carregando contratos..."); try { const d = await api("/api/contracts"), rows = d.contracts || []; const soon = (x) => x.ends_on && new Date(x.ends_on) >= new Date() && new Date(x.ends_on) <= new Date(Date.now() + 30 * 864e5); dashboardGrid.innerHTML = intro(title, "Controle vigências, valores e o relacionamento com cada cliente.", "contrato") + `<section class="data-card operations-table"><div class="table-wrap"><table><thead><tr><th>Contrato</th><th>Cliente</th><th>Valor</th><th>Vigência</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map((x) => `<tr class="${soon(x) ? "operations-expiring" : ""}"><td>${esc(x.name)}${soon(x) ? " <b>Vence em até 30 dias</b>" : ""}</td><td>${esc(x.client_name || "Sem cliente")}</td><td>${money(x.value)}</td><td>${date(x.starts_on)} — ${date(x.ends_on)}</td><td>${esc(labels[x.status] || x.status)}</td><td><button class="compact-action" data-edit="${x.id}" type="button">Editar</button> <button class="compact-action" data-delete="${x.id}" type="button">Excluir</button></td></tr>`).join("") || state("empty", "Nenhum contrato", "Comece cadastrando o primeiro contrato.")}</tbody></table></div></section>`; bindCommon("contrato", rows, "/api/contracts"); } catch (e) { dashboardGrid.innerHTML = intro(title, "Controle vigências, valores e o relacionamento com cada cliente.", "contrato") + state("error", e.message); } }
async function renderProjects() { const title = "Projetos"; dashboardGrid.innerHTML = intro(title, "Acompanhe progresso, status, clientes e contratos.", "projeto") + state("loading", "Carregando projetos..."); try { const d = await api("/api/projects"), rows = d.projects || []; dashboardGrid.innerHTML = intro(title, "Acompanhe progresso, status, clientes e contratos.", "projeto") + `<section class="data-card operations-table"><div class="table-wrap"><table><thead><tr><th>Projeto</th><th>Cliente / contrato</th><th>Progresso</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map((x) => `<tr><td>${esc(x.name)}</td><td>${esc(x.client_name || "Sem cliente")}<small>${esc(x.contract_name || "")}</small></td><td><div class="operations-progress"><span style="width:${Math.max(0, Math.min(100, Number(x.progress) || 0))}%"></span></div><small>${Number(x.progress) || 0}%</small></td><td>${esc(labels[x.status] || x.status)}</td><td><button class="compact-action" data-progress="${x.id}" type="button">Atualizar progresso</button> <button class="compact-action" data-edit="${x.id}" type="button">Editar</button></td></tr>`).join("") || state("empty", "Nenhum projeto", "Crie um projeto para acompanhar entregas.")}</tbody></table></div></section>`; bindCommon("projeto", rows, "/api/projects"); dashboardGrid.querySelectorAll("[data-progress]").forEach((b) => b.addEventListener("click", () => { const x = rows.find((r) => String(r.id) === b.dataset.progress); setup("projeto").then(() => { const f = document.querySelector("#create-form"); f.elements.progress.value = x.progress || 0; f.dataset.method = "PATCH"; f.dataset.endpoint = `/api/projects/${x.id}`; }); })); } catch (e) { dashboardGrid.innerHTML = intro(title, "Acompanhe progresso, status, clientes e contratos.", "projeto") + state("error", e.message); } }
async function renderFiles() { dashboardGrid.innerHTML = intro("Arquivos", "Metadados e links externos organizados por projeto e cliente.", "arquivo") + state("loading", "Carregando arquivos..."); try { const [fd, pd] = await Promise.all([api("/api/files"), api("/api/projects")]), rows = fd.files || []; dashboardGrid.innerHTML = intro("Arquivos", "Metadados e links externos organizados por projeto e cliente.", "arquivo") + `<section class="data-card operations-table"><div class="operations-toolbar"><select data-file-project><option value="">Todos os projetos</option>${(pd.projects || []).map((p) => `<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select></div><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Projeto</th><th>Cliente</th><th>Ações</th></tr></thead><tbody>${rows.map((x) => `<tr data-project="${x.project_id || ""}"><td><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.name)}</a></td><td>${esc(x.kind || "Outro")}</td><td>${esc(x.project_name || x.project_id || "—")}</td><td>${esc(x.client_name || "—")}</td><td><button class="compact-action" data-delete="${x.id}" type="button">Excluir</button></td></tr>`).join("") || state("empty", "Nenhum arquivo", "Adicione um link externo para começar.")}</tbody></table></div></section>`; bindCommon("arquivo", rows, "/api/files"); dashboardGrid.querySelector("[data-file-project]").addEventListener("change", (e) => dashboardGrid.querySelectorAll("tbody tr").forEach((r) => { r.hidden = !!e.target.value && r.dataset.project !== e.target.value; })); } catch (e) { dashboardGrid.innerHTML = intro("Arquivos", "Metadados e links externos organizados por projeto e cliente.", "arquivo") + state("error", e.message); } }
async function renderTickets() { dashboardGrid.innerHTML = intro("Tickets", "Organize solicitações e acompanhe cada resolução.", "ticket") + state("loading", "Carregando tickets..."); try { const d = await api("/api/tickets"), rows = d.tickets || [], statuses = ["open", "in_progress", "waiting", "done"]; dashboardGrid.innerHTML = intro("Tickets", "Organize solicitações e acompanhe cada resolução.", "ticket") + `<p class="operations-urgent">Urgentes: <strong>${rows.filter((x) => x.priority === "urgent" && x.status !== "done").length}</strong></p><section class="operations-kanban">${statuses.map((s) => `<div class="data-card operations-column" data-status="${s}"><h3>${esc(labels[s])}</h3>${rows.filter((x) => x.status === s).map((x) => `<article draggable="true" data-ticket="${x.id}" class="operations-ticket"><strong>${esc(x.title)}</strong><small>${esc(x.client_name || "Sem cliente")}</small><span class="operations-priority priority-${esc(x.priority)}">${esc(labels[x.priority] || x.priority)}</span><button class="compact-action" data-edit="${x.id}" type="button">Editar</button></article>`).join("")}</div>`).join("")}</section>`; bindCommon("ticket", rows, "/api/tickets"); dashboardGrid.querySelectorAll("[data-ticket]").forEach((x) => x.addEventListener("dragstart", (e) => e.dataTransfer.setData("text/plain", x.dataset.ticket))); dashboardGrid.querySelectorAll("[data-status]").forEach((col) => { col.addEventListener("dragover", (e) => e.preventDefault()); col.addEventListener("drop", async (e) => { const id = e.dataTransfer.getData("text/plain"); if (id) { await api(`/api/tickets/${id}`, { method: "PATCH", body: { status: col.dataset.status } }); renderTickets(); } }); }); } catch (e) { dashboardGrid.innerHTML = intro("Tickets", "Organize solicitações e acompanhe cada resolução.", "ticket") + state("error", e.message); } }
const contractProjectObserver = new MutationObserver(async () => {
  const table = dashboardGrid.querySelector(".operations-table tbody");
  if (!table || table.dataset.projectActions === "1") return;
  table.dataset.projectActions = "1";
  try {
    const rows = (await api("/api/contracts")).contracts || [];
    table.querySelectorAll("tr").forEach((row, index) => {
      const contract = rows[index];
      if (!contract || !["signed", "active"].includes(contract.status) || contract.project_id) return;
      const button = document.createElement("button"); button.className = "compact-action"; button.type = "button"; button.textContent = "Criar projeto";
      button.addEventListener("click", async () => { button.disabled = true; button.textContent = "Criando..."; try { await api(`/api/contracts/${contract.id}/create-project`, { method: "POST", body: {} }); toast("Projeto criado a partir do contrato.", "success"); location.hash = "#projetos"; } catch (error) { button.disabled = false; button.textContent = "Criar projeto"; toast(error.message, "error"); } });
      row.lastElementChild?.append(" ", button);
    });
  } catch {}
});
contractProjectObserver.observe(dashboardGrid, { childList: true, subtree: true });
registerRoutes({ contratos: renderContracts, projetos: renderProjects, arquivos: renderFiles, tickets: renderTickets });
