const esc = (value) => escapeHtml(value ?? "");
async function renderTeamAccess() {
  dashboardGrid.innerHTML = stateBlock.loading("Carregando equipe...");
  try {
    const [data, dashboard] = await Promise.all([api("/api/team/access-status"), api("/api/team/dashboard")]); const users = data.users || []; const m = dashboard.members || {}, t = dashboard.tasks || {};
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Gestão</p><h2>Equipe</h2><p>Controle papéis, produtividade e acessos sem apagar o histórico.</p></div><button class="button button-secondary compact-action" type="button" data-revoke-all>Encerrar todas as sessões</button></section><section class="metrics"><article class="metric-card"><span class="metric-label">Membros</span><strong>${m.total || 0}</strong><small>${m.active || 0} ativos · ${m.inactive || 0} inativos</small></article><article class="metric-card"><span class="metric-label">Disponibilidade</span><strong>${m.available || 0}</strong><small>${m.online || 0} online · ${m.busy || 0} ocupados</small></article><article class="metric-card"><span class="metric-label">Tarefas</span><strong>${t.pending || 0}</strong><small>${t.overdue || 0} atrasadas</small></article><article class="metric-card"><span class="metric-label">Horas trabalhadas</span><strong>${Math.floor(Number(dashboard.hours?.total_minutes || 0) / 60)}h</strong><small>${dashboard.tickets?.total || 0} tickets em atendimento</small></article></section><section class="data-card config-card"><div class="config-members">${users.map((user) => `<article class="config-member"><div><strong>${esc(user.name)}</strong><small>${esc(user.email)} · ${esc(user.role)} · ${esc(user.access_status || "active")}</small></div><button class="compact-action" type="button" data-access="${esc(user.id)}" data-status="${esc(user.access_status || "active")}" ${user.access_status !== "active" ? "disabled" : ""}>${user.access_status === "active" ? "Encerrar acesso" : "Usuário desativado"}</button></article>`).join("") || stateBlock.empty("Nenhum membro cadastrado.")}</div></section>`;
    dashboardGrid.querySelectorAll("[data-access]").forEach((button) => button.addEventListener("click", async () => { if (!window.confirm("Encerrar o acesso deste usuário? O cadastro será preservado.")) return; await api(`/api/team/${button.dataset.access}/access`, { method: "PATCH", body: { access_status: "inactive" } }); renderTeamAccess(); }));
    dashboardGrid.querySelector("[data-revoke-all]")?.addEventListener("click", async () => { if (!window.confirm("Encerrar todas as sessões do workspace? Todos precisarão entrar novamente.")) return; await api("/api/team/sessions/revoke-all", { method: "POST" }); window.location.reload(); });
  } catch (error) { dashboardGrid.innerHTML = stateBlock.error(error.message, "team-retry"); }
}
registerRoutes({ equipe: renderTeamAccess });
