const templateEsc = (value) => escapeHtml(value ?? "");
const templateTypes = { proposal: "Proposta", contract: "Contrato", project: "Projeto", task: "Tarefa", checklist: "Checklist", charge: "Cobrança", followup: "Follow-up", support: "Atendimento", ticket: "Resposta de ticket", briefing: "Briefing", delivery_term: "Termo de entrega", report: "Relatório", notification: "Notificação", email: "E-mail", message: "Mensagem", whatsapp: "WhatsApp" };
const templateFilter = { search: "", kind: "" };

async function renderTemplatesScreen() {
  const title = "Templates", description = "Modelos reutilizáveis para propostas, contratos, mensagens e operação.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-template-new type="button">+ Novo template</button></section>${stateBlock.loading("Carregando templates...")}`;
  try {
    const params = new URLSearchParams(); if (templateFilter.search) params.set("search", templateFilter.search); if (templateFilter.kind) params.set("kind", templateFilter.kind); const items = (await api(`/api/templates?${params}`)).templates || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-template-new type="button">+ Novo template</button></section><section class="data-card automation-list"><div class="finance-toolbar"><input type="search" data-template-search value="${templateEsc(templateFilter.search)}" placeholder="Buscar nome, categoria ou conteúdo" aria-label="Buscar template"><select data-template-filter aria-label="Filtrar tipo"><option value="">Todos os tipos</option>${Object.entries(templateTypes).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div><div class="template-grid">${items.length ? items.map((item) => `<article class="data-card template-card"><div class="section-heading"><div><h3>${templateEsc(item.name)}</h3><small>${templateEsc(templateTypes[item.kind] || item.kind || "Modelo")}${item.category ? ` · ${templateEsc(item.category)}` : ""}</small></div><span class="finance-status ${item.active === false ? "neutral" : "positive"}">${item.active === false ? "Inativo" : "Disponível"}</span></div>${item.subject ? `<p><strong>Assunto:</strong> ${templateEsc(item.subject)}</p>` : ""}<p class="template-preview-text">${templateEsc(item.body || "Sem conteúdo")}</p><div class="template-actions"><button class="compact-action" data-template-preview="${templateEsc(item.id)}" type="button">Pré-visualizar</button><button class="compact-action" data-template-edit="${templateEsc(item.id)}" type="button">Editar</button><button class="compact-action" data-template-duplicate="${templateEsc(item.id)}" type="button">Duplicar</button><button class="compact-action" data-template-default="${templateEsc(item.id)}" type="button">Definir padrão</button><button class="compact-action" data-template-delete="${templateEsc(item.id)}" type="button">Excluir</button></div></article>`).join("") : stateBlock.empty("Nenhum template", "Crie um modelo para reutilizar em seus fluxos.", "Criar template", "template-empty")}</div></section>`;
    const search = dashboardGrid.querySelector("[data-template-search]"), kind = dashboardGrid.querySelector("[data-template-filter]"); kind.value = templateFilter.kind; let timer; search?.addEventListener("input", () => { clearTimeout(timer); templateFilter.search = search.value.trim(); timer = setTimeout(renderTemplatesScreen, 250); }); kind?.addEventListener("change", () => { templateFilter.kind = kind.value; renderTemplatesScreen(); });
    const openNew = () => openCreateDialog("template"); dashboardGrid.querySelector("[data-template-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-template-empty]")?.addEventListener("click", openNew);
    dashboardGrid.querySelectorAll("[data-template-preview]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.templatePreview)); if (item) ui.drawer({ title: item.name, subtitle: templateTypes[item.kind] || item.kind || "Template", html: `<div class="template-drawer-content">${item.subject ? `<p><strong>Assunto</strong><br>${templateEsc(item.subject)}</p>` : ""}<pre>${templateEsc(item.body || "")}</pre>${item.variables ? `<p><strong>Variáveis</strong><br>${templateEsc(item.variables)}</p>` : ""}</div>` }); }));
    dashboardGrid.querySelectorAll("[data-template-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.templateEdit)); if (item) openEditDialog("template", item, `/api/templates/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-template-duplicate]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/templates/${button.dataset.templateDuplicate}/duplicate`, { method: "POST", body: {} }); toast("Template duplicado.", "success"); renderTemplatesScreen(); } catch (error) { button.disabled = false; toast(error.message, "error"); } }));
    dashboardGrid.querySelectorAll("[data-template-default]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/templates/${button.dataset.templateDefault}/default`, { method: "PATCH", body: {} }); toast("Template padrão definido.", "success"); renderTemplatesScreen(); } catch (error) { button.disabled = false; toast(error.message, "error"); } }));
    dashboardGrid.querySelectorAll("[data-template-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir template?", onConfirm: async () => { try { await api(`/api/templates/${button.dataset.templateDelete}`, { method: "DELETE" }); toast("Template excluído.", "success"); renderTemplatesScreen(); } catch (error) { toast(error.message, "error"); } } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "template-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderTemplatesScreen); }
}

registerRoutes({ templates: renderTemplatesScreen });
