/* Biblioteca de templates com manutenção e pré-visualização do conteúdo real. */
const templateEsc = (value) => escapeHtml(value ?? "");
const templateTypes = { proposal: "Proposta", contract: "Contrato", project: "Projeto", task: "Tarefa", checklist: "Checklist", charge: "Cobrança", followup: "Follow-up", support: "Atendimento", ticket: "Resposta de ticket", briefing: "Briefing", delivery_term: "Termo de entrega", report: "Relatório", notification: "Notificação", email: "E-mail", message: "Mensagem", whatsapp: "WhatsApp" };

async function renderTemplatesScreen() {
  const title = "Templates", description = "Modelos reutilizáveis para propostas, contratos, mensagens e operação.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-template-new type="button">+ Novo template</button></section>${stateBlock.loading("Carregando templates...")}`;
  try {
    const items = (await api("/api/templates")).templates || [];
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-template-new type="button">+ Novo template</button></section><section class="data-card automation-list"><div class="finance-toolbar"><input type="search" data-template-search placeholder="Buscar nome, categoria ou conteúdo" aria-label="Buscar template"><select data-template-filter aria-label="Filtrar tipo"><option value="">Todos os tipos</option>${Object.entries(templateTypes).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></div><div class="template-grid">${items.length ? items.map((item) => `<article class="data-card template-card" data-template-row data-kind="${templateEsc(item.kind || "")}"><div class="section-heading"><div><h3>${templateEsc(item.name)}</h3><small>${templateEsc(templateTypes[item.kind] || item.kind || "Modelo")}${item.category ? ` · ${templateEsc(item.category)}` : ""}</small></div><span class="finance-status ${item.active === false ? "neutral" : "positive"}">${item.active === false ? "Inativo" : "Disponível"}</span></div>${item.subject ? `<p><strong>Assunto:</strong> ${templateEsc(item.subject)}</p>` : ""}<p class="template-preview-text">${templateEsc(item.body || "Sem conteúdo")}</p><div class="template-actions"><button class="compact-action" data-template-preview="${item.id}" type="button">Pré-visualizar</button><button class="compact-action" data-template-edit="${item.id}" type="button">Editar</button><button class="compact-action" data-template-delete="${item.id}" type="button">Excluir</button></div></article>`).join("") : stateBlock.empty("Nenhum template", "Crie um modelo para reutilizar em seus fluxos.", "Criar template", "template-empty")}</div></section>`;
    const openNew = () => openCreateDialog("template"); dashboardGrid.querySelector("[data-template-new]")?.addEventListener("click", openNew); dashboardGrid.querySelector("[data-template-empty]")?.addEventListener("click", openNew);
    const filter = () => { const query = dashboardGrid.querySelector("[data-template-search]").value.toLocaleLowerCase("pt-BR"), kind = dashboardGrid.querySelector("[data-template-filter]").value; dashboardGrid.querySelectorAll("[data-template-row]").forEach((row) => { row.hidden = (query && !row.textContent.toLocaleLowerCase("pt-BR").includes(query)) || (kind && row.dataset.kind !== kind); }); };
    dashboardGrid.querySelector("[data-template-search]")?.addEventListener("input", filter); dashboardGrid.querySelector("[data-template-filter]")?.addEventListener("change", filter);
    dashboardGrid.querySelectorAll("[data-template-preview]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.templatePreview)); if (!item) return; ui.drawer({ title: item.name, subtitle: templateTypes[item.kind] || item.kind || "Template", html: `<div class="template-drawer-content">${item.subject ? `<p><strong>Assunto</strong><br>${templateEsc(item.subject)}</p>` : ""}<pre>${templateEsc(item.body || "")}</pre>${item.variables ? `<p><strong>Variáveis</strong><br>${templateEsc(item.variables)}</p>` : ""}</div>` }); }));
    dashboardGrid.querySelectorAll("[data-template-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.templateEdit)); if (item) openEditDialog("template", item, `/api/templates/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-template-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir template?", onConfirm: async () => { await api(`/api/templates/${button.dataset.templateDelete}`, { method: "DELETE" }); toast("Template excluído.", "success"); renderTemplatesScreen(); } })));
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Automações</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "template-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderTemplatesScreen); }
}

registerRoutes({ templates: renderTemplatesScreen });

const templateActionsObserver = new MutationObserver(() => {
  if (location.hash.replace(/^#/, "") !== "templates") return;
  dashboardGrid.querySelectorAll("[data-template-row]").forEach((row) => {
    const actions = row.querySelector(".template-actions"); if (!actions || actions.querySelector("[data-template-duplicate]")) return;
    const button = document.createElement("button"); button.type = "button"; button.className = "compact-action"; button.dataset.templateDuplicate = row.querySelector("[data-template-edit]")?.dataset.templateEdit || ""; button.textContent = "Duplicar";
    button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/templates/${button.dataset.templateDuplicate}/duplicate`, { method: "POST", body: {} }); toast("Template duplicado.", "success"); renderTemplatesScreen(); } catch (error) { toast(error.message, "error"); button.disabled = false; } }); actions.append(button);
    const defaultButton = document.createElement("button"); defaultButton.type = "button"; defaultButton.className = "compact-action"; defaultButton.dataset.templateDefault = button.dataset.templateDuplicate; defaultButton.textContent = "Definir padrão";
    defaultButton.addEventListener("click", async () => { defaultButton.disabled = true; try { await api(`/api/templates/${defaultButton.dataset.templateDefault}/default`, { method: "PATCH", body: {} }); toast("Template padrão definido.", "success"); renderTemplatesScreen(); } catch (error) { toast(error.message, "error"); defaultButton.disabled = false; } }); actions.append(defaultButton);
  });
});
templateActionsObserver.observe(dashboardGrid, { childList: true, subtree: true });
