const ticketEsc = (value) => escapeHtml(value ?? "");
const ticketLabels = { new: "Novo", open: "Aberto", in_analysis: "Em análise", in_progress: "Em atendimento", waiting_client: "Aguardando cliente", waiting_third_party: "Aguardando terceiro", resolved: "Resolvido", closed: "Fechado", reopened: "Reaberto", cancelled: "Cancelado" };
const ticketPriorities = { low: "Baixa", medium: "Média", high: "Alta", urgent: "Urgente" };
const ticketFilter = { search: "", status: "", priority: "" };

async function renderTicketsScreen() {
  const title = "Tickets", description = "Suporte, manutenção e solicitações com prioridade e status rastreáveis.";
  dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-ticket-new type="button">+ Novo ticket</button></section>${stateBlock.loading("Carregando tickets...")}`;
  try {
    const params = new URLSearchParams(); if (ticketFilter.search) params.set("search", ticketFilter.search); if (ticketFilter.status) params.set("status", ticketFilter.status); if (ticketFilter.priority) params.set("priority", ticketFilter.priority);
    const items = (await api(`/api/tickets?${params}`)).tickets || [];
    createConfig.ticket.fields.find((field) => field.name === "status").options = Object.entries(ticketLabels);
    dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2><p>${description}</p></div><button class="button button-primary compact-action" data-ticket-new type="button">+ Novo ticket</button></section><section class="finance-toolbar"><input type="search" data-ticket-search value="${ticketEsc(ticketFilter.search)}" placeholder="Buscar título, cliente ou projeto" aria-label="Buscar ticket"><select data-ticket-filter aria-label="Filtrar status"><option value="">Todos os status</option>${Object.entries(ticketLabels).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select><select data-ticket-priority aria-label="Filtrar prioridade"><option value="">Todas as prioridades</option>${Object.entries(ticketPriorities).map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select></section><section class="operations-kanban">${Object.entries(ticketLabels).map(([status, label]) => `<div class="data-card operations-column" data-ticket-column="${status}"><h3>${label} <small>${items.filter((item) => item.status === status).length}</small></h3>${items.filter((item) => item.status === status).map((item) => `<article draggable="true" class="operations-ticket" data-ticket-row><strong>${ticketEsc(item.title)}</strong><small>${ticketEsc(item.client_name || "Sem cliente")}${item.project_name ? ` · ${ticketEsc(item.project_name)}` : ""}</small><span class="operations-priority priority-${ticketEsc(item.priority)}">${ticketPriorities[item.priority] || ticketEsc(item.priority || "Média")}</span><div><button class="compact-action" data-ticket-edit="${ticketEsc(item.id)}" type="button">Editar</button><button class="compact-action" data-ticket-delete="${ticketEsc(item.id)}" type="button">Excluir</button></div></article>`).join("")}</div>`).join("")}</section>`;
    const search = dashboardGrid.querySelector("[data-ticket-search]"), status = dashboardGrid.querySelector("[data-ticket-filter]"), priority = dashboardGrid.querySelector("[data-ticket-priority]"); status.value = ticketFilter.status; priority.value = ticketFilter.priority; let timer;
    search?.addEventListener("input", () => { clearTimeout(timer); ticketFilter.search = search.value.trim(); timer = setTimeout(renderTicketsScreen, 250); }); status?.addEventListener("change", () => { ticketFilter.status = status.value; renderTicketsScreen(); }); priority?.addEventListener("change", () => { ticketFilter.priority = priority.value; renderTicketsScreen(); });
    dashboardGrid.querySelector("[data-ticket-new]")?.addEventListener("click", () => openCreateDialog("ticket"));
    dashboardGrid.querySelectorAll("[data-ticket-edit]").forEach((button) => button.addEventListener("click", () => { const item = items.find((entry) => String(entry.id) === String(button.dataset.ticketEdit)); if (item) openEditDialog("ticket", item, `/api/tickets/${item.id}`); }));
    dashboardGrid.querySelectorAll("[data-ticket-delete]").forEach((button) => button.addEventListener("click", () => ui.confirmInline(button, { text: "Excluir ticket?", onConfirm: async () => { try { await api(`/api/tickets/${button.dataset.ticketDelete}`, { method: "DELETE" }); toast("Ticket excluído.", "success"); renderTicketsScreen(); } catch (error) { toast(error.message, "error"); } } })));
    dashboardGrid.querySelectorAll("[data-ticket-row]").forEach((card) => card.addEventListener("dragstart", (event) => event.dataTransfer.setData("text/plain", card.querySelector("[data-ticket-edit]")?.dataset.ticketEdit || "")));
    dashboardGrid.querySelectorAll("[data-ticket-column]").forEach((column) => { column.addEventListener("dragover", (event) => event.preventDefault()); column.addEventListener("drop", async (event) => { const id = event.dataTransfer.getData("text/plain"); if (!id) return; try { await api(`/api/tickets/${id}`, { method: "PATCH", body: { status: column.dataset.ticketColumn } }); toast("Status atualizado.", "success"); renderTicketsScreen(); } catch (error) { toast(error.message, "error"); } }); });
  } catch (error) { dashboardGrid.innerHTML = `<section class="page-intro"><div><p class="card-kicker">Operação</p><h2>${title}</h2></div></section>${stateBlock.error(error.message, "ticket-retry")}`; dashboardGrid.querySelector(".state-retry")?.addEventListener("click", renderTicketsScreen); }
}

registerRoutes({ tickets: renderTicketsScreen });
