import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import { createServer } from "node:http";
import { register } from "./configuracoes.js";
const org = "00000000-0000-0000-0000-000000000001";
function setup(user = { id: 1, organization_id: org, role: "owner", name: "Owner" }, duplicate = false) { const calls = []; const pool = { query: async (sql, p) => { calls.push({ sql, p }); if (sql.startsWith("select id,name,email,role")) return { rows: [{ id: 1, name: "A", email: "a@x.com", role: "owner", created_at: "2026-01-01" }] }; if (sql.startsWith("insert into users")) { if (duplicate) throw { code: "23505" }; return { rowCount: 1, rows: [{ id: 2, name: p[0], email: p[1], role: p[4], created_at: "2026-01-01" }] }; } if (sql.startsWith("insert into password_resets")) return { rowCount: 1, rows: [] }; if (sql.startsWith("select password_hash")) return { rows: [{ password_hash: "salt:expected" }] }; if (sql.startsWith("update users set name")) return { rowCount: 1, rows: [{ id: 1, name: p[0], email: "a@x.com", role: "owner", organization_id: org }] }; return { rowCount: 0, rows: [] }; } }; const app = express(); app.use(express.json()); app.use((req, _res, next) => { req.user = user; next(); }); register(app, { pool, tenant: () => org, classifyDbError: () => ({ status: 503, error: "Erro" }), hashPassword: () => ({ salt: "salt", hash: "hash" }), verifyPassword: (p) => p === "correct", signSession: () => "session", sessionCookie: () => "focus_session=session" }); return { app, calls }; }
async function call(h, path, options = {}) { const s = createServer(h.app); await new Promise((r) => s.listen(0, r)); try { return await fetch(`http://127.0.0.1:${s.address().port}${path}`, { headers: { "content-type": "application/json" }, ...options }); } finally { s.close(); } }
test("GET team filtra organização e omite password_hash", async () => { const h = setup(); const r = await call(h, "/api/team"); const b = await r.json(); assert.equal(r.status, 200); assert.equal(b.users[0].password_hash, undefined); assert.match(h.calls[0].sql, /organization_id/); });
test("invite válido responde 201 com resetLink e duplicado 409", async () => { const h = setup(); const r = await call(h, "/api/team/invite", { method: "POST", body: JSON.stringify({ name: "Novo", email: "novo@x.com", role: "member" }) }); assert.equal(r.status, 201); assert.match((await r.json()).resetLink, /^\/#reset=/); const dup = await call(setup(undefined, true), "/api/team/invite", { method: "POST", body: JSON.stringify({ name: "Novo", email: "novo@x.com", role: "member" }) }); assert.equal(dup.status, 409); });
test("membro comum recebe 403 ao convidar", async () => { const r = await call(setup({ id: 2, organization_id: org, role: "member" }), "/api/team/invite", { method: "POST", body: JSON.stringify({ name: "x", email: "x@x.com", role: "member" }) }); assert.equal(r.status, 403); });
test("senha com atual incorreta responde 400", async () => { const r = await call(setup(), "/api/profile/password", { method: "POST", body: JSON.stringify({ currentPassword: "wrong", newPassword: "12345678" }) }); assert.equal(r.status, 400); });
test("PATCH profile devolve Set-Cookie", async () => { const r = await call(setup(), "/api/profile", { method: "PATCH", body: JSON.stringify({ name: "Novo nome" }) }); assert.equal(r.status, 200); assert.match(r.headers.get("set-cookie"), /focus_session/); });
