import crypto from "node:crypto";
import { sendEmail, renderEmail, APP_URL } from "../mailer.js";

const roles = new Set(["owner", "admin", "member"]);
const text = (v) => typeof v === "string" ? v.trim() : "";
const validEmail = (v) => /^\S+@\S+\.\S+$/.test(v);
export function register(app, ctx) {
  const { pool, tenant, classifyDbError } = ctx;
  const hashPassword = ctx.hashPassword || ((password) => { const salt = crypto.randomBytes(16).toString("hex"); return { salt, hash: crypto.scryptSync(password, salt, 64).toString("hex") }; });
  const verifyPassword = ctx.verifyPassword || ((password, salt, expected) => { try { return crypto.timingSafeEqual(Buffer.from(hashPassword(password, salt).hash, "hex"), Buffer.from(expected, "hex")); } catch { return false; } });
  // Papel sempre lido do banco: o cookie pode estar desatualizado após uma mudança de papel.
  const roleOf = async (req, org) => { const q = await pool.query("select role from users where id=$1 and organization_id=$2", [req.user?.id, org]); return q.rows[0]?.role || null; };
  const authorized = async (req, org) => ["owner", "admin"].includes(await roleOf(req, org));
  const fail = (res, status, error) => res.status(status).json({ error });
  app.get("/api/team/roles", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select id,name,department,permissions,hidden_fields from team_roles where organization_id=$1 order by name", [org]); res.json({ roles: q.rows }); } catch (e) { const x = classifyDbError(e, "Não foi possível carregar os cargos."); fail(res, x.status, x.error); } });
  app.patch("/api/team/:id/team-role", async (req, res) => { const org = tenant(req, res); if (!org) return; if (!(await authorized(req, org))) return fail(res, 403, "Você não tem permissão."); const roleId = req.body?.team_role_id == null || req.body.team_role_id === "" ? null : Number(req.body.team_role_id); if (roleId !== null && !Number.isInteger(roleId)) return fail(res, 400, "Cargo inválido."); try { if (roleId !== null) { const role = await pool.query("select id from team_roles where id=$1 and organization_id=$2", [roleId, org]); if (!role.rowCount) return fail(res, 400, "Cargo não pertence ao workspace."); } const q = await pool.query("update users set team_role_id=$1 where id=$2 and organization_id=$3 returning id,name,email,role,team_role_id,created_at", [roleId, req.params.id, org]); if (!q.rowCount) return fail(res, 404, "Membro não encontrado."); res.json({ user: q.rows[0] }); } catch (e) { const x = classifyDbError(e, "Não foi possível atribuir o cargo."); fail(res, x.status, x.error); } });
  app.get("/api/team", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select id,name,email,role,created_at from users where organization_id=$1 order by created_at", [org]); res.json({ users: q.rows }); } catch (e) { const x = classifyDbError(e, "Não foi possível carregar a equipe."); fail(res, x.status, x.error); } });
  app.post("/api/team/invite", async (req, res) => { const org = tenant(req, res); if (!org) return; if (!(await authorized(req, org))) return fail(res, 403, "Você não tem permissão para convidar."); const name = text(req.body?.name), email = text(req.body?.email).toLowerCase(), role = text(req.body?.role) || "member"; if (name.length < 2 || !validEmail(email) || !roles.has(role)) return fail(res, 400, "Nome, e-mail e papel válidos são obrigatórios."); if (role === "owner" && (await roleOf(req, org)) !== "owner") return fail(res, 403, "Apenas proprietários podem criar outro proprietário."); const token = crypto.randomBytes(32).toString("base64url"), hashed = hashPassword(crypto.randomBytes(24).toString("base64url")); try { const u = await pool.query("insert into users (name,email,password_hash,organization_id,role) values ($1,$2,$3,$4,$5) returning id,name,email,role,created_at", [name, email, `${hashed.salt}:${hashed.hash}`, org, role]); await pool.query("insert into password_resets (user_id,token_hash,expires_at) values ($1,$2,now()+interval '7 days')", [u.rows[0].id, crypto.createHash("sha256").update(token).digest("hex")]); const inviteLink = `${APP_URL}/#reset=${token}`; const orgName = (await pool.query("select name from organizations where id=$1", [org])).rows[0]?.name || "FocusDev"; const { html, text } = renderEmail({ title: `Você foi convidado para ${orgName}`, intro: `${req.user?.name || "Um colega"} adicionou você ao workspace ${orgName} no FocusDev. Crie sua senha para entrar; o link vale por 7 dias.`, actionLabel: "Criar minha senha", actionUrl: inviteLink }); const delivery = await sendEmail({ to: email, subject: `Convite para ${orgName} · FocusDev`, html, text }).catch(() => ({ sent: false })); res.status(201).json({ user: u.rows[0], emailSent: Boolean(delivery?.sent) }); } catch (e) { if (e.code === "23505") return fail(res, 409, "Este e-mail já está cadastrado."); const x = classifyDbError(e, "Não foi possível convidar."); fail(res, x.status, x.error); } });
  app.patch("/api/team/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; if (!(await authorized(req, org))) return fail(res, 403, "Você não tem permissão."); const role = text(req.body?.role); if (!roles.has(role)) return fail(res, 400, "Papel inválido."); try { const callerRole = await roleOf(req, org); const targetRole = (await pool.query("select role from users where id=$1 and organization_id=$2", [req.params.id, org])).rows[0]?.role; if (targetRole === undefined) return fail(res, 404, "Membro não encontrado."); if ((role === "owner" || targetRole === "owner") && callerRole !== "owner") return fail(res, 403, "Apenas proprietários podem alterar o papel de proprietário."); if (role !== "owner") { const q = await pool.query("select count(*)::int as total from users where organization_id=$1 and role='owner'", [org]); const current = await pool.query("select role from users where id=$1 and organization_id=$2", [req.params.id, org]); if (current.rows[0]?.role === "owner" && Number(q.rows[0]?.total) <= 1) return fail(res, 400, "Não é possível rebaixar o último proprietário."); } const q = await pool.query("update users set role=$1 where id=$2 and organization_id=$3 returning id,name,email,role,created_at", [role, req.params.id, org]); if (!q.rowCount) return fail(res, 404, "Membro não encontrado."); res.json({ user: q.rows[0] }); } catch (e) { const x = classifyDbError(e, "Não foi possível atualizar o papel."); fail(res, x.status, x.error); } });
  app.delete("/api/team/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; if (!(await authorized(req, org))) return fail(res, 403, "Você não tem permissão."); if (String(req.params.id) === String(req.user?.id)) return fail(res, 400, "Você não pode remover a si mesmo."); try { const current = await pool.query("select role from users where id=$1 and organization_id=$2", [req.params.id, org]); if (current.rows[0]?.role === "owner" && (await roleOf(req, org)) !== "owner") return fail(res, 403, "Apenas proprietários podem remover um proprietário."); if (current.rows[0]?.role === "owner") { const q = await pool.query("select count(*)::int as total from users where organization_id=$1 and role='owner'", [org]); if (Number(q.rows[0]?.total) <= 1) return fail(res, 400, "Não é possível remover o último proprietário."); } const q = await pool.query("delete from users where id=$1 and organization_id=$2 returning id", [req.params.id, org]); if (!q.rowCount) return fail(res, 404, "Membro não encontrado."); res.status(204).end(); } catch (e) { const x = classifyDbError(e, "Não foi possível remover o membro."); fail(res, x.status, x.error); } });
  app.get("/api/organization", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select id,name,settings from organizations where id=$1", [org]); if (!q.rowCount) return fail(res, 404, "Organização não encontrada."); const role = await roleOf(req, org), organization = { ...q.rows[0] }; if (!["owner", "admin"].includes(role)) { const settings = { ...(organization.settings || {}) }; ["pix_key", "bank_account", "bank_accounts", "company_document"].forEach((key) => delete settings[key]); organization.settings = settings; } res.json({ organization }); } catch (e) { const x = classifyDbError(e, "Não foi possível carregar a organização."); fail(res, x.status, x.error); } });
  app.patch("/api/organization", async (req, res) => { const org = tenant(req, res); if (!org) return; if (!(await authorized(req, org))) return fail(res, 403, "Você não tem permissão."); const name = req.body?.name === undefined ? undefined : text(req.body.name), settings = req.body?.settings; if (name !== undefined && name.length < 2) return fail(res, 400, "Nome inválido."); try { const q = await pool.query("update organizations set name=coalesce($1,name), settings=coalesce($2,settings) where id=$3 returning id,name,settings", [name, settings === undefined ? null : settings, org]); res.json({ organization: q.rows[0] }); } catch (e) { const x = classifyDbError(e, "Não foi possível salvar a organização."); fail(res, x.status, x.error); } });
  app.patch("/api/profile", async (req, res) => { const org = tenant(req, res); if (!org) return; const name = text(req.body?.name); if (name.length < 2) return fail(res, 400, "Nome inválido."); try { const q = await pool.query("update users set name=$1 where id=$2 and organization_id=$3 returning id,name,email,role,organization_id", [name, req.user.id, org]); if (!q.rowCount) return fail(res, 404, "Usuário não encontrado."); if (ctx.signSession && ctx.sessionCookie) res.setHeader("Set-Cookie", ctx.sessionCookie(ctx.signSession(q.rows[0]))); res.json({ user: q.rows[0] }); } catch (e) { const x = classifyDbError(e, "Não foi possível salvar o perfil."); fail(res, x.status, x.error); } });
  app.post("/api/profile/password", async (req, res) => { const org = tenant(req, res); if (!org) return; const current = String(req.body?.currentPassword || ""), next = String(req.body?.newPassword || ""); if (next.length < 8) return fail(res, 400, "A nova senha deve ter pelo menos 8 caracteres."); try { const q = await pool.query("select password_hash from users where id=$1 and organization_id=$2", [req.user.id, org]); const [salt, expected] = q.rows[0]?.password_hash?.split(":") || []; if (!salt || !verifyPassword(current, salt, expected)) return fail(res, 400, "A senha atual está incorreta."); const h = hashPassword(next); await pool.query("update users set password_hash=$1,access_revoked_at=now() where id=$2 and organization_id=$3", [`${h.salt}:${h.hash}`, req.user.id, org]); res.setHeader("Set-Cookie", "focus_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0"); res.status(204).end(); } catch (e) { const x = classifyDbError(e, "Não foi possível alterar a senha."); fail(res, x.status, x.error); } });
}
