/* Rotas específicas do CRM comercial. */
export function register(app, ctx) {
  const { pool, tenant, asText, classifyDbError, validateRelations } = ctx;
  const fail = (res, e, msg) => { const out = classifyDbError(e, msg); res.status(out.status).json({ error: out.error }); };
  const org = (req, res) => tenant(req, res);
  const statuses = { campaign: ["draft", "active", "paused", "done"], proposal: ["draft", "sent", "accepted", "rejected"] };
  app.get("/api/campaigns", async (req,res) => { const o=org(req,res); if(!o)return; try { const q=await pool.query("select * from campaigns where organization_id=$1 order by created_at desc",[o]); res.json({campaigns:q.rows}); } catch(e){fail(res,e,"Não foi possível carregar campanhas.");} });
  app.post("/api/campaigns", async (req,res) => { const o=org(req,res); if(!o)return; const name=asText(req.body?.name), channel=asText(req.body?.channel)||"other", budget=Number(req.body?.budget||0); if(!name||!["email","whatsapp","ads","social","other"].includes(channel)||!Number.isFinite(budget)||budget<0)return res.status(400).json({error:"Informe nome, canal e orçamento válidos."}); try { const q=await pool.query("insert into campaigns (organization_id,name,channel,budget,starts_on,ends_on) values ($1,$2,$3,$4,$5,$6) returning *",[o,name,channel,budget,req.body?.starts_on||null,req.body?.ends_on||null]); res.status(201).json({campaign:q.rows[0]}); }catch(e){fail(res,e,"Não foi possível criar campanha.");} });
  app.patch("/api/campaigns/:id", async(req,res)=>{const o=org(req,res);if(!o)return;const status=req.body?.status;if(!statuses.campaign.includes(status))return res.status(400).json({error:"Status inválido."});try{const q=await pool.query("update campaigns set status=$1,updated_at=now() where id=$2 and organization_id=$3 returning *",[status,req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Campanha não encontrada."});res.json({campaign:q.rows[0]});}catch(e){fail(res,e,"Não foi possível atualizar campanha.");}});
  app.delete("/api/campaigns/:id", async(req,res)=>{const o=org(req,res);if(!o)return;try{const q=await pool.query("delete from campaigns where id=$1 and organization_id=$2 returning id",[req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Campanha não encontrada."});res.status(204).end();}catch(e){fail(res,e,"Não foi possível excluir campanha.");}});
  app.get("/api/proposals", async(req,res)=>{const o=org(req,res);if(!o)return;try{const q=await pool.query("select p.*,o.name opportunity_name from proposals p left join opportunities o on o.id=p.opportunity_id and o.organization_id=p.organization_id where p.organization_id=$1 order by p.created_at desc",[o]);res.json({proposals:q.rows});}catch(e){fail(res,e,"Não foi possível carregar propostas.");}});
  app.post("/api/proposals", async(req,res)=>{const o=org(req,res);if(!o)return;const title=asText(req.body?.title), amount=Number(req.body?.amount||0), oid=req.body?.opportunity_id||null;if(!title||!Number.isFinite(amount)||amount<0)return res.status(400).json({error:"Informe título e valor válidos."});try{if(oid)await validateRelations({opportunity_id:oid},o);const q=await pool.query("insert into proposals (organization_id,opportunity_id,title,amount,valid_until,notes) values ($1,$2,$3,$4,$5,$6) returning *",[o,oid,title,amount,req.body?.valid_until||null,asText(req.body?.notes)]);res.status(201).json({proposal:q.rows[0]});}catch(e){if(e.code==="invalid_relation")return res.status(400).json({error:e.message});fail(res,e,"Não foi possível criar proposta.");}});
  app.patch("/api/proposals/:id", async(req,res)=>{const o=org(req,res), status=req.body?.status;if(!o)return;if(!statuses.proposal.includes(status))return res.status(400).json({error:"Status inválido."});try{const q=await pool.query("update proposals set status=$1,updated_at=now() where id=$2 and organization_id=$3 returning *",[status,req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Proposta não encontrada."});if(status==="accepted"&&q.rows[0].opportunity_id)await pool.query("update opportunities set stage='won',updated_at=now() where id=$1 and organization_id=$2",[q.rows[0].opportunity_id,o]);res.json({proposal:q.rows[0]});}catch(e){fail(res,e,"Não foi possível atualizar proposta.");}});
  app.delete("/api/proposals/:id", async(req,res)=>{const o=org(req,res);if(!o)return;try{const q=await pool.query("delete from proposals where id=$1 and organization_id=$2 returning id",[req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Proposta não encontrada."});res.status(204).end();}catch(e){fail(res,e,"Não foi possível excluir proposta.");}});
  app.get("/api/followups", async(req,res)=>{const o=org(req,res);if(!o)return;try{const q=await pool.query("select f.*,l.name lead_name from followups f left join leads l on l.id=f.lead_id and l.organization_id=f.organization_id where f.organization_id=$1 order by f.due_at",[o]);res.json({followups:q.rows});}catch(e){fail(res,e,"Não foi possível carregar follow-ups.");}});
  app.post("/api/followups", async(req,res)=>{const o=org(req,res), lead=req.body?.lead_id, due=req.body?.due_at;if(!o)return;if(!lead||!due||Number.isNaN(Date.parse(due)))return res.status(400).json({error:"Informe lead e data válidos."});try{await validateRelations({lead_id:lead},o);const q=await pool.query("insert into followups (organization_id,lead_id,due_at,channel,note) values ($1,$2,$3,$4,$5) returning *",[o,lead,due,asText(req.body?.channel),asText(req.body?.note)]);res.status(201).json({followup:q.rows[0]});}catch(e){if(e.code==="invalid_relation")return res.status(400).json({error:e.message});fail(res,e,"Não foi possível criar follow-up.");}});
  app.patch("/api/followups/:id", async(req,res)=>{const o=org(req,res);if(!o)return;const done=req.body?.done_at||null;try{const q=await pool.query("update followups set done_at=$1 where id=$2 and organization_id=$3 returning *",[done,req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Follow-up não encontrado."});res.json({followup:q.rows[0]});}catch(e){fail(res,e,"Não foi possível atualizar follow-up.");}});
  app.delete("/api/followups/:id", async(req,res)=>{const o=org(req,res);if(!o)return;try{const q=await pool.query("delete from followups where id=$1 and organization_id=$2 returning id",[req.params.id,o]);if(!q.rowCount)return res.status(404).json({error:"Follow-up não encontrado."});res.status(204).end();}catch(e){fail(res,e,"Não foi possível excluir follow-up.");}});
}
