import { expandRecurringEvents } from "../recurrence.js";

const recurrenceValues = ["none", "daily", "weekly", "monthly", "yearly"];
const text = (value) => typeof value === "string" ? value.trim() : "";
const eventFields = ["title", "starts_at", "description", "recurrence", "reminder_minutes", "event_type", "status", "ends_at", "all_day", "client_id", "project_id", "contract_id", "location", "color", "participants", "meeting_notes", "reminder_channels", "recurrence_until"];
const inputValues = (body) => [text(body.title), body.startsAt, text(body.description) || null, recurrenceValues.includes(body.recurrence) ? body.recurrence : "none", Math.max(0, Number(body.reminderMinutes) || 0), text(body.event_type) || "other", text(body.status) || "pending", body.endsAt || null, Boolean(body.all_day), body.client_id || null, body.project_id || null, body.contract_id || null, text(body.location) || null, text(body.color) || null, text(body.participants) || null, text(body.meeting_notes) || null, text(body.reminder_channels) || null, body.recurrenceUntil || null];
const validDate = (value) => value && !Number.isNaN(Date.parse(value));

export function register(app, ctx) {
  const { pool, tenant, classifyDbError } = ctx;
  const fail = (res, error, fallback) => { const out = classifyDbError(error, fallback); res.status(out.status).json({ error: out.error }); };
  app.get("/api/events", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select * from events where organization_id=$1 order by starts_at", [org]); res.json({ events: expandRecurringEvents(q.rows) }); } catch (error) { fail(res, error, "Não foi possível carregar os eventos."); } });
  app.post("/api/events", async (req, res) => { const org = tenant(req, res); if (!org) return; const body = req.body || {}, values = inputValues(body); if (!values[0] || !validDate(values[1]) || (values[7] && !validDate(values[7])) || (values[17] && !validDate(values[17]))) return res.status(400).json({ error: "Informe título e horários válidos." }); try { const q = await pool.query(`insert into events (organization_id,${eventFields.join(",")}) values ($1,${eventFields.map((_, index) => `$${index + 2}`).join(",")}) returning *`, [org, ...values]); res.status(201).json({ event: q.rows[0] }); } catch (error) { fail(res, error, "Não foi possível criar o evento."); } });
  app.patch("/api/events/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; const body = req.body || {}, map = { title: "title", startsAt: "starts_at", description: "description", recurrence: "recurrence", reminderMinutes: "reminder_minutes", event_type: "event_type", status: "status", endsAt: "ends_at", all_day: "all_day", client_id: "client_id", project_id: "project_id", contract_id: "contract_id", location: "location", color: "color", participants: "participants", meeting_notes: "meeting_notes", reminder_channels: "reminder_channels", recurrenceUntil: "recurrence_until" }, updates = [], values = []; for (const [input, column] of Object.entries(map)) if (Object.prototype.hasOwnProperty.call(body, input)) { let value = body[input]; if (["title", "description", "event_type", "status", "location", "color", "participants", "meeting_notes", "reminder_channels"].includes(input)) value = text(value) || null; if (input === "recurrence" && !recurrenceValues.includes(value)) return res.status(400).json({ error: "Recorrência inválida." }); if (input === "reminderMinutes") value = Math.max(0, Number(value) || 0); if (input === "all_day") value = Boolean(value); if (["startsAt", "endsAt", "recurrenceUntil"].includes(input) && value && !validDate(value)) return res.status(400).json({ error: "Data do evento inválida." }); values.push(value); updates.push(`${column}=$${values.length}`); } if (body.title !== undefined && !text(body.title)) return res.status(400).json({ error: "Título inválido." }); if (!updates.length) return res.status(400).json({ error: "Nenhum campo válido informado." }); try { const q = await pool.query(`update events set ${updates.join(",")} where id=$${values.length + 1} and organization_id=$${values.length + 2} returning *`, [...values, req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Evento não encontrado." }); res.json({ event: q.rows[0] }); } catch (error) { fail(res, error, "Não foi possível atualizar o evento."); } });
  app.delete("/api/events/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("delete from events where id=$1 and organization_id=$2 returning id", [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Evento não encontrado." }); res.status(204).end(); } catch (error) { fail(res, error, "Não foi possível excluir o evento."); } });
}

export { eventFields, recurrenceValues };
