import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import { createServer } from "node:http";
import { register } from "./financeiro.js";

const ORG = "00000000-0000-0000-0000-000000000001";
function setup() {
  const calls = [];
  const pool = { query: async (sql, params) => { calls.push({ sql, params }); if (sql.includes("generate_series")) return { rows: [{ month: "2026-08", revenue: "10", expense: "3", result: "7" }] }; if (sql.startsWith("select s.*")) return { rows: [{ id: 1, organization_id: ORG, plan: "Pro", amount: "20", status: "active" }] }; if (sql.startsWith("insert into subscriptions")) return { rows: [{ id: 2, organization_id: ORG, plan: "Pro", amount: "20" }] }; if (sql.startsWith("select * from bank_account_transactions")) return { rows: [{ id: 20, bank_account_id: 8, kind: "credit", amount: "100" }] }; return { rows: [] }; }, connect: async () => ({ query: async (sql, params) => { calls.push({ sql, params }); if (sql.startsWith("select * from contracts where")) return { rowCount: 1, rows: [{ id: 9, organization_id: ORG, client_id: 7, status: "active", name: "Site", value: "2700", down_payment: "300", installments: 2, installment_value: "1200", payment_method: "pix" }] }; if (sql.startsWith("select * from payables where")) return { rowCount: 1, rows: [{ id: 11, organization_id: ORG, description: "Servidor", amount: "120", supplier: "Cloud", status: "pending", due_at: "2026-09-20" }] }; if (sql.startsWith("select * from bank_accounts where")) return { rowCount: 1, rows: [{ id: 8, organization_id: ORG, current_balance: "500" }] }; if (sql.startsWith("insert into receivables")) return { rowCount: 1, rows: [{ id: calls.filter((call) => call.sql.startsWith("insert into receivables")).length }] }; if (sql.startsWith("insert into expenses")) return { rowCount: 1, rows: [{ id: 12, amount: "120", status: "paid" }] }; if (sql.startsWith("insert into bank_account_transactions")) return { rowCount: 1, rows: [{ id: 20, kind: "credit", amount: "100" }] }; if (sql.startsWith("update payables")) return { rowCount: 1, rows: [{ id: 11, status: "paid" }] }; if (sql.startsWith("update bank_accounts")) return { rowCount: 1, rows: [{ id: 8, current_balance: "600" }] }; return { rowCount: 0, rows: [] }; }, release() {} }) };
  const app = express(); app.use(express.json());
  const ctx = { pool, tenant: (_req, res) => { res.locals.org = ORG; return ORG; }, asText: (v) => typeof v === "string" ? v.trim() : "", classifyDbError: (_e, fallback) => ({ status: 503, error: fallback }), validateRelations: async () => {} };
  register(app, ctx); const server = createServer(app);
  return { app, server, calls };
}
async function request(t, path, options = {}) { await new Promise((resolve) => t.server.listen(0, resolve)); const port = t.server.address().port; const response = await fetch(`http://127.0.0.1:${port}${path}`, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) }, body: options.body ? JSON.stringify(options.body) : undefined }); t.server.close(); return response; }

test("pagamento rejeita valor inválido antes da baixa", async () => { const t = setup(); const response = await request(t, "/api/receivables/7/record-payment", { method: "POST", body: { amount: 0 } }); assert.equal(response.status, 400); });
test("baixa conta a pagar cria despesa paga", async () => { const t = setup(); const response = await request(t, "/api/payables/11/record-payment", { method: "POST", body: {} }); assert.equal(response.status, 201); assert.equal((await response.json()).expense.status, "paid"); assert.equal(t.calls.some((call) => call.sql.startsWith("insert into expenses")), true); });
test("movimentação bancária atualiza o saldo", async () => { const t = setup(); const response = await request(t, "/api/bank_accounts/8/transactions", { method: "POST", body: { kind: "credit", amount: 100, description: "Recebimento" } }); assert.equal(response.status, 201); assert.equal((await response.json()).bank_account.current_balance, "600"); });
test("cobrança exige conta a receber do workspace", async () => { const t = setup(); const response = await request(t, "/api/receivables/7/create-charge", { method: "POST", body: { channel: "pix" } }); assert.equal(response.status, 404); });
test("gera entrada e parcelas do contrato sem duplicar", async () => { const t = setup(); const response = await request(t, "/api/contracts/9/create-receivables", { method: "POST", body: {} }); assert.equal(response.status, 201); assert.equal((await response.json()).receivables.length, 3); assert.equal(t.calls.filter((x) => x.sql.startsWith("insert into receivables")).length, 3); });

test("summary agrega por mês", async () => { const t = setup(); const response = await request(t, "/api/finance/summary?months=6"); assert.equal(response.status, 200); assert.deepEqual((await response.json()).summary[0], { month: "2026-08", revenue: "10", expense: "3", result: "7" }); });
test("subscriptions filtra por organização", async () => { const t = setup(); const response = await request(t, "/api/subscriptions"); assert.equal(response.status, 200); assert.equal(t.calls.find((x) => x.sql.startsWith("select s.*")).params[0], ORG); });
test("POST subscriptions válido responde 201", async () => { const t = setup(); const response = await request(t, "/api/subscriptions", { method: "POST", body: { plan: "Pro", amount: 20 } }); assert.equal(response.status, 201); });
test("POST subscriptions inválido responde 400", async () => { const t = setup(); const response = await request(t, "/api/subscriptions", { method: "POST", body: { plan: "", amount: -1 } }); assert.equal(response.status, 400); });
