/* Rotas HTTP do domínio inbox. */
import { sendWhatsappText } from "./whatsapp.js";
export function register(app, ctx) {
  const { pool, tenant, asText, classifyDbError } = ctx;
  const fail = (res, error, fallback) => { const out = classifyDbError(error, fallback); res.status(out.status).json({ error: out.error }); };
  const relation = async (id, table, org) => { if (id === null || id === undefined || id === "") return null; const q = await pool.query(`select id from ${table} where id=$1 and organization_id=$2`, [id, org]); return q.rowCount ? id : false; };
  app.get("/api/conversations", async (req, res) => {
    const org = tenant(req, res); if (!org) return; const status = req.query.status || "open";
    if (!["open", "archived", "all"].includes(status)) return res.status(400).json({ error: "Status inválido." });
    const values = [org, status], where = ["c.organization_id=$1", "($2='all' or c.status=$2)"], search = asText(req.query?.search);
    if (["internal", "email", "whatsapp"].includes(String(req.query?.channel))) { values.push(String(req.query.channel)); where.push(`c.channel=$${values.length}`); }
    if (req.query?.unread === "true") where.push("c.unread_count > 0");
    if (search) { values.push(`%${search.slice(0, 120)}%`); const p = `$${values.length}`; where.push(`(coalesce(c.subject,'') ilike ${p} or coalesce(co.name,'') ilike ${p} or coalesce(cl.name,'') ilike ${p} or coalesce(c.remote_number,'') ilike ${p} or exists (select 1 from messages sm where sm.conversation_id=c.id and sm.organization_id=c.organization_id and sm.body ilike ${p}))`); }
    const hasPaging = req.query?.limit !== undefined || req.query?.offset !== undefined; const limit = Math.min(Math.max(Number.parseInt(req.query?.limit, 10) || 100, 1), 100), offset = Math.max(Number.parseInt(req.query?.offset, 10) || 0, 0); if (hasPaging) values.push(limit, offset);
    const paging = hasPaging ? ` limit $${values.length - 1} offset $${values.length}` : "";
    try { const q = await pool.query(`select c.*,co.name contact_name,co.phone contact_phone,cl.name client_name,(select body from messages m where m.conversation_id=c.id order by m.created_at desc limit 1) last_message,(select count(*)::int from messages m where m.conversation_id=c.id) message_count from conversations c left join contacts co on co.id=c.contact_id and co.organization_id=c.organization_id left join clients cl on cl.id=c.client_id and cl.organization_id=c.organization_id where ${where.join(" and ")} order by c.last_message_at desc nulls last,c.created_at desc${paging}`, values); res.json({ conversations: q.rows, ...(hasPaging ? { pagination: { limit, offset, returned: q.rows.length } } : {}) }); } catch (e) { fail(res, e, "Não foi possível carregar as conversas."); }
  });
  app.post("/api/conversations", async (req, res) => { const org = tenant(req, res); if (!org) return; const subject = asText(req.body?.subject), channel = req.body?.channel || "internal"; if (!subject || !["internal", "email", "whatsapp"].includes(channel)) return res.status(400).json({ error: "Informe assunto e canal válidos." }); try { const contact = await relation(req.body?.contact_id, "contacts", org), client = await relation(req.body?.client_id, "clients", org); if (contact === false || client === false) return res.status(400).json({ error: "Contato ou cliente inválido." }); const remote = channel === "whatsapp" ? String(req.body?.remote_number || "").replace(/\D/g, "") || null : null; if (channel === "whatsapp" && (!remote || remote.length < 10)) return res.status(400).json({ error: "Informe o número do WhatsApp com DDI e DDD." }); const c = await pool.query("insert into conversations (organization_id,subject,contact_id,client_id,channel,remote_number) values ($1,$2,$3,$4,$5,$6) returning *", [org, subject, contact, client, channel, remote]); let row = c.rows[0]; const body = asText(req.body?.message); if (body) { const m = await pool.query("insert into messages (organization_id,conversation_id,author_user_id,direction,body) values ($1,$2,$3,'out',$4) returning *", [org, row.id, req.user?.id || null, body]); await pool.query("update conversations set last_message_at=$1,updated_at=now() where id=$2 and organization_id=$3", [m.rows[0].created_at, row.id, org]); row = { ...row, last_message_at: m.rows[0].created_at }; } res.status(201).json({ conversation: row }); } catch (e) { fail(res, e, "Não foi possível criar a conversa."); } });
  app.get("/api/conversations/:id/messages", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select * from messages where conversation_id=$1 and organization_id=$2 order by created_at", [req.params.id, org]); res.json({ messages: q.rows }); } catch (e) { fail(res, e, "Não foi possível carregar as mensagens."); } });
  app.post("/api/conversations/:id/messages", async (req, res) => { const org = tenant(req, res); if (!org) return; const body = asText(req.body?.body); if (!body) return res.status(400).json({ error: "A mensagem não pode estar vazia." }); try { const c = await pool.query("select id,channel,remote_number from conversations where id=$1 and organization_id=$2", [req.params.id, org]); if (!c.rowCount) return res.status(404).json({ error: "Conversa não encontrada." }); if (c.rows[0].channel === "whatsapp" && c.rows[0].remote_number) { try { await sendWhatsappText(pool, org, c.rows[0].remote_number, body); } catch (error) { return res.status(error.status || 502).json({ error: `Não foi possível enviar pelo WhatsApp: ${error.message}` }); } } const m = await pool.query("insert into messages (organization_id,conversation_id,author_user_id,direction,body) values ($1,$2,$3,'out',$4) returning *", [org, req.params.id, req.user?.id || null, body]); await pool.query("update conversations set last_message_at=$1,updated_at=now() where id=$2 and organization_id=$3", [m.rows[0].created_at, req.params.id, org]); res.status(201).json({ message: m.rows[0] }); } catch (e) { fail(res, e, "Não foi possível enviar a mensagem."); } });
  app.patch("/api/conversations/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; const status = req.body?.status; if (status !== undefined && !["open", "archived"].includes(status)) return res.status(400).json({ error: "Status inválido." }); try { if (req.body?.contact_id !== undefined) { const contact = await relation(req.body.contact_id, "contacts", org); if (contact === false) return res.status(400).json({ error: "Contato inválido." }); await pool.query("update conversations set contact_id=$1 where id=$2 and organization_id=$3", [contact, req.params.id, org]); } const q = await pool.query("update conversations set status=coalesce($1,status),unread_count=case when $1='archived' or $4=true then 0 when $5=true then greatest(unread_count,1) else unread_count end,updated_at=now() where id=$2 and organization_id=$3 returning *", [status ?? null, req.params.id, org, Boolean(req.body?.read), Boolean(req.body?.unread)]); if (!q.rowCount) return res.status(404).json({ error: "Conversa não encontrada." }); if (req.body?.read) await pool.query("update messages set read_at=coalesce(read_at,now()) where conversation_id=$1 and organization_id=$2 and direction='in'", [req.params.id, org]); res.json({ conversation: q.rows[0] }); } catch (e) { fail(res, e, "Não foi possível atualizar a conversa."); } });
  app.delete("/api/conversations/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("delete from conversations where id=$1 and organization_id=$2 returning id", [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Conversa não encontrada." }); res.status(204).end(); } catch (e) { fail(res, e, "Não foi possível excluir a conversa."); } });
}
