/* Notificações internas do workspace. */
export function register(app, ctx) {
  const { pool, tenant, classifyDbError } = ctx;
  const fail = (res, error, fallback) => { const out = classifyDbError(error, fallback); res.status(out.status).json({ error: out.error }); };
  app.get("/api/notifications", async (req, res) => { const org = tenant(req, res); if (!org) return; const limit = Math.min(Math.max(Number(req.query.limit) || 30, 1), 100); try { const q = await pool.query("select id,message,read_at,created_at,automation_id from notifications where organization_id=$1 and (user_id=$2 or user_id is null) order by read_at nulls first,created_at desc limit $3", [org, req.user.id, limit]); const unread = await pool.query("select count(*)::int as count from notifications where organization_id=$1 and (user_id=$2 or user_id is null) and read_at is null", [org, req.user.id]); res.json({ notifications: q.rows, unread_count: Number(unread.rows[0]?.count || 0) }); } catch (e) { fail(res, e, "Não foi possível carregar as notificações."); } });
  app.get("/api/notifications/unread-count", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select count(*)::int as count from notifications where organization_id=$1 and (user_id=$2 or user_id is null) and read_at is null", [org, req.user.id]); res.json({ count: Number(q.rows[0]?.count || 0) }); } catch (e) { fail(res, e, "Não foi possível consultar as notificações."); } });
  app.patch("/api/notifications/:id/read", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("update notifications set read_at=coalesce(read_at,now()) where id=$1 and organization_id=$2 and (user_id=$3 or user_id is null) returning id,read_at", [req.params.id, org, req.user.id]); if (!q.rowCount) return res.status(404).json({ error: "Notificação não encontrada." }); res.json({ notification: q.rows[0] }); } catch (e) { fail(res, e, "Não foi possível marcar a notificação."); } });
  app.post("/api/notifications/read-all", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("update notifications set read_at=coalesce(read_at,now()) where organization_id=$1 and (user_id=$2 or user_id is null) and read_at is null", [org, req.user.id]); res.json({ updated: q.rowCount }); } catch (e) { fail(res, e, "Não foi possível marcar as notificações."); } });
}
