/* Notificações internas do workspace. */
export function register(app, ctx) {
  const { pool, tenant, classifyDbError } = ctx;
  const fail = (res, error, fallback) => { const out = classifyDbError(error, fallback); res.status(out.status).json({ error: out.error }); };
  app.get("/api/notifications", async (req, res) => { const org = tenant(req, res); if (!org) return; const limit = Math.min(Math.max(Number(req.query.limit) || 30, 1), 100), status = ["all", "unread", "archived"].includes(req.query.status) ? req.query.status : "all"; try { const q = await pool.query("select id,message,read_at,archived_at,created_at,automation_id,entity_type,entity_id from notifications where organization_id=$1 and (user_id=$2 or user_id is null) and ($3='archived' and archived_at is not null or $3<>'archived' and archived_at is null) and ($3<>'unread' or read_at is null) order by read_at nulls first,created_at desc limit $4", [org, req.user.id, status, limit]); const unread = await pool.query("select count(*)::int as count from notifications where organization_id=$1 and (user_id=$2 or user_id is null) and archived_at is null and read_at is null", [org, req.user.id]); res.json({ notifications: q.rows, unread_count: Number(unread.rows[0]?.count || 0) }); } catch (e) { fail(res, e, "Não foi possível carregar as notificações."); } });
  app.get("/api/notifications/unread-count", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select count(*)::int as count from notifications where organization_id=$1 and (user_id=$2 or user_id is null) and read_at is null", [org, req.user.id]); res.json({ count: Number(q.rows[0]?.count || 0) }); } catch (e) { fail(res, e, "Não foi possível consultar as notificações."); } });
  app.patch("/api/notifications/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; const read = req.body?.read, archived = req.body?.archived; if (read !== undefined && typeof read !== "boolean" || archived !== undefined && typeof archived !== "boolean") return res.status(400).json({ error: "Ação de notificação inválida." }); try { const q = await pool.query("update notifications set read_at=case when $4=true then coalesce(read_at,now()) when $4=false then null else read_at end,archived_at=case when $5=true then coalesce(archived_at,now()) when $5=false then null else archived_at end where id=$1 and organization_id=$2 and (user_id=$3 or user_id is null) returning id,read_at,archived_at", [req.params.id, org, req.user.id, read ?? null, archived ?? null]); if (!q.rowCount) return res.status(404).json({ error: "Notificação não encontrada." }); res.json({ notification: q.rows[0] }); } catch (e) { fail(res, e, "Não foi possível atualizar a notificação."); } });
  app.patch("/api/notifications/:id/read", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("update notifications set read_at=coalesce(read_at,now()) where id=$1 and organization_id=$2 and (user_id=$3 or user_id is null) returning id,read_at,archived_at", [req.params.id, org, req.user.id]); if (!q.rowCount) return res.status(404).json({ error: "Notificação não encontrada." }); res.json({ notification: q.rows[0] }); } catch (e) { fail(res, e, "Não foi possível marcar a notificação."); } });
  app.post("/api/notifications/read-all", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("update notifications set read_at=coalesce(read_at,now()) where organization_id=$1 and (user_id=$2 or user_id is null) and archived_at is null and read_at is null", [org, req.user.id]); res.json({ updated: q.rowCount }); } catch (e) { fail(res, e, "Não foi possível marcar as notificações."); } });
}
