import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import { createServer } from "node:http";
import { registerProposalPublicRoutes } from "./proposal-public.js";

const org = "00000000-0000-0000-0000-000000000001";
async function request(server, path, options = {}) { const address = server.address(); return fetch(`http://127.0.0.1:${address.port}${path}`, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) }, body: options.body === undefined ? undefined : JSON.stringify(options.body) }); }
function setup() { const calls = []; const query = async (sql, params) => { calls.push({ sql, params }); if (sql.startsWith("update proposals set status")) return { rowCount: 1, rows: [{ id: 5, title: "Site", status: "accepted", organization_id: org, opportunity_id: 8, lead_id: 9 }] }; return { rowCount: 1, rows: [{ id: 5, title: "Site", status: "sent", organization_id: org }] }; }; const pool = { query, connect: async () => ({ query, release() {} }) }; const app = express(); app.use(express.json()); registerProposalPublicRoutes(app, { pool, tenant: () => org, requireAuth: (_req, _res, next) => next(), classifyDbError: (_error, fallback) => ({ status: 500, error: fallback }) }); return { app, calls }; }

test("aprovação pública exige nome e e-mail válidos", async (t) => { const { app } = setup(), server = createServer(app); await new Promise((resolve) => server.listen(0, resolve)); t.after(() => server.close()); const response = await request(server, "/api/proposals/public/token/decision", { method: "POST", body: { decision: "accepted", name: "", email: "x" } }); assert.equal(response.status, 400); });
test("aprovação pública atualiza proposta e relacionamentos no workspace", async (t) => { const { app, calls } = setup(), server = createServer(app); await new Promise((resolve) => server.listen(0, resolve)); t.after(() => server.close()); const response = await request(server, "/api/proposals/public/token/decision", { method: "POST", body: { decision: "accepted", name: "Cliente", email: "cliente@example.com" } }); assert.equal(response.status, 200); assert.equal((await response.json()).decided, true); assert.ok(calls.some((call) => call.sql.includes("update opportunities") && call.params[2] === org)); assert.ok(calls.some((call) => call.sql.includes("update leads") && call.params[1] === org)); });
