import crypto from "node:crypto";

const encryptionKey = () => crypto.createHash("sha256").update(process.env.VAULT_ENCRYPTION_KEY || process.env.SESSION_SECRET || "development-only-change-me").digest();
const encrypt = (value) => { const iv = crypto.randomBytes(12), cipher = crypto.createCipheriv("aes-256-gcm", encryptionKey(), iv); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); return { ciphertext: ciphertext.toString("base64url"), iv: iv.toString("base64url"), tag: cipher.getAuthTag().toString("base64url") }; };
const decrypt = (row) => { const decipher = crypto.createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(row.secret_iv, "base64url")); decipher.setAuthTag(Buffer.from(row.secret_tag, "base64url")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(row.secret_ciphertext, "base64url")), decipher.final()]).toString("utf8")); };
const safeSecret = (value) => ({ username: value?.username ? "••••••••" : "", password: value?.password ? "••••••••" : "", api_key: value?.api_key ? "••••••••" : "", notes: value?.notes ? "••••••••" : "" });

export function register(app, ctx) {
  const { pool, tenant, classifyDbError, verifyPassword } = ctx;
  const fail = (res, error, fallback) => { const out = classifyDbError(error, fallback); res.status(out.status).json({ error: out.error }); };
  const metadata = (row, secret) => ({ id: row.id, name: row.name, service: row.service, client_id: row.client_id, project_id: row.project_id, expires_on: row.expires_on, secret: safeSecret(secret), created_at: row.created_at, updated_at: row.updated_at });
  const relation = async (id, table, org) => { if (id === undefined || id === null || id === "") return null; const q = await pool.query(`select id from ${table} where id=$1 and organization_id=$2`, [id, org]); return q.rowCount ? id : false; };
  const fields = (body) => ({ username: String(body?.username || "").trim().slice(0, 500), password: String(body?.password || "").slice(0, 2000), api_key: String(body?.api_key || "").slice(0, 2000), notes: String(body?.notes || "").slice(0, 2000) });
  app.get("/api/vault", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select id,name,service,client_id,project_id,expires_on,secret_ciphertext,secret_iv,secret_tag,created_at,updated_at from vault_accesses where organization_id=$1 order by created_at desc", [org]); res.json({ vault: q.rows.map((row) => metadata(row, decrypt(row))) }); } catch (e) { fail(res, e, "Não foi possível carregar o cofre de acessos."); } });
  app.post("/api/vault", async (req, res) => { const org = tenant(req, res); if (!org) return; const name = String(req.body?.name || "").trim(), service = String(req.body?.service || "").trim(); if (!name || !service) return res.status(400).json({ error: "Nome e serviço são obrigatórios." }); try { const client = await relation(req.body?.client_id, "clients", org), project = await relation(req.body?.project_id, "projects", org); if (client === false || project === false) return res.status(400).json({ error: "Cliente ou projeto inválido." }); const secret = encrypt(fields(req.body)); const q = await pool.query("insert into vault_accesses (organization_id,client_id,project_id,name,service,expires_on,secret_ciphertext,secret_iv,secret_tag,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id,name,service,client_id,project_id,expires_on,secret_ciphertext,secret_iv,secret_tag,created_at,updated_at", [org, client, project, name.slice(0, 180), service.slice(0, 180), req.body?.expires_on || null, secret.ciphertext, secret.iv, secret.tag, req.user.id]); res.status(201).json({ vault_access: metadata(q.rows[0], fields(req.body)) }); } catch (e) { fail(res, e, "Não foi possível salvar o acesso protegido."); } });
  app.post("/api/vault/:id/reveal", async (req, res) => { const org = tenant(req, res); if (!org) return; const password = String(req.body?.confirmation_password || ""); if (!password) return res.status(400).json({ error: "Confirme sua senha para revelar o acesso." }); try { const user = await pool.query("select password_hash from users where id=$1 and organization_id=$2", [req.user.id, org]), [salt, hash] = user.rows[0]?.password_hash?.split(":") || []; if (!salt || !hash || !verifyPassword(password, salt, hash)) return res.status(401).json({ error: "Senha de confirmação inválida." }); const q = await pool.query("select * from vault_accesses where id=$1 and organization_id=$2", [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Acesso não encontrado." }); res.json({ secret: decrypt(q.rows[0]) }); } catch (e) { fail(res, e, "Não foi possível revelar o acesso."); } });
  app.patch("/api/vault/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const current = await pool.query("select * from vault_accesses where id=$1 and organization_id=$2", [req.params.id, org]); if (!current.rowCount) return res.status(404).json({ error: "Acesso não encontrado." }); const row = current.rows[0], client = req.body?.client_id === undefined ? row.client_id : await relation(req.body.client_id, "clients", org), project = req.body?.project_id === undefined ? row.project_id : await relation(req.body.project_id, "projects", org); if (client === false || project === false) return res.status(400).json({ error: "Cliente ou projeto inválido." }); const oldSecret = decrypt(row), updatedSecret = req.body?.password !== undefined || req.body?.api_key !== undefined || req.body?.username !== undefined || req.body?.notes !== undefined ? { ...oldSecret, ...fields({ ...oldSecret, ...req.body }) } : oldSecret, secret = encrypt(updatedSecret); const q = await pool.query("update vault_accesses set name=coalesce($1,name),service=coalesce($2,service),client_id=$3,project_id=$4,expires_on=coalesce($5,expires_on),secret_ciphertext=$6,secret_iv=$7,secret_tag=$8,updated_at=now() where id=$9 and organization_id=$10 returning id,name,service,client_id,project_id,expires_on,secret_ciphertext,secret_iv,secret_tag,created_at,updated_at", [req.body?.name || null, req.body?.service || null, client, project, req.body?.expires_on || null, secret.ciphertext, secret.iv, secret.tag, req.params.id, org]); res.json({ vault_access: metadata(q.rows[0], updatedSecret) }); } catch (e) { fail(res, e, "Não foi possível atualizar o acesso protegido."); } });
  app.delete("/api/vault/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("delete from vault_accesses where id=$1 and organization_id=$2 returning id", [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Acesso não encontrado." }); res.status(204).end(); } catch (e) { fail(res, e, "Não foi possível excluir o acesso."); } });
}
