import "dotenv/config";
import express from "express";
import cors from "cors";
import pg from "pg";
import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expandRecurringEvents } from "./recurrence.js";
import { singular, classifyDbError, isValidAmount, TABLES_WITH_UPDATED_AT, normalizeIdentity } from "./http-helpers.js";
import { attachResetRoutes } from "./auth-reset.js";
import { runMigrations } from "./migrate.js";
import { registerDomainRoutes } from "./routes/index.js";
import { startAutomationRunner } from "./automations-runner.js";

const { Pool } = pg;
export const app = express();
const port = Number(process.env.PORT || 3000);
export const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === "true" ? { rejectUnauthorized: false } : undefined });
const DEFAULT_ORGANIZATION_ID = process.env.DEFAULT_ORGANIZATION_ID || "00000000-0000-0000-0000-000000000001";
const SESSION_SECRET = process.env.SESSION_SECRET || "development-only-change-me";
const SESSION_MAX_AGE = 60 * 60 * 24 * 7;
if (process.env.NODE_ENV === "production" && (!process.env.SESSION_SECRET || process.env.SESSION_SECRET.length < 32)) throw new Error("SESSION_SECRET must be set to at least 32 characters in production.");
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const organizationId = (req) => { const value = req.user?.organization_id || req.get("x-organization-id") || req.query.organizationId || DEFAULT_ORGANIZATION_ID; return UUID.test(String(value)) ? String(value) : null; };
const tenant = (req, res) => { const id = organizationId(req); if (!id) res.status(400).json({ error: "organization_id inválido." }); return id; };
const asText = (v) => typeof v === "string" ? v.trim() : "";
const allowedOrigins = new Set((process.env.CORS_ORIGINS || "").split(",").map((origin) => origin.trim()).filter(Boolean));
app.use(cors({ origin(origin, callback) {
  if (!origin || allowedOrigins.has(origin)) return callback(null, true);
  return callback(null, false);
} }));
app.use(express.json({ limit: "1mb" }));
app.use((_req, res, next) => { res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin"); next(); });
app.use((req, _res, next) => { if (/^\/api\/(events|tasks)\/\d+-(?:[^/?]+)$/.test(req.path) || /^\/api\/(events|tasks)\/\d+\/(?:details|schedule)$/.test(req.path)) req.url = req.url.replace(/(\/api\/(?:events|tasks)\/\d+)(?:-[^/?]+|\/(?:details|schedule))/, "$1"); next(); });
const frontendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
app.use((req, res, next) => {
  if (req.path === "/" || req.path === "/index.html" || req.path === "/service-worker.js") {
    res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
  }
  next();
});
app.use(express.static(frontendRoot));

const hashPassword = (password, salt = crypto.randomBytes(16).toString("hex")) => ({ salt, hash: crypto.scryptSync(password, salt, 64).toString("hex") });
const verifyPassword = (password, salt, expected) => { try { return crypto.timingSafeEqual(Buffer.from(hashPassword(password, salt).hash, "hex"), Buffer.from(expected, "hex")); } catch { return false; } };
const signSession = (user) => { const payload = Buffer.from(JSON.stringify({ id: user.id, name: user.name, email: user.email, organization_id: user.organization_id, exp: Math.floor(Date.now() / 1000) + SESSION_MAX_AGE })).toString("base64url"); const signature = crypto.createHmac("sha256", SESSION_SECRET).update(payload).digest("base64url"); return `${payload}.${signature}`; };
const parseCookies = (header = "") => Object.fromEntries(header.split(";").map((part) => part.trim().split("=")).filter(([key, value]) => key && value).map(([key, ...value]) => [key, value.join("=")]));
const readSession = (req) => { try { const [payload, signature] = (parseCookies(req.get("cookie")).focus_session || "").split("."); if (!payload || !signature) return null; const expected = crypto.createHmac("sha256", SESSION_SECRET).update(payload).digest("base64url"); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; const session = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")); return session.exp > Math.floor(Date.now() / 1000) ? session : null; } catch { return null; } };
const sessionCookie = (token, maxAge = SESSION_MAX_AGE) => `focus_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${maxAge}${process.env.NODE_ENV === "production" ? "; Secure" : ""}`;
const requireAuth = (req, res, next) => { const user = readSession(req); if (!user) return res.status(401).json({ error: "Autenticação necessária." }); req.user = user; return next(); };
app.post("/api/auth/register", async (req, res) => { const name = asText(req.body?.name), email = asText(req.body?.email).toLowerCase(), password = String(req.body?.password || ""); if (name.length < 2 || !/^\S+@\S+\.\S+$/.test(email) || password.length < 8) return res.status(400).json({ error: "Nome, e-mail e senha válidos são obrigatórios." }); const client = await pool.connect().catch(() => null); if (!client) return res.status(503).json({ error: "Serviço indisponível." }); try { const { salt, hash } = hashPassword(password); await client.query("begin"); const org = await client.query("insert into organizations (name) values ($1) returning id", [`Workspace de ${name}`]); const q = await client.query("insert into users (name,email,password_hash,organization_id,role) values ($1,$2,$3,$4,'owner') returning id,name,email,organization_id,role", [name, email, `${salt}:${hash}`, org.rows[0].id]); await client.query("commit"); res.status(201).json({ user: q.rows[0] }); } catch (e) { await client.query("rollback").catch(() => {}); res.status(e.code === "23505" ? 409 : 503).json({ error: e.code === "23505" ? "Este e-mail já está cadastrado." : "Não foi possível criar a conta." }); } finally { client.release(); } });
app.post("/api/auth/login", async (req, res) => { const email = asText(req.body?.email).toLowerCase(), password = String(req.body?.password || ""); try { const q = await pool.query("select id,name,email,password_hash,organization_id,role from users where email=$1", [email]); const u = q.rows[0], [salt, hash] = u?.password_hash?.split(":") || []; if (!u || !salt || !verifyPassword(password, salt, hash)) return res.status(401).json({ error: "E-mail ou senha inválidos." }); const user = { id: u.id, name: u.name, email: u.email, organization_id: u.organization_id, role: u.role || "member" }; res.setHeader("Set-Cookie", sessionCookie(signSession(user))); res.json({ user }); } catch { res.status(503).json({ error: "Serviço indisponível." }); } });
app.get("/api/auth/me", requireAuth, (req, res) => res.json({ user: req.user }));
app.post("/api/auth/logout", (_req, res) => { res.setHeader("Set-Cookie", sessionCookie("", 0)); res.status(204).end(); });
attachResetRoutes(app, { pool, hashPassword });
app.get("/api/health", async (_req, res) => { try { const q = await pool.query("select now() as time"); res.json({ ok: true, database: "connected", time: q.rows[0].time }); } catch { res.status(503).json({ ok: false, database: "unavailable", error: "Database unavailable." }); } });
/* Rotas públicas (sem sessão): autenticação, health, portal do cliente (token) e webhook do WhatsApp (token). */
const PUBLIC_API_PREFIXES = ["/auth/", "/portal/", "/whatsapp/webhook/"];
app.use("/api", (req, res, next) => { if (req.path === "/health" || PUBLIC_API_PREFIXES.some((prefix) => req.path.startsWith(prefix))) return next(); return requireAuth(req, res, next); });

const entities = {
  contacts: { fields: ["name", "email", "phone", "role", "notes", "department", "document", "birth_date", "city", "state", "preferred_channel", "contact_type", "source", "owner", "tags", "is_primary", "company_id"], required: ["name"] }, companies: { fields: ["name", "document", "email", "phone", "website", "address", "legal_name", "trade_name", "state_registration", "municipal_registration", "status", "founded_on", "size", "segment", "primary_activity", "whatsapp", "zip_code", "street", "street_number", "city", "state", "country", "internal_owner", "source", "last_cnpj_lookup_at"], required: ["name"] },
  leads: { fields: ["name", "company", "company_id", "contact_id", "email", "phone", "source", "status", "notes", "value", "campaign_id"], required: ["name"] }, opportunities: { fields: ["name", "lead_id", "company_id", "contact_id", "stage", "amount", "expected_close", "notes", "probability"], required: ["name"] },
  clients: { fields: ["name", "company_id", "contact_id", "email", "phone", "status", "legal_name", "trade_name", "person_type", "avatar_url", "document", "founded_on", "source", "responsible_name", "responsible_role", "whatsapp", "secondary_phone", "website", "instagram", "linkedin", "contact_hours", "preferred_channel", "zip_code", "street", "street_number", "complement", "neighborhood", "city", "state", "country", "segment", "company_size", "services_interest", "main_need", "estimated_budget", "urgency", "sales_owner", "funnel_stage", "lead_temperature", "closing_probability", "first_contact_at", "last_contact_at", "next_contact_at", "next_action", "commercial_notes", "default_payment_terms", "preferred_payment_method", "monthly_fee", "due_day", "financial_status", "pix_key", "invoice_data", "internal_notes"], required: ["name"] }, contracts: { fields: ["name", "client_id", "opportunity_id", "status", "value", "starts_on", "ends_on"], required: ["name", "client_id"] },
  projects: { fields: ["name", "contract_id", "client_id", "status", "progress"], required: ["name"] }, tasks: { fields: ["title", "project_id", "status", "priority", "due_at", "tags", "parent_id", "description", "client_id", "stage", "assignee", "participants", "starts_at", "category", "estimated_minutes", "worked_minutes", "hourly_cost", "checklist", "recurrence", "recurrence_until", "blocked_reason", "internal_notes"], required: ["title"] },
  revenues: { fields: ["description", "contract_id", "project_id", "amount", "gross_amount", "discount", "fees", "tax_estimate", "net_amount", "category", "payment_method", "account_name", "document_number", "receipt_url", "status", "due_at", "paid_at"], required: ["description", "amount"] }, expenses: { fields: ["description", "project_id", "client_id", "amount", "supplier", "category", "payment_method", "account_name", "recurrence", "cost_center", "status", "due_at", "paid_at"], required: ["description", "amount"] },
  receivables: { fields: ["description", "client_id", "contract_id", "proposal_id", "project_id", "amount", "original_amount", "discount", "interest", "fine", "updated_amount", "installment_number", "payment_method", "responsible", "due_at", "status", "paid_at"], required: ["description", "amount", "due_at"] }, charges: { fields: ["receivable_id", "client_id", "project_id", "provider", "external_id", "channel", "payment_url", "message", "status", "amount", "due_at"], required: ["amount"] }, payments: { fields: ["receivable_id", "charge_id", "amount", "paid_at", "method", "external_id"], required: ["amount"] }
};
const normalize = (table, body) => { const spec = entities[table]; const values = {}; for (const key of spec.fields) if (body?.[key] !== undefined) values[key] = body[key]; for (const key of ["email", "document", "phone"]) if (values[key] !== undefined) values[key] = normalizeIdentity(key, values[key]); if (table === "tasks" && typeof values.tags === "string") values.tags = values.tags.split(",").map(asText).filter(Boolean).slice(0, 8); if (!["amount", "value"].every((k) => values[k] === undefined || isValidAmount(table, k, values[k]))) throw new Error("amount must be a positive number"); return values; };
const relations = { company_id: "companies", contact_id: "contacts", lead_id: "leads", opportunity_id: "opportunities", client_id: "clients", contract_id: "contracts", project_id: "projects", parent_id: "tasks", receivable_id: "receivables", charge_id: "charges" };
async function validateRelations(values, org) { for (const [field, table] of Object.entries(relations)) { if (values[field] === undefined || values[field] === null || values[field] === "") continue; const result = await pool.query(`select 1 from ${table} where id=$1 and organization_id=$2`, [values[field], org]); if (!result.rowCount) { const error = new Error(`${field} does not belong to this organization.`); error.code = "invalid_relation"; throw error; } } }
const createCrud = (table) => {
  const route = `/api/${table}`; app.post(route, async (req, res) => { const org = tenant(req, res); if (!org) return; let values; try { values = normalize(table, req.body); await validateRelations(values, org); } catch (e) { if (e.code === "invalid_relation" || e.message === "amount must be a positive number") return res.status(400).json({ error: e.message }); return res.status(503).json({ error: "Não foi possível validar o registro." }); } const missing = entities[table].required.find((k) => values[k] === undefined || values[k] === ""); if (missing) return res.status(400).json({ error: `${missing} is required.` }); const keys = Object.keys(values), cols = ["organization_id", ...keys], params = [org, ...keys.map((k) => values[k])], marks = cols.map((_, i) => `$${i + 1}`); try { const q = await pool.query(`insert into ${table} (${cols.join(",")}) values (${marks.join(",")}) returning *`, params); res.status(201).json({ [singular(table)]: q.rows[0] }); } catch (e) { const { status, error } = classifyDbError(e, "Não foi possível criar o registro."); res.status(status).json({ error }); } });
  app.get(route, async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query(`select * from ${table} where organization_id=$1 order by created_at desc`, [org]); res.json({ [table]: q.rows }); } catch { res.status(503).json({ error: "Não foi possível carregar os registros." }); } });
  app.delete(`${route}/:id`, async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query(`delete from ${table} where id=$1 and organization_id=$2 returning id`, [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Registro não encontrado." }); res.status(204).end(); } catch { res.status(503).json({ error: "Não foi possível excluir o registro." }); } });
  app.patch(`${route}/:id`, async (req, res) => { const org = tenant(req, res); if (!org) return; let values; try { values = normalize(table, req.body); await validateRelations(values, org); } catch (e) { if (e.code === "invalid_relation" || e.message === "amount must be a positive number") return res.status(400).json({ error: e.message }); return res.status(503).json({ error: "Não foi possível validar o registro." }); } const keys = Object.keys(values); if (!keys.length) return res.status(400).json({ error: "Nenhum campo válido informado." }); try { const setClause = [...keys.map((k, i) => `${k}=$${i + 1}`), ...(TABLES_WITH_UPDATED_AT.has(table) ? ["updated_at=now()"] : [])].join(","); const q = await pool.query(`update ${table} set ${setClause} where id=$${keys.length + 1} and organization_id=$${keys.length + 2} returning *`, [...keys.map((k) => values[k]), req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Registro não encontrado." }); if (table === "opportunities" && ["won", "lost"].includes(values.stage) && q.rows[0].lead_id) await pool.query("update leads set status=$1, updated_at=now() where id=$2 and organization_id=$3", [values.stage, q.rows[0].lead_id, org]).catch(() => {}); res.json({ [singular(table)]: q.rows[0] }); } catch (e) { const { status, error } = classifyDbError(e, "Não foi possível atualizar o registro."); res.status(status).json({ error }); } });
}; Object.keys(entities).forEach(createCrud);

app.get("/api/dashboard", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const [tasks, leads, projects, revenue] = await Promise.all([pool.query("select count(*)::int total from tasks where organization_id=$1 and status <> 'done'", [org]), pool.query("select count(*)::int total from leads where organization_id=$1 and status <> 'won'", [org]), pool.query("select count(*)::int total from projects where organization_id=$1 and status='active'", [org]), pool.query("select coalesce(sum(amount),0) total from revenues where organization_id=$1 and paid_at >= date_trunc('month',current_date)", [org])]); res.json({ tasks: tasks.rows[0].total, leads: leads.rows[0].total, projects: projects.rows[0].total, revenue: revenue.rows[0].total }); } catch { res.status(503).json({ error: "Não foi possível carregar o dashboard." }); } });

app.post("/api/events", async (req, res) => { const org = tenant(req, res); if (!org) return; const title = asText(req.body?.title), startsAt = req.body?.startsAt; if (!title || !startsAt || Number.isNaN(Date.parse(startsAt))) return res.status(400).json({ error: "Informe título e horário válidos." }); const recurrence = ["none", "daily", "weekly", "monthly"].includes(req.body?.recurrence) ? req.body.recurrence : "none"; try { const q = await pool.query("insert into events (organization_id,title,starts_at,description,recurrence,reminder_minutes) values ($1,$2,$3,$4,$5,$6) returning *", [org, title, startsAt, asText(req.body?.description) || null, recurrence, Math.max(0, Number(req.body?.reminderMinutes) || 0)]); res.status(201).json({ event: q.rows[0] }); } catch (e) { const { status, error } = classifyDbError(e, "Não foi possível criar o evento."); res.status(status).json({ error }); } });
app.get("/api/events", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("select * from events where organization_id=$1 order by starts_at", [org]); res.json({ events: expandRecurringEvents(q.rows) }); } catch { res.status(503).json({ error: "Não foi possível carregar os eventos." }); } });
app.patch("/api/events/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; const fields = {}; if (req.body?.title !== undefined) fields.title = asText(req.body.title); if (req.body?.startsAt !== undefined) fields.starts_at = req.body.startsAt; if (req.body?.description !== undefined) fields.description = asText(req.body.description) || null; if (req.body?.recurrence !== undefined) fields.recurrence = ["none", "daily", "weekly", "monthly"].includes(req.body.recurrence) ? req.body.recurrence : null; if (req.body?.reminderMinutes !== undefined) fields.reminder_minutes = Math.max(0, Number(req.body.reminderMinutes) || 0); if (fields.title === "" || (fields.starts_at !== undefined && Number.isNaN(Date.parse(fields.starts_at))) || fields.recurrence === null) return res.status(400).json({ error: "Dados do evento inválidos." }); const keys = Object.keys(fields); if (!keys.length) return res.status(400).json({ error: "Nenhum campo válido informado." }); try { const q = await pool.query(`update events set ${keys.map((key, index) => `${key}=$${index + 1}`).join(",")} where id=$${keys.length + 1} and organization_id=$${keys.length + 2} returning *`, [...keys.map((key) => fields[key]), req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Evento não encontrado." }); res.json({ event: q.rows[0] }); } catch (e) { const { status, error } = classifyDbError(e, "Não foi possível atualizar o evento."); res.status(status).json({ error }); } });
app.delete("/api/events/:id", async (req, res) => { const org = tenant(req, res); if (!org) return; try { const q = await pool.query("delete from events where id=$1 and organization_id=$2 returning id", [req.params.id, org]); if (!q.rowCount) return res.status(404).json({ error: "Evento não encontrado." }); res.status(204).end(); } catch { res.status(503).json({ error: "Não foi possível excluir o evento." }); } });

registerDomainRoutes(app, { pool, tenant, requireAuth, asText, classifyDbError, singular, validateRelations, normalize, entities, hashPassword, verifyPassword, signSession, sessionCookie });

async function start() { try { await runMigrations(pool); app.listen(port, "0.0.0.0", () => { console.log(`FocusApp API listening on ${port}`); startAutomationRunner(pool); }); } catch (e) { console.error("FocusApp API could not connect to PostgreSQL:", e.message); process.exitCode = 1; } }
if (process.env.NODE_ENV !== "test") start();
