const starterTemplates = [
  ["proposal", "[Biblioteca] Proposta comercial completa", "Comercial", "Proposta comercial — {{client_name}}", "Olá, {{client_name}}!\n\nÉ um prazer apresentar esta proposta para {{project_name}}.\n\nEscopo\n{{scope}}\n\nInvestimento: {{total_amount}}\nPrazo: {{delivery_days}} dias\nValidade: {{valid_until}}\n\nSe fizer sentido, responda a esta mensagem para avançarmos.", "client_name,project_name,scope,total_amount,delivery_days,valid_until"],
  ["contract", "[Biblioteca] Contrato de prestação de serviços", "Jurídico", "Contrato — {{project_name}}", "CONTRATO DE PRESTAÇÃO DE SERVIÇOS\n\nCONTRATANTE: {{client_name}}\nCONTRATADA: {{company_name}}\n\n1. OBJETO\n{{scope}}\n\n2. PRAZO E INVESTIMENTO\nPrazo: {{delivery_days}} dias. Valor: {{total_amount}}.\n\n3. RESPONSABILIDADES\nAs partes concordam com o escopo, prazos e critérios de aceite descritos neste documento.", "client_name,company_name,scope,delivery_days,total_amount"],
  ["project", "[Biblioteca] Projeto de entrega padrão", "Operação", "Projeto — {{project_name}}", "Objetivo: {{objective}}\nCliente: {{client_name}}\nResponsável: {{responsible}}\nPrazo: {{delivery_days}} dias\n\nEntregas:\n{{deliverables}}\n\nCritério de aceite:\n{{acceptance_criteria}}", "project_name,objective,client_name,responsible,delivery_days,deliverables,acceptance_criteria"],
  ["task", "[Biblioteca] Tarefa operacional", "Operação", "{{task_title}}", "Objetivo: {{objective}}\nContexto: {{context}}\nPrazo: {{due_date}}\nResponsável: {{responsible}}\nCritério de conclusão: {{done_criteria}}", "task_title,objective,context,due_date,responsible,done_criteria"],
  ["checklist", "[Biblioteca] Checklist de início de projeto", "Operação", "Checklist de kickoff", "[ ] Confirmar escopo e prioridades\n[ ] Validar acessos e materiais\n[ ] Definir responsáveis\n[ ] Agendar kickoff\n[ ] Registrar riscos e dependências\n[ ] Confirmar primeira entrega", ""],
  ["charge", "[Biblioteca] Cobrança cordial", "Financeiro", "Lembrete de pagamento — {{invoice_number}}", "Olá, {{client_name}}!\n\nPassando para lembrar que a cobrança {{invoice_number}}, no valor de {{amount}}, vence em {{due_date}}.\n\nSe já realizou o pagamento, desconsidere esta mensagem. Se precisar de ajuda, fale conosco.", "client_name,invoice_number,amount,due_date"],
  ["followup", "[Biblioteca] Follow-up após proposta", "Comercial", "Podemos avançar, {{client_name}}?", "Olá, {{client_name}}!\n\nQueria saber se conseguiu avaliar a proposta sobre {{project_name}}. Posso esclarecer alguma dúvida ou ajustar algum ponto para seguirmos?\n\nFico à disposição.", "client_name,project_name"],
  ["support", "[Biblioteca] Resposta de suporte inicial", "Atendimento", "Recebemos sua solicitação", "Olá, {{client_name}}!\n\nRecebemos sua solicitação {{ticket_number}} e ela já está com nossa equipe.\n\nPrazo estimado de retorno: {{sla}}.\nResponsável: {{responsible}}.\n\nSe tiver novas informações, responda nesta mesma conversa.", "client_name,ticket_number,sla,responsible"],
  ["ticket", "[Biblioteca] Registro de ticket", "Atendimento", "Ticket {{ticket_number}} — {{subject}}", "Assunto: {{subject}}\nCliente: {{client_name}}\nPrioridade: {{priority}}\nDescrição:\n{{description}}\n\nPróxima ação: {{next_action}}", "ticket_number,subject,client_name,priority,description,next_action"],
  ["briefing", "[Biblioteca] Briefing de projeto", "Planejamento", "Briefing — {{project_name}}", "Contexto do negócio:\n{{business_context}}\n\nObjetivo principal:\n{{objective}}\n\nPúblico:\n{{audience}}\n\nReferências:\n{{references}}\n\nRestrições e preferências:\n{{constraints}}\n\nPrazo desejado: {{deadline}}", "project_name,business_context,objective,audience,references,constraints,deadline"],
  ["delivery_term", "[Biblioteca] Termos de entrega", "Operação", "Termos de entrega — {{project_name}}", "A entrega será realizada em até {{delivery_days}} dias úteis após o recebimento de todos os materiais necessários.\n\nInclui: {{included_scope}}\nNão inclui: {{excluded_scope}}\nRevisões previstas: {{revisions_count}}\nCritério de aceite: {{acceptance_criteria}}", "project_name,delivery_days,included_scope,excluded_scope,revisions_count,acceptance_criteria"],
  ["report", "[Biblioteca] Relatório mensal", "Gestão", "Relatório de resultados — {{period}}", "Resumo executivo\n{{summary}}\n\nIndicadores\n{{metrics}}\n\nEntregas realizadas\n{{deliveries}}\n\nPróximos passos\n{{next_steps}}\n\nPontos de atenção\n{{risks}}", "period,summary,metrics,deliveries,next_steps,risks"],
  ["notification", "[Biblioteca] Notificação interna", "Gestão", "Atenção: {{event_name}}", "{{event_name}}\n\nCliente: {{client_name}}\nResponsável: {{responsible}}\nPrazo: {{due_date}}\n\nAcesse o FocusApp para consultar os detalhes e registrar a próxima ação.", "event_name,client_name,responsible,due_date"],
  ["email", "[Biblioteca] E-mail institucional", "Comunicação", "{{subject}}", "Olá, {{client_name}}!\n\n{{message}}\n\nSe precisar de qualquer coisa, estamos à disposição.\n\nAtenciosamente,\n{{company_name}}", "subject,client_name,message,company_name"],
  ["message", "[Biblioteca] Mensagem curta de atendimento", "Comunicação", "", "Olá, {{client_name}}! {{message}} Se precisar, estou por aqui.", "client_name,message"],
  ["whatsapp", "[Biblioteca] WhatsApp de confirmação", "Comunicação", "", "Olá, {{client_name}}! Confirmando nosso {{appointment_type}} para {{appointment_date}} às {{appointment_time}}. Pode confirmar?", "client_name,appointment_type,appointment_date,appointment_time"],
  ["proposal", "[Propostas] Página de vendas — R$ 799", "Propostas prontas", "Proposta — Página de vendas", "Objetivo: criar uma página de vendas clara, responsiva e preparada para conversão.\n\nInclui:\n• Estrutura da página e CTA\n• Design responsivo\n• Formulário e WhatsApp\n• Publicação\n\nInvestimento: R$ 799,00\nPrazo estimado: 7 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
  ["proposal", "[Propostas] Site institucional — R$ 999", "Propostas prontas", "Proposta — Site institucional", "Site profissional para apresentar a empresa, serviços, diferenciais e canais de contato.\n\nInclui:\n• Até 5 seções\n• SEO básico\n• Integração com WhatsApp\n• Layout responsivo\n\nInvestimento: R$ 999,00\nPrazo estimado: 10 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
  ["proposal", "[Propostas] Site Motion — R$ 1.499", "Propostas prontas", "Proposta — Site Motion", "Experiência digital premium com animações, transições e apresentação marcante.\n\nInclui:\n• Tudo do site institucional\n• Animações de entrada e scroll\n• Hero premium\n• Ajustes de experiência\n\nInvestimento: R$ 1.499,00\nPrazo estimado: 14 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
  ["proposal", "[Propostas] Google Meu Negócio — R$ 899", "Propostas prontas", "Proposta — Google Meu Negócio e posicionamento", "Implantação e otimização da presença local da empresa no Google.\n\nInclui:\n• Configuração do perfil\n• Categorias, serviços e descrição\n• Orientação para avaliações\n• Plano de conteúdo local\n\nInvestimento: R$ 899,00\nPrazo estimado: 7 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
  ["proposal", "[Propostas] App MVP — a partir de R$ 3.999", "Propostas prontas", "Proposta — App MVP", "Transformação da ideia em um produto mínimo viável para validar com usuários.\n\nInclui:\n• Descoberta e definição do MVP\n• Fluxo de telas\n• Desenvolvimento funcional\n• Painel básico e publicação orientada\n\nInvestimento inicial: R$ 3.999,00\nPrazo estimado: 45 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
  ["proposal", "[Propostas] Web app sob medida — R$ 4.999", "Propostas prontas", "Proposta — Web app sob medida", "Sistema web personalizado para centralizar processos, clientes e operação.\n\nInclui:\n• Arquitetura do produto\n• Interface responsiva\n• Login e permissões\n• Banco de dados\n• Deploy e documentação\n\nInvestimento: R$ 4.999,00\nPrazo estimado: 45 dias úteis\nCondições: {{payment_terms}}", "payment_terms"],
];

const focussTemplates = [
  ["proposal", "[Focussdev] Proposta — Landing Page", "Focussdev", "Proposta — Landing Page", "Olá, {{client_name}}!\n\nApresentamos a criação de uma Landing Page profissional para {{project_name}}.\n\nInclui:\n• Até 8 seções e design personalizado\n• Responsividade, WhatsApp e formulário\n• SEO básico, Analytics e Meta Pixel\n• Domínio, SSL e otimização\n• 2 rodadas de alterações\n\nInvestimento: {{total_amount}}\nPrazo: {{delivery_days}} dias úteis\nCondições: {{payment_terms}}", "client_name,project_name,total_amount,delivery_days,payment_terms"],
  ["proposal", "[Focussdev] Proposta — Site Profissional", "Focussdev", "Proposta — Site Profissional", "Olá, {{client_name}}!\n\nProposta para um site profissional de até 6 páginas, com design exclusivo, responsividade, animações, WhatsApp, formulários, Analytics, Pixel, SEO, domínio, SSL e desempenho otimizado.\n\nInvestimento: {{total_amount}}\nPrazo: {{delivery_days}} dias úteis\nCondições: {{payment_terms}}", "client_name,total_amount,delivery_days,payment_terms"],
  ["proposal", "[Focussdev] Proposta — Sistema Web ou Aplicativo", "Focussdev", "Proposta — Produto digital sob medida", "Olá, {{client_name}}!\n\nVamos transformar a necessidade {{project_name}} em um produto digital com escopo claro, interface responsiva, autenticação, banco de dados, painel administrativo, integrações e documentação.\n\nEscopo detalhado:\n{{scope}}\n\nInvestimento: {{total_amount}}\nPrazo: {{delivery_days}} dias úteis\nCondições: {{payment_terms}}", "client_name,project_name,scope,total_amount,delivery_days,payment_terms"],
  ["proposal", "[Focussdev] Proposta — Chatbot com IA", "Focussdev", "Proposta — Chatbot com IA", "Olá, {{client_name}}!\n\nImplantação de chatbot com IA para atendimento, base de conhecimento, captação e qualificação de leads, fluxos personalizados e transferência para atendimento humano.\n\nImplantação: {{total_amount}}\nMensalidade: {{monthly_amount}}\nCondições: {{payment_terms}}", "client_name,total_amount,monthly_amount,payment_terms"],
  ["contract", "[Focussdev] Contrato — Prestação de serviços digitais", "Jurídico", "Contrato de prestação de serviços — {{project_name}}", "CONTRATO DE PRESTAÇÃO DE SERVIÇOS DIGITAIS\n\nCONTRATANTE: {{client_name}}\nCONTRATADA: {{company_name}}\n\n1. OBJETO\n{{scope}}\n\n2. PRAZO E INVESTIMENTO\nPrazo estimado: {{delivery_days}} dias úteis. Investimento: {{total_amount}}.\n\n3. ENTREGAS E REVISÕES\nEntregas: {{deliverables}}\nRevisões incluídas: {{revisions_count}}\n\n4. RESPONSABILIDADES\nO cliente fornecerá conteúdos, acessos e aprovações necessários. Alterações fora do escopo serão orçadas separadamente.\n\n5. ACEITE\nA entrega será considerada aceita após aprovação registrada ou ausência de manifestação no prazo definido na proposta.", "client_name,company_name,project_name,scope,delivery_days,total_amount,deliverables,revisions_count"],
  ["contract", "[Focussdev] Contrato — Manutenção mensal", "Jurídico", "Contrato de manutenção — {{client_name}}", "CONTRATO DE MANUTENÇÃO E SUPORTE\n\nCLIENTE: {{client_name}}\nPRESTADORA: {{company_name}}\n\nServiço: {{service_name}}\nMensalidade: {{monthly_amount}}\nVencimento: {{due_date}}\n\nInclui: atualizações, correções, backups, monitoramento e pequenas alterações conforme o plano contratado. Novas funcionalidades e demandas fora do limite serão orçadas separadamente.\n\nCancelamento e prazos: {{cancellation_terms}}", "client_name,company_name,service_name,monthly_amount,due_date,cancellation_terms"],
  ["delivery_term", "[Focussdev] Termo de entrega e aceite", "Operação", "Termo de entrega — {{project_name}}", "TERMO DE ENTREGA E ACEITE\n\nProjeto: {{project_name}}\nCliente: {{client_name}}\n\nEntregas realizadas:\n{{deliverables}}\n\nPendências ou observações:\n{{pending_items}}\n\nO cliente declara que recebeu acesso à entrega para validação e poderá registrar ajustes previstos no escopo.\n\nResponsável: {{responsible}}\nData: {{delivery_date}}\nPrazo para manifestação: {{acceptance_deadline}}", "project_name,client_name,deliverables,pending_items,responsible,delivery_date,acceptance_deadline"],
  ["email", "[Focussdev] Onboarding de cliente", "Atendimento", "Vamos começar o projeto, {{client_name}}!", "Olá, {{client_name}}!\n\nSeu projeto {{project_name}} foi iniciado. Para avançarmos, envie os materiais, acessos, referências e informações descritos no briefing.\n\nPróximos passos:\n{{next_steps}}\n\nPrazo da primeira etapa: {{first_deadline}}\n\nEstamos à disposição,\n{{company_name}}", "client_name,project_name,next_steps,first_deadline,company_name"],
  ["message", "[Focussdev] Solicitação de aprovação", "Atendimento", "", "Olá, {{client_name}}! A etapa {{delivery_name}} está pronta para sua avaliação. Acesse o portal e registre sua aprovação ou os ajustes previstos no escopo. Prazo para retorno: {{acceptance_deadline}}.", "client_name,delivery_name,acceptance_deadline"],
  ["whatsapp", "[Focussdev] Follow-up comercial", "Comercial", "", "Olá, {{client_name}}! Passando para saber se conseguiu avaliar a proposta de {{project_name}}. Posso esclarecer alguma dúvida e ajustar os próximos passos?", "client_name,project_name"]
];

const starterCatalog = [
  { sku: "BIB-SVC-001", name: "Consultoria estratégica", kind: "service", price: 1800, unit: "projeto", category: "Consultoria", short_description: "Diagnóstico, prioridades e plano de ação para o próximo ciclo.", full_description: "Mapeamento do cenário atual, definição de objetivos, plano de 30 dias e reunião de apresentação.", features: "Diagnóstico inicial\nPlano de ação priorizado\nReunião executiva", benefits: "Mais clareza para decidir\nFoco no que gera resultado", delivery_days: 7, modules_count: 3, revisions_count: 1, public_visible: true, highlighted: true, tags: "consultoria,estratégia", billing_type: "one_time", max_installments: 3 },
  { sku: "BIB-SVC-002", name: "Implantação FocusApp", kind: "service", price: 3200, unit: "implantação", category: "Implantação", short_description: "Configuração do workspace, processos, templates e treinamento da equipe.", full_description: "Organização do workspace, cadastro da biblioteca inicial, criação dos fluxos e treinamento de uso.", features: "Configuração do workspace\nImportação de dados essenciais\nTreinamento da equipe", benefits: "Operação organizada desde o primeiro dia\nMenos retrabalho", delivery_days: 10, modules_count: 5, revisions_count: 2, public_visible: true, tags: "implantação,setup", billing_type: "one_time", max_installments: 6 },
  { sku: "BIB-PLN-001", name: "Plano Essencial", kind: "plan", price: 149, unit: "mês", category: "Planos", short_description: "A base para organizar clientes, tarefas e financeiro.", features: "CRM\nTarefas e projetos\nAgenda\nRelatórios básicos", limits: "Até 3 usuários\nAté 100 clientes ativos", benefits: "Visão centralizada da operação", recurrence: "monthly", term_days: 30, public_visible: true, billing_type: "recurring", max_installments: 1 },
  { sku: "BIB-PLN-002", name: "Plano Profissional", kind: "subscription", price: 349, unit: "mês", category: "Planos", short_description: "Automação, catálogo, formulários e gestão completa.", features: "Tudo do Essencial\nAutomações\nCatálogo público\nFormulários\nPortal do cliente", limits: "Até 10 usuários\nClientes ilimitados", benefits: "Escala com processos previsíveis", recurrence: "monthly", term_days: 30, public_visible: true, highlighted: true, billing_type: "recurring", max_installments: 1 },
  { sku: "BIB-PKG-001", name: "Pacote comercial completo", kind: "package", price: 2490, unit: "pacote", category: "Pacotes", short_description: "Consultoria, proposta, follow-ups e configuração do funil.", features: "Diagnóstico comercial\nTemplates de proposta\nFunil configurado\nSequência de follow-up", benefits: "Mais velocidade para vender\nProcesso comercial replicável", delivery_days: 12, public_visible: true, tags: "comercial,vendas", billing_type: "one_time", max_installments: 6 },
  { sku: "BIB-ADD-001", name: "Módulo de automações", kind: "addon", price: 99, unit: "mês", category: "Adicionais", short_description: "Ative fluxos prontos para reduzir tarefas manuais.", features: "Alertas de prazo\nFollow-up automático\nNotificações internas", benefits: "Economia de tempo\nMenos esquecimentos", recurrence: "monthly", term_days: 30, public_visible: true, tags: "automação", billing_type: "recurring", max_installments: 1 },
  { sku: "FOC-PAG-001", name: "Página de vendas", kind: "service", price: 799, unit: "projeto", category: "Sites e páginas", short_description: "Página de alta conversão para apresentar uma oferta e gerar contatos.", features: "Copy estrutural\nDesign responsivo\nFormulário de contato\nPublicação", benefits: "Presença profissional e captação de leads", delivery_days: 7, public_visible: true, tags: "landing-page,conversão", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-SIT-001", name: "Site institucional", kind: "service", price: 999, unit: "projeto", category: "Sites e páginas", short_description: "Site profissional para apresentar a empresa, serviços e contatos.", features: "Até 5 seções\nSEO básico\nResponsivo\nIntegração WhatsApp", benefits: "Credibilidade e presença digital", delivery_days: 10, public_visible: true, tags: "site,institucional", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-MOT-001", name: "Site Motion", kind: "service", price: 1499, unit: "projeto", category: "Sites e páginas", short_description: "Site institucional com animações, transições e apresentação marcante.", features: "Tudo do institucional\nAnimações de entrada\nEfeitos de scroll\nSeção hero premium", benefits: "Experiência memorável e diferenciação visual", delivery_days: 14, public_visible: true, highlighted: true, tags: "site,motion,animação", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-SIT-002", name: "Site completo — Essencial", kind: "package", price: 999, unit: "projeto", category: "Sites completos", short_description: "Site completo de entrada para empresas que precisam começar bem na internet.", features: "Até 7 seções\nSEO local\nBlog ou portfólio\nWhatsApp e formulário\nAnalytics", benefits: "Estrutura sólida para crescer", delivery_days: 15, public_visible: true, tags: "site,completo", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-SIT-003", name: "Site completo — Premium", kind: "package", price: 4999, unit: "projeto", category: "Sites completos", short_description: "Projeto completo sob medida, com estratégia, conteúdo, design premium e integrações.", features: "Arquitetura completa\nDesign exclusivo\nMotion e interações\nSEO técnico\nIntegrações e automações\nTreinamento", benefits: "Posicionamento digital completo e escalável", delivery_days: 30, public_visible: true, highlighted: true, tags: "site,premium,estratégia", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-GMB-001", name: "Google Meu Negócio + posicionamento", kind: "service", price: 899, unit: "implantação", category: "Presença digital", short_description: "Configuração e otimização do perfil da empresa no Google para ser encontrada localmente.", features: "Configuração do perfil\nCategorias e serviços\nDescrição otimizada\nPlano de avaliações\nOrientação de conteúdo local", benefits: "Mais visibilidade nas buscas e no mapa", delivery_days: 7, public_visible: true, tags: "google,seo,local", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-APP-001", name: "App MVP", kind: "service", price: 3999, unit: "projeto", category: "Apps e sistemas", short_description: "Aplicativo inicial validável para transformar uma ideia em produto.", features: "Descoberta e escopo\nFluxo de telas\nMVP funcional\nPainel básico\nPublicação orientada", benefits: "Validação rápida com base para evoluir", delivery_days: 45, public_visible: true, tags: "app,mvp,produto", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-CHAT-001", name: "Chatbot inteligente", kind: "service", price: 1499, unit: "implantação", category: "Automação e IA", short_description: "Chatbot para atendimento, triagem, perguntas frequentes e captação.", features: "Roteiro conversacional\nBase de perguntas\nCaptação de dados\nIntegração com WhatsApp ou site", benefits: "Atendimento mais rápido e disponível", delivery_days: 14, public_visible: true, tags: "chatbot,ia,whatsapp", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-WEB-001", name: "Web app sob medida", kind: "service", price: 4999, unit: "projeto", category: "Apps e sistemas", short_description: "Sistema web personalizado para processos, clientes, equipe e operação.", features: "Arquitetura do produto\nInterface responsiva\nLogin e permissões\nBanco de dados\nDeploy e documentação", benefits: "Processos digitais feitos para sua operação", delivery_days: 45, public_visible: true, tags: "web-app,sistema,software", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-DES-001", name: "Design de produto e identidade digital", kind: "service", price: 1299, unit: "projeto", category: "Design", short_description: "Identidade visual digital e interface para comunicar valor com clareza.", features: "Direção visual\nPaleta e tipografia\nComponentes de interface\nProtótipo navegável\nGuia de aplicação", benefits: "Marca mais consistente e produto mais fácil de usar", delivery_days: 14, public_visible: true, tags: "design,ui,identidade", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-EST-001", name: "Estrutura digital da empresa", kind: "package", price: 899, unit: "implantação", category: "Estratégia digital", short_description: "Organização da presença digital, canais, ofertas e fluxo de atendimento.", features: "Mapa de canais\nOrganização de ofertas\nPadrão de comunicação\nFluxo de leads\nPlano de próximos passos", benefits: "Empresa mais organizada e pronta para vender online", delivery_days: 10, public_visible: true, tags: "estrutura,processos,digital", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-CON-001", name: "Consultoria digital", kind: "service", price: 499, unit: "sessão", category: "Consultoria", short_description: "Orientação prática para tomar decisões digitais com prioridade e clareza.", features: "Reunião de diagnóstico\nAnálise de presença digital\nRecomendações priorizadas\nPlano de ação", benefits: "Decisões melhores sem desperdício de tempo", delivery_days: 2, public_visible: true, tags: "consultoria,digital", billing_type: "one_time", max_installments: 1 },
];

/* Catálogo comercial completo da Focussdev, organizado por seção e pronto para propostas. */
const focussCatalog = [
  { sku: "FOC-IND-001", name: "Landing Page — a partir de R$ 999", kind: "service", price: 999, unit: "projeto", category: "Serviços individuais", short_description: "Landing page profissional para apresentar uma oferta e gerar contatos.", features: "Até 8 seções\nDesign personalizado\nResponsivo\nWhatsApp e formulário\nRedes sociais\nSEO básico\nGoogle Analytics e Meta Pixel\nDomínio, SSL e velocidade\n2 rodadas de alterações", recurrence: "Não", full_description: "Landing page profissional, responsiva para celular, tablet e desktop, com botão de WhatsApp, formulário de contato, redes sociais, SEO básico, Google Analytics, Meta Pixel, configuração de domínio, SSL, otimização de velocidade e 2 rodadas de alterações. Manutenção mensal opcional.", delivery_days: 10, public_visible: true, tags: "landing-page,site,conversão", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-IND-002", name: "Site Profissional — a partir de R$ 1.997", kind: "service", price: 1997, unit: "projeto", category: "Serviços individuais", short_description: "Site profissional completo para fortalecer a presença digital da empresa.", features: "Até 6 páginas\nDesign exclusivo\nResponsividade\nAnimações\nWhatsApp e formulários\nGoogle Maps e redes sociais\nAnalytics, Pixel e SEO\nDomínio, SSL e desempenho", recurrence: "Não", full_description: "Até 6 páginas, incluindo Home, Sobre, Serviços, Contato e páginas personalizadas, com design exclusivo, responsividade, animações, WhatsApp, formulários, Google Maps, redes sociais, Google Analytics, Meta Pixel, SEO inicial, domínio, SSL e otimização de desempenho. Manutenção mensal opcional.", delivery_days: 20, public_visible: true, tags: "site,institucional,design", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-IND-003", name: "Sistema Web — a partir de R$ 3.997", kind: "service", price: 3997, unit: "implantação", category: "Serviços individuais", short_description: "Sistema web sob medida para centralizar processos e operação.", features: "Login e usuários\nClientes e dashboard\nBanco de dados\nPainel administrativo\nPerfis e permissões\nRelatórios, filtros e exportação\nAPIs, integrações e automações\nHistórico de atividades", recurrence: "Opcional", full_description: "Desenvolvimento personalizado com login, cadastro de usuários e clientes, dashboard, banco de dados, painel administrativo, perfis e permissões, relatórios, filtros, exportação de dados, APIs, integrações, automações e histórico. Hospedagem, backups, suporte, monitoramento e atualizações conforme escopo. Recorrência opcional.", delivery_days: 45, public_visible: true, tags: "sistema,web-app,software", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-IND-004", name: "Aplicativo — a partir de R$ 4.997", kind: "service", price: 4997, unit: "implantação", category: "Serviços individuais", short_description: "Aplicativo personalizado com painel, integrações e infraestrutura.", features: "UI/UX\nLogin e cadastro\nPerfil e usuários\nBanco de dados\nPainel administrativo\nAPIs e notificações\nIntegrações e funções personalizadas\nPublicação conforme escopo", recurrence: "Opcional", full_description: "Desenvolvimento do aplicativo, UI/UX, login, cadastro, perfil, banco de dados, painel administrativo, APIs, notificações, gestão de usuários, integrações, funcionalidades personalizadas, preparação e publicação conforme escopo. Infraestrutura, manutenção, atualizações, monitoramento e suporte opcionais.", delivery_days: 60, public_visible: true, tags: "app,mobile,produto", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-IND-005", name: "Chatbot com IA — implantação a partir de R$ 1.997", kind: "service", price: 1997, unit: "implantação", category: "Serviços individuais", short_description: "Atendimento automatizado com IA, base de conhecimento e captação.", features: "IA personalizada\nBase de conhecimento\nFAQ e fluxos\nCaptação e qualificação\nTransferência humana\nCRM e integrações\nHistórico e painel\nMonitoramento e suporte", recurrence: "Sim", full_description: "Chatbot personalizado com IA configurada para a empresa, base de conhecimento, atendimento automático, perguntas frequentes, captação e qualificação de leads, fluxos personalizados, transferência para atendimento humano, CRM quando previsto, integrações, histórico, painel, infraestrutura, manutenção, monitoramento, atualização da base, ajustes de fluxos e suporte. Mensalidade e consumo conforme plano.", delivery_days: 20, public_visible: true, highlighted: true, tags: "chatbot,ia,atendimento", billing_type: "recurring", max_installments: 12 },
  { sku: "FOC-IND-006", name: "Automações — a partir de R$ 1.497", kind: "service", price: 1497, unit: "projeto", category: "Serviços individuais", short_description: "Automação de processos, leads, CRM, mensagens e integrações.", features: "Leads e CRM\nFormulários e planilhas\nE-mail e notificações\nFollow-up\nWebhooks e APIs\nIntegrações entre sistemas\nDistribuição automática\nFluxos personalizados", recurrence: "Depende do projeto", full_description: "Automação de processos, leads, CRM, formulários, planilhas, e-mail, notificações, follow-up, webhooks, APIs, integrações entre sistemas, distribuição automática de leads e fluxos personalizados. Pode ser vendido como projeto único ou implantação mais mensalidade, conforme a infraestrutura utilizada.", delivery_days: 20, public_visible: true, tags: "automação,crm,integration", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-IND-007", name: "Gestão de Tráfego Pago — a partir de R$ 997/mês", kind: "service", price: 997, unit: "mês", category: "Serviços individuais", short_description: "Gestão estratégica de campanhas Meta Ads e Google Ads.", features: "Meta Ads e Google Ads\nPlanejamento e campanhas\nPúblicos e remarketing\nPixel e conversões\nTestes e otimização\nAnálise de resultados\nRelatório mensal", recurrence: "Sim", full_description: "Planejamento, estruturação de campanhas, públicos, remarketing, pixel, conversões, testes de anúncios, otimização, análise de resultados e relatório mensal. Verba de anúncios não inclusa.", public_visible: true, tags: "trafego,meta-ads,google-ads", billing_type: "recurring", max_installments: 1 },
  { sku: "FOC-IND-008", name: "Design para Redes — a partir de R$ 697/mês", kind: "service", price: 697, unit: "mês", category: "Serviços individuais", short_description: "Pacote mensal de peças para redes e campanhas.", features: "12 peças mensais\nPosts e stories\nCarrosséis\nBanners\nCriativos publicitários\nMateriais promocionais\nPadronização e adaptações", recurrence: "Sim", full_description: "12 peças mensais entre posts, stories, carrosséis, banners, criativos publicitários e materiais promocionais, com padronização visual e adaptação para diferentes formatos.", public_visible: true, tags: "design,redes-sociais,criativos", billing_type: "recurring", max_installments: 1 },
  { sku: "FOC-IND-009", name: "Identidade Visual — a partir de R$ 697", kind: "service", price: 697, unit: "projeto", category: "Serviços individuais", short_description: "Identidade visual essencial para apresentar a marca com consistência.", features: "Logo e variações\nPaleta de cores\nTipografia\nElementos visuais\nAplicações básicas\nFoto de perfil\nCapa para redes\nMini guia visual", recurrence: "Não", full_description: "Logo, variações da marca, paleta de cores, tipografia, elementos visuais, aplicações básicas, foto de perfil, capa para redes e mini guia visual.", delivery_days: 10, public_visible: true, tags: "identidade,branding,design", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-IND-010", name: "Google Meu Negócio — R$ 697", kind: "service", price: 697, unit: "implantação", category: "Serviços individuais", short_description: "Configuração e otimização inicial da presença local no Google.", features: "Perfil e categorias\nDescrição e serviços\nProdutos e horários\nLinks e fotos\nInformações comerciais\nEstratégia de avaliações\nOtimização local", recurrence: "Não", full_description: "Configuração e otimização do perfil, categorias, descrição, serviços, produtos, horários, links, fotos e informações comerciais, com organização do perfil, estratégia para avaliações e otimização inicial para buscas locais. Gestão opcional por R$ 397/mês.", delivery_days: 7, public_visible: true, tags: "google,google-meu-negocio,local", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-IND-011", name: "Posicionamento nas Redes Sociais — a partir de R$ 997/mês", kind: "service", price: 997, unit: "mês", category: "Serviços individuais", short_description: "Estratégia, conteúdo e crescimento para redes sociais.", features: "Estratégia e análise\nBio e identidade do perfil\nLinha editorial\nCalendário de conteúdo\n12 conteúdos mensais\nCopy, posts, stories e carrosséis\nConcorrentes e relatório", recurrence: "Sim", full_description: "Estratégia de posicionamento, análise do perfil, bio, identidade, linha editorial, calendário, 12 conteúdos mensais, copy, posts, stories, carrosséis, análise de concorrentes, estratégia de crescimento e relatório mensal.", public_visible: true, tags: "social-media,conteudo,posicionamento", billing_type: "recurring", max_installments: 1 },
  { sku: "FOC-IND-012", name: "Manutenção de Sites — a partir de R$ 297/mês", kind: "service", price: 297, unit: "mês", category: "Serviços individuais", short_description: "Manutenção técnica e acompanhamento contínuo de sites.", features: "Atualizações e correções\nBackup\nMonitoramento\nPequenas alterações\nSuporte técnico\nVerificação de funcionamento", recurrence: "Sim", full_description: "Atualizações, correções, backup, monitoramento, pequenas alterações, suporte técnico e verificação contínua de funcionamento.", public_visible: true, tags: "manutencao,site,suporte", billing_type: "recurring", max_installments: 1 },
  { sku: "FOC-PAC-001", name: "FOCUSS START — R$ 1.997", kind: "package", price: 1997, unit: "pacote", category: "Pacotes Focussdev", short_description: "Presença digital profissional para pequenas empresas.", features: "Landing Page\nWhatsApp e formulário\nGoogle Meu Negócio\nRedes configuradas\nIdentidade visual básica\nAnalytics, Pixel e SEO inicial", recurrence: "Não", full_description: "Landing Page, design responsivo, WhatsApp, formulário, Google Meu Negócio, configuração inicial das redes, identidade visual básica, Google Analytics, Meta Pixel e SEO inicial. Objetivo: colocar uma pequena empresa profissionalmente no digital.", delivery_days: 20, public_visible: true, highlighted: true, tags: "pacote,start,pequena-empresa", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-PAC-002", name: "FOCUSS BUSINESS — R$ 3.497", kind: "package", price: 3497, unit: "pacote", category: "Pacotes Focussdev", short_description: "Site, marca e estrutura comercial para empresas em crescimento.", features: "Site até 6 páginas\nGoogle Meu Negócio\nIdentidade visual\nRedes configuradas\n6 peças sociais\nWhatsApp, formulários e SEO\nAutomação básica de leads", recurrence: "Opcional", full_description: "Site profissional de até 6 páginas, design personalizado, Google Meu Negócio, identidade visual, configuração das redes, 6 peças para redes sociais, WhatsApp, formulários, Google Analytics, Meta Pixel, SEO e automação básica de leads. Mensal opcional para manutenção, conteúdo, design, Google e suporte.", delivery_days: 30, public_visible: true, highlighted: true, tags: "pacote,business,site", billing_type: "one_time", max_installments: 12 },
  { sku: "FOC-PAC-003", name: "FOCUSS VENDAS — implantação R$ 3.997 + R$ 1.297/mês", kind: "package", price: 3997, unit: "implantação", category: "Pacotes Focussdev", short_description: "Estrutura completa de conversão, CRM, chatbot e campanhas.", features: "Landing de conversão\nCopy e design\nTracking, CRM e chatbot\nAutomação de leads\nEstrutura de campanhas\nMeta Ads e Google Ads\nTestes, otimizações e relatórios", recurrence: "Sim", full_description: "Implantação com landing page de alta conversão, copywriting, design, Meta Pixel, Google Analytics, tracking, CRM, chatbot, automação de leads, estrutura de campanhas, remarketing e Google Meu Negócio. Mensal de R$ 1.297 com gestão Meta Ads e Google Ads, otimizações, testes, criativos, relatórios e acompanhamento. Verba de anúncios separada.", delivery_days: 35, public_visible: true, highlighted: true, tags: "pacote,vendas,performance", billing_type: "recurring", max_installments: 12 },
  { sku: "FOC-PAC-004", name: "FOCUSS IA — implantação R$ 4.997+ + R$ 497/mês", kind: "package", price: 4997, unit: "implantação", category: "Pacotes Focussdev", short_description: "IA, CRM e automações para atendimento e vendas.", features: "Chatbot com IA\nBase de conhecimento\nCRM e funil\nQualificação e follow-up\nAutomações e APIs\nAgendamentos e painel\nInfraestrutura e suporte", recurrence: "Sim", full_description: "Implantação com chatbot com IA, base de conhecimento, CRM, funil, qualificação de leads, atendimento automatizado, follow-up, automações, integrações, APIs, agendamentos e painel. Mensal a partir de R$ 497 para infraestrutura, IA, monitoramento, manutenção, atualizações, ajustes, suporte e consumo dentro do plano.", delivery_days: 40, public_visible: true, highlighted: true, tags: "pacote,ia,crm", billing_type: "recurring", max_installments: 12 },
  { sku: "FOC-PAC-005", name: "FOCUSS PERFORMANCE — implantação R$ 5.997 + R$ 1.997/mês", kind: "package", price: 5997, unit: "implantação", category: "Pacotes Focussdev", short_description: "Site, aquisição, automação, conteúdo e gestão de performance.", features: "Site e landing de campanha\nCRM, chatbot e automações\nGoogle Meu Negócio\nAnalytics, Pixel e tracking\nMeta Ads e Google Ads\nDesign, criativos e conteúdo\nRelatórios e otimizações", recurrence: "Sim", full_description: "Implantação com site profissional, landing page de campanha, CRM, chatbot, automações, Google Meu Negócio, estrutura das redes, Analytics, Meta Pixel, tracking e campanhas. Mensal de R$ 1.997 para tráfego, design, criativos, conteúdo, posicionamento, chatbot, automações, otimizações e relatórios.", delivery_days: 45, public_visible: true, highlighted: true, tags: "pacote,performance,marketing", billing_type: "recurring", max_installments: 12 },
  { sku: "FOC-PAC-006", name: "FOCUSS 360 — implantação a partir de R$ 9.997 + R$ 2.997/mês", kind: "package", price: 9997, unit: "implantação", category: "Pacotes Focussdev", short_description: "A operação digital completa: tecnologia, IA, marketing, marca e suporte.", features: "Site premium e landing pages\nCRM, painéis e APIs\nChatbot e automações\nMeta Ads e Google Ads\nTracking e Analytics\nDesign, conteúdo e copy\nSEO, redes e conversão\nSuporte prioritário", recurrence: "Sim", full_description: "Pacote completo com site premium, landing pages, CRM, painéis, integrações, APIs, chatbot com IA, atendimento automatizado, qualificação, follow-up, automações comerciais, Meta Ads, Google Ads, aquisição, tracking, Analytics, design, criativos, conteúdo, copywriting, posicionamento, identidade visual, Google Meu Negócio, SEO inicial, redes sociais, estrutura de conversão, suporte prioritário e acompanhamento estratégico. Mensal a partir de R$ 2.997.", delivery_days: 75, public_visible: true, highlighted: true, tags: "pacote,360,estrategia", billing_type: "recurring", max_installments: 12 },
  { sku: "FOC-DIG-001", name: "Catálogo Digital — R$ 199", kind: "product", price: 199, unit: "projeto", category: "Produtos digitais", short_description: "Catálogo online com produtos, preços, categorias e WhatsApp.", features: "Até 15 produtos\nFotos, nome e descrição\nPreços e categorias\nBotão Tenho interesse\nWhatsApp\nIdentidade e responsividade\nLink próprio", recurrence: "Não", full_description: "Catálogo digital com até 15 produtos, fotos, nome, descrição, preço, categorias, botão Tenho interesse, WhatsApp, identidade da empresa, layout responsivo e link próprio. Upgrade: 30 produtos por R$ 299 ou 50 produtos por R$ 399.", public_visible: true, tags: "catalogo,produto,whatsapp", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-002", name: "Cardápio Digital — R$ 199", kind: "product", price: 199, unit: "projeto", category: "Produtos digitais", short_description: "Cardápio online para restaurantes, lanchonetes e delivery.", features: "Categorias e até 30 itens\nFotos, preços e descrições\nCombos\nWhatsApp\nHorário e endereço\nQR Code para mesas e balcão", recurrence: "Não", full_description: "Cardápio digital com categorias, até 30 itens, fotos, preços, descrições, combos, WhatsApp, horário, endereço e QR Code para mesas ou balcão.", public_visible: true, tags: "cardapio,restaurante,qr-code", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-003", name: "Site One Page — R$ 399", kind: "product", price: 399, unit: "projeto", category: "Produtos digitais", short_description: "Site econômico de uma página baseado nos modelos Focussdev.", features: "Página única\nAté 5 seções\nSobre e serviços\nDiferenciais e contato\nWhatsApp e redes\nResponsivo\nDesign baseado em modelo", recurrence: "Não", full_description: "Site econômico de uma página com até 5 seções, sobre, serviços, diferenciais, contato, WhatsApp, redes sociais, responsividade e design baseado em modelos Focussdev. Não inclui design totalmente personalizado, copy avançada ou tracking completo.", public_visible: true, tags: "site,one-page,entrada", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-004", name: "Site Essencial — R$ 599", kind: "product", price: 599, unit: "projeto", category: "Produtos digitais", short_description: "Primeiro site profissional com até 3 páginas.", features: "Início, Serviços e Contato\nDesign baseado em template\nResponsivo\nWhatsApp e formulário\nRedes sociais\nSEO básico", recurrence: "Não", full_description: "Até 3 páginas: Início, Serviços e Contato, com design baseado em template, responsividade, WhatsApp, formulário, redes sociais e SEO básico.", public_visible: true, tags: "site,essencial,template", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-DIG-005", name: "Site para Autônomo — R$ 399", kind: "product", price: 399, unit: "projeto", category: "Produtos digitais", short_description: "Página profissional para autônomos e prestadores de serviço.", features: "Apresentação\nServiços\nFotos de trabalhos\nÁrea atendida\nDepoimentos\nWhatsApp, redes e formulário", recurrence: "Não", full_description: "Para eletricista, mecânico, advogado, fotógrafo, personal, técnico, pintor, consultor e outros profissionais. Inclui apresentação, serviços, fotos de trabalhos, área atendida, depoimentos, WhatsApp, redes sociais e formulário.", public_visible: true, tags: "autonomo,profissional,servicos", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-006", name: "Página para Imóvel — R$ 199", kind: "product", price: 199, unit: "página", category: "Produtos digitais", short_description: "Página de imóvel com galeria, localização e formulário de interesse.", features: "Fotos e galeria\nDescrição e características\nValor e localização\nWhatsApp\nFormulário de interesse", recurrence: "Não", full_description: "Página para divulgação de imóvel com fotos, descrição, características, valor, localização, galeria, botão de WhatsApp e formulário de interesse. Ideal para corretoras que precisam publicar várias páginas.", public_visible: true, tags: "imovel,imobiliaria,corretor", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-007", name: "Página para Veículo — R$ 199", kind: "product", price: 199, unit: "página", category: "Produtos digitais", short_description: "Página de veículo pronta para venda e divulgação.", features: "Galeria\nModelo, ano e quilometragem\nCaracterísticas\nValor e condições\nWhatsApp e formulário", recurrence: "Não", full_description: "Galeria, modelo, ano, quilometragem, características, valor, condições, WhatsApp e formulário. Boa oferta para garagens e vendedores.", public_visible: true, tags: "veiculo,garagem,vendas", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-008", name: "Página de Evento — R$ 249", kind: "product", price: 249, unit: "página", category: "Produtos digitais", short_description: "Página de evento com programação, inscrição e compartilhamento.", features: "Nome, data e contagem regressiva\nLocalização\nProgramação\nConvidados e palestrantes\nGaleria\nInscrição e WhatsApp\nCompartilhamento", recurrence: "Não", full_description: "Página de evento com nome, data, contagem regressiva, localização, programação, convidados ou palestrantes, galeria, inscrição, WhatsApp e compartilhamento.", public_visible: true, tags: "evento,inscricao,landing", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-009", name: "Convite Digital — R$ 149", kind: "product", price: 149, unit: "projeto", category: "Produtos digitais", short_description: "Convite digital personalizado e compartilhável pelo WhatsApp.", features: "Data e horário\nLocalização\nContagem regressiva\nConfirmação de presença\nBotão para Maps\nCompartilhamento", recurrence: "Não", full_description: "Convite personalizado com data, horário, localização, contagem regressiva, confirmação de presença, botão para Maps e compartilhamento por WhatsApp.", public_visible: true, tags: "convite,eventos,whatsapp", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-010", name: "Portfólio Online — R$ 249", kind: "product", price: 249, unit: "projeto", category: "Produtos digitais", short_description: "Portfólio online para mostrar projetos, experiência e serviços.", features: "Apresentação\nProjetos e galeria\nServiços\nExperiência\nContato, redes e WhatsApp", recurrence: "Não", full_description: "Apresentação, projetos, galeria, serviços, experiência, contato, redes sociais e WhatsApp.", public_visible: true, tags: "portfolio,criativo,profissional", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-011", name: "Currículo Online — R$ 149", kind: "product", price: 149, unit: "projeto", category: "Produtos digitais", short_description: "Currículo online profissional com opção de download.", features: "Foto e apresentação\nExperiência e formação\nCompetências\nProjetos\nRedes profissionais\nContato\nDownload do currículo", recurrence: "Não", full_description: "Foto, apresentação, experiência, formação, competências, projetos, redes profissionais, contato e download do currículo fornecido pelo cliente.", public_visible: true, tags: "curriculo,carreira,portfolio", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-012", name: "Mini Loja — R$ 399", kind: "product", price: 399, unit: "projeto", category: "Produtos digitais", short_description: "Mini loja com catálogo, busca, carrinho simples e pedido pelo WhatsApp.", features: "Até 20 produtos\nCategorias e busca\nFotos, valores e descrições\nCarrinho simples\nPedido direcionado para WhatsApp", recurrence: "Não", full_description: "Mini loja sem e-commerce completo: até 20 produtos, categorias, fotos, valores, descrições, busca, carrinho simples e pedido direcionado para WhatsApp. E-commerce completo pode ser oferecido como upgrade.", public_visible: true, tags: "loja,carrinho,whatsapp", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-DIG-013", name: "Página Delivery — R$ 299", kind: "product", price: 299, unit: "projeto", category: "Produtos digitais", short_description: "Página de delivery com produtos, combos e pedido pelo WhatsApp.", features: "Produtos e combos\nPromoções\nHorários\nTaxas informativas\nRegião atendida\nLocalização\nWhatsApp e botão de pedido", recurrence: "Não", full_description: "Produtos, combos, promoções, horários, taxas informativas, região atendida, localização, WhatsApp e botão de pedido.", public_visible: true, tags: "delivery,restaurante,pedidos", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-014", name: "Página de Agendamento — R$ 249+", kind: "product", price: 249, unit: "projeto", category: "Produtos digitais", short_description: "Página para apresentar serviços e receber solicitações de agendamento.", features: "Serviços e profissionais\nHorários\nSolicitação de agendamento\nDados do cliente\nWhatsApp e confirmação", recurrence: "Depende da ferramenta", full_description: "Serviços, profissionais, horários, solicitação ou agendamento, dados do cliente, WhatsApp e confirmação. O valor pode variar conforme a ferramenta utilizada.", public_visible: true, tags: "agendamento,servicos,agenda", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-015", name: "Apresentação Empresarial Online — R$ 249", kind: "product", price: 249, unit: "projeto", category: "Produtos digitais", short_description: "Apresentação comercial da empresa transformada em página online.", features: "Quem somos\nServiços e diferenciais\nClientes e projetos\nDepoimentos\nContato e WhatsApp\nCTA para orçamento", recurrence: "Não", full_description: "Quem somos, serviços, diferenciais, clientes, projetos, depoimentos, contato, WhatsApp e CTA para orçamento.", public_visible: true, tags: "empresa,apresentacao,comercial", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-DIG-016", name: "Gerador de Orçamento Simples — R$ 399", kind: "product", price: 399, unit: "projeto", category: "Produtos digitais", short_description: "Ferramenta simples para montar e compartilhar orçamentos.", features: "Cadastro de cliente\nSeleção de serviços\nQuantidade e valores\nTotal\nDados da empresa\nGeração e compartilhamento", recurrence: "Não", full_description: "Cadastro de cliente, seleção de serviços, quantidade, valores, total, dados da empresa, geração de orçamento e compartilhamento.", public_visible: true, tags: "orcamento,proposta,ferramenta", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-DIG-017", name: "Página de Avaliações — R$ 149", kind: "product", price: 149, unit: "projeto", category: "Produtos digitais", short_description: "Página e QR Code para incentivar avaliações da empresa.", features: "QR Code\nPágina personalizada\nIdentidade da empresa\nOrientação para avaliação\nLinks para plataformas\nWhatsApp", recurrence: "Não", full_description: "QR Code, página personalizada, identidade da empresa, orientação para avaliação, links para plataformas configuradas e botão de WhatsApp.", public_visible: true, tags: "avaliacoes,qr-code,reputacao", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-EXP-001", name: "Comércio Express — R$ 399", kind: "package", price: 399, unit: "pacote", category: "Pacotinhos Express", short_description: "Catálogo digital, página da empresa, WhatsApp e QR Code.", features: "Catálogo digital\nPágina da empresa\nWhatsApp\nQR Code", recurrence: "Não", full_description: "Catálogo digital + página da empresa + WhatsApp + QR Code.", public_visible: true, tags: "express,comercio,catalogo", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-EXP-002", name: "Restaurante Express — R$ 399", kind: "package", price: 399, unit: "pacote", category: "Pacotinhos Express", short_description: "Cardápio digital com QR Code, contato, localização e WhatsApp.", features: "Cardápio digital\nQR Code\nPágina de contato e localização\nWhatsApp", recurrence: "Não", full_description: "Cardápio digital + QR Code + página de contato e localização + WhatsApp.", public_visible: true, tags: "express,restaurante,cardapio", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-EXP-003", name: "Autônomo Express — R$ 499", kind: "package", price: 499, unit: "pacote", category: "Pacotinhos Express", short_description: "Site One Page, portfólio, formulário e WhatsApp para autônomos.", features: "Site One Page\nPortfólio\nFormulário\nWhatsApp", recurrence: "Não", full_description: "Site One Page + portfólio + formulário + WhatsApp.", public_visible: true, tags: "express,autonomo,site", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-EXP-004", name: "Corretor Express — R$ 499", kind: "package", price: 499, unit: "pacote", category: "Pacotinhos Express", short_description: "Página profissional com até 3 páginas de imóveis e WhatsApp.", features: "Página profissional\nAté 3 páginas de imóveis\nWhatsApp", recurrence: "Não", full_description: "Página profissional + até 3 páginas de imóveis + WhatsApp.", public_visible: true, tags: "express,corretor,imoveis", billing_type: "one_time", max_installments: 3 },
  { sku: "FOC-EXP-005", name: "Empresa Express — R$ 699", kind: "package", price: 699, unit: "pacote", category: "Pacotinhos Express", short_description: "Site simples, apresentação empresarial, formulário, WhatsApp e SEO.", features: "Site de 3 páginas\nApresentação empresarial\nFormulário\nWhatsApp\nSEO básico", recurrence: "Não", full_description: "Site simples de 3 páginas + apresentação empresarial + formulário + WhatsApp + SEO básico.", public_visible: true, tags: "express,empresa,site", billing_type: "one_time", max_installments: 6 },
  { sku: "FOC-EXP-006", name: "Vendas Express — R$ 799", kind: "package", price: 799, unit: "pacote", category: "Pacotinhos Express", short_description: "Site One Page, catálogo, orçamento, WhatsApp e captação básica.", features: "Site One Page\nCatálogo\nFormulário de orçamento\nWhatsApp\nCaptação básica", recurrence: "Não", full_description: "Site One Page + catálogo + formulário de orçamento + WhatsApp + estrutura básica de captação.", public_visible: true, highlighted: true, tags: "express,vendas,conversao", billing_type: "one_time", max_installments: 6 }
];

const formFields = {
  capture: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "phone", label: "WhatsApp", type: "tel", required: true }, { name: "interest", label: "O que você procura?", type: "textarea", required: true }],
  quote: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "company", label: "Empresa", type: "text" }, { name: "budget", label: "Faixa de investimento", type: "select", options: ["Até R$ 1.000", "R$ 1.000 a R$ 5.000", "Acima de R$ 5.000"] }, { name: "scope", label: "Descreva o que precisa", type: "textarea", required: true }],
  briefing: [{ name: "project", label: "Nome do projeto", type: "text", required: true }, { name: "objective", label: "Objetivo", type: "textarea", required: true }, { name: "audience", label: "Público", type: "text" }, { name: "references", label: "Referências", type: "textarea" }, { name: "deadline", label: "Prazo desejado", type: "date" }],
  support: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "subject", label: "Assunto", type: "text", required: true }, { name: "priority", label: "Prioridade", type: "select", options: ["Baixa", "Normal", "Alta", "Urgente"] }, { name: "description", label: "Como podemos ajudar?", type: "textarea", required: true }],
  satisfaction: [{ name: "name", label: "Nome", type: "text" }, { name: "score", label: "Nota de 0 a 10", type: "number", required: true }, { name: "what_went_well", label: "O que foi bom?", type: "textarea" }, { name: "improvement", label: "O que podemos melhorar?", type: "textarea" }],
  onboarding: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "company", label: "Empresa", type: "text" }, { name: "goals", label: "Objetivos para os próximos 90 dias", type: "textarea", required: true }, { name: "access_notes", label: "Acessos e observações", type: "textarea" }],
};

const starterForms = Object.entries(formFields).map(([kind, schema]) => ({ name: `[Biblioteca] ${({ capture: "Captação de lead", quote: "Pedido de orçamento", briefing: "Briefing de projeto", support: "Solicitação de suporte", satisfaction: "Pesquisa de satisfação", onboarding: "Onboarding de cliente" })[kind]}`, kind, schema, automation_config: { create: kind === "support" ? "ticket" : kind === "quote" ? "opportunity" : "lead", notify: "responsible" }, status: "draft" }));
const focussForms = [
  { name: "[Focussdev] Cadastro rápido de cliente", kind: "capture", schema: [{ name: "name", label: "Nome ou empresa", type: "text", required: true }, { name: "document", label: "CPF/CNPJ", type: "text" }, { name: "email", label: "E-mail", type: "email" }, { name: "phone", label: "WhatsApp", type: "tel" }, { name: "address", label: "Endereço", type: "text" }, { name: "need", label: "Necessidade principal", type: "textarea" }], automation_config: { create: "client", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Briefing de site ou landing page", kind: "briefing", schema: [{ name: "business", label: "Nome e segmento da empresa", type: "text", required: true }, { name: "objective", label: "Objetivo do projeto", type: "textarea", required: true }, { name: "audience", label: "Público-alvo", type: "textarea" }, { name: "services", label: "Serviços ou produtos", type: "textarea" }, { name: "references", label: "Referências e concorrentes", type: "textarea" }, { name: "content", label: "Materiais disponíveis", type: "textarea" }, { name: "deadline", label: "Prazo desejado", type: "text" }], automation_config: { create: "briefing", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Briefing de sistema ou aplicativo", kind: "briefing", schema: [{ name: "product", label: "Nome do produto", type: "text", required: true }, { name: "problem", label: "Problema que resolve", type: "textarea", required: true }, { name: "users", label: "Quem usará", type: "textarea" }, { name: "features", label: "Funcionalidades desejadas", type: "textarea" }, { name: "integrations", label: "Integrações necessárias", type: "textarea" }, { name: "references", label: "Referências", type: "textarea" }, { name: "budget", label: "Faixa de investimento", type: "text" }], automation_config: { create: "briefing", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Briefing de identidade visual", kind: "briefing", schema: [{ name: "brand", label: "Nome da marca", type: "text", required: true }, { name: "segment", label: "Segmento", type: "text" }, { name: "positioning", label: "Como a marca deve ser percebida", type: "textarea" }, { name: "colors", label: "Cores ou referências", type: "text" }, { name: "references", label: "Marcas de referência", type: "textarea" }, { name: "applications", label: "Onde a identidade será usada", type: "textarea" }], automation_config: { create: "briefing", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Solicitação de manutenção", kind: "support", schema: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "project", label: "Site ou projeto", type: "text", required: true }, { name: "priority", label: "Prioridade", type: "select", options: ["Baixa", "Normal", "Alta", "Urgente"] }, { name: "description", label: "O que precisa ser ajustado", type: "textarea", required: true }, { name: "attachment", label: "Link ou anexo de referência", type: "text" }], automation_config: { create: "ticket", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Aprovação de entrega", kind: "satisfaction", schema: [{ name: "decision", label: "Decisão", type: "select", options: ["Aprovado", "Aprovado com observações", "Solicitar ajustes"] }, { name: "observations", label: "Observações", type: "textarea" }, { name: "name", label: "Nome do responsável", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }], automation_config: { create: "approval", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Solicitação de conteúdo e tráfego", kind: "capture", schema: [{ name: "campaign", label: "Campanha ou período", type: "text", required: true }, { name: "objective", label: "Objetivo", type: "textarea", required: true }, { name: "offer", label: "Oferta", type: "textarea" }, { name: "audience", label: "Público", type: "textarea" }, { name: "assets", label: "Materiais disponíveis", type: "textarea" }, { name: "approval", label: "Responsável pela aprovação", type: "text" }], automation_config: { create: "task", notify: "responsible" }, status: "published" },
  { name: "[Focussdev] Onboarding de chatbot IA", kind: "onboarding", schema: [{ name: "business", label: "Empresa e segmento", type: "text", required: true }, { name: "tone", label: "Tom de voz", type: "text" }, { name: "faq", label: "Perguntas frequentes", type: "textarea" }, { name: "services", label: "Serviços e preços", type: "textarea" }, { name: "handoff", label: "Quando transferir para humano", type: "textarea" }, { name: "channels", label: "Canais de atendimento", type: "text" }, { name: "accesses", label: "Acessos ou links necessários", type: "textarea" }], automation_config: { create: "task", notify: "responsible" }, status: "published" }
];

const starterAutomations = [
  ["[Biblioteca] Novo lead → tarefa de contato", "lead_created", "create_task", "Comercial", "Criar uma tarefa de primeiro contato para cada novo lead.", [{ field: "status", operator: "equals", value: "new" }], [{ type: "task", title: "Entrar em contato com {{lead_name}}", due_in_hours: 4 }]],
  ["[Biblioteca] Lead sem resposta → follow-up", "lead_no_response", "create_followup", "Comercial", "Criar follow-up quando o lead ficar sem resposta.", [], [{ type: "followup", days: 2 }]],
  ["[Biblioteca] Proposta aprovada → criar projeto", "proposal_approved", "create_project", "Operação", "Preparar o projeto assim que a proposta for aprovada.", [], [{ type: "project", template: "[Biblioteca] Projeto de entrega padrão" }]],
  ["[Biblioteca] Contrato assinado → onboarding", "contract_signed", "send_onboarding", "Operação", "Enviar o formulário de onboarding após a assinatura.", [], [{ type: "form", name: "[Biblioteca] Onboarding de cliente" }]],
  ["[Biblioteca] Tarefa vencendo → avisar responsável", "task_due_soon", "notify_responsible", "Operação", "Avisar o responsável antes do vencimento.", [], [{ type: "notification", template: "[Biblioteca] Notificação interna" }]],
  ["[Biblioteca] Cobrança vencida → criar follow-up", "receivable_overdue", "create_followup", "Financeiro", "Criar uma ação de cobrança para títulos vencidos.", [], [{ type: "followup", template: "[Biblioteca] Cobrança cordial" }]],
  ["[Biblioteca] Ticket criado → notificar atendimento", "ticket_created", "notify", "Atendimento", "Avisar a equipe quando uma nova solicitação chegar.", [], [{ type: "channel", value: "internal" }]],
  ["[Biblioteca] Projeto concluído → pesquisa", "project_created", "request_satisfaction", "Experiência", "Disponibilizar pesquisa após a conclusão do ciclo.", [], [{ type: "form", name: "[Biblioteca] Pesquisa de satisfação" }]],
];

const focussAutomations = [
  ["[Focussdev] Cliente cadastrado → enviar onboarding", "client_created", "send_onboarding", "Atendimento", "Preparar o cliente recém-cadastrado para iniciar o projeto.", [], [{ type: "form", name: "[Focussdev] Briefing de site ou landing page" }]],
  ["[Focussdev] Entrega publicada → solicitar aprovação", "delivery_published", "request_approval", "Operação", "Solicitar aprovação sempre que uma entrega for publicada.", [], [{ type: "form", name: "[Focussdev] Aprovação de entrega" }]],
  ["[Focussdev] Ticket urgente → notificar responsável", "ticket_created", "notify", "Atendimento", "Avisar imediatamente quando o ticket tiver prioridade alta ou urgente.", [{ field: "priority", operator: "in", value: ["high", "urgent", "Alta", "Urgente"] }], [{ type: "channel", value: "internal" }]],
  ["[Focussdev] Recebimento confirmado → atualizar cliente", "payment_received", "notify", "Financeiro", "Registrar a confirmação de recebimento e avisar o responsável comercial.", [], [{ type: "channel", value: "internal" }]],
  ["[Focussdev] Projeto sem atividade → criar follow-up", "project_inactive", "create_followup", "Operação", "Criar uma ação quando um projeto ficar sem movimentação.", [], [{ type: "followup", days: 2 }]],
  ["[Focussdev] Formulário comercial → criar oportunidade", "form_submitted", "create_opportunity", "Transformar respostas comerciais em oportunidade para acompanhamento.", [{ field: "kind", operator: "in", value: ["capture", "quote"] }], [{ type: "opportunity" }]],
  ["[Focussdev] Manutenção vencendo → lembrar renovação", "subscription_due", "notify", "Financeiro", "Lembrar a equipe sobre contratos e manutenções recorrentes próximos do vencimento.", [], [{ type: "channel", value: "internal" }]]
];

export async function ensureStarterLibrary(pool, organizationId) {
  if (!pool?.connect || !organizationId) return { templates: 0, catalog: 0, forms: 0, automations: 0 };
  const client = await pool.connect();
  const counts = { templates: 0, catalog: 0, forms: 0, automations: 0 };
  try {
    await client.query("begin");
    await client.query("select pg_advisory_xact_lock(hashtext($1))", [`starter-library:${organizationId}`]);
    for (const [kind, name, category, subject, body, variables] of [...starterTemplates, ...focussTemplates]) {
      const q = await client.query("select 1 from templates where organization_id=$1 and name=$2", [organizationId, name]);
      if (!q.rowCount) { await client.query("insert into templates (organization_id,kind,name,body,category,subject,language,variables,favorite,is_default,version) values ($1,$2,$3,$4,$5,$6,'pt-BR',$7,false,false,1)", [organizationId, kind, name, body, category, subject || null, variables]); counts.templates += 1; }
    }
    for (const item of [...starterCatalog, ...focussCatalog]) {
      const q = await client.query("select 1 from catalog_items where organization_id=$1 and sku=$2", [organizationId, item.sku]);
      if (!q.rowCount) { const fields = Object.keys(item), values = fields.map((field) => item[field]); await client.query(`insert into catalog_items (organization_id,${fields.join(",")}) values ($1,${fields.map((_, index) => `$${index + 2}`).join(",")})`, [organizationId, ...values]); counts.catalog += 1; }
    }
    for (const item of [...starterForms, ...focussForms]) {
      const q = await client.query("select 1 from forms where organization_id=$1 and name=$2", [organizationId, item.name]);
      if (!q.rowCount) { await client.query("insert into forms (organization_id,name,kind,schema,automation_config,status) values ($1,$2,$3,$4,$5,$6)", [organizationId, item.name, item.kind, JSON.stringify(item.schema), JSON.stringify(item.automation_config), item.status]); counts.forms += 1; }
    }
    for (const [name, trigger, action, category, description, conditions, actions] of [...starterAutomations, ...focussAutomations]) {
      const q = await client.query("select 1 from automations where organization_id=$1 and name=$2", [organizationId, name]);
      if (!q.rowCount) { await client.query("insert into automations (organization_id,name,trigger,action,config,active,status,category,description,conditions,actions,avoid_duplicates) values ($1,$2,$3,$4,'{}'::jsonb,false,'paused',$5,$6,$7,$8,true)", [organizationId, name, trigger, action, category, description, JSON.stringify(conditions), JSON.stringify(actions)]); counts.automations += 1; }
    }
    await client.query("commit");
    return counts;
  } catch (error) { await client.query("rollback").catch(() => {}); throw error; }
  finally { client.release(); }
}

export { starterTemplates, starterCatalog, starterForms, starterAutomations, focussCatalog, focussTemplates, focussForms, focussAutomations };
