const starterTemplates = [
  ["proposal", "[Biblioteca] Proposta comercial completa", "Comercial", "Proposta comercial — {{client_name}}", "Olá, {{client_name}}!\n\nÉ um prazer apresentar esta proposta para {{project_name}}.\n\nEscopo\n{{scope}}\n\nInvestimento: {{total_amount}}\nPrazo: {{delivery_days}} dias\nValidade: {{valid_until}}\n\nSe fizer sentido, responda a esta mensagem para avançarmos.", "client_name,project_name,scope,total_amount,delivery_days,valid_until"],
  ["contract", "[Biblioteca] Contrato de prestação de serviços", "Jurídico", "Contrato — {{project_name}}", "CONTRATO DE PRESTAÇÃO DE SERVIÇOS\n\nCONTRATANTE: {{client_name}}\nCONTRATADA: {{company_name}}\n\n1. OBJETO\n{{scope}}\n\n2. PRAZO E INVESTIMENTO\nPrazo: {{delivery_days}} dias. Valor: {{total_amount}}.\n\n3. RESPONSABILIDADES\nAs partes concordam com o escopo, prazos e critérios de aceite descritos neste documento.", "client_name,company_name,scope,delivery_days,total_amount"],
  ["project", "[Biblioteca] Projeto de entrega padrão", "Operação", "Projeto — {{project_name}}", "Objetivo: {{objective}}\nCliente: {{client_name}}\nResponsável: {{responsible}}\nPrazo: {{delivery_days}} dias\n\nEntregas:\n{{deliverables}}\n\nCritério de aceite:\n{{acceptance_criteria}}", "project_name,objective,client_name,responsible,delivery_days,deliverables,acceptance_criteria"],
  ["task", "[Biblioteca] Tarefa operacional", "Operação", "{{task_title}}", "Objetivo: {{objective}}\nContexto: {{context}}\nPrazo: {{due_date}}\nResponsável: {{responsible}}\nCritério de conclusão: {{done_criteria}}", "task_title,objective,context,due_date,responsible,done_criteria"],
  ["checklist", "[Biblioteca] Checklist de início de projeto", "Operação", "Checklist de kickoff", "[ ] Confirmar escopo e prioridades\n[ ] Validar acessos e materiais\n[ ] Definir responsáveis\n[ ] Agendar kickoff\n[ ] Registrar riscos e dependências\n[ ] Confirmar primeira entrega", ""],
  ["charge", "[Biblioteca] Cobrança cordial", "Financeiro", "Lembrete de pagamento — {{invoice_number}}", "Olá, {{client_name}}!\n\nPassando para lembrar que a cobrança {{invoice_number}}, no valor de {{amount}}, vence em {{due_date}}.\n\nSe já realizou o pagamento, desconsidere esta mensagem. Se precisar de ajuda, fale conosco.", "client_name,invoice_number,amount,due_date"],
  ["followup", "[Biblioteca] Follow-up após proposta", "Comercial", "Podemos avançar, {{client_name}}?", "Olá, {{client_name}}!\n\nQueria saber se conseguiu avaliar a proposta sobre {{project_name}}. Posso esclarecer alguma dúvida ou ajustar algum ponto para seguirmos?\n\nFico à disposição.", "client_name,project_name"],
  ["support", "[Biblioteca] Resposta de suporte inicial", "Atendimento", "Recebemos sua solicitação", "Olá, {{client_name}}!\n\nRecebemos sua solicitação {{ticket_number}} e ela já está com nossa equipe.\n\nPrazo estimado de retorno: {{sla}}.\nResponsável: {{responsible}}.\n\nSe tiver novas informações, responda nesta mesma conversa.", "client_name,ticket_number,sla,responsible"],
  ["ticket", "[Biblioteca] Registro de ticket", "Atendimento", "Ticket {{ticket_number}} — {{subject}}", "Assunto: {{subject}}\nCliente: {{client_name}}\nPrioridade: {{priority}}\nDescrição:\n{{description}}\n\nPróxima ação: {{next_action}}", "ticket_number,subject,client_name,priority,description,next_action"],
  ["briefing", "[Biblioteca] Briefing de projeto", "Planejamento", "Briefing — {{project_name}}", "Contexto do negócio:\n{{business_context}}\n\nObjetivo principal:\n{{objective}}\n\nPúblico:\n{{audience}}\n\nReferências:\n{{references}}\n\nRestrições e preferências:\n{{constraints}}\n\nPrazo desejado: {{deadline}}", "project_name,business_context,objective,audience,references,constraints,deadline"],
  ["delivery_term", "[Biblioteca] Termos de entrega", "Operação", "Termos de entrega — {{project_name}}", "A entrega será realizada em até {{delivery_days}} dias úteis após o recebimento de todos os materiais necessários.\n\nInclui: {{included_scope}}\nNão inclui: {{excluded_scope}}\nRevisões previstas: {{revisions_count}}\nCritério de aceite: {{acceptance_criteria}}", "project_name,delivery_days,included_scope,excluded_scope,revisions_count,acceptance_criteria"],
  ["report", "[Biblioteca] Relatório mensal", "Gestão", "Relatório de resultados — {{period}}", "Resumo executivo\n{{summary}}\n\nIndicadores\n{{metrics}}\n\nEntregas realizadas\n{{deliveries}}\n\nPróximos passos\n{{next_steps}}\n\nPontos de atenção\n{{risks}}", "period,summary,metrics,deliveries,next_steps,risks"],
  ["notification", "[Biblioteca] Notificação interna", "Gestão", "Atenção: {{event_name}}", "{{event_name}}\n\nCliente: {{client_name}}\nResponsável: {{responsible}}\nPrazo: {{due_date}}\n\nAcesse o FocusApp para consultar os detalhes e registrar a próxima ação.", "event_name,client_name,responsible,due_date"],
  ["email", "[Biblioteca] E-mail institucional", "Comunicação", "{{subject}}", "Olá, {{client_name}}!\n\n{{message}}\n\nSe precisar de qualquer coisa, estamos à disposição.\n\nAtenciosamente,\n{{company_name}}", "subject,client_name,message,company_name"],
  ["message", "[Biblioteca] Mensagem curta de atendimento", "Comunicação", "", "Olá, {{client_name}}! {{message}} Se precisar, estou por aqui.", "client_name,message"],
  ["whatsapp", "[Biblioteca] WhatsApp de confirmação", "Comunicação", "", "Olá, {{client_name}}! Confirmando nosso {{appointment_type}} para {{appointment_date}} às {{appointment_time}}. Pode confirmar?", "client_name,appointment_type,appointment_date,appointment_time"],
];

const starterCatalog = [
  { sku: "BIB-SVC-001", name: "Consultoria estratégica", kind: "service", price: 1800, unit: "projeto", category: "Consultoria", short_description: "Diagnóstico, prioridades e plano de ação para o próximo ciclo.", full_description: "Mapeamento do cenário atual, definição de objetivos, plano de 30 dias e reunião de apresentação.", features: "Diagnóstico inicial\nPlano de ação priorizado\nReunião executiva", benefits: "Mais clareza para decidir\nFoco no que gera resultado", delivery_days: 7, modules_count: 3, revisions_count: 1, public_visible: true, highlighted: true, tags: "consultoria,estratégia", billing_type: "one_time", max_installments: 3 },
  { sku: "BIB-SVC-002", name: "Implantação FocusApp", kind: "service", price: 3200, unit: "implantação", category: "Implantação", short_description: "Configuração do workspace, processos, templates e treinamento da equipe.", full_description: "Organização do workspace, cadastro da biblioteca inicial, criação dos fluxos e treinamento de uso.", features: "Configuração do workspace\nImportação de dados essenciais\nTreinamento da equipe", benefits: "Operação organizada desde o primeiro dia\nMenos retrabalho", delivery_days: 10, modules_count: 5, revisions_count: 2, public_visible: true, tags: "implantação,setup", billing_type: "one_time", max_installments: 6 },
  { sku: "BIB-PLN-001", name: "Plano Essencial", kind: "plan", price: 149, unit: "mês", category: "Planos", short_description: "A base para organizar clientes, tarefas e financeiro.", features: "CRM\nTarefas e projetos\nAgenda\nRelatórios básicos", limits: "Até 3 usuários\nAté 100 clientes ativos", benefits: "Visão centralizada da operação", recurrence: "monthly", term_days: 30, public_visible: true, billing_type: "recurring", max_installments: 1 },
  { sku: "BIB-PLN-002", name: "Plano Profissional", kind: "subscription", price: 349, unit: "mês", category: "Planos", short_description: "Automação, catálogo, formulários e gestão completa.", features: "Tudo do Essencial\nAutomações\nCatálogo público\nFormulários\nPortal do cliente", limits: "Até 10 usuários\nClientes ilimitados", benefits: "Escala com processos previsíveis", recurrence: "monthly", term_days: 30, public_visible: true, highlighted: true, billing_type: "recurring", max_installments: 1 },
  { sku: "BIB-PKG-001", name: "Pacote comercial completo", kind: "package", price: 2490, unit: "pacote", category: "Pacotes", short_description: "Consultoria, proposta, follow-ups e configuração do funil.", features: "Diagnóstico comercial\nTemplates de proposta\nFunil configurado\nSequência de follow-up", benefits: "Mais velocidade para vender\nProcesso comercial replicável", delivery_days: 12, public_visible: true, tags: "comercial,vendas", billing_type: "one_time", max_installments: 6 },
  { sku: "BIB-ADD-001", name: "Módulo de automações", kind: "addon", price: 99, unit: "mês", category: "Adicionais", short_description: "Ative fluxos prontos para reduzir tarefas manuais.", features: "Alertas de prazo\nFollow-up automático\nNotificações internas", benefits: "Economia de tempo\nMenos esquecimentos", recurrence: "monthly", term_days: 30, public_visible: true, tags: "automação", billing_type: "recurring", max_installments: 1 },
];

const formFields = {
  capture: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "phone", label: "WhatsApp", type: "tel", required: true }, { name: "interest", label: "O que você procura?", type: "textarea", required: true }],
  quote: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "company", label: "Empresa", type: "text" }, { name: "budget", label: "Faixa de investimento", type: "select", options: ["Até R$ 1.000", "R$ 1.000 a R$ 5.000", "Acima de R$ 5.000"] }, { name: "scope", label: "Descreva o que precisa", type: "textarea", required: true }],
  briefing: [{ name: "project", label: "Nome do projeto", type: "text", required: true }, { name: "objective", label: "Objetivo", type: "textarea", required: true }, { name: "audience", label: "Público", type: "text" }, { name: "references", label: "Referências", type: "textarea" }, { name: "deadline", label: "Prazo desejado", type: "date" }],
  support: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "subject", label: "Assunto", type: "text", required: true }, { name: "priority", label: "Prioridade", type: "select", options: ["Baixa", "Normal", "Alta", "Urgente"] }, { name: "description", label: "Como podemos ajudar?", type: "textarea", required: true }],
  satisfaction: [{ name: "name", label: "Nome", type: "text" }, { name: "score", label: "Nota de 0 a 10", type: "number", required: true }, { name: "what_went_well", label: "O que foi bom?", type: "textarea" }, { name: "improvement", label: "O que podemos melhorar?", type: "textarea" }],
  onboarding: [{ name: "name", label: "Nome", type: "text", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "company", label: "Empresa", type: "text" }, { name: "goals", label: "Objetivos para os próximos 90 dias", type: "textarea", required: true }, { name: "access_notes", label: "Acessos e observações", type: "textarea" }],
};

const starterForms = Object.entries(formFields).map(([kind, schema]) => ({ name: `[Biblioteca] ${({ capture: "Captação de lead", quote: "Pedido de orçamento", briefing: "Briefing de projeto", support: "Solicitação de suporte", satisfaction: "Pesquisa de satisfação", onboarding: "Onboarding de cliente" })[kind]}`, kind, schema, automation_config: { create: kind === "support" ? "ticket" : kind === "quote" ? "opportunity" : "lead", notify: "responsible" }, status: "draft" }));
const starterAutomations = [
  ["[Biblioteca] Novo lead → tarefa de contato", "lead_created", "create_task", "Comercial", "Criar uma tarefa de primeiro contato para cada novo lead.", [{ field: "status", operator: "equals", value: "new" }], [{ type: "task", title: "Entrar em contato com {{lead_name}}", due_in_hours: 4 }]],
  ["[Biblioteca] Lead sem resposta → follow-up", "lead_no_response", "create_followup", "Comercial", "Criar follow-up quando o lead ficar sem resposta.", [], [{ type: "followup", days: 2 }]],
  ["[Biblioteca] Proposta aprovada → criar projeto", "proposal_approved", "create_project", "Operação", "Preparar o projeto assim que a proposta for aprovada.", [], [{ type: "project", template: "[Biblioteca] Projeto de entrega padrão" }]],
  ["[Biblioteca] Contrato assinado → onboarding", "contract_signed", "send_onboarding", "Operação", "Enviar o formulário de onboarding após a assinatura.", [], [{ type: "form", name: "[Biblioteca] Onboarding de cliente" }]],
  ["[Biblioteca] Tarefa vencendo → avisar responsável", "task_due_soon", "notify_responsible", "Operação", "Avisar o responsável antes do vencimento.", [], [{ type: "notification", template: "[Biblioteca] Notificação interna" }]],
  ["[Biblioteca] Cobrança vencida → criar follow-up", "receivable_overdue", "create_followup", "Financeiro", "Criar uma ação de cobrança para títulos vencidos.", [], [{ type: "followup", template: "[Biblioteca] Cobrança cordial" }]],
  ["[Biblioteca] Ticket criado → notificar atendimento", "ticket_created", "notify", "Atendimento", "Avisar a equipe quando uma nova solicitação chegar.", [], [{ type: "channel", value: "internal" }]],
  ["[Biblioteca] Projeto concluído → pesquisa", "project_created", "request_satisfaction", "Experiência", "Disponibilizar pesquisa após a conclusão do ciclo.", [], [{ type: "form", name: "[Biblioteca] Pesquisa de satisfação" }]],
];

export async function ensureStarterLibrary(pool, organizationId) {
  if (!pool?.connect || !organizationId) return { templates: 0, catalog: 0, forms: 0, automations: 0 };
  const client = await pool.connect();
  const counts = { templates: 0, catalog: 0, forms: 0, automations: 0 };
  try {
    await client.query("begin");
    await client.query("select pg_advisory_xact_lock(hashtext($1))", [`starter-library:${organizationId}`]);
    for (const [kind, name, category, subject, body, variables] of starterTemplates) {
      const q = await client.query("select 1 from templates where organization_id=$1 and name=$2", [organizationId, name]);
      if (!q.rowCount) { await client.query("insert into templates (organization_id,kind,name,body,category,subject,language,variables,favorite,is_default,version) values ($1,$2,$3,$4,$5,$6,'pt-BR',$7,false,false,1)", [organizationId, kind, name, body, category, subject || null, variables]); counts.templates += 1; }
    }
    for (const item of starterCatalog) {
      const q = await client.query("select 1 from catalog_items where organization_id=$1 and sku=$2", [organizationId, item.sku]);
      if (!q.rowCount) { const fields = Object.keys(item), values = fields.map((field) => item[field]); await client.query(`insert into catalog_items (organization_id,${fields.join(",")}) values ($1,${fields.map((_, index) => `$${index + 2}`).join(",")})`, [organizationId, ...values]); counts.catalog += 1; }
    }
    for (const item of starterForms) {
      const q = await client.query("select 1 from forms where organization_id=$1 and name=$2", [organizationId, item.name]);
      if (!q.rowCount) { await client.query("insert into forms (organization_id,name,kind,schema,automation_config,status) values ($1,$2,$3,$4,$5,$6)", [organizationId, item.name, item.kind, JSON.stringify(item.schema), JSON.stringify(item.automation_config), item.status]); counts.forms += 1; }
    }
    for (const [name, trigger, action, category, description, conditions, actions] of starterAutomations) {
      const q = await client.query("select 1 from automations where organization_id=$1 and name=$2", [organizationId, name]);
      if (!q.rowCount) { await client.query("insert into automations (organization_id,name,trigger,action,config,active,status,category,description,conditions,actions,avoid_duplicates) values ($1,$2,$3,$4,'{}'::jsonb,false,'paused',$5,$6,$7,$8,true)", [organizationId, name, trigger, action, category, description, JSON.stringify(conditions), JSON.stringify(actions)]); counts.automations += 1; }
    }
    await client.query("commit");
    return counts;
  } catch (error) { await client.query("rollback").catch(() => {}); throw error; }
  finally { client.release(); }
}

export { starterTemplates, starterCatalog, starterForms, starterAutomations };
