-- Sincroniza tabelas criadas por versões antigas do schema: adiciona colunas que faltam.
-- Gerado a partir de server/schema.sql; idempotente (add column if not exists).
-- NOT NULL só é aplicado quando existe default; do contrário a coluna fica nula para linhas antigas.
alter table organizations add column if not exists name text;
alter table organizations add column if not exists created_at timestamptz default now() not null;
alter table users add column if not exists name text;
alter table users add column if not exists email text;
alter table users add column if not exists password_hash text;
alter table users add column if not exists organization_id uuid references organizations(id);
alter table users add column if not exists created_at timestamptz default now() not null;
alter table contacts add column if not exists organization_id uuid references organizations(id);
alter table contacts add column if not exists name text;
alter table contacts add column if not exists email text;
alter table contacts add column if not exists phone text;
alter table contacts add column if not exists role text;
alter table contacts add column if not exists notes text;
alter table contacts add column if not exists created_at timestamptz default now() not null;
alter table contacts add column if not exists updated_at timestamptz default now() not null;
alter table companies add column if not exists organization_id uuid references organizations(id);
alter table companies add column if not exists name text;
alter table companies add column if not exists document text;
alter table companies add column if not exists email text;
alter table companies add column if not exists phone text;
alter table companies add column if not exists website text;
alter table companies add column if not exists address text;
alter table companies add column if not exists created_at timestamptz default now() not null;
alter table companies add column if not exists updated_at timestamptz default now() not null;
alter table leads add column if not exists organization_id uuid references organizations(id);
alter table leads add column if not exists name text;
alter table leads add column if not exists company text;
alter table leads add column if not exists company_id bigint references companies(id) on delete set null;
alter table leads add column if not exists contact_id bigint references contacts(id) on delete set null;
alter table leads add column if not exists email text;
alter table leads add column if not exists phone text;
alter table leads add column if not exists source text;
alter table leads add column if not exists status text default 'new' not null;
alter table leads add column if not exists created_at timestamptz default now() not null;
alter table leads add column if not exists updated_at timestamptz default now() not null;
alter table opportunities add column if not exists organization_id uuid references organizations(id);
alter table opportunities add column if not exists lead_id bigint references leads(id) on delete set null;
alter table opportunities add column if not exists company_id bigint references companies(id) on delete set null;
alter table opportunities add column if not exists name text;
alter table opportunities add column if not exists stage text default 'qualification' not null;
alter table opportunities add column if not exists amount numeric(14,2) default 0 not null;
alter table opportunities add column if not exists expected_close date;
alter table opportunities add column if not exists created_at timestamptz default now() not null;
alter table opportunities add column if not exists updated_at timestamptz default now() not null;
alter table clients add column if not exists organization_id uuid references organizations(id);
alter table clients add column if not exists company_id bigint references companies(id) on delete set null;
alter table clients add column if not exists contact_id bigint references contacts(id) on delete set null;
alter table clients add column if not exists name text;
alter table clients add column if not exists email text;
alter table clients add column if not exists phone text;
alter table clients add column if not exists status text default 'active' not null;
alter table clients add column if not exists created_at timestamptz default now() not null;
alter table clients add column if not exists updated_at timestamptz default now() not null;
alter table contracts add column if not exists organization_id uuid references organizations(id);
alter table contracts add column if not exists client_id bigint references clients(id) on delete cascade;
alter table contracts add column if not exists opportunity_id bigint references opportunities(id) on delete set null;
alter table contracts add column if not exists name text;
alter table contracts add column if not exists status text default 'draft' not null;
alter table contracts add column if not exists value numeric(14,2) default 0 not null;
alter table contracts add column if not exists starts_on date;
alter table contracts add column if not exists ends_on date;
alter table contracts add column if not exists created_at timestamptz default now() not null;
alter table contracts add column if not exists updated_at timestamptz default now() not null;
alter table projects add column if not exists organization_id uuid references organizations(id);
alter table projects add column if not exists contract_id bigint references contracts(id) on delete set null;
alter table projects add column if not exists client_id bigint references clients(id) on delete set null;
alter table projects add column if not exists name text;
alter table projects add column if not exists status text default 'active' not null;
alter table projects add column if not exists progress smallint default 0 not null;
alter table projects add column if not exists created_at timestamptz default now() not null;
alter table projects add column if not exists updated_at timestamptz default now() not null;
alter table tasks add column if not exists organization_id uuid references organizations(id);
alter table tasks add column if not exists project_id bigint references projects(id) on delete cascade;
alter table tasks add column if not exists title text;
alter table tasks add column if not exists status text default 'todo' not null;
alter table tasks add column if not exists priority text default 'medium' not null;
alter table tasks add column if not exists due_at timestamptz;
alter table tasks add column if not exists tags text[] default '{}' not null;
alter table tasks add column if not exists parent_id bigint references tasks(id) on delete cascade;
alter table tasks add column if not exists created_at timestamptz default now() not null;
alter table tasks add column if not exists updated_at timestamptz default now() not null;
alter table revenues add column if not exists organization_id uuid references organizations(id);
alter table revenues add column if not exists contract_id bigint references contracts(id) on delete set null;
alter table revenues add column if not exists description text;
alter table revenues add column if not exists amount numeric(14,2);
alter table revenues add column if not exists due_at timestamptz;
alter table revenues add column if not exists paid_at timestamptz;
alter table revenues add column if not exists created_at timestamptz default now() not null;
alter table expenses add column if not exists organization_id uuid references organizations(id);
alter table expenses add column if not exists project_id bigint references projects(id) on delete set null;
alter table expenses add column if not exists description text;
alter table expenses add column if not exists amount numeric(14,2);
alter table expenses add column if not exists due_at timestamptz;
alter table expenses add column if not exists paid_at timestamptz;
alter table expenses add column if not exists created_at timestamptz default now() not null;
alter table receivables add column if not exists organization_id uuid references organizations(id);
alter table receivables add column if not exists client_id bigint references clients(id) on delete set null;
alter table receivables add column if not exists contract_id bigint references contracts(id) on delete set null;
alter table receivables add column if not exists description text;
alter table receivables add column if not exists amount numeric(14,2);
alter table receivables add column if not exists due_at date;
alter table receivables add column if not exists status text default 'pending' not null;
alter table receivables add column if not exists paid_at timestamptz;
alter table receivables add column if not exists created_at timestamptz default now() not null;
alter table charges add column if not exists organization_id uuid references organizations(id);
alter table charges add column if not exists receivable_id bigint references receivables(id) on delete cascade;
alter table charges add column if not exists provider text;
alter table charges add column if not exists external_id text;
alter table charges add column if not exists status text default 'pending' not null;
alter table charges add column if not exists amount numeric(14,2);
alter table charges add column if not exists due_at date;
alter table charges add column if not exists created_at timestamptz default now() not null;
alter table payments add column if not exists organization_id uuid references organizations(id);
alter table payments add column if not exists receivable_id bigint references receivables(id) on delete set null;
alter table payments add column if not exists charge_id bigint references charges(id) on delete set null;
alter table payments add column if not exists amount numeric(14,2);
alter table payments add column if not exists paid_at timestamptz default now() not null;
alter table payments add column if not exists method text;
alter table payments add column if not exists external_id text;
alter table events add column if not exists organization_id uuid references organizations(id);
alter table events add column if not exists title text;
alter table events add column if not exists starts_at timestamptz;
alter table events add column if not exists description text;
alter table events add column if not exists recurrence text default 'none' not null;
alter table events add column if not exists reminder_minutes integer default 30 not null;
alter table events add column if not exists created_at timestamptz default now() not null;
alter table password_resets add column if not exists user_id uuid references users(id) on delete cascade;
alter table password_resets add column if not exists token_hash text;
alter table password_resets add column if not exists expires_at timestamptz;
alter table password_resets add column if not exists used_at timestamptz;
alter table password_resets add column if not exists created_at timestamptz default now() not null;
