alter table projects add column if not exists internal_code text;
alter table projects add column if not exists project_type text;
alter table projects add column if not exists description text;
alter table projects add column if not exists responsible text;
alter table projects add column if not exists team text;
alter table projects add column if not exists priority text default 'medium';
alter table projects add column if not exists current_stage text;
alter table projects add column if not exists starts_on date;
alter table projects add column if not exists due_on date;
alter table projects add column if not exists completed_on date;
alter table projects add column if not exists block_reason text;
alter table projects add column if not exists next_action text;
alter table projects add column if not exists next_action_at timestamptz;
alter table projects add column if not exists objective text;
alter table projects add column if not exists audience text;
alter table projects add column if not exists features text;
alter table projects add column if not exists modules text;
alter table projects add column if not exists integrations text;
alter table projects add column if not exists visual_identity text;
alter table projects add column if not exists technologies text;
alter table projects add column if not exists requirements text;
alter table projects add column if not exists out_of_scope text;
alter table projects add column if not exists technical_notes text;
alter table projects add column if not exists completion_criteria text;
alter table projects add column if not exists domain text;
alter table projects add column if not exists domain_provider text;
alter table projects add column if not exists hosting_provider text;
alter table projects add column if not exists repository_url text;
alter table projects add column if not exists development_url text;
alter table projects add column if not exists staging_url text;
alter table projects add column if not exists production_url text;
alter table projects add column if not exists database_provider text;
alter table projects add column if not exists external_apis text;
alter table projects add column if not exists access_storage_reference text;
alter table projects add column if not exists total_value numeric(14,2) default 0;
alter table projects add column if not exists down_payment numeric(14,2) default 0;
alter table projects add column if not exists payment_status text;
alter table projects add column if not exists payment_method text;
alter table projects add column if not exists installments integer;
alter table projects add column if not exists installment_value numeric(14,2);
alter table projects add column if not exists payment_due_dates text;
alter table projects add column if not exists discount numeric(14,2) default 0;
alter table projects add column if not exists additional_costs numeric(14,2) default 0;
alter table projects add column if not exists server_monthly_cost numeric(14,2) default 0;
alter table projects add column if not exists maintenance_monthly_value numeric(14,2) default 0;
alter table projects add column if not exists api_service_costs numeric(14,2) default 0;
alter table projects add column if not exists financial_notes text;
alter table projects add column if not exists pending_items text;
alter table projects add column if not exists observations text;
alter table projects add column if not exists published_at timestamptz;
alter table projects add column if not exists delivered boolean default false;
alter table projects add column if not exists acceptance_signed boolean default false;
alter table projects add column if not exists training_done boolean default false;
alter table projects add column if not exists warranty_until date;
alter table projects add column if not exists support_period text;
alter table projects add column if not exists maintenance_plan text;
alter table projects add column if not exists recurring_value numeric(14,2) default 0;
alter table projects add column if not exists next_renewal_on date;
alter table projects add column if not exists backup_done boolean default false;
alter table projects add column if not exists source_delivered boolean default false;
alter table projects add column if not exists accesses_transferred boolean default false;
alter table projects add column if not exists final_notes text;
alter table receivables add column if not exists project_id bigint references projects(id) on delete set null;
create index if not exists idx_receivables_org_project on receivables(organization_id, project_id);
create index if not exists idx_projects_org_due_on on projects(organization_id, due_on);
create index if not exists idx_projects_org_status on projects(organization_id, status);
