alter table clients add column if not exists legal_name text;
alter table clients add column if not exists trade_name text;
alter table clients add column if not exists person_type text default 'company';
alter table clients add column if not exists avatar_url text;
alter table clients add column if not exists document text;
alter table clients add column if not exists founded_on date;
alter table clients add column if not exists source text;
alter table clients add column if not exists responsible_name text;
alter table clients add column if not exists responsible_role text;
alter table clients add column if not exists whatsapp text;
alter table clients add column if not exists secondary_phone text;
alter table clients add column if not exists website text;
alter table clients add column if not exists instagram text;
alter table clients add column if not exists linkedin text;
alter table clients add column if not exists contact_hours text;
alter table clients add column if not exists preferred_channel text;
alter table clients add column if not exists zip_code text;
alter table clients add column if not exists street text;
alter table clients add column if not exists street_number text;
alter table clients add column if not exists complement text;
alter table clients add column if not exists neighborhood text;
alter table clients add column if not exists city text;
alter table clients add column if not exists state text;
alter table clients add column if not exists country text default 'Brasil';
alter table clients add column if not exists segment text;
alter table clients add column if not exists company_size text;
alter table clients add column if not exists services_interest text;
alter table clients add column if not exists main_need text;
alter table clients add column if not exists estimated_budget numeric(14,2);
alter table clients add column if not exists urgency text;
alter table clients add column if not exists sales_owner text;
alter table clients add column if not exists funnel_stage text;
alter table clients add column if not exists lead_temperature text;
alter table clients add column if not exists closing_probability smallint;
alter table clients add column if not exists first_contact_at timestamptz;
alter table clients add column if not exists last_contact_at timestamptz;
alter table clients add column if not exists next_contact_at timestamptz;
alter table clients add column if not exists next_action text;
alter table clients add column if not exists commercial_notes text;
alter table clients add column if not exists default_payment_terms text;
alter table clients add column if not exists preferred_payment_method text;
alter table clients add column if not exists monthly_fee numeric(14,2) default 0;
alter table clients add column if not exists due_day smallint;
alter table clients add column if not exists financial_status text;
alter table clients add column if not exists pix_key text;
alter table clients add column if not exists invoice_data text;
alter table clients add column if not exists internal_notes text;
create index if not exists idx_clients_org_document on clients(organization_id, document);
create index if not exists idx_clients_org_status on clients(organization_id, status);
