alter table contracts add column if not exists contract_number text;
alter table contracts add column if not exists contract_type text;
alter table contracts add column if not exists proposal_id bigint references proposals(id) on delete set null;
alter table contracts add column if not exists project_id bigint references projects(id) on delete set null;
alter table contracts add column if not exists issued_on date default current_date;
alter table contracts add column if not exists description text;
alter table contracts add column if not exists scope_included text;
alter table contracts add column if not exists scope_excluded text;
alter table contracts add column if not exists deliverables text;
alter table contracts add column if not exists technologies text;
alter table contracts add column if not exists milestones text;
alter table contracts add column if not exists client_approval_days integer;
alter table contracts add column if not exists client_responsibilities text;
alter table contracts add column if not exists provider_responsibilities text;
alter table contracts add column if not exists revisions_included integer;
alter table contracts add column if not exists change_policy text;
alter table contracts add column if not exists additional_change_value numeric(14,2);
alter table contracts add column if not exists total_value numeric(14,2) default 0;
alter table contracts add column if not exists down_payment numeric(14,2) default 0;
alter table contracts add column if not exists discount numeric(14,2) default 0;
alter table contracts add column if not exists installments integer default 1;
alter table contracts add column if not exists installment_value numeric(14,2) default 0;
alter table contracts add column if not exists payment_method text;
alter table contracts add column if not exists payment_due_dates text;
alter table contracts add column if not exists late_fee numeric(8,4) default 0;
alter table contracts add column if not exists late_interest numeric(8,4) default 0;
alter table contracts add column if not exists payment_rules text;
alter table contracts add column if not exists maintenance_monthly numeric(14,2) default 0;
alter table contracts add column if not exists hosting_monthly numeric(14,2) default 0;
alter table contracts add column if not exists server_monthly numeric(14,2) default 0;
alter table contracts add column if not exists domain_monthly numeric(14,2) default 0;
alter table contracts add column if not exists apis_monthly numeric(14,2) default 0;
alter table contracts add column if not exists licenses_monthly numeric(14,2) default 0;
alter table contracts add column if not exists recurring_due_on date;
alter table contracts add column if not exists recurring_rules text;
alter table contracts add column if not exists warranty_period text;
alter table contracts add column if not exists support_period text;
alter table contracts add column if not exists intellectual_property text;
alter table contracts add column if not exists cancellation_terms text;
alter table contracts add column if not exists data_protection_terms text;
alter table contracts add column if not exists signature_data jsonb;
create index if not exists idx_contracts_org_project on contracts(organization_id, project_id);
create index if not exists idx_contracts_org_proposal on contracts(organization_id, proposal_id);
