alter table proposals drop constraint if exists proposals_status_check;
alter table proposals add constraint proposals_status_check check (status in ('draft','sent','viewed','negotiation','accepted','rejected','expired','cancelled'));
alter table proposals add column if not exists proposal_number text;
alter table proposals add column if not exists client_id bigint references clients(id) on delete set null;
alter table proposals add column if not exists contact_id bigint references contacts(id) on delete set null;
alter table proposals add column if not exists project_id bigint references projects(id) on delete set null;
alter table proposals add column if not exists sales_owner text;
alter table proposals add column if not exists issued_on date default current_date;
alter table proposals add column if not exists presentation text;
alter table proposals add column if not exists identified_need text;
alter table proposals add column if not exists objective text;
alter table proposals add column if not exists proposed_solution text;
alter table proposals add column if not exists benefits text;
alter table proposals add column if not exists differentiators text;
alter table proposals add column if not exists service_type text;
alter table proposals add column if not exists scope_included text;
alter table proposals add column if not exists modules text;
alter table proposals add column if not exists integrations text;
alter table proposals add column if not exists technologies text;
alter table proposals add column if not exists revisions_included integer default 1;
alter table proposals add column if not exists responsibilities_provider text;
alter table proposals add column if not exists responsibilities_client text;
alter table proposals add column if not exists scope_excluded text;
alter table proposals add column if not exists optional_services text;
alter table proposals add column if not exists discount numeric(14,2) default 0;
alter table proposals add column if not exists additional_fees numeric(14,2) default 0;
alter table proposals add column if not exists final_amount numeric(14,2) default 0;
alter table proposals add column if not exists down_payment numeric(14,2) default 0;
alter table proposals add column if not exists balance_remaining numeric(14,2) default 0;
alter table proposals add column if not exists installments integer default 1;
alter table proposals add column if not exists installment_amount numeric(14,2) default 0;
alter table proposals add column if not exists payment_method text;
alter table proposals add column if not exists payment_due_dates text;
alter table proposals add column if not exists late_fee numeric(8,4) default 0;
alter table proposals add column if not exists late_interest numeric(8,4) default 0;
alter table proposals add column if not exists recurring_costs text;
alter table proposals add column if not exists proposal_terms text;
alter table proposals add column if not exists approver_name text;
alter table proposals add column if not exists approver_document text;
alter table proposals add column if not exists approver_email text;
alter table proposals add column if not exists approved_at timestamptz;
alter table proposals add column if not exists acceptance_comment text;
alter table proposals add column if not exists acceptance_ip inet;
alter table proposals add column if not exists accepted_terms boolean default false;
create index if not exists idx_proposals_org_client on proposals(organization_id, client_id);
create index if not exists idx_proposals_org_project on proposals(organization_id, project_id);
