alter table tasks drop constraint if exists tasks_priority_check;
alter table tasks add constraint tasks_priority_check check (priority in ('low','medium','high','urgent'));
alter table tasks add column if not exists description text;
alter table tasks add column if not exists client_id bigint references clients(id) on delete set null;
alter table tasks add column if not exists stage text;
alter table tasks add column if not exists assignee text;
alter table tasks add column if not exists participants text;
alter table tasks add column if not exists starts_at timestamptz;
alter table tasks add column if not exists category text;
alter table tasks add column if not exists estimated_minutes integer default 0;
alter table tasks add column if not exists worked_minutes integer default 0;
alter table tasks add column if not exists hourly_cost numeric(14,2) default 0;
alter table tasks add column if not exists checklist jsonb default '[]'::jsonb;
alter table tasks add column if not exists recurrence text default 'none';
alter table tasks add column if not exists recurrence_until date;
alter table tasks add column if not exists blocked_reason text;
alter table tasks add column if not exists internal_notes text;
create index if not exists idx_tasks_org_client on tasks(organization_id, client_id);
create index if not exists idx_tasks_org_status on tasks(organization_id, status);
