alter table contacts add column if not exists department text;
alter table contacts add column if not exists document text;
alter table contacts add column if not exists birth_date date;
alter table contacts add column if not exists city text;
alter table contacts add column if not exists state text;
alter table contacts add column if not exists preferred_channel text;
alter table contacts add column if not exists contact_type text;
alter table contacts add column if not exists source text;
alter table contacts add column if not exists owner text;
alter table contacts add column if not exists tags text;
alter table contacts add column if not exists is_primary boolean default false;
alter table companies add column if not exists legal_name text;
alter table companies add column if not exists trade_name text;
alter table companies add column if not exists state_registration text;
alter table companies add column if not exists municipal_registration text;
alter table companies add column if not exists status text;
alter table companies add column if not exists founded_on date;
alter table companies add column if not exists size text;
alter table companies add column if not exists segment text;
alter table companies add column if not exists primary_activity text;
alter table companies add column if not exists whatsapp text;
alter table companies add column if not exists zip_code text;
alter table companies add column if not exists street text;
alter table companies add column if not exists street_number text;
alter table companies add column if not exists city text;
alter table companies add column if not exists state text;
alter table companies add column if not exists country text default 'Brasil';
alter table companies add column if not exists internal_owner text;
alter table companies add column if not exists source text;
alter table companies add column if not exists last_cnpj_lookup_at timestamptz;
create index if not exists idx_contacts_org_company_primary on contacts(organization_id, company_id, is_primary);
create index if not exists idx_companies_org_document on companies(organization_id, document);
