alter table revenues add column if not exists project_id bigint references projects(id) on delete set null;
alter table revenues add column if not exists category text;
alter table revenues add column if not exists gross_amount numeric(14,2);
alter table revenues add column if not exists discount numeric(14,2) default 0;
alter table revenues add column if not exists fees numeric(14,2) default 0;
alter table revenues add column if not exists tax_estimate numeric(14,2) default 0;
alter table revenues add column if not exists net_amount numeric(14,2);
alter table revenues add column if not exists payment_method text;
alter table revenues add column if not exists account_name text;
alter table revenues add column if not exists document_number text;
alter table revenues add column if not exists receipt_url text;
alter table revenues add column if not exists status text default 'confirmed';
alter table expenses add column if not exists client_id bigint references clients(id) on delete set null;
alter table expenses add column if not exists supplier text;
alter table expenses add column if not exists category text;
alter table expenses add column if not exists payment_method text;
alter table expenses add column if not exists account_name text;
alter table expenses add column if not exists recurrence text;
alter table expenses add column if not exists cost_center text;
alter table expenses add column if not exists status text default 'pending';
alter table receivables add column if not exists original_amount numeric(14,2);
alter table receivables add column if not exists discount numeric(14,2) default 0;
alter table receivables add column if not exists interest numeric(14,2) default 0;
alter table receivables add column if not exists fine numeric(14,2) default 0;
alter table receivables add column if not exists updated_amount numeric(14,2);
alter table receivables add column if not exists installment_number integer;
alter table receivables add column if not exists proposal_id bigint references proposals(id) on delete set null;
alter table receivables add column if not exists project_id bigint references projects(id) on delete set null;
alter table receivables add column if not exists payment_method text;
alter table receivables add column if not exists responsible text;
alter table charges add column if not exists client_id bigint references clients(id) on delete set null;
alter table charges add column if not exists project_id bigint references projects(id) on delete set null;
alter table charges add column if not exists channel text;
alter table charges add column if not exists payment_url text;
alter table charges add column if not exists message text;
create index if not exists idx_revenues_org_project on revenues(organization_id, project_id);
create index if not exists idx_expenses_org_project on expenses(organization_id, project_id);
