alter table catalog_items add column if not exists sku text;
alter table catalog_items add column if not exists short_description text;
alter table catalog_items add column if not exists full_description text;
alter table catalog_items add column if not exists archived_at timestamptz;
alter table catalog_items add column if not exists tags text;
alter table catalog_items add column if not exists min_price numeric(14,2);
alter table catalog_items add column if not exists promotional_price numeric(14,2);
alter table catalog_items add column if not exists internal_cost numeric(14,2) default 0;
alter table catalog_items add column if not exists billing_type text default 'one_time';
alter table catalog_items add column if not exists entry_price numeric(14,2) default 0;
alter table catalog_items add column if not exists max_installments integer;
alter table catalog_items add column if not exists max_discount numeric(8,2) default 0;
alter table catalog_items add column if not exists sales_commission numeric(8,2) default 0;
alter table catalog_items add column if not exists estimated_taxes numeric(8,2) default 0;
alter table catalog_items add column if not exists included_scope text;
alter table catalog_items add column if not exists excluded_scope text;
alter table catalog_items add column if not exists deliverables text;
alter table catalog_items add column if not exists modules_count integer;
alter table catalog_items add column if not exists revisions_count integer;
alter table catalog_items add column if not exists average_term_days integer;
alter table catalog_items add column if not exists warranty_period text;
alter table catalog_items add column if not exists support_included text;
alter table catalog_items add column if not exists client_responsibilities text;
alter table catalog_items add column if not exists required_materials text;
alter table catalog_items add column if not exists technical_requirements text;
alter table catalog_items add column if not exists internal_notes text;
create unique index if not exists idx_catalog_items_org_sku on catalog_items(organization_id, sku) where sku is not null;
