alter table automations add column if not exists description text;
alter table automations add column if not exists category text;
alter table automations add column if not exists responsible text;
alter table automations add column if not exists status text default 'draft';
alter table automations add column if not exists conditions jsonb default '[]'::jsonb;
alter table automations add column if not exists actions jsonb default '[]'::jsonb;
alter table automations add column if not exists allowed_hours text;
alter table automations add column if not exists execution_limit integer;
alter table automations add column if not exists starts_on date;
alter table automations add column if not exists ends_on date;
alter table automations add column if not exists avoid_duplicates boolean default true;
alter table automations add column if not exists last_error text;
alter table templates add column if not exists category text;
alter table templates add column if not exists subject text;
alter table templates add column if not exists language text default 'pt-BR';
alter table templates add column if not exists variables text;
alter table templates add column if not exists service_id bigint;
alter table templates add column if not exists favorite boolean default false;
alter table templates add column if not exists is_default boolean default false;
alter table templates add column if not exists version integer default 1;
alter table templates add column if not exists internal_notes text;
alter table integrations add column if not exists category text;
alter table integrations add column if not exists environment text default 'production';
alter table integrations add column if not exists account_name text;
alter table integrations add column if not exists last_sync_at timestamptz;
alter table integrations add column if not exists enabled_events text;
alter table integrations add column if not exists responsible text;
alter table integrations add column if not exists granted_permissions text;
alter table integrations add column if not exists last_error text;
create table if not exists integration_logs (id bigserial primary key, organization_id uuid not null references organizations(id), integration_id bigint references integrations(id) on delete cascade, level text not null default 'info', message text not null, created_at timestamptz not null default now());
create index if not exists idx_integration_logs_org_created on integration_logs(organization_id, created_at desc);
