alter table users add column if not exists avatar_url text;
alter table users add column if not exists document text;
alter table users add column if not exists birth_date date;
alter table users add column if not exists phone text;
alter table users add column if not exists whatsapp text;
alter table users add column if not exists address text;
alter table users add column if not exists emergency_contact text;
alter table users add column if not exists job_title text;
alter table users add column if not exists department text;
alter table users add column if not exists employment_type text;
alter table users add column if not exists started_on date;
alter table users add column if not exists work_schedule text;
alter table users add column if not exists hourly_rate numeric(14,2);
alter table users add column if not exists monthly_rate numeric(14,2);
alter table users add column if not exists commission_rate numeric(8,2);
alter table users add column if not exists skills text;
alter table users add column if not exists experience_level text;
alter table users add column if not exists manager_id uuid references users(id) on delete set null;
alter table users add column if not exists access_status text default 'active';
alter table users add column if not exists access_expires_on date;
alter table users add column if not exists two_factor_enabled boolean default false;
alter table users add column if not exists availability text;
create index if not exists idx_users_org_department on users(organization_id, department);
create index if not exists idx_users_org_access_status on users(organization_id, access_status);
